Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Factor__c</fullName>
        <label>Adjustment Factor %</label>
        <picklist>
            <picklistValues>
                <fullName>-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Alternate_E_Mail_Address__c</fullName>
        <label>Alternate E-Mail Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alternate_Mobile__c</fullName>
        <label>Alternate Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_EndYear__c</fullName>
        <label>Estimated Life EndYear</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_Expectancy__c</fullName>
        <label>Estimated Life Expectancy</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Status_del__c</fullName>
        <label>Residential Status</label>
        <picklist>
            <picklistValues>
                <fullName>Permanent Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident but not Ordinary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Resident</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retirement_Age__c</fullName>
        <label>Retirement Age</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retirement_Year__c</fullName>
        <label>Retirement Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>General</description>
        <label>General</label>
    </recordTypes>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Approve_Action_Plan__c.object
<CustomObject>
    <description>Created for new action plan</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approve Action Plans</relationshipLabel>
        <relationshipName>Approve_Action_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Investment_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investment Asset</label>
        <referenceTo>Investment_Asset__c</referenceTo>
        <relationshipLabel>Approve Action Plans</relationshipLabel>
        <relationshipName>Approve_Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approve Action Plan</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approve Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/ARPP_Detail__c.object
<CustomObject>
    <description>New object for ARPP  calculation</description>
    <fields>
        <fullName>Approve_Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approve Action Plan</label>
        <referenceTo>Approve_Action_Plan__c</referenceTo>
        <relationshipName>ARPP_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ARPP_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Tracker</label>
        <referenceTo>Execution_Tracker__c</referenceTo>
        <relationshipName>ARPP_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RPP Detail</label>
    <nameField>
        <displayFormat>RPP-{00000}</displayFormat>
        <label>RPP Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RPP Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agreed_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Agreed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Provided to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Handed over to Ops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approve_Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approve Action Plan</label>
        <referenceTo>Approve_Action_Plan__c</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ET_Status__c</fullName>
        <label>ET Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <formula>Approve_Action_Plan__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Floating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Floating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Total_Remaining_Balance__c</fullName>
        <label>Total Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold (Align to goal)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investment Assets</relationshipLabel>
        <relationshipName>Investment_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Gold</fullName>
        <active>true</active>
        <description>Added regarding new FP changes</description>
        <label>Gold and Silver</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stocks</fullName>
        <active>true</active>
        <label>Stocks</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InvestmentAsset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>InvestmentAsset</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/EditETforSTPControllerTest.cls
/**
*  Test class for Controller class EditETforSTPController
*
*   Revision History:
*
*   Version        Author             Date            Description
*   1.0            Aditi/Prajakta    02/04/2013      Initial Draft
*/
 
public with sharing class EditETforSTPControllerTest {

    //test Method
	@isTest
	public static  void testEditETforSTPController()
	{
		Schema.DescribeSObjectResult DESCRIBE_RESULT = Account.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_MAP = DESCRIBE_RESULT.getRecordTypeInfosByName();
    	
    	Schema.DescribeSObjectResult DESCRIBE_RESULT_INVESTMENT = Investment_Asset__c.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_INVESTMENTMAP = DESCRIBE_RESULT_INVESTMENT.getRecordTypeInfosByName();
    	
    	//Insert RecordType record
    	List<RecTypes__c> lstRecTypes = new List<RecTypes__c>();
    	RecTypes__c objRecType = new RecTypes__c(Name='General_Business', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	
    	RecTypes__c objRecType1 = new RecTypes__c(Name='AccountFamily', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Family Member').getRecordTypeId());
    	RecTypes__c objRecType2 = new RecTypes__c(Name='AccountClient', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
    	
    	lstRecTypes.add(objRecType);										 
    	lstRecTypes.add(objRecType1);
    	lstRecTypes.add(objRecType2);	
    	insert lstRecTypes;
    	
    	//Insert RecordType for Insurance record
    	List<InvestmentAsset__c> lstRecTypesInvestment = new List<InvestmentAsset__c>();
    	InvestmentAsset__c objInvestmentRecType = new InvestmentAsset__c(Name='Stocks', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Stocks').getRecordTypeId());
    	
    	InvestmentAsset__c objInvestmentRecType1 = new InvestmentAsset__c(Name='Fixed Income', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Fixed Income').getRecordTypeId());
    	InvestmentAsset__c objInvestmentRecType2 = new InvestmentAsset__c(Name='Gold and Silver', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Gold and Silver').getRecordTypeId());
    											 
    	InvestmentAsset__c objInvestmentRecType3 = new InvestmentAsset__c(Name='Mutual Fund', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Mutual Fund').getRecordTypeId());
    	lstRecTypesInvestment.add(objInvestmentRecType);										 
    	lstRecTypesInvestment.add(objInvestmentRecType1);
    	lstRecTypesInvestment.add(objInvestmentRecType2);	
    	lstRecTypesInvestment.add(objInvestmentRecType3);
    	
    	insert lstRecTypesInvestment;
    	
    	List<smagicbasic__SMS_Template__c> lstTemplate = new List<smagicbasic__SMS_Template__c>();
    	
    	smagicbasic__SMS_Template__c template= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Discontinuation Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	
    	smagicbasic__SMS_Template__c template1= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Renewal Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	lstTemplate.add(template);
    	lstTemplate.add(template1);
    	
    	insert lstTemplate;
    	
     //Insert Account record
    	Account objBPAccount = new Account(Name='Parner Account Test',
    								RecordTypeId= RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	insert 	objBPAccount;
    	
	    
		//RecordType objRT = [Select Id from RecordType where Name = 'Client' and SobjectType = 'Account'];
		Account objAccount = new Account(LastName='Test',FirstName='Test',Adjustment_Factor__c='2',
	                       PersonTitle='TestData', PersonBirthdate= system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463732345',
	                       Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',
	                       Retirement_Year__c=2034, Residential_Status_del__c='own', Retirement_Age__c='58', Estimated_Life_Expectancy__c='67',
	                       Estimated_Life_EndYear__c=2041, Relationship_to_Entity__pc='husband', RecordTypeId = RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
	    insert objAccount;
	    
	    
	    Investment_Asset__c inv = new Investment_Asset__c(Entity__c=objAccount.id,action__c='yes',RecordTypeId=RECORD_TYPE_INFO_INVESTMENTMAP.get('Stocks').getRecordTypeId(),
	    												Maturity_Date__c = system.today());
	    insert inv;		
	    Investment_Asset__c inv1 = new Investment_Asset__c(Entity__c=objAccount.id,action__c='yes',RecordTypeId=RECORD_TYPE_INFO_INVESTMENTMAP.get('Mutual Fund').getRecordTypeId(),
	    												Maturity_Date__c = system.today());
	    insert inv1;	
	    				
	    List<Approve_Action_Plan__c> lstAP = new List<Approve_Action_Plan__c>();										
	    Approve_Action_Plan__c objAAP1 = new Approve_Action_Plan__c(Account__c = objAccount.Id,Investment_Asset__c = inv1.Id);
	    lstAP.add(objAAP1);
	    
	    Approve_Action_Plan__c objAAP2 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    lstAP.add(objAAP2);
        
        insert lstAP;
        
        List<Execution_Tracker__c> lstET = new List<Execution_Tracker__c>();
        Execution_Tracker__c objET1 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Total_Remaining_Balance__c = 200,Agreed_Amount__c = 202,Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP1.Id, Type__c = 'Lumpsum',Action__c = 'STP To');
        lstET.add(objET1);
        Execution_Tracker__c objET2 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Total_Remaining_Balance__c = 200,Agreed_Amount__c = 202,Application_Status__c = 'Closed', Approve_Action_Plan__c = objAAP2.Id, Type__c = 'Lumpsum',Action__c = 'Lumpsum');
        lstET.add(objET2);
        insert lstET;
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('eid', objAccount.id);
        Apexpages.currentPage().getParameters().put('id', objAAP2.Id);
		Apexpages.currentPage().getParameters().put('type', 'Lumpsum');
        EditETforSTPController objEETC1 = new EditETforSTPController(); 
      	objEETC1.assignTask();
      	objEETC1.getEntities();
      	objEETC1.updateExecutionTracker();
      	
      	ApexPages.currentPage().getParameters().put('eid', objAccount.id);
        Apexpages.currentPage().getParameters().put('etid', objET1.Id);
        Apexpages.currentPage().getParameters().put('type', 'Lumpsum');
		Apexpages.currentPage().getParameters().put('userType', 'opsTeam');
        EditETforSTPController objEETC2 = new EditETforSTPController(); 
      	objEETC2.assignTask();
      	objEETC2.getEntities();
      	objEETC2.updateExecutionTracker();
      	objEETC2.getApplicationStatus();
      	
      	ApexPages.currentPage().getParameters().put('eid',null);
        Apexpages.currentPage().getParameters().put('etid', objET1.Id);
        Apexpages.currentPage().getParameters().put('type', 'Lumpsum');
		Apexpages.currentPage().getParameters().put('userType', 'opsTeam');
        EditETforSTPController objEETC3 = new EditETforSTPController(); 
      	objEETC3.getEntities();
      	
      	
      	try
      	{
      		ApexPages.currentPage().getParameters().put('eid', objAccount.id);
        	Apexpages.currentPage().getParameters().put('id', objAAP1.Id);
			Apexpages.currentPage().getParameters().put('type', 'Lumpsum');
        	EditETforSTPController objEETC4 = new EditETforSTPController(); 
        	objEETC4.getEntities();
      		objEETC4.updateExecutionTracker();
      	}
      	catch(Exception e)
      	{
      		
      	}
      	
        Test.stopTest();
	}
	@isTest
	public static  void testEditETforSTPController1()
	{
		Schema.DescribeSObjectResult DESCRIBE_RESULT = Account.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_MAP = DESCRIBE_RESULT.getRecordTypeInfosByName();
    	
    	Schema.DescribeSObjectResult DESCRIBE_RESULT_INVESTMENT = Investment_Asset__c.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_INVESTMENTMAP = DESCRIBE_RESULT_INVESTMENT.getRecordTypeInfosByName();
    	
    	//Insert RecordType record
    	List<RecTypes__c> lstRecTypes = new List<RecTypes__c>();
    	RecTypes__c objRecType = new RecTypes__c(Name='General_Business', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	
    	RecTypes__c objRecType1 = new RecTypes__c(Name='AccountFamily', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Family Member').getRecordTypeId());
    	RecTypes__c objRecType2 = new RecTypes__c(Name='AccountClient', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
    	
    	lstRecTypes.add(objRecType);										 
    	lstRecTypes.add(objRecType1);
    	lstRecTypes.add(objRecType2);	
    	insert lstRecTypes;
    	
    	//Insert RecordType for Insurance record
    	List<InvestmentAsset__c> lstRecTypesInvestment = new List<InvestmentAsset__c>();
    	InvestmentAsset__c objInvestmentRecType = new InvestmentAsset__c(Name='Stocks', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Stocks').getRecordTypeId());
    	
    	InvestmentAsset__c objInvestmentRecType1 = new InvestmentAsset__c(Name='Fixed Income', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Fixed Income').getRecordTypeId());
    	InvestmentAsset__c objInvestmentRecType2 = new InvestmentAsset__c(Name='Gold and Silver', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Gold and Silver').getRecordTypeId());
    											 
    	InvestmentAsset__c objInvestmentRecType3 = new InvestmentAsset__c(Name='Mutual Fund', 
    											 RecordTypeId__c=RECORD_TYPE_INFO_INVESTMENTMAP.get('Mutual Fund').getRecordTypeId());
    	lstRecTypesInvestment.add(objInvestmentRecType);										 
    	lstRecTypesInvestment.add(objInvestmentRecType1);
    	lstRecTypesInvestment.add(objInvestmentRecType2);	
    	lstRecTypesInvestment.add(objInvestmentRecType3);
    	
    	insert lstRecTypesInvestment;
    	
    	List<smagicbasic__SMS_Template__c> lstTemplate = new List<smagicbasic__SMS_Template__c>();
    	
    	smagicbasic__SMS_Template__c template= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Discontinuation Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	
    	smagicbasic__SMS_Template__c template1= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Renewal Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	lstTemplate.add(template);
    	lstTemplate.add(template1);
    	
    	insert lstTemplate;
    	
     //Insert Account record
    	Account objBPAccount = new Account(Name='Parner Account Test',
    								RecordTypeId= RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	insert 	objBPAccount;
    	
	    
		//RecordType objRT = [Select Id from RecordType where Name = 'Client' and SobjectType = 'Account'];
		Account objAccount = new Account(LastName='Test',FirstName='Test',Adjustment_Factor__c='2',
	                       PersonTitle='TestData', PersonBirthdate= system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463732345',
	                       Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',
	                       Retirement_Year__c=2034, Residential_Status_del__c='own', Retirement_Age__c='58', Estimated_Life_Expectancy__c='67',
	                       Estimated_Life_EndYear__c=2041, Relationship_to_Entity__pc='husband', RecordTypeId = RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
	    insert objAccount;
	    
	    
	    Investment_Asset__c inv = new Investment_Asset__c(Entity__c=objAccount.id,action__c='yes',RecordTypeId=RECORD_TYPE_INFO_INVESTMENTMAP.get('Stocks').getRecordTypeId(),
	    												Maturity_Date__c = system.today());
	    insert inv;		
	    Investment_Asset__c inv1 = new Investment_Asset__c(Entity__c=objAccount.id,action__c='yes',RecordTypeId=RECORD_TYPE_INFO_INVESTMENTMAP.get('Mutual Fund').getRecordTypeId(),
	    												Maturity_Date__c = system.today());
	    insert inv1;	
	    				
	    List<Approve_Action_Plan__c> lstAP = new List<Approve_Action_Plan__c>();										
	    Approve_Action_Plan__c objAAP1 = new Approve_Action_Plan__c(Account__c = objAccount.Id,Investment_Asset__c = inv1.Id);
	    lstAP.add(objAAP1);
	    
	    Approve_Action_Plan__c objAAP2 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    lstAP.add(objAAP2);
        
        insert lstAP;
        
        List<Execution_Tracker__c> lstET = new List<Execution_Tracker__c>();
        Execution_Tracker__c objET1 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Total_Remaining_Balance__c = 200,Agreed_Amount__c = 202,Executed_Product_Name__c = 'Axis Lumpsum Fund1',
        									Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP1.Id, Type__c = 'Lumpsum',Action__c = 'STP To');
        lstET.add(objET1);
        Execution_Tracker__c objET2 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Total_Remaining_Balance__c = 200,Agreed_Amount__c = 202,Application_Status__c = 'Closed', Approve_Action_Plan__c = objAAP2.Id, Type__c = 'Lumpsum',Action__c = 'Lumpsum');
        lstET.add(objET2);
        insert lstET;
        
         Product_Manufacturer_Master__c PM1 = new Product_Manufacturer_Master__c(Name='Axis1', Short_Code__c='Axis1', 
        																		Is_Active__c=true);
        insert PM1;
        List<Product_Master__c> lstProductMaster = new List<Product_Master__c>();
        //Insert SIP Product record
        Product_Master__c objProduct = new Product_Master__c(Product_Manufacturer__c=PM1.Id, 
                                                            Is_Active__c=true, Product_Name__c='Axis SIP Fund', ProductType__c='Mutual Fund'
                                                            ,Investment_Type__c='SIP');
        lstProductMaster.add(objProduct);   
        
        //Insert Lumpsum Product record
        Product_Master__c objProduct1 = new Product_Master__c(Product_Manufacturer__c=PM1.Id, 
                                                            Is_Active__c=true, Product_Name__c='Axis Lumpsum Fund1', ProductType__c='Mutual Fund'
                                                            ,Investment_Type__c='Lumpsum');
        lstProductMaster.add(objProduct1);   
        
        
        //Insert Life Insurace Product record
        Product_Master__c objProduct2 = new Product_Master__c(Product_Manufacturer__c=PM1.Id, 
                                                            Is_Active__c=true, Product_Name__c='Axis Life Insurance', ProductType__c='Life Insurance'
                                                            ,Policy_Type__c='Term Life');
        lstProductMaster.add(objProduct2);  
        
         
        //Insert General Insurace Product record
        Product_Master__c objProduct3 = new Product_Master__c(Product_Manufacturer__c=PM1.Id, 
                                                            Is_Active__c=true, Product_Name__c='Bajaj General Insurance', ProductType__c='General Insurance'
                                                            ,Policy_Type__c='Critical Illness');
        lstProductMaster.add(objProduct3);  
        
        insert lstProductMaster;
        
         ARPP_Detail__c objARPP = new ARPP_Detail__c(Entity__c = objAccount.Id,Approve_Action_Plan__c = objAAP1.id,
       												Product__c= objProduct.Id, Type__c = 'Lumpsum', Commission__c = null,
       												Actual_Commission__c = null,Remark__c = 'Product Detail is not Found',
       												ET_Remark__c = 'Actual Product Commision not found',
       												Execution_Tracker__c = objET1.Id,
       												Action_Plan_Amount__c = 1000,Execution_Tracker_Actual_Product__c= null);
       												
        insert objARPP;			
        
        Test.startTest();
      	try
      	{
      		ApexPages.currentPage().getParameters().put('eid', objAccount.id);
	        Apexpages.currentPage().getParameters().put('etid', objET1.Id);
	        Apexpages.currentPage().getParameters().put('type', 'Lumpsum');
			Apexpages.currentPage().getParameters().put('userType', 'opsTeam');
	        EditETforSTPController objEETC2 = new EditETforSTPController(); 
	      	objEETC2.updateARPPDetail();
	      	//objEETC2.getApplicationStatus();
      	}
      	catch(Exception e)
      	{
      		
      	}
      	
        Test.stopTest();
	}
}