Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Debt__c</fullName>
        <defaultValue>7</defaultValue>
        <label>Debt</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_Estimated_Life_Expectancy__c</fullName>
        <label>Default Estimated Life Expectancy</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Retirement_Age__c</fullName>
        <label>Default Retirement Age</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equity__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Equity</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Return_on_Investment__c</fullName>
        <label>Expected Return on Investment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gold_Growth_Rate__c</fullName>
        <defaultValue>10</defaultValue>
        <description>Added to decide growth rate of new record type GOLD in Investment Asset.</description>
        <label>Gold Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Gold__c</fullName>
        <defaultValue>10</defaultValue>
        <label>Gold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Income_Growth_Rate__c</fullName>
        <label>Income Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Number_Of_Months__c</fullName>
        <label>Number Of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan_Generation_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Added in FP changes</description>
        <label>Plan Generation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>To select user.</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Ffreedom</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_profile__c</fullName>
        <label>Risk profile</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stock_Growth_Rate__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Stock Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is created to select the related virtual partner of that entity.

Practice Owner (Partner): Account Record Type</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Entity_Global_Assumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entity Global Assumptions</relationshipLabel>
        <relationshipName>ntity_Global_Assumptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CashFlow_Projection_End_Year__c</fullName>
        <label>CashFlow Projection End Year</label>
        <picklist>
            <picklistValues>
                <fullName>Retirement Year</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Life Expectency</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Data_Collection_Analysis_Control__c</fullName>
        <label>Data Collection Analysis Control</label>
        <picklist>
            <picklistValues>
                <fullName>Portfolio Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Networth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Flow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Allocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Succession Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Assumptions</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Default_Estimated_Life_Expectancy__c</fullName>
        <label>Default Estimated Life Expectancy</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Retirement_Age__c</fullName>
        <description>This field is created by the Eternus . If the field Retirement Age form the account is null then fetch this field.</description>
        <label>Default Retirement Age</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Return_on_Investment__c</fullName>
        <label>Expected Return on Investment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Financial_Planing_Output_Report__c</fullName>
        <label>Financial Planing Output Report</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disclosure Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goal Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Goal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summary Action Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annexure 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Acknowledgement</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Goals_Allowed_List__c</fullName>
        <label>Goals Allowed List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marriage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parental Responsibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money to Heirs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Gold_Growth_Rate__c</fullName>
        <defaultValue>8</defaultValue>
        <description>Added to decide growth rate of new record type GOLD in Investment Asset.</description>
        <label>Gold Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Income_Growth_Rate__c</fullName>
        <label>Income Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>No_of_Goals__c</fullName>
        <label>No of Goals</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_Months__c</fullName>
        <label>Number Of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Growth_Rate__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Stock Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Entity Global Assumption</label>
    <nameField>
        <label>Entity Global Assumption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Global Assumptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/GlobalAssumptionController.cls
/*
	Revision History:
	
    Version     Version Author     Date         Comments
    1.0         Persistent         NA  		  	Initial Draft
   
	2.0			Manasi Ranade	   25/05/2011   Added two fields Default_Retirement_Age__c and Default_Estimated_Life_Expectancy__c
					  							in Entity_Global_Assumption__c object.
					  							so fetching those values in GlobalAssumptionController constructor.   
	2.0			Manasi Ranade	  30/05/2011	Added cancel button to cancel the operation.	
	3.0			Prajakta Sanap    01/04/2013    Added Gold Growth Rate for the new record type Gold in Investment Asset			  							 											
*/

public class GlobalAssumptionController 
{
    public GlobalAssumptionService globalAssService{get;set;}
    public Entity_Global_Assumption__c globalAssumption{get;set;}
    public Entity_Global_Assumption__c entityAssumption{get;set;}
    public List<GoalProfileBean>stdGoalProfileList{get;set;}
    //Added on : 1/2/2013 : Aditi Satpute : Hide Save button for Business Partner Financial Plan //Sanat
	public Boolean isDisplaySaveButton{get;set;}
	
    /* Commented Global Assumption Changes
	public List<Account> lstAcc
    {
    	get
    	{
    		if(lstAcc == null)
    		{
    			lstAcc = [select Id ,Equity__c,Debt__c,Gold__c from Account where id =: entityId];
    		}
    		return lstAcc;
    	}
    set; 
    } 
    public List<Account>  lstToUpdate
    {
    	get
    	{
    		if(lstToUpdate == null)
    			lstToUpdate = new List<Account>();
    		return lstToUpdate;
    	}
    	set;
    }*/
    public List<GoalProfileBean> customGoalProfileList{get;set;}
    public Boolean isDisplay{get;set;}
    public String entityId{get;set;} 
    public double Equity{get;set;}
    public double Debt{get;set;}
    public double Gold{get;set;}
    
    public String riskProfile{get;set;} 
    public String goalProfileTitle{get;set;}
 
	public GlobalAssumptionController()
	{
		isDisplay=false; 
		//Code Added on : 1/2/2013 : Aditi Satpute : Hide Save button for Business Partner Financial Plan : by default true //Sanat
   		isDisplaySaveButton = true;
   		
		entityAssumption = new Entity_Global_Assumption__c();
		stdGoalProfileList = new List<GoalProfileBean>();
		globalAssService = new GlobalAssumptionService();
	 	entityId = Apexpages.currentPage().getParameters().get('entityId');
	    //globalAssumption = globalAssService.getEntityGlobalAssumption(entityId);
	    List<Entity_Global_Assumption__c> globalAssumptionList=[
                                                               SELECT 
                                                                      Expected_Return_on_Investment__c,Income_Growth_Rate__c,
                                                                      Inflation_Rate__c,Account__c,Number_Of_Months__c ,Stock_Growth_Rate__c,
                                                                      Gold_Growth_Rate__c,	   /* Prajakta - FP changes - 01-04-2013 */
                                                                      Default_Estimated_Life_Expectancy__c,Default_Retirement_Age__c,
                                                                      Data_Collection_Analysis_Control__c, //Gaurav- 09-04-2013
                                                                      Financial_Planing_Output_Report__c,
                                                                      CashFlow_Projection_End_Year__c ,/* Aditi - FP enhancement changes - 15-10-2013 */
                                                                      Goals_Allowed_List__c,
                                                                      No_of_Goals__c
                                                               FROM
                                                                       Entity_Global_Assumption__c
                                                               WHERE 
                                                                        Account__c=:entityId
                                                                        
                                                               ORDER BY CreatedDate desc
                                                               ];
        //globalAssumption = globalAssumptionList[0];   
        entityAssumption = globalAssumptionList[0];                                                     
		//entityAssumption.Account__c = entityId;
	/*	entityAssumption.No_of_Goals__c = globalAssumption.No_of_Goals__c;
		entityAssumption.Data_Collection_Analysis_Control__c = globalAssumption.Data_Collection_Analysis_Control__c;
		entityAssumption.Financial_Planing_Output_Report__c = globalAssumption.Financial_Planing_Output_Report__c;
		entityAssumption.Goals_Allowed_List__c = globalAssumption.Goals_Allowed_List__c;
	*/	
		//Added Code on : 1/2/2013 : Aditi Satpute : Hide Save button for Business Partner Financial Plan //Sanat
	    User objBPUser = [Select Profile.Name, ProfileId, UserType, Name, Id From User where Id =: UserInfo.getUserId() limit 1];
	    if(objBPUser.UserType.equalsIgnoreCase('PowerPartner'))
	    {
	    	isDisplaySaveButton = false;
	    }	
		
		//if(globalAssumption != null )
		//{
			/*//entityAssumption.id = globalAssumption.id;
			if(globalAssumption.Expected_Return_on_Investment__c!=null)
			{
				entityAssumption.Expected_Return_on_Investment__c = globalAssumption.Expected_Return_on_Investment__c;
			}
			if(globalAssumption.Income_Growth_Rate__c!=null)
			{
				entityAssumption.Income_Growth_Rate__c=globalAssumption.Income_Growth_Rate__c;
			}
			if(globalAssumption.Inflation_Rate__c!=null)
			{
				entityAssumption.Inflation_Rate__c=globalAssumption.Inflation_Rate__c;
			}
			if(globalAssumption.Number_Of_Months__c!=null)
			{
				entityAssumption.Number_Of_Months__c=globalAssumption.Number_Of_Months__c;
			}
			// Eternus Solutions      
			// Author  : Manasi Ranade
			// Issue Id: F0018      
			// Date    : 27/05/2011
			// Purpose : Added two fields Default_Retirement_Age__c and Default_Estimated_Life_Expectancy__c
		  	//						in Entity_Global_Assumption__c object.
			
			if(globalAssumption.Default_Retirement_Age__c!=null)
			{
				entityAssumption.Default_Retirement_Age__c = globalAssumption.Default_Retirement_Age__c;
			}
			if(globalAssumption.Default_Estimated_Life_Expectancy__c!=null)
			{
				entityAssumption.Default_Estimated_Life_Expectancy__c = globalAssumption.Default_Estimated_Life_Expectancy__c;
			}
			if(globalAssumption.Stock_Growth_Rate__c!=null)
			{
				entityAssumption.Stock_Growth_Rate__c = globalAssumption.Stock_Growth_Rate__c;
			}
			// Prajakta - FP changes - 01-04-2013 
			if(globalAssumption.Gold_Growth_Rate__c!=null)	   
			{
				entityAssumption.Gold_Growth_Rate__c = globalAssumption.Gold_Growth_Rate__c;
			}
			if(globalAssumption.CashFlow_Projection_End_Year__c!=null)	   
			{
				entityAssumption.CashFlow_Projection_End_Year__c = globalAssumption.CashFlow_Projection_End_Year__c;
			}
		*/
			//Commented Global Assumption Changes
			//==================================================================================================================================
			 system.debug('*********EntityId**: GlobalAssumptionController*****'+entityId);
			 
 	 	 Account objAcc = [select Id, Name, Related_To__c, Virtual_Partner__c, Risk_profile__c, OwnerId,
 	 	 							Plan_Generation_Date__c
 	 	 							from Account where Id = :  entityId];
 	 	 system.debug('****controller*****objAcc*******'+objAcc);
 	 	 
 	 	 Integer currentYear = objAcc.Plan_Generation_Date__c != null ? objAcc.Plan_Generation_Date__c.year() : system.today().year();
 	 	 riskProfile = objAcc.Risk_profile__c;
		 //error.debugLog('============riskProfile=============='+riskProfile);
		 
		 goalProfileTitle = 'Standard Goal Profile';
		 if(riskProfile != null)
		 {
		 	if(riskProfile == 'High')
		 		goalProfileTitle = 'High Goal Profile'; 
		 	else if(riskProfile == 'Medium')
		 		goalProfileTitle = 'Medium Goal Profile';
		 	else if(riskProfile == 'Low')
		 		goalProfileTitle = 'Low Goal Profile';
		 	/*else if(riskProfile == '' || riskProfile == null)
		 		goalProfileTitle = 'Standard Goal Profile';*/
		 }
		 
 	 	 Account FfreedomAcc = new Account();
 	 	 Account BusinessAcc = new Account();
 	 	 Account VirtualAcc = new Account();
 	 	 List<Account> lstVirtualAcc = new List<Account>();
 	 
 	 	 double ReturnExpected;
 	 	 system.debug('**objAcc.Related_To__c**'+objAcc.Related_To__c);
 	 	 if(objAcc.Related_To__c == 'Ffreedom')
 	 	 {
 	 	 	FfreedomAcc = [select id,Expected_Return_on_Investment__c,Equity__c,Gold__c,Debt__c,Income_Growth_Rate__c,Inflation_Rate__c,
 	 	 							Gold_Growth_Rate__c,
 	 	 							Default_Estimated_Life_Expectancy__c,Number_Of_Months__c,Stock_Growth_Rate__c,Default_Retirement_Age__c 
 	 	 					from Account 
 	 	 					where Related_To__c = 'Ffreedom' 
 	 	 					and RecordTypeId =: RecTypes__c.getInstance('General_Business').Record_Type_Value__c 
 	 	 					limit 1];
 	 	 	Equity = FfreedomAcc.Equity__c;
 	 	 	Debt = FfreedomAcc.Debt__c;
 	 	 	//Gold = FfreedomAcc.Gold__c;
			if(currentYear > 2013)
            {
             	Gold = FfreedomAcc.Gold__c;
            }
            else
            {
             	Gold = Double.valueOf(Label.Gold_Interest_Rate);
            }
 	 	 }
 	 	 else if(objAcc.Related_To__c == 'Business Partner')
 	 	 {
 	 	 	map<id,User> mapUser = new map<id,User>([select Id, Name, ProfileId, ContactId, Profile.Name from User]);
 	 	 	system.debug('**mapUser**' + mapUser);
 	 	 	map<id,Contact> mapContact = new map<id,Contact>([select id,AccountId from Contact]);
 	 	 	
 	 	 	map<id,Account> BusinessAccMap = new map<id,Account>
							([select id,Expected_Return_on_Investment__c,Equity__c,Gold__c,Debt__c,Income_Growth_Rate__c,Inflation_Rate__c,
									Gold_Growth_Rate__c,
 	 	 							Default_Estimated_Life_Expectancy__c,Number_Of_Months__c,Stock_Growth_Rate__c,Default_Retirement_Age__c 
 	 	 					from Account 
 	 	 					where Related_To__c = 'Business Partner' 
 	 	 					and RecordTypeId =: RecTypes__c.getInstance('General_Business').Record_Type_Value__c 
 	 	 				    ]);
 	 	 				    
 	 	 	Account objBusinessAcc = new Account();
 	 	 	User objUser = new User();
 	 	 	Contact objContact = new Contact();
 	 	 	
 	 	 	system.debug('============objAcc.OwnerId=============='+objAcc.OwnerId);
 	 	 	if(mapUser.containsKey(objAcc.OwnerId))
 	 	 	{
 	 	 		objUser = mapUser.get(objAcc.OwnerId);
 	 	 		
 	 	 		if(objUser != Null)
 	 	 		{
					if(mapContact.containsKey(objUser.ContactId))
					{	
						objContact = mapContact.get(objUser.ContactId);
						system.debug('============objContact=====in if========='+objContact);
						if(objContact != Null)
						{
							if(BusinessAccMap.ContainsKey(objContact.AccountId))
							{
								objBusinessAcc = BusinessAccMap.get(objContact.AccountId);
								if(objBusinessAcc != null)
								{
									system.debug('============objBusinessAcc=====in if========='+objBusinessAcc);
									Equity = objBusinessAcc.Equity__c;
						 	 	 	Debt = objBusinessAcc.Debt__c;
						 	 	 	//Gold = objBusinessAcc.Gold__c;
						 	 	 	if(currentYear > 2013)
				                     {
				                     	Gold = objBusinessAcc.Gold__c;
				                     }
				                     else
				                     {
				                     	Gold = Double.valueOf(Label.Gold_Interest_Rate);
				                     } 	 	 	 		
								}
							} 
						}
					}
 	 	 		}
 	 	 	}
 	 	 }
 	 	 
 	 	 else if(objAcc.Related_To__c == 'Virtual Partner')
 	 	 {
 	 	 	 map<Id,Account> virtualAccMap = new map<Id,Account> 
 	 	 					([select id,Expected_Return_on_Investment__c,Equity__c,Gold__c,Debt__c,Income_Growth_Rate__c,Inflation_Rate__c,
 	 	 							Gold_Growth_Rate__c,
 	 	 							Default_Estimated_Life_Expectancy__c,Number_Of_Months__c,Stock_Growth_Rate__c,Default_Retirement_Age__c 
 	 	 					from Account 
 	 	 					where Related_To__c = 'Virtual Partner' 
 	 	 					and RecordTypeId =: RecTypes__c.getInstance('General_Business').Record_Type_Value__c]);
 	 	 	Account objVirtualAcc = new Account();				
        	if(virtualAccMap.containsKey(objAcc.Virtual_Partner__c))
       		{
				objVirtualAcc = virtualAccMap.get(objAcc.Virtual_Partner__c);
				if(objVirtualAcc != null)
				{
					 Equity = objVirtualAcc.Equity__c;
		 	 	 	 Debt = objVirtualAcc.Debt__c;
		 	 	 	 if(currentYear > 2013)
                     {
                     	Gold = objVirtualAcc.Gold__c;
                     }
                     else
                     {
                     	Gold = Double.valueOf(Label.Gold_Interest_Rate);
                     } 
		 	 	 	 //Gold = objVirtualAcc.Gold__c;		
					 system.debug('============objVirtualAcc=============='+objVirtualAcc);
				}
        	 }
 	 	 }
 	 	 
		//==================================================================================================================================
	  	//}
	 
       stdGoalProfileList = globalAssService.getStdGoalProfileList(riskProfile); 
       customGoalProfileList=globalAssService.getCustomGoalProfileList(entityId);
  }
   
     public Pagereference display(){
     	globalAssService.isDisplay = !(globalAssService.isDisplay);
     	return null;
     } 
     public Pagereference save(){
     	/*Commented Global Assumption Changes
     	for(Account objAcc : lstAcc)
		{
			objAcc.Equity__c = equity;
			objAcc.Debt__c = debt;
			objAcc.Gold__c = gold;
			system.debug('*****new objAcc****'+objAcc);
			lstToUpdate.add(objAcc);
		}	
		update lstToUpdate;
     	*/
     	globalAssService.saveAssumption(entityAssumption,entityId);
     	system.debug('****customGoalProfileList**in save ****'+customGoalProfileList);
      	globalAssService.saveGoalProfile(stdGoalProfileList,customGoalProfileList,entityId);
      	Pagereference pageRef=new pageReference ('/apex/GlobalAssumptionPage?entityId='+entityId+'&tabname=Financial Planning');
      	pageRef.setRedirect(true);
     	return pageRef; 
     }	  
     
   /* public List<selectOption> getCashFlowProjectionPicklist()
    { 
       List<selectOption> options = new List<selectOption>();
        Schema.DescribeFieldResult field = Schema.sObjectType.Entity_Global_Assumption__c.fields.CashFlow_Projection_End_Year__c;
        List<Schema.PicklistEntry> picklist = field.getPicklistValues();
        //options.add(new selectOption('', '--None--'));
        for(Schema.PicklistEntry p : picklist) 
        {
            options.add(new selectOption(p.getLabel(), p.getLabel()));
        }
        
        return options;
    }*/
     
    /** Eternus Solutions      **/
	/** Author  : Manasi Ranade*/
	/** Issue Id: F0023      **/
	/** Date    : 30/05/2011 **/
	/** Purpose : Added cancel button to cancel the operation.	**/
	/****************************************************/
 	public Pagereference Cancel(){
 		Pagereference PageGlobalAssumption = new pageReference ('/apex/GlobalAssumptionPage?entityId='+entityId+'&tabname=Financial Planning');
 		PageGlobalAssumption.setRedirect(true);
 		return PageGlobalAssumption;
 	}	
}