Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Portal_Id__c</fullName>
        <label>Portal_Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Synched_Date_Time__c</fullName>
        <label>Synched Date Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/SyncDeletedRecords__c.object
<CustomObject>
    <description>it Contain all deleted records</description>
    <fields>
        <fullName>SObjectType__c</fullName>
        <label>SObjectType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sobject_ID__c</fullName>
        <label>Sobject_ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sync_DataTime__c</fullName>
        <description>same as last Modified datetime</description>
        <label>Sync_DataTime</label>
        <type>DateTime</type>
    </fields>
    <label>SyncDeletedRecord</label>
    <nameField>
        <displayFormat>SDR-{0000}</displayFormat>
        <label>SyncDeletedRecordsID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SyncDeletedRecords</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Portal_Id__c</fullName>
        <label>Portal Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Synched_Date_Time__c</fullName>
        <label>Synched Date Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/HandlerForAfterDeleteOnUser.cls
public with sharing class HandlerForAfterDeleteOnUser 
{
    public void afterDeleteUser(list<User> lstUser)
    {
        
        SyncDeletedRecords__c objSDR = null;
         list<SyncDeletedRecords__c> lstSDR = new List<SyncDeletedRecords__c>();
         
        for(User objUser : lstUser)
        {
        	objSDR = new SyncDeletedRecords__c();
            objSDR.Sobject_ID__c = objUser.ID;
            objSDR.Sync_DataTime__c  = objUser.Synched_Date_Time__c;
            objSDR.SObjectType__c = 'User';
            
            lstSDR.add(objSDR);
        }   
        insert lstSDR;
    
    }
    
     @IsTest(seealldata = true) 
      public static void testCoverage() 
      {
         TestData_Ffreedom testData = new TestData_Ffreedom();
         Account parent = new Account();
          parent = testData.initializeAccount();
          insert parent;
          Account child = new Account(); 
          child = testData.init_FamilyMember(parent);
          child.Portal_Id__c = '1';
          insert child;
          User obUser = [select Id from User limit 1];
          /*User objuser = new User();
          
          objuser.LastName = 'test user';
          objuser.IsActive=true; 
          objuser.Email='a@gmail.com'; 
          objuser.Alias='a'; 
          objuser.CommunityNickname='sdsad';
          objuser.TimeZoneSidKey='GMT';
          objuser.LocaleSidKey ='en_GB';   
          objuser.EmailEncodingKey='ISO-8859-1';   
          objuser.ProfileId=objProfile.Id;
          objuser.LanguageLocaleKey='en_US';
          insert objuser;*/
             
             
                    test.startTest();
             // delete obUser ;
          test.stopTest();
      }
}