Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Members</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Planner_Details__c.object
<CustomObject>
    <label>Planner Details</label>
    <nameField>
        <label>Planner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planner Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Portfolio_Report__c.object
<CustomObject>
    <fields>
        <fullName>Absolute_Ret__c</fullName>
        <label>Absolute Ret</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Annualized_Ret__c</fullName>
        <label>Annualized Ret</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <label>Asset Class</label>
        <picklist>
            <picklistValues>
                <fullName>Debt: Floating Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Liquid Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Medium Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Ultra Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity: Tax Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid: Monthly Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid: Equity Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity : Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity: Diversified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Dividend_Reivestment__c</fullName>
        <label>Dividend Reivestment</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portfolio Report</relationshipLabel>
        <relationshipName>Portfolio_Report</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Folio_Number__c</fullName>
        <label>Folio Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Gain__c</fullName>
        <label>Gain</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Nav_p__c</fullName>
        <label>Nav</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Portfolio_Type__c</fullName>
        <label>Portfolio Type</label>
        <picklist>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Purchase Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scheme_Scrip_Name__c</fullName>
        <label>Scheme/Scrip Name</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>NOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UniqueName__c</fullName>
        <externalId>true</externalId>
        <label>UniqueName</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Units_Quanitity__c</fullName>
        <label>Units/Quanitity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Portfolio Report</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portfolio Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Purchase_Sales_Report__c.object
<CustomObject>
    <fields>
        <fullName>Absolute_Return__c</fullName>
        <label>Absolute Return</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Purchase Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annualized_Return__c</fullName>
        <label>Annualized Return</label>
        <precision>17</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <label>Asset Class</label>
        <picklist>
            <picklistValues>
                <fullName>Debt: Floating Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Liquid Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Medium Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Ultra Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity: Tax Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid: Monthly Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid: Equity Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity : Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity: Diversified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Date__c</fullName>
        <label>Current Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DividendReivestment__c</fullName>
        <label>DividendReivestment</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Purchase_Report</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Folio_Number__c</fullName>
        <label>Folio Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NAV_Date__c</fullName>
        <label>NAV Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NAV__c</fullName>
        <label>NAV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheme_Name__c</fullName>
        <label>Scheme Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unique_Name__c</fullName>
        <label>Unique Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Purchase Sales Report</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Purchase Sales Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Sales Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <label>Asset Class</label>
        <picklist>
            <picklistValues>
                <fullName>Equity: Mid &amp; Small Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity: Large &amp; Mid Cap</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Date__c</fullName>
        <label>Current Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Folio_Number__c</fullName>
        <label>Folio Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gain__c</fullName>
        <label>Gain</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Portfolio_Type__c</fullName>
        <label>Portfolio Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Purchase Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UniqueName__c</fullName>
        <externalId>true</externalId>
        <label>UniqueName</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>current_Value__c</fullName>
        <label>current Value</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tranctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/Test_PortfolioController.cls
@isTest
private class Test_PortfolioController {
  
  public static testMethod void testPortal()
  {
  	try
    {
    Test.startTest();
    
    Map<Id, Account> childMap = new Map<Id, Account>();
    List<Account> allEntities = new List<Account>();
    List<Account> updateEntities = new List<Account>();
    
    List<AccountShare> shares = new List<AccountShare>();
    List<Portfolio_Report__c> allPortfolios = new List<Portfolio_Report__c>();
    List<Purchase_Sales_Report__c> allPurchaseSales = new List<Purchase_Sales_Report__c>();
    List<PortfolioController.detailedReportWrapper> detailedReportWrapperList =new List<PortfolioController.detailedReportWrapper>();
    List<PortfolioController.childDetailedReportWrapper> childDetailedReportWrapperList=new List<PortfolioController.childDetailedReportWrapper>();
    List<PortfolioController.summaryReportWrapper>  parentSummaryDataList =new List<PortfolioController.summaryReportWrapper>();
    List<PortfolioController.childSummaryReportWrapper> childSummaryReportWrapperList=new List<PortfolioController.childSummaryReportWrapper> ();
    
    
        Account son = [select Id, Parent_Entity__c from Account where Parent_Entity__c != null and RecordTypeId !=:RecTypes__c.getInstance('General_Business').Record_Type_Value__c LIMIT 1 ];
        Account act = [select Id, PersonContactId from Account where Id =:son.Parent_Entity__c and RecordTypeId !=:RecTypes__c.getInstance('General_Business').Record_Type_Value__c];
      
        datetime t = System.now();
        date d = Date.newInstance(t.year(),t.month(),t.day());
       
      Portfolio_Report__c Parent_Portfolio2 = new Portfolio_Report__c( Entity__c=act.Id,UniqueName__c='UniqueName2',Asset_Class__c='Debt: Floating Rate ',  Scheme_Scrip_Name__c='Kotak Mahindra',Transaction_Type__c='SIP', Current_Value__c=2000,Portfolio_Type__c='MF',Units_Quanitity__c=100,Purchase_Amount__c=200,Folio_Number__c ='2',Absolute_Ret__c=10,Annualized_Ret__c=20,Dividend_Reivestment__c ='Yes',Nav_p__c=5,Gain__c=10,Date__c=d);
      allPortfolios.add(Parent_Portfolio2);
      
      Portfolio_Report__c son_Portfolio2 = new Portfolio_Report__c( Entity__c=son.Id,UniqueName__c='UniqueName4',Asset_Class__c='Debt: Floating Rate ',  Scheme_Scrip_Name__c='HDFC',Transaction_Type__c='NOR', Current_Value__c=2000,Portfolio_Type__c='EQ',Units_Quanitity__c=100,Purchase_Amount__c=200,Folio_Number__c ='4',Absolute_Ret__c=10,Annualized_Ret__c=20,Dividend_Reivestment__c ='Yes',Nav_p__c=5,Gain__c=10,Date__c=d);
      allPortfolios.add(son_Portfolio2);
      
      
      	 insert allPortfolios;
    ID ProfileID = [ Select id from Profile where name = 'Customer Portal Standard - Custom'].id;
    
    List<User> u1 = [select Id from User where contactid = :act.PersonContactId];
    User user;
    if(u1 == null || u1.isEmpty()){
      user = new User( email='test-user@fakeemail.com', contactid = act.PersonContactId, profileid = ProfileID, UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1',TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', FirstName = 'Test_Parent_Fname', LastName = 'Test_Parent_Lname' );
      insert user; 
    
    }
    else{
      user= u1[0];
    }
    
    
        Purchase_Sales_Report__c parentPS3=new Purchase_Sales_Report__c(Entity__c=act.Id,Unique_Name__c='UniqueName2',Units__c=10,Absolute_Return__c=10,Type__c='MF',Scheme_Name__c='HDFC',NAV__c=10,Folio_Number__c='1',Current_Value__c=1000,Annualized_Return__c=2, Amount__c=100, DividendReivestment__c='Yes', Transaction__c='Sales',NAV_Date__c=d,Current_Date__c=d);
      allPurchaseSales.add(parentPS3);
      Purchase_Sales_Report__c parentPS4=new Purchase_Sales_Report__c(Entity__c=act.Id,Unique_Name__c='UniqueName2',Units__c=10,Absolute_Return__c=10,Type__c='MF',Scheme_Name__c='Birla Sun Life',NAV__c=10,Folio_Number__c='1',Current_Value__c=1000,Annualized_Return__c=2, Amount__c=100, DividendReivestment__c='Yes', Transaction__c='Sales',NAV_Date__c=d,Current_Date__c=d);
      allPurchaseSales.add(parentPS4);
      Purchase_Sales_Report__c sonPS1=new Purchase_Sales_Report__c(Entity__c=son.Id,Unique_Name__c='UniqueName3',Units__c=10,Absolute_Return__c=10,Type__c='MF',Scheme_Name__c='Kotak Mahindra',NAV__c=10,Folio_Number__c='1',Current_Value__c=1000,Annualized_Return__c=2, Amount__c=100, DividendReivestment__c='Yes', Transaction__c='Sales',NAV_Date__c=d,Current_Date__c=d);
      allPurchaseSales.add(sonPS1);
      
      Purchase_Sales_Report__c sonPS4=new Purchase_Sales_Report__c(Entity__c=son.Id,Unique_Name__c='UniqueName4',Units__c=10,Absolute_Return__c=10,Type__c='MF',Scheme_Name__c='Kotak Mahindra',NAV__c=10,Folio_Number__c='1',Current_Value__c=1000,Annualized_Return__c=2, Amount__c=100, DividendReivestment__c='Yes', Transaction__c='Sales',NAV_Date__c=d,Current_Date__c=d);
      allPurchaseSales.add(sonPS4);
      
        
      insert   allPurchaseSales;
    
    
    AccountShare thisShare1 = new AccountShare(UserOrGroupId=user.Id,AccountId=son.Id,AccountAccessLevel='Read',OpportunityAccessLevel = 'Edit');
    shares.add(thisShare1);
    
    insert shares;
    
    System.runas(user){
      PortfolioController controller=new PortfolioController();
      User user2=controller.getCurrentUserDetails();
        detailedReportWrapperList=controller.getAllDataList();
        childDetailedReportWrapperList=controller.getAllChildDetailedRecords();
        parentSummaryDataList= controller.getSummaryDataList();
        childSummaryReportWrapperList=controller.getAllChildSummaryRecords();
        Planner_Details__c plan =controller.getPlannerDescription();
        String welcomeMessage=controller.getWelcomeMessage();
    }
    
      Test.stopTest();
       }
      catch(Exception e )
      {
      	system.debug('******error*****'+e);	
      }
  } 

}