Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Factor__c</fullName>
        <label>Adjustment Factor %</label>
        <picklist>
            <picklistValues>
                <fullName>-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Alternate_E_Mail_Address__c</fullName>
        <label>Alternate E-Mail Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alternate_Mobile__c</fullName>
        <label>Alternate Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_EndYear__c</fullName>
        <label>Estimated Life EndYear</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_Expectancy__c</fullName>
        <label>Estimated Life Expectancy</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Status_del__c</fullName>
        <label>Residential Status</label>
        <picklist>
            <picklistValues>
                <fullName>Permanent Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident but not Ordinary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Resident</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retirement_Age__c</fullName>
        <label>Retirement Age</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retirement_Year__c</fullName>
        <label>Retirement Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>General</description>
        <label>General</label>
    </recordTypes>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Approve_Action_Plan__c.object
<CustomObject>
    <description>Created for new action plan</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approve Action Plans</relationshipLabel>
        <relationshipName>Approve_Action_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Investment_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investment Asset</label>
        <referenceTo>Investment_Asset__c</referenceTo>
        <relationshipLabel>Approve Action Plans</relationshipLabel>
        <relationshipName>Approve_Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approve Action Plan</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approve Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Provided to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Handed over to Ops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approve_Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approve Action Plan</label>
        <referenceTo>Approve_Action_Plan__c</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ET_Status__c</fullName>
        <label>ET Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Floating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Floating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surrender Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/EditETforSurrenderLifeInsuranceTest.cls
/**
*  Test class for Controller class EditETforSurrenderLifeInsuranceTest
*
*   Revision History:
*
*   Version        Author             Date            Description
*   1.0            Aditi/Prajakta    05/04/2013      Initial Draft
*/

public with sharing class EditETforSurrenderLifeInsuranceTest 
{
	//test Method
	@isTest
	public static  void testEditETforSurrenderLifeInsurance()
	{
		
		Schema.DescribeSObjectResult DESCRIBE_RESULT = Account.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_MAP = DESCRIBE_RESULT.getRecordTypeInfosByName();
    	
    	Schema.DescribeSObjectResult DESCRIBE_RESULT_INVESTMENT = Investment_Asset__c.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_INVESTMENTMAP = DESCRIBE_RESULT_INVESTMENT.getRecordTypeInfosByName();
    	
    	//Insert RecordType record
    	List<RecTypes__c> lstRecTypes = new List<RecTypes__c>();
    	RecTypes__c objRecType = new RecTypes__c(Name='General_Business', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	
    	RecTypes__c objRecType1 = new RecTypes__c(Name='AccountFamily', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Family Member').getRecordTypeId());
    	RecTypes__c objRecType2 = new RecTypes__c(Name='AccountClient', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
    	
    	lstRecTypes.add(objRecType);										 
    	lstRecTypes.add(objRecType1);
    	lstRecTypes.add(objRecType2);	
    	insert lstRecTypes;
    	
    	List<smagicbasic__SMS_Template__c> lstTemplate = new List<smagicbasic__SMS_Template__c>();
    	
    	smagicbasic__SMS_Template__c template= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Discontinuation Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	
    	smagicbasic__SMS_Template__c template1= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Renewal Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	lstTemplate.add(template);
    	lstTemplate.add(template1);
    	
    	insert lstTemplate;
    	
        //Insert Account record
    	Account objBPAccount = new Account(Name='Parner Account Test',
    								RecordTypeId= RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	insert 	objBPAccount;
    	
	    
		//RecordType objRT = [Select Id from RecordType where Name = 'Client' and SobjectType = 'Account'];
		Account objAccount = new Account(LastName='Test',FirstName='Test',Adjustment_Factor__c='2',
	                       PersonTitle='TestData', PersonBirthdate= system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463732345',
	                       Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',
	                       Retirement_Year__c=2034, Residential_Status_del__c='own', Retirement_Age__c='58', Estimated_Life_Expectancy__c='67',
	                       Estimated_Life_EndYear__c=2041, Relationship_to_Entity__pc='husband', RecordTypeId =  RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
	    insert objAccount;
	    
	    Approve_Action_Plan__c objAAP1 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    insert objAAP1;
	    
	    Approve_Action_Plan__c objAAP2 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    insert objAAP2;
        
        List<Execution_Tracker__c> lstET = new List<Execution_Tracker__c>();
        Execution_Tracker__c objET1 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP2.Id, Type__c = Label.Surrender_Insurance);
        lstET.add(objET1);
        Execution_Tracker__c objET2 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Application_Status__c = 'Closed', Approve_Action_Plan__c = objAAP2.Id, Type__c = Label.Surrender_Insurance);
        lstET.add(objET2);
        insert lstET;
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('eid', objAccount.id);
        ApexPages.currentPage().getParameters().put('etid', objET1.id);
        Apexpages.currentPage().getParameters().put('id', objAAP2.Id);
		Apexpages.currentPage().getParameters().put('type', Label.Surrender_Insurance);
        EditETforSurrenderLifeInsurance objEETC1 = new EditETforSurrenderLifeInsurance(); 
      	objEETC1.assignTask();
      	objEETC1.getEntities();
      	objEETC1.updateExecutionTracker();
      	
      	ApexPages.currentPage().getParameters().put('eid', objAccount.id);
        ApexPages.currentPage().getParameters().put('etid', objET1.id);
        Apexpages.currentPage().getParameters().put('id', objAAP2.Id);
		Apexpages.currentPage().getParameters().put('type', 'other');
        EditETforSurrenderLifeInsurance objEETC2 = new EditETforSurrenderLifeInsurance(); 
      	objEETC2.assignTask();
      	objEETC2.getEntities();
      	objEETC2.updateExecutionTracker();
      	objEETC2.getApplicationStatus();
        Test.stopTest();
	}
}