Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Factor__c</fullName>
        <label>Adjustment Factor %</label>
        <picklist>
            <picklistValues>
                <fullName>-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Alternate_E_Mail_Address__c</fullName>
        <label>Alternate E-Mail Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alternate_Mobile__c</fullName>
        <label>Alternate Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_EndYear__c</fullName>
        <label>Estimated Life EndYear</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_Expectancy__c</fullName>
        <label>Estimated Life Expectancy</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>To select user.</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Ffreedom</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residential_Status_del__c</fullName>
        <label>Residential Status</label>
        <picklist>
            <picklistValues>
                <fullName>Permanent Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident but not Ordinary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Resident</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retirement_Age__c</fullName>
        <label>Retirement Age</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retirement_Year__c</fullName>
        <label>Retirement Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is created to select the related virtual partner of that entity.

Practice Owner (Partner): Account Record Type</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Will__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check yes if the Will has been created</description>
        <label>Will</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Manufacturer_Master__c.object
<CustomObject>
    <description>Created for product master</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product Master</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <description>Product master</description>
        <label>Short Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Master__c.object
<CustomObject>
    <fields>
        <fullName>Base_Product_Weightage__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Base Product Weightage</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Product Master object</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>No_of_Goals_Allowed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>No of Goals Allowed</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exchange-Traded Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FFreedom Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Added Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Manufacturer__c</fullName>
        <label>Product Manufacturer</label>
        <referenceTo>Product_Manufacturer_Master__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Product_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Grace_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renewal Grace Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Period_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renewal Period In Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Period_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Subscription Period In Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PRD-{000000}</displayFormat>
        <label>Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Price_Book__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education_Cess__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Education Cess</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Price_value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Products where Price Category is One Time, Price should be set as a decimal number containing 2 decimal places. e.g. 12545.22. 
Products where Price Category is other One Time, Price should be set as percentage containing 2 decimal places. e.g.  0.75.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Code</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Product Price Books</relationshipLabel>
        <relationshipName>Product_Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Service Tax</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sp_Education_Cess__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sp. Education Cess</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VAT</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <displayFormat>PRBK-{0000000}</displayFormat>
        <label>Product Price Book Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestPurchasedServicesController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 
 */
@isTest(seeAllData= true)
private class TestPurchasedServicesController {

    static testMethod void testPurchsedServicesController() {
        
        Product_Manufacturer_Master__c objProductManufacturer = new Product_Manufacturer_Master__c(Name='HDFC Life Insurance1', Short_Code__c='HDFCLI', Is_Active__c=true);
        insert objProductManufacturer;
        
        //Insert Product Master record
        Product_Master__c objProductMaster = new Product_Master__c(Product_Manufacturer__c= objProductManufacturer.Id, 
                                                            Is_Active__c=false, Product_Name__c='Starter Financial Planning', ProductType__c='Base Product',
                                                            Subscription_Period_In_Days__c = 365, No_of_Goals_Allowed__c = 3 ,Renewal_Period_In_Days__c = 365,Base_Product_Weightage__c=1,
                                                            Renewal_Grace_Days__c = 30);
        insert objProductMaster;
        
        //Insert Product Master record
        Product_Master__c objProductMaster1 = new Product_Master__c(Product_Manufacturer__c= objProductManufacturer.Id, 
                                                            Is_Active__c=false, Product_Name__c='Will1', ProductType__c='Value Added Services',
                                                            Subscription_Period_In_Days__c = 365, Renewal_Period_In_Days__c = 365,Base_Product_Weightage__c=1,
                                                            Renewal_Grace_Days__c = 30);
        insert objProductMaster1;
        
        //Insert Product Price Book record
        Product_Price_Book__c objPriceBook = new Product_Price_Book__c(Product_code__c = objProductMaster.Id, Price_value__c = 1500, Discount__c= 500,
                                                                        Service_Tax__c = 2, Sp_Education_Cess__c = 4, VAT__c = 5, Education_Cess__c = 6);
        insert objPriceBook;    
        
        
        //Insert Product Price Book record
        Product_Price_Book__c objPriceBook1 = new Product_Price_Book__c(Product_code__c = objProductMaster1.Id, Price_value__c = 1500, Discount__c= 500,
                                                                        Service_Tax__c = 2, Sp_Education_Cess__c = 4, VAT__c = 5, Education_Cess__c = 6);
        insert objPriceBook1;
        
        
        Account objGeneralAccount = new Account(Name='Parner Account Test',
    								RecordTypeId = RecTypes__c.getInstance('General_Business').Record_Type_Value__c);
    	insert 	objGeneralAccount;
    	
        Account objAccount = new Account(LastName='Test Freedom', Adjustment_Factor__c='2',Virtual_Partner__c = objGeneralAccount.Id,
                           PersonTitle='TestData', PersonBirthdate = system.today().addYears(- 25), PersonHomePhone='54623676',PersonMobilePhone='5463712345',
                           Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',PersonMailingStreet='aa',
                           PersonMailingCity='bbb', Residential_Status_del__c='own',Retirement_Age__c='30',Estimated_Life_Expectancy__c='67',
                           Estimated_Life_EndYear__c=2041,Relationship_to_Entity__pc='husband', Related_To__c ='Ffreedom',
                           RecordTypeId = RecTypes__c.getInstance('AccountClient').Record_Type_Value__c ,Will__c = true); 
        insert objAccount;
        ApexPages.currentPage().getParameters().put('entityid', String.valueOf(objAccount.Id));
        PurchasedServicesController objPurchasedServices1 = new PurchasedServicesController();
        objPurchasedServices1.selectedProductName = 'None';
        objPurchasedServices1.saveProduct();
        
        //Insert Entity record
        Account objAccount1 = new Account(LastName='Test Freedom', Adjustment_Factor__c='2',
                           PersonTitle='TestData',PersonBirthdate=system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463712345',Virtual_Partner__c = objGeneralAccount.Id,
                           Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',PersonMailingStreet='aa',
                           PersonMailingCity='bbb',Retirement_Year__c=2034,Residential_Status_del__c='own',Retirement_Age__c='58',Estimated_Life_Expectancy__c='67',
                           Estimated_Life_EndYear__c=2041,Relationship_to_Entity__pc='husband', Related_To__c ='Ffreedom',
                           RecordTypeId = RecTypes__c.getInstance('AccountClient').Record_Type_Value__c ,Will__c = true);   
        insert objAccount1;
        
       
        Test.startTest(); 
        
        ApexPages.currentPage().getParameters().put('entityid', String.valueOf(objAccount1.Id));
        PurchasedServicesController objPurchasedServices = new PurchasedServicesController();
        objPurchasedServices.selectedProductName = 'None';
        objPurchasedServices.saveProduct();
        
        objPurchasedServices.selectedProductName = 'Starter Financial Planning';    
        objPurchasedServices.selectedTopUpGoals = '1';
        objPurchasedServices.productPrice(); 
        objPurchasedServices.addValueAddedServices();
        objPurchasedServices.lstWrapperPurchaseOrder[0].selectedServiceName = 'None';
        objPurchasedServices.addValueAddedServices();
        objPurchasedServices.cancelProduct();
        objPurchasedServices.lstWrapperPurchaseOrder[0].selectedServiceName = 'Will1';
        ApexPages.currentPage().getParameters().put('index', '0');
        objPurchasedServices.valueAddedService();
        objPurchasedServices.lstWrapperPurchaseOrder[0].selectedServiceName = 'None';
        ApexPages.currentPage().getParameters().put('index', '0');
        objPurchasedServices.valueAddedService();
        objPurchasedServices.saveProduct();
        objPurchasedServices.selectedProductName = 'None';
        objPurchasedServices.productPrice();
        ApexPages.currentPage().getParameters().put('indexNumber', '0');
        objPurchasedServices.deleteService();
        Test.stopTest();                                        
    }
    
    
}//end of PurchasedServicesControllerTest class