Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Service_Deliverables__c.object
<CustomObject>
    <fields>
        <fullName>Call__c</fullName>
        <description>Jan –Dec  values will be for New Member
Q1 – Q4 for ‘Ongoing Member’ record type</description>
        <label>Call</label>
        <picklist>
            <picklistValues>
                <fullName>January</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>February</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>March</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>April</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>May</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>June</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>July</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>August</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>September</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>October</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>November</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>December</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This flag will be checked to true once the current financial year ends</description>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>This will be last day of the current financial year</description>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>Cheque Received Date + 1 yr (Entity/Renewal record)</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <description>Q1 – Q4 for “New Member”</description>
        <label>Meeting</label>
        <picklist>
            <picklistValues>
                <fullName>Q1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st Half Year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd Half Year</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>RelatedAccount__c</fullName>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Deliverables</relationshipLabel>
        <relationshipName>Service_Deliverables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>This will 1st day of the current financial year</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Service Deliverable</label>
    <nameField>
        <displayFormat>SD-{000000}</displayFormat>
        <label>Service Deliverables Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Deliverables</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ServiceDeliverableScheduler.cls
/**
 * @Author: Dipak Nikam
 * @since :26th Dec 2011
 * @Description: ServiceDeliverableScheduler is Scheduler class which run on 1st April of every Year which checks ServiceDeliverable records in BatchServiceDeliverableUpdateCompFlag batch.
 *				1)if the expiration date is greater than 31st March then it creates the new  ServiceDeliverable records. 
 * 				2)Get all records where end date is 31st March of that year and set the Completed flag to true	
 *  @Mahesh
 *	1.1         Mahesh Hirugade		  14/3/2012	    Added filters to query : Account Rec Type is Client & Account Status is Active. 	
 */
global class ServiceDeliverableScheduler implements Schedulable 
{
	public Date currentDate{set;get;}
	public ServiceDeliverableScheduler ()
	{
		currentDate = System.today();
	}
	global void execute(SchedulableContext SC) 
	{
		Date dtDate = Date.newInstance(currentDate.year(), 3, 31);
		String strDate = String.valueOf(dtDate);
		String strActive='Active'; 
		Id clientRecType = [Select r.Name, r.Id From RecordType r where r.Name = 'Client' limit 1].Id;
		String strQuery = 'Select s.Start_Date__c, s.RelatedAccount__c, s.RecordTypeId, s.Name, s.Meeting__c, s.Id, s.Expiration_Date__c, s.End_Date__c, s.Completed__c, s.Call__c,s.RelatedAccount__r.RecordTypeId  From Service_Deliverables__c s where Completed__c = false and End_Date__c ='+strDate+'and s.RelatedAccount__r.RecordTypeId ='+ '\''+clientRecType + '\'' + ' and s.RelatedAccount__r.Entity_Status__c = ' + '\'' +strActive +'\'';
		
		BatchServiceDeliverableUpdateCompFlag objSeviceDeliverable =  new BatchServiceDeliverableUpdateCompFlag();
		objSeviceDeliverable.Datecurrent = currentDate;
		objSeviceDeliverable.query = strQuery;
		Database.executeBatch(objSeviceDeliverable,10);
	}
}