Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Life_Insurance_Suggested_Cover__c</fullName>
        <label>Life Insurance Suggested Cover</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Members</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>General</description>
        <label>General</label>
    </recordTypes>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>EPF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superannuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Saving Certificate (NSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kisan Vikas Patra (KVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indra Vikas Patra / Others (IVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Income Plan (MIP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Recurring Deposit (RD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Time Deposit (FD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Provident Fund (PPF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Citizens Savings Scheme (SCSS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash in hand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others…</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset_Types__c</fullName>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>EPF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superannuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Saving Certificate (NSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kisan Vikas Patra (KVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indra Vikas Patra / Others (IVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Income Plan (MIP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Recurring Deposit (RD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Time Deposit (FD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Provident Fund (PPF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Citizens Savings Scheme (SCSS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash in hand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Limited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jewelry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash and Cash Equivalents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Assets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-office Savings Schemes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Portfolio_Report__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <label>Asset Class</label>
        <picklist>
            <picklistValues>
                <fullName>Debt: Floating Rate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Liquid Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Medium Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt: Ultra Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity: Tax Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid: Monthly Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid: Equity Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity : Shares</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity: Diversified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portfolio Report</relationshipLabel>
        <relationshipName>Portfolio_Report</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portfolio_Type__c</fullName>
        <label>Portfolio Type</label>
        <picklist>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Amount__c</fullName>
        <label>Purchase Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Scheme_Scrip_Name__c</fullName>
        <label>Scheme/Scrip Name</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>NOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units_Quanitity__c</fullName>
        <label>Units/Quanitity</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Portfolio Report</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portfolio Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/SIP_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>SIP Tracker</relationshipLabel>
        <relationshipName>SIP_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SIP Tracker</label>
    <nameField>
        <displayFormat>SIP-{0}</displayFormat>
        <label>SIP Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SIP Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/Test_ConsolidatedStatementController.cls
@isTest
private class Test_ConsolidatedStatementController {

    static testMethod void myUnitTest() {
         
         List<Asset__c> allAssets = new List<Asset__c>();
         List<Portfolio_Report__c> allPortfolios = new List<Portfolio_Report__c>();
         List<Insurance__c> allInsurances = new List<Insurance__c>();
         List<Loan__c> allLoans = new List<Loan__c>();
         
         Account act = new Account(FirstName='TestHello', LastName='TestWorld', Entity_Status__c='Active',Life_Insurance_Suggested_Cover__c=1000);
         insert act;
         Account child=new Account(Parent_Entity__c=act.Id,FirstName='ChildTestHello', LastName='ChildTestWorld', Entity_Status__c='Active',Life_Insurance_Suggested_Cover__c=1000);
         insert child;   
         PageReference ref = new PageReference ('apex/ConsolidatedStatement?Id='+act.Id);
         Test.setCurrentPageReference(ref);
         Portfolio_Report__c port1 = new Portfolio_Report__c( Entity__c=act.Id,Purchase_Amount__c=2000, Units_Quanitity__c=1000, Asset_Class__c='Debt: Floating Rate', Scheme_Scrip_Name__c='Birla Sun Life',Transaction_Type__c='SIP', Current_Value__c=2000,Portfolio_Type__c='EQ');
    	 allPortfolios.add(port1);
    	 Portfolio_Report__c port2 = new Portfolio_Report__c( Entity__c=act.Id,Purchase_Amount__c=2000,Units_Quanitity__c=1000,Asset_Class__c='Equity: Tax Planning', Scheme_Scrip_Name__c='Kotak Mahindra',Transaction_Type__c='SIP', Current_Value__c=2000,Portfolio_Type__c='MF');
    	 allPortfolios.add(port2);
    	 Portfolio_Report__c port3 = new Portfolio_Report__c( Entity__c=act.Id,Purchase_Amount__c=2000,Units_Quanitity__c=1000,Asset_Class__c='Debt: Short Term', Scheme_Scrip_Name__c='HDFC',Transaction_Type__c='NOR', Current_Value__c=2000,Portfolio_Type__c='EQ');
  		 allPortfolios.add(port3);
  		 Portfolio_Report__c childPortfolio = new Portfolio_Report__c( Entity__c=child.Id,Purchase_Amount__c=2000,Units_Quanitity__c=1000,Asset_Class__c='Equity: Shares', Scheme_Scrip_Name__c='HDFC',Transaction_Type__c='NOR', Current_Value__c=2000,Portfolio_Type__c='EQ');
  		 allPortfolios.add(childPortfolio);	
  		 insert allPortfolios;
  		 
  		  Asset__c asset1 = new Asset__c(Entity__c= act.Id,Account_Type__c='EPF',  Asset_Types__c='Personal Assets',Asset_Sub_Types__c='',Current_Value__c=1000.0,Categories__c='Debt');
    	  allAssets.add(asset1); 
    	  Asset__c asset2 = new Asset__c( Entity__c= act.Id,Account_Type__c='EPF', Asset_Types__c='Cash and Cash Equivalents',Asset_Sub_Types__c='Current A/c', Current_Value__c=1000,Categories__c='Others');
    	  allAssets.add(asset2);
    	  Asset__c asset3 = new Asset__c( Entity__c= act.Id,Account_Type__c='EPF', Asset_Types__c='Business Assets',Asset_Sub_Types__c='LLP', Current_Value__c=1000,Categories__c='Equity');
    	  allAssets.add(asset3);  
    	  Asset__c asset4 = new Asset__c( Entity__c= act.Id,Account_Type__c='EPF', Asset_Types__c='Post-office Savings Schemes',Asset_Sub_Types__c='National Saving Certificate (NSC)', Current_Value__c=1000,Categories__c='Real Estate');
    	  allAssets.add(asset4);
    	  Asset__c asset5 = new Asset__c(Entity__c= act.Id,Account_Type__c='EPF', Asset_Types__c='Bank Deposits',Asset_Sub_Types__c='Recurring Deposit', Current_Value__c=1000,Categories__c='Gold');
    	  allAssets.add(asset5);
    	  Asset__c asset6 = new Asset__c(Entity__c= act.Id,Account_Type__c='EPF', Asset_Types__c='Real Estate Accounts',Asset_Sub_Types__c='Land', Current_Value__c=1000,Categories__c='Gold');
    	  allAssets.add(asset6);
    	  Asset__c childAsset = new Asset__c(Entity__c= child.Id,Account_Type__c='EPF', Asset_Types__c='Bank Deposits',Asset_Sub_Types__c='Fixed Deposit', Current_Value__c=1000,Categories__c='Real Estate');
    	  allAssets.add(childAsset);        	    	  
    	  insert allAssets;
  		   		 
  		 
  		  Id lifeInsuranceId =  [select Id from RecordType where Name= 'Life Insurance' limit 1].Id;
  		  Id generalInsuranceId =  [select Id from RecordType where Name= 'General Insurance' limit 1].Id;
  		  Date dueDate = System.today();
  		  system.debug('________lifeInsuranceId_____'+lifeInsuranceId);
  		  system.debug('_______________act.Id__________'+act.Id);
  		  Insurance__c ins1 = new Insurance__c( RecordTypeId=lifeInsuranceId,Death_Benefit_Rs__c=4000, Premium_End_Date__c=dueDate,Entity__c=act.Id,Premium_Due_date__c=dueDate, Sum_Assured_Rs__c=3000,Premium_Amount_Rs__c =300,Policy_Type__c='Other',Premium_Frequency__c ='Monthly',Insurance_Company__c ='Birla',Categories__c='Gold');
  		  allInsurances.add(ins1);
  		  Insurance__c ins2 = new Insurance__c( RecordTypeId=lifeInsuranceId,Death_Benefit_Rs__c=4000,Premium_End_Date__c=dueDate,Entity__c=act.Id,Premium_Due_date__c=dueDate,Sum_Assured_Rs__c=3000,Premium_Amount_Rs__c =300,Policy_Type__c='Term Life',Premium_Frequency__c ='Monthly',Insurance_Company__c='Kotak',Categories__c='Real Estate');	 
  		  allInsurances.add(ins2);
  		  Insurance__c ins3 = new Insurance__c( RecordTypeId=lifeInsuranceId,Death_Benefit_Rs__c=4000,Premium_End_Date__c=dueDate,Entity__c=act.Id,Premium_Due_date__c=dueDate,Sum_Assured_Rs__c=3000,Premium_Amount_Rs__c =300,Policy_Type__c='Whole Life',Premium_Frequency__c ='Monthly',Insurance_Company__c='Mahindra',Categories__c='Equity');	 
  		  allInsurances.add(ins3);
  		 
  		 
  		  Insurance__c ins4 = new Insurance__c( RecordTypeId=generalInsuranceId,Entity__c=act.Id,Premium_End_Date__c=dueDate,Suggested_Cover_General_Insurance__c=2000,Premium_Due_date__c=dueDate,Sum_Assured_Rs__c=3000,Premium_Amount_Rs__c =300,Policy_Type__c='Medical',Premium_Frequency__c ='Monthly',Insurance_Company__c='Kotak',Categories__c='Real Estate');	 
  		  allInsurances.add(ins4);
  		  Insurance__c ins5 = new Insurance__c( RecordTypeId=generalInsuranceId,Entity__c=act.Id,Premium_End_Date__c=dueDate,Suggested_Cover_General_Insurance__c=2000,Premium_Due_date__c=dueDate,Sum_Assured_Rs__c=3000,Premium_Amount_Rs__c =300,Policy_Type__c='Vehicle',Premium_Frequency__c ='Monthly',Insurance_Company__c='Mahindra',Categories__c='Equity');	 
  		  allInsurances.add(ins5);
   		 
   		 
   		  Insurance__c childInsurance = new Insurance__c( RecordTypeId=lifeInsuranceId,Death_Benefit_Rs__c=4000,Premium_End_Date__c=dueDate,Entity__c=child.Id,Premium_Due_date__c=dueDate,Sum_Assured_Rs__c=3000,Premium_Amount_Rs__c =300,Policy_Type__c='Whole Life',Premium_Frequency__c ='Monthly',Insurance_Company__c='HDFC',Categories__c='Equity');	 
  		  allInsurances.add(childInsurance);	 	 
  		  //insert allInsurances;
  		   
  		  Loan__c loan1 = new Loan__c(Entity__c=act.Id,Fixed_Floating__c='Fixed',Loan_Type__c='Home Loan',Next_EMI_Date__c=dueDate,Premium_End_Date__c=dueDate, Term_No_of_years__c=2, EMI__c=1000);
  		  allLoans.add(loan1);
  		  Loan__c loan2 = new Loan__c(Entity__c=act.Id,Fixed_Floating__c='Floating',Loan_Type__c='Auto Loan',Next_EMI_Date__c=dueDate,Premium_End_Date__c=dueDate,Term_No_of_years__c=2,EMI__c=1000);
  		  allLoans.add(loan2);
  		  Loan__c loan3 = new Loan__c(Entity__c=act.Id,Fixed_Floating__c='Fixed',Loan_Type__c='Credit Card Loan',Next_EMI_Date__c=dueDate,Premium_End_Date__c=dueDate,Term_No_of_years__c=2,EMI__c=1000);
  		  allLoans.add(loan3);
  		  Loan__c loan4 = new Loan__c(Entity__c=act.Id,Fixed_Floating__c='Fixed',Loan_Type__c='Personal Loan',Next_EMI_Date__c=dueDate,Premium_End_Date__c=dueDate,Term_No_of_years__c=2,EMI__c=1000);
  		  allLoans.add(loan4);
  		  Loan__c loan5 = new Loan__c(Entity__c=act.Id,Fixed_Floating__c='Fixed',Loan_Type__c='Business Loan',Next_EMI_Date__c=dueDate,Premium_End_Date__c=dueDate,Term_No_of_years__c=2,EMI__c=1000);
  		  allLoans.add(loan5);
  		  Loan__c loan6 = new Loan__c(Entity__c=act.Id,Fixed_Floating__c='Fixed',Loan_Type__c='Other Loan',Next_EMI_Date__c=dueDate,Premium_End_Date__c=dueDate,Term_No_of_years__c=2,EMI__c=1000);
  		  allLoans.add(loan6);
  		  
  		  
  		  
  		  Loan__c loan7 = new Loan__c(Entity__c=child.Id,Fixed_Floating__c='Floating',Loan_Type__c='Student Loan',Next_EMI_Date__c=dueDate,Premium_End_Date__c=dueDate,Term_No_of_years__c=2,EMI__c=1000);
  		  allLoans.add(loan7);
  		  insert allLoans;
  		  Test.startTest();
  		  ConsolidatedStatementController csc = new ConsolidatedStatementController();
  		  List<ConsolidatedStatementController.InvestmentAssetsWrapper> equityWrapperList = csc.getEquityInvestmentAssets();
  		  List<ConsolidatedStatementController.InvestmentAssetsWrapper> debtWrapperList = csc.getDebtInvestmentAssets();
  		  List<ConsolidatedStatementController.InsuranceWrapper>  lifeInsuranceWrapperList = csc.getLifeInsuranceWrapper();
  		  List<ConsolidatedStatementController.InsuranceWrapper>  generalInsuranceWrapperList = csc.getGeneralInsuranceWrapper();
  		  List<ConsolidatedStatementController.AssetsWrapper> assetWrapperList = csc.getAssetsWrapper();
  		  List<ConsolidatedStatementController.LoanWrapper> loanWrapperList = csc.getLoanWrapper();
  		  List<ConsolidatedStatementController.SuccessionPlanningWrapper> SuccessionPlanningWrapperList = csc.getSuccessionPlanningWrapper();
  		  String emiSubtotal = csc.getEmiSubTotal();
  		  String debtInvesmentAssetsSubTotal = csc.getdebtInvestmentAssetsSubTotal();
  		  String equityInvesmentAssetsSubTotal = csc.getequityInvestmentAssetsSubTotal();
  		  List<Loan__c> Loans = csc.getAllLoans();
  		  List<Insurance__c> Insurances = csc.getAllInsurances();
  		  List<SIP_Tracker__c> getSipTrackerList = csc.getSipTracker();
  		  String chartUrl = csc.getchartURL();
	      Test.stopTest();
    }
}