Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <defaultValue>00</defaultValue>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Company_Address__c</fullName>
        <label>Company Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_ID__c</fullName>
        <label>Email ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <description>This field stores logo for each Partner Portals</description>
        <inlineHelpText>Partner Portal Logo</inlineHelpText>
        <label>Logo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is created to select the related virtual partner of that entity.

Practice Owner (Partner): Account Record Type</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>IF(MONTH(TODAY())&gt;MONTH( Birthdate),

    YEAR(TODAY())-YEAR(Birthdate),

    IF(AND(MONTH(TODAY()) = MONTH(Birthdate), DAY(Birthdate) &gt;= DAY(Birthdate)),
               YEAR(TODAY())-YEAR(Birthdate),
               (YEAR(TODAY())-YEAR(Birthdate))-1)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>To select related virtual partner.</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerLeads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Lead_Platform_User__c.object
<CustomObject>
    <description>Its is the custom Lead object created for standard platform user.</description>
    <fields>
        <fullName>Age__c</fullName>
        <defaultValue>30</defaultValue>
        <label>Age</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Source__c</fullName>
        <label>Lead Source</label>
        <picklist>
            <picklistValues>
                <fullName>BNI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corp Comm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Engines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminar (MKT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seminar (WS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FP Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web-Onlinepromotion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web-XRay</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Virtual Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Lead</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Lead_Source__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>This stores lead source required for KPI</description>
    <label>Lead Source for KPI</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Workstations__c</fullName>
        <label>Workstations</label>
        <picklist>
            <picklistValues>
                <fullName>Galaxy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amethyst</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pinnacle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maegan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/Test_BeforeInsertBeforeUpdateLead.cls
//Created on 1/8/12 By Aditi Satpute during Partner Portal related implementation
 
@isTest
private class Test_BeforeInsertBeforeUpdateLead {

    static testMethod void myUnitTest() {
    	Contact con;
    
    	List<User> standardUser = [select Id from user where usertype = 'Standard' and Profile.Name like '%System Admin%' limit 1];
       System.runAs(standardUser[0])
       {
       		     
       		Lead newLead=new Lead(LastName='Test Lead',Status='Open',MobilePhone='313241',Age__c=30);
	    	insert newLead;  
	       	//Account created for enabling Partner Portal
	       	//Date : 1/8/12 , Code Added By: Aditi 
	       	Account partnerAcc=new Account(Name='Parner Account Test',RecordTypeId=RecTypes__c.getInstance('General_Business').Record_Type_Value__c);
	       	insert partnerAcc;

	       	//Contact created for enabling Partner Portal	       
	       	//Date : 1/8/12 , Code Added By: Aditi 
	      	con=new Contact(FirstName='Parner Contact Test', LastName='Contact',AccountId= partnerAcc.id);
	       	insert con;
	       	
	       		//Need to comment below ===============================
	       	/*Account partnerAcc1 = new Account(Name='Parner Account Test',RecordTypeId=RecTypes__c.getInstance('General_Business').Record_Type_Value__c);
	       	insert partnerAcc1;
	  	 	List<Account> acc = [select id,Logo__c, Email_ID__c, Company_Address__c, Phone, Name from Account where RecordTypeId = :RecTypes__c.getInstance('General_Business').Record_Type_Value__c]; 
			*/
	//  	list<Lead_Platform_User__c> lstLeads = 	new list<Lead_Platform_User__c>();
	    	//Lead_Platform_User__c lead1 = new Lead_Platform_User__c(Virtual_Partner__c = acc[0].id,/*Need to comment below */First_Name__c = 'Platform', Name = 'User', Lead_Status__c = 'Converted', Lead_Source__c = 'Web', Mobile__c = '9898989898', Age__c = 23);
	    	//insert lead1;
	    	//lstLeads.add(lead1);
	    	//=====================================================
	    }
       //Role created for Partner Portal
       //Date : 1/8/12 , Code Added By: Aditi 
      /*  List <UserRole> ur1 = [select Id from UserRole where   PortalType='Partner' limit 1];
  	   
  	   Profile prof = [select id 
                      from profile 
                     where usertype = 'PowerPartner'
                     limit 1];
  	   ID PartnerProfileID =prof.id;
  	   User u1;
 	   if(ur1!=null && ur1.size() > 0)
  	   {
  	   		//User created for Partner Portal
  	   		//Date : 1/8/12 , Code Added By: Aditi 
	    	 u1 = new User(Workstations__c = 'All',userroleid=ur1[0].id,ContactId= con.id, email='test-user@fakeemail.com',ProfileId = PartnerProfileID,UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1',TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', FirstName = 'Test_Parent_Fname', LastName = 'Test_Parent_Lname' );
	       insert u1;
  	   }
  	   System.runAs(u1)
  	   {
  	   	 	//Account created after logging as Partner Portal User
  	   	 	//Date : 1/8/12 , Code Added By: Aditi 
  	   	 		   	 	
  	   	 	Account PatnersClientAcc=new Account(LastName='Partners Client',FirstName='PQR',RecordTypeId= RecTypes__c.getInstance ('AccountClient').Record_Type_Value__c); //Gaurav
  	   	 	//'01220000000DnK3AAK');
	       	upsert PatnersClientAcc;
	       	
	       	Lead PartnersLead=new Lead(LastName='Partners Lead',Status='Open',MobilePhone='312421',Age__c=30);
	       	insert PartnersLead;
	       	
	       
  	   }*/
    }
}