Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cheque_Received_Date__c</fullName>
        <label>Cheque Received Date - 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Collection_Date__c</fullName>
        <label>Data Collection Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Execution_Completion_Dates__c</fullName>
        <label>Execution Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Members</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Approved_Date__c</fullName>
        <label>Plan Approved Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Presented_Date__c</fullName>
        <label>Plan Presented Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Writing_Date__c</fullName>
        <label>Plan Writing Completion Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold (Align to goal)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset_Types__c</fullName>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>EPF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superannuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Saving Certificate (NSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kisan Vikas Patra (KVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indra Vikas Patra / Others (IVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Income Plan (MIP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Recurring Deposit (RD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Time Deposit (FD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Provident Fund (PPF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Citizens Savings Scheme (SCSS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash in hand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Limited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jewelry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Assets</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Year__c</fullName>
        <label>End Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expected_Growth_Rate__c</fullName>
        <label>Expected Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Start_Year__c</fullName>
        <label>Start Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/AssetRecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AssetRecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Client_Details__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Details</relationshipLabel>
        <relationshipName>Client_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Details (Parent Entity)</relationshipLabel>
        <relationshipName>Client_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Detail</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Client Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Current_Expenses__c</fullName>
        <label>Current Expenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Year__c</fullName>
        <label>End Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Frequency__c</fullName>
        <label>Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half-Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yearly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>General_Expenses__c</fullName>
        <label>General Expenses</label>
        <picklist>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transportation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recreation &amp; Entertainment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Year__c</fullName>
        <label>Start Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goal Profiles</relationshipLabel>
        <relationshipName>Goal_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debt_Allocation__c</fullName>
        <label>Debt Allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Equity_Allocation__c</fullName>
        <label>Equity Allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Goal_Profile_Type__c</fullName>
        <label>Goal Profile Type</label>
        <picklist>
            <controllingField>Risk_Type__c</controllingField>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customized</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gold_allocation__c</fullName>
        <label>Gold allocation</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Goal Profile</label>
    <nameField>
        <label>Goal Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/Test_Update_EntityStage_Trigger.cls
@isTest
private class Test_Update_EntityStage_Trigger 
{
	 //Deployement Manasi
	  static testMethod void testTriggerDeleteParent()
	  {/*
	  	//system.debug('*******RecTypes__c.getInstanceRecord_Type_Value__c********'+RecTypes__c.getInstance('AccountClient').Record_Type_Value__c);
		    Id clientRecId=RecTypes__c.getInstance('AccountClient').Record_Type_Value__c;
		     Id familyRecId=RecTypes__c.getInstance('AccountFamily').Record_Type_Value__c;
		       
		     Account act = new Account(FirstName='ABC',LastName='XYZ',RecordTypeId=clientRecId);
		     insert act;
		     
		       Account son=new Account(FirstName='PQR',LastName='LMN',Parent_Entity__c=act.id,RecordTypeId=familyRecId);
		      insert son;
		      
		      Account Daughter =new Account(FirstName='EFG',LastName='HIJ',Parent_Entity__c=act.id,RecordTypeId=familyRecId);
		      insert Daughter;
		      
		  /*    Asset__c asset=new Asset__c(Expected_Growth_Rate__c=4,End_Year__c='2034',Start_Year__c='2001',
		                              Entity__c=act.id,action__c='yes',Asset_Types__c='Gold',RecordTypeId=AssetRecTypes__c.getInstance('Personal Assets').RecordTypeId__c);//RecordTypeId='01220000000HYzWAAW' : mahesh
		        insert asset;
		        
		        /*Client_Details__c accs=new Client_Details__c(Entity__c = act.id);
		      insert accs;
		        
		        Expense__c exp=new Expense__c(Entity_Name__c=act.id,General_Expenses__c='Housing',Current_Expenses__c=12536,Frequency__c='Monthly');
		        upsert exp;
		        
		        Goal_Profile__c goalProfile=new Goal_Profile__c(Name='Moderately Aggressive',Account__c=act.id,Goal_Profile_Type__c='Customized',Debt_Allocation__c=23,Equity_Allocation__c=32,Gold_allocation__c=33);
		        insert goalProfile;
		        
		        Lead newLd = new Lead(LastName = 'Tesqqqqt', Status='Open');
		    insert newLd;
		    
		    Opportunity opp = new Opportunity(Name='Test', CloseDate= System.today(), StageName='Interested', Lead__c=newLd.Id,AccountId = act.Id);
		    insert opp;
		    */
		//   Delete son;
		//    Delete act;
	  }
		/*
static testMethod void testTrigger(){
		Test.startTest();
		List<Account> updateList= new List<Account>();
		List<Account> accounts =new List<Account>();
		Account act1 = new Account(FirstName='Test_Fname1',LastName='Test_Lname',Entity_Status__c='Active');
		accounts.add(act1);
		Account act2 = new Account(FirstName='Test_Fname2',LastName='Test_Lname',Entity_Status__c='Active');
		accounts.add(act2);
		Account act3 = new Account(FirstName='Test_Fname3',LastName='Test_Lname',Entity_Status__c='Active');
		accounts.add(act3);
		Account act4 = new Account(FirstName='Test_Fname4',LastName='Test_Lname',Entity_Status__c='Active');
		accounts.add(act4);
		/*Account act5 = new Account(FirstName='Test_Fname5',LastName='Test_Lname',Entity_Status__c='Active');
		accounts.add(act5);
		Account act6 = new Account(FirstName='Test_Fname6',LastName='Test_Lname',Entity_Status__c='Active');
		accounts.add(act6);
   //     insert accounts;
        
        /* Commented on 01Mar 2012 : because Cheque_Received_Date__c will be removed from Account object */
       //accounts= [select Id,Cheque_Received_Date__c from Account where LastName = 'Test_Lname'];
/*     accounts= [select Id from Account where LastName = 'Test_Lname'];
       
       for (Integer i=0;i<accounts.size();i++){
       	   Account acc=accounts.get(i);
       	   if(acc.Id==act1.Id){
       	   	  acc.Cheque_Received_Date__c=System.today();
       	   	  updateList.add(acc);
       	   }
       	   else
       	   if(acc.Id==act1.Id){
       	   	  acc.Data_Collection_Date__c=System.today();
       	   	  updateList.add(acc);	
       	   }
       	   else if(acc.Id==act2.Id){
       	   	  acc.Data_Collection_Date__c=System.today();
       	   	  acc.Plan_Writing_Date__c=System.today().addDays(1);
       	   	  updateList.add(acc);	
       	   }
       	   
       	//   ======Deleted Plan_Presented_Date__c field from Account object======
       	  else if(acc.Id==act4.Id){
       	   	  acc.Data_Collection_Date__c=System.today();
       	   	  acc.Plan_Writing_Date__c=System.today().addDays(1);
       	   	  //acc.Plan_Presented_Date__c=System.today().addDays(2);
       	   	  updateList.add(acc);	
       	   }
       	   
       	   else if(acc.Id==act3.Id){
       	   	  acc.Data_Collection_Date__c=System.today();
       	   	  acc.Plan_Writing_Date__c=System.today().addDays(1);
       	   	  //acc.Plan_Presented_Date__c=System.today().addDays(2);
       	   	  acc.Plan_Approved_Date__c=System.today().addDays(3);	
       	   	  updateList.add(acc);
       	   }
       	   else if(acc.Id==act4.Id){
       	   	  acc.Data_Collection_Date__c=System.today();
       	   	  acc.Plan_Writing_Date__c=System.today().addDays(1);
       	   	 // acc.Plan_Presented_Date__c=System.today().addDays(2);
       	   	  acc.Plan_Approved_Date__c=System.today().addDays(3);
       	   	  acc.Execution_Completion_Dates__c=System.today().addDays(4);	
       	   	  updateList.add(acc);
       	   }
		}
       
        update updateList; 
       
       Test.stopTest();
	}*/
}