Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Finametrica_Score__c</fullName>
        <label>Finametrica Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Risk_profile__c</fullName>
        <label>Risk profile</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marriage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parental Responsibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money to Heirs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <description>Space for ‘Remarks’ where the FP can give additional advice(Only for Goal)</description>
        <inlineHelpText>Space for ‘Remarks’ where the FP can give additional advice</inlineHelpText>
        <label>Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Risk_Profile__c</fullName>
        <label>Risk Profile</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Remarks__c.object
<CustomObject>
    <description>Space for ‘Remarks’ where the FP can give additional advice.(Except for Goal)</description>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Remark related entity</description>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Remarks</relationshipLabel>
        <relationshipName>Remarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <description>Space for ‘Remarks’ where the FP can give additional advice(Except for Goal)</description>
        <inlineHelpText>space for ‘Remarks’ where the FP can give additional advice</inlineHelpText>
        <label>Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Remark</label>
    <nameField>
        <label>Remarks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remarks</pluralLabel>
    <recordTypes>
        <fullName>RiskProfiler</fullName>
        <active>true</active>
        <description>Remark for RiskProfile</description>
        <label>RiskProfiler</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ProfilerQuestionControllerTest.cls
/*
Revision History:

	Version     Version Author     Date        Comments
	1.0         --           	   --	  	   Initial Draft
	2.0  		Prajakta Sanap     22/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.				   				 					   
*/

@isTest
private class ProfilerQuestionControllerTest 
{
    static ProfilerQuestionPageController pfQnsCon;
    public static Account acc;
    
    static void testData()
    {
        TestData_Ffreedom testData = new TestData_Ffreedom();
		acc = testData.initializeAccount();
        upsert acc;
        system.assertNotEquals(null, acc.id);
        Apexpages.currentPage().getParameters().put('entityId',acc.id);
        pfQnsCon = new ProfilerQuestionPageController();
    }
   
    static testMethod void ProfileTest() 
    {
        test.startTest();
        testData();
        acc.Finametrica_Score__c = 15;
        update acc;
        acc.Finametrica_Score__c = 45;
        update acc;
        acc.Finametrica_Score__c = 75;
        update acc;
        //pfQnsCon.save();
        test.stopTest();
    }
   	
   	static testMethod void saveTest() 
   	{
        test.startTest();
        //testData();
        TestData_Ffreedom testData = new TestData_Ffreedom();
		Account account = testData.initializeAccount();
		account.Risk_profile__c = 'Medium';
		account.Finametrica_Score__c = 56;
		account.LastName = 'Risk Test';
        insert account;
        Goal__c objGoal = new Goal__c(Goal_Type__c = 'Test', Entity__c = account.Id); 
	    insert objGoal;
	    
	    Apexpages.currentPage().getParameters().put('entityId',account.id);
        pfQnsCon = new ProfilerQuestionPageController();
        pfQnsCon.save();
        test.stopTest();
    }
  	
  	static testMethod void saveRemarkTest() 
   	{
        test.startTest();
        testData();
        
        ID RecTypeId = [select id from RecordType where Name=: 'RiskProfiler'][0].id;
        Remarks__c objSaveRemark = new Remarks__c();
        objSaveRemark.Entity__c = acc.id;
        objSaveRemark.Remark__c = 'strRemark';
        objSaveRemark.RecordTypeId = RecTypeId;
        insert objSaveRemark;
        pfQnsCon.save();
        test.stopTest();
    }
    
    
    
  	static testMethod void saveDirectTest() 
   	{
		test.startTest();
		TestData_Ffreedom testData = new TestData_Ffreedom();
		Account account = testData.initializeAccount();
		account.Risk_profile__c = 'Medium';
		account.Finametrica_Score__c = 56;
		account.LastName = 'Risk Test';
        insert account;
        account = [
	    	select id, LastName
	    		 , Finametrica_Score__c
	          from Account
	          where id =: account.id
	    ];
	    system.debug('------------------aaaaaaaaaa------'+account);
	    account.Finametrica_Score__c = 23;
	    update account;
	    
	   
	    
	    Apexpages.currentPage().getParameters().put('entityId',account.id);
        pfQnsCon = new ProfilerQuestionPageController();
	    //pfQnsCon = new ProfilerQuestionPageController();
	    //pfQnsCon.save();
        test.stopTest();
    }
  	
  	static testMethod void saveRiskProfileForGoalsTest() 
   	{
        test.startTest();
        testData();
        pfQnsCon.save();
        pfQnsCon.saveRiskProfileForGoals();
        test.stopTest();
    }
    
    static testMethod void cancelTest() 
    {
        test.startTest();
        testData();
        pfQnsCon.cancelPopup();
        test.stopTest();
    }
    
}