Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Referred_by_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referred by Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Referred by Entity)</relationshipLabel>
        <relationshipName>Entity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Flat_Commission__c</fullName>
        <label>Total Flat Commission</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is created to select the related virtual partner of that entity.

Practice Owner (Partner): Account Record Type</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Master__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <displayFormat>PRD-{000000}</displayFormat>
        <label>Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Price_Book__c.object
<CustomObject>
    <fields>
        <fullName>Flat_Commission__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Flat Commission</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Products where Price Category is One Time, Price should be set as a decimal number containing 2 decimal places. e.g. 12545.22. 
Products where Price Category is other One Time, Price should be set as percentage containing 2 decimal places. e.g.  0.75.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Code</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Product Price Books</relationshipLabel>
        <relationshipName>Product_Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <displayFormat>PRBK-{0000000}</displayFormat>
        <label>Product Price Book Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_Orders</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Master__c</fullName>
        <label>Product Master</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Product_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product  Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Selected_Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/PurchaseOrderHandler.cls
public class PurchaseOrderHandler 
{
	public static Boolean isRecursiveAccountFlatCommissionInsert = true;
	public static Boolean isRecursiveAccountFlatCommissionUpdate = true;
	Id clientRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId();
	
	public void onAfterInsert(Map<Id, Purchase_Order__c> mapNewIdTopPurchaseOrder)
	{
		try{
			Map<Id, Purchase_Order__c> mapEntityIdToPurchaseOrder = new Map<Id, Purchase_Order__c>();
			List<FeedItem> lstFeedItem = new List<FeedItem>();
			Set<String> setProudctOrderNumber = new Set<String>();
			
			for(Purchase_Order__c objPO : mapNewIdTopPurchaseOrder.values())
			{
				if(objPO.Product_Type__c == 'Base Product')
				{
					mapEntityIdToPurchaseOrder.put(objPO.Entity__c, objPO);
					setProudctOrderNumber.add(objPO.Order__c);
				}
			}
			
			
			Map<Id, List<Purchase_Order__c>> mapEntityIdToLstCompletedPurchaseOrder = new Map<Id, List<Purchase_Order__c>>();
			
			for(Purchase_Order__c objPO : [Select Selected_Product__c, Order__c, Entity__c from Purchase_Order__c 
											where Order__c IN: setProudctOrderNumber  and Entity__c IN: mapEntityIdToPurchaseOrder.keySet() 
											order by CreatedDate desc])
			{
				if(!mapEntityIdToLstCompletedPurchaseOrder.containsKey(objPO.Entity__c))
				{
					mapEntityIdToLstCompletedPurchaseOrder.put(objPO.Entity__c, new List<Purchase_Order__c>{objPO});
				}
				else
				{
					mapEntityIdToLstCompletedPurchaseOrder.get(objPO.Entity__c).add(objPO);
				}
			}
			
			Map<Id, Account> mapIdToEntity = new Map<Id, Account>([Select Name, OwnerId from Account where Id IN : mapEntityIdToPurchaseOrder.keySet()]);
			
			for(Id entityId : mapEntityIdToPurchaseOrder.keySet())
			{
				FeedItem post = new FeedItem();
				post.ParentId = mapIdToEntity.get(entityId).OwnerId;
				if(!mapEntityIdToLstCompletedPurchaseOrder.containsKey(entityId))
				{
					post.Body = 'New Order: '+ mapEntityIdToPurchaseOrder.get(entityId).Order__c + ' has been created for Entity "'+ mapIdToEntity.get(entityId).Name+'".';
				}
				else
				{
					Purchase_Order__c objPurchaseOrder = mapEntityIdToLstCompletedPurchaseOrder.get(EntityId)[0];
					post.Body = 'Purchase Order '+ mapEntityIdToPurchaseOrder.get(entityId).Order__c + ' has been successfully upgraded for Entity "'+ mapIdToEntity.get(entityId).Name+'" with "';
					post.Body += mapEntityIdToPurchaseOrder.get(entityId).Selected_Product__c +'" Base Proudct.';
				}				     			
				lstFeedItem.add(post);
			}
			
			insert lstFeedItem;
		}
		catch(Exception e)
		{
			System.debug('------------------------error-----------------'+e);
		}
	}
	
	/*
	public void onAfterInsertPurchaseOrder(Map<Id, Purchase_Order__c> mapNewIdTopPurchaseOrder)
	{
		if(isRecursiveAccountFlatCommission)
		{
			Map<Id, Purchase_Order__c> mapEntityIdToPurchaseOrder = new Map<Id, Purchase_Order__c>();
			Map<Id, String> mapPurchaseOrderIdToProductMaster = new Map<Id, String>();
			Map<Id, Product_Price_Book__c> mapProductMasterIdToPriceBook = new Map<Id, Product_Price_Book__c>();
			Map<Id, Account> mapIdToVirtualPartner = new Map<Id, Account>();
			Map<Id, Account> mapIdToVirtualPartnerId = new Map<Id, Account>();
			Map<Id, Account> mapIdToAccount = new Map<Id, Account>();
			Double flatCommission = 0;
			
			for(Purchase_Order__c objPO : mapNewIdTopPurchaseOrder.values())
			{
					mapEntityIdToPurchaseOrder.put(objPO.Entity__c, objPO);
					mapPurchaseOrderIdToProductMaster.put(objPO.Id, objPO.Product_Master__c);	
			}
														 
			List<Product_Price_Book__c> lstPriceBook =  [Select Product_code__c, 
																Price_value__c, 
																Name, 
																Flat_Commission__c 
														 From Product_Price_Book__c
														 Where Product_code__c IN : mapPurchaseOrderIdToProductMaster.values()];
														 
			for(Product_Price_Book__c objProductPriceBook : lstPriceBook)	
			{
				mapProductMasterIdToPriceBook.put(objProductPriceBook.Product_code__c, objProductPriceBook);
				system.debug('************mapProductMasterIdToPriceBook'+mapProductMasterIdToPriceBook);
			}										 
														 
			List<Account> lstAccount = [Select Id, Virtual_Partner__c, Total_Flat_Commission__c, 
				 															(Select Id 
				 															 From Product_Orders__r 
				 															 Where Id IN: mapNewIdTopPurchaseOrder.keyset() )
				 							 					    From Account 
				 							 					    Where Id IN: mapEntityIdToPurchaseOrder.keyset()]; 
				 							 					    
			for(Account objAccount : lstAccount)	
			{
				mapIdToVirtualPartnerId.put(objAccount.Virtual_Partner__c, objAccount);
				system.debug('************mapIdToVirtualPartnerId'+mapIdToVirtualPartnerId);
				mapIdToAccount.put(objAccount.Id, objAccount);
			} 							 					    
			
			map<Id, Account> mapIdToVirtualPartnerAccount = new Map<Id, Account>([Select Id, Virtual_Partner__c, Total_Flat_Commission__c 
								 							 					  From Account 
								 							 					  Where Id IN: mapIdToVirtualPartnerId.keyset()]); 									 
			for(Account objAccount : mapIdToVirtualPartnerAccount.values())
			{
				mapIdToVirtualPartner.put(objAccount.Virtual_Partner__c, objAccount);
				system.debug('************mapIdToVirtualPartner'+mapIdToVirtualPartner);
			}
			
			
			for(Purchase_Order__c objPO  : mapNewIdTopPurchaseOrder.values())
			{
				system.debug('************objPO'+objPO);
				Account objAccount =  mapIdToAccount.get(objPO.Entity__c);
				Account objPartnerAccount = mapIdToVirtualPartnerAccount.get(objAccount.Virtual_Partner__c);	
				
				system.debug('************objAccount'+objAccount);
				system.debug('************objPartnerAccount'+objPartnerAccount);
				
				Product_Price_Book__c objProductPriceBook = mapProductMasterIdToPriceBook.get(objPO.Product_Master__c);
				
				flatCommission = objPartnerAccount.Total_Flat_Commission__c != null ?  objPartnerAccount.Total_Flat_Commission__c : 0;
				objProductPriceBook.Flat_Commission__c = objProductPriceBook.Flat_Commission__c != null ? objProductPriceBook.Flat_Commission__c: 0;
				objPartnerAccount.Total_Flat_Commission__c= flatCommission + objProductPriceBook.Flat_Commission__c ;
				system.debug('************bjPartnerAccount.Total_Flat_Commission__c'+objPartnerAccount.Total_Flat_Commission__c);
				
				mapIdToVirtualPartnerAccount.put(objPartnerAccount.Id, objPartnerAccount);
			}
							 
			if(mapIdToVirtualPartnerAccount.size() > 0 && mapIdToVirtualPartnerAccount.keyset() != null)
				update mapIdToVirtualPartnerAccount.values();
			isRecursiveAccountFlatCommission = false;	
		}			 
	}
	/*
	public void onAfterUpdatePurchaseOrder(Map<Id, Purchase_Order__c> mapNewIdTopPurchaseOrder)
	{
		
		{
			Map<Id, Purchase_Order__c> mapEntityIdToPurchaseOrder = new Map<Id, Purchase_Order__c>();
			Map<Id, String> mapPurchaseOrderIdToProductMaster = new Map<Id, String>();
			Map<Id, Product_Price_Book__c> mapProductMasterIdToPriceBook = new Map<Id, Product_Price_Book__c>();
			Map<Id, Account> mapIdToVirtualPartner = new Map<Id, Account>();
			Map<Id, Account> mapIdToVirtualPartnerId = new Map<Id, Account>();
			Map<Id, Account> mapIdToAccount = new Map<Id, Account>();
			Double flatCommission = 0;
			
			for(Purchase_Order__c objPO : mapNewIdTopPurchaseOrder.values())
			{
					mapEntityIdToPurchaseOrder.put(objPO.Entity__c, objPO);
			}
						
			List<Purchase_Order__c> lstFinalPurcahseOrder = new List<Purchase_Order__c>(); 		
			lstFinalPurcahseOrder = [Select Selected_Product__c,Entity__c, Product_Type__c, 
																Product_Price__c, Product_Master__c, Name, Id 
													     From Purchase_Order__c 
													     Where Entity__c IN: mapEntityIdToPurchaseOrder.keyset()  
													    and Product_Type__c = 'Base Product' order By CreatedDate Desc limit 1];
			mapPurchaseOrderIdToProductMaster.put(lstFinalPurcahseOrder[0].Id, lstFinalPurcahseOrder[0].Product_Master__c);											    
													    			
			List<Purchase_Order__c>  lstPurchaseOrder = [Select Selected_Product__c,Entity__c, Product_Type__c, 
																Product_Price__c, Product_Master__c, Name, Id 
													     From Purchase_Order__c 
													     Where Entity__c IN: mapEntityIdToPurchaseOrder.keyset() and Product_Type__c != 'Base Product'  
													    ];
													    
			lstFinalPurcahseOrder.addAll(lstPurchaseOrder);	
												     		
			for(Purchase_Order__c objPurchaseOrder : lstPurchaseOrder)
			{
				mapPurchaseOrderIdToProductMaster.put(objPurchaseOrder.Id, objPurchaseOrder.Product_Master__c);	
			}									
				
			system.debug('************mapPurchaseOrderIdToProductMaster'+mapPurchaseOrderIdToProductMaster);	
			system.debug('************lstFinalPurcahseOrdersize'+lstFinalPurcahseOrder.size());	
			system.debug('************lstFinalPurcahseOrder'+lstFinalPurcahseOrder);	
												 
			List<Product_Price_Book__c> lstPriceBook =  [Select Product_code__c, 
																Price_value__c, 
																Name, 
																Flat_Commission__c 
														 From Product_Price_Book__c
														 Where Product_code__c IN : mapPurchaseOrderIdToProductMaster.values()];
														 
			for(Product_Price_Book__c objProductPriceBook : lstPriceBook)	
			{
				mapProductMasterIdToPriceBook.put(objProductPriceBook.Product_code__c, objProductPriceBook);
				system.debug('************mapProductMasterIdToPriceBook'+mapProductMasterIdToPriceBook);
			}										 
														 
			List<Account> lstAccount = [Select Id, Virtual_Partner__c, Total_Flat_Commission__c, 
				 															(Select Id 
				 															 From Product_Orders__r 
				 															 Where Id IN: mapNewIdTopPurchaseOrder.keyset() )
				 							 					    From Account 
				 							 					    Where Id IN: mapEntityIdToPurchaseOrder.keyset()]; 
				 							 					    
			for(Account objAccount : lstAccount)	
			{
				objAccount.Total_Flat_Commission__c = 0;
				mapIdToVirtualPartnerId.put(objAccount.Virtual_Partner__c, objAccount);
				system.debug('************mapIdToVirtualPartnerId'+mapIdToVirtualPartnerId);
				mapIdToAccount.put(objAccount.Id, objAccount);
			} 							 					    
			
			map<Id, Account> mapIdToVirtualPartnerAccount = new Map<Id, Account>([Select Id, Virtual_Partner__c, Total_Flat_Commission__c 
								 							 					  From Account 
								 							 					  Where Id IN: mapIdToVirtualPartnerId.keyset()]); 									 
			for(Account objPartnerAccount : mapIdToVirtualPartnerAccount.values())
			{
				objPartnerAccount.Total_Flat_Commission__c =  0;
				mapIdToVirtualPartner.put(objPartnerAccount.Virtual_Partner__c, objPartnerAccount);
				system.debug('************mapIdToVirtualPartner'+mapIdToVirtualPartner);
			}
			
			
			

			for(Purchase_Order__c objPO  : lstFinalPurcahseOrder)
			{
				system.debug('************objPO'+objPO);
				Account objAccount =  mapIdToAccount.get(objPO.Entity__c);
				Account objPartnerAccount = mapIdToVirtualPartnerAccount.get(objAccount.Virtual_Partner__c);	
				
				system.debug('************objPartnerAccount Tf'+objPartnerAccount.Total_Flat_Commission__c);
				system.debug('************objPartnerAccount'+objPartnerAccount);
				
				Product_Price_Book__c objProductPriceBook = mapProductMasterIdToPriceBook.get(objPO.Product_Master__c);
				objProductPriceBook.Flat_Commission__c = objProductPriceBook.Flat_Commission__c != null ? objProductPriceBook.Flat_Commission__c: 0;
				//flatCommission = objAccount.Total_Flat_Commission__c != null ?  objAccount.Total_Flat_Commission__c : 0;
				//objAccount.Total_Flat_Commission__c= flatCommission + objProductPriceBook.Flat_Commission__c ;
				
				flatCommission = objPartnerAccount.Total_Flat_Commission__c != null ?  objPartnerAccount.Total_Flat_Commission__c : 0;
				//objProductPriceBook.Flat_Commission__c = objProductPriceBook.Flat_Commission__c != null ? objProductPriceBook.Flat_Commission__c: 0;
				objPartnerAccount.Total_Flat_Commission__c= flatCommission + objProductPriceBook.Flat_Commission__c ;
				//objPartnerAccount.Total_Flat_Commission__c = flatCommission + objAccount.Total_Flat_Commission__c;
				system.debug('************bjPartnerAccount.Total_Flat_Commission__c'+objPartnerAccount.Total_Flat_Commission__c);
				
				mapIdToVirtualPartnerAccount.put(objPartnerAccount.Id, objPartnerAccount);
			}
							 
			if(mapIdToVirtualPartnerAccount.size() > 0 && mapIdToVirtualPartnerAccount.keyset() != null)
				update mapIdToVirtualPartnerAccount.values();
		}			 
		
		
	}	*/
	
	public void onAfterInsertUpdatePurchaseOrder(Map<Id, Purchase_Order__c> mapNewIdTopPurchaseOrder)
	{
		if(isRecursiveAccountFlatCommissionInsert || isRecursiveAccountFlatCommissionUpdate)
		{
			system.debug('************isRecursiveAccountFlatCommissionStart'+isRecursiveAccountFlatCommissionInsert);
			system.debug('************isRecursiveAccountFlatCommissionUpdateStart'+isRecursiveAccountFlatCommissionUpdate);
			Map<Id, List<Purchase_Order__c>> mapProductMasterIdTolstPurchaseOrder = new Map<Id, List<Purchase_Order__c>>(); 
			Map<Id, Purchase_Order__c> mapEntityIdToPurchaseOrder = new Map<Id, Purchase_Order__c>();
			Map<Id, Purchase_Order__c> mapEntityIdToPurchaseOrderNew = new Map<Id, Purchase_Order__c>();
			Map<Id, String> mapPurchaseOrderIdToProductMaster = new Map<Id, String>();
			Map<Id, Product_Price_Book__c> mapProductMasterIdToPriceBook = new Map<Id, Product_Price_Book__c>();
			Map<Id, Account> mapIdToVirtualPartner = new Map<Id, Account>();
			Map<Id, Account> mapIdToVirtualPartnerAccount = new Map<Id, Account>();
			Map<Id, Account> mapIdToAccount = new Map<Id, Account>();
			List<Product_Price_Book__c> lstPriceBook = new List<Product_Price_Book__c> ();
			Map<Id, List<Purchase_Order__c>> mapEntityIdTolstPurchaseOrder = new Map<Id, List<Purchase_Order__c>>(); 
			Set<Id> setVirtualPartnerId = new Set<Id>();
			
				
			system.debug('************mapNewIdTopPurchaseOrder'+mapNewIdTopPurchaseOrder);	
			
			
			List<Purchase_Order__c>  lstPurchaseOrder = [Select Selected_Product__c,Entity__c, Product_Type__c,
																	Entity__r.Virtual_Partner__c,Product_Master__r.Name,
																	Entity__r.RecordTypeId,
																	Product_Price__c, Product_Master__c, Name, Id 
														 From Purchase_Order__c 
														 Where Id IN: mapNewIdTopPurchaseOrder.keySet()
														 ];
														 
			for(Purchase_Order__c objPurchaseOrder: lstPurchaseOrder)//mapNewIdTopPurchaseOrder.values())
			{
				//mapEntityIdToPurchaseOrder.put(objPurchaseOrder.Entity__c, objPurchaseOrder);
				setVirtualPartnerId.add(objPurchaseOrder.Entity__r.Virtual_Partner__c);
				
			}
			system.debug('************setVirtualPartnerId'+setVirtualPartnerId);
			
			
				List<Purchase_Order__c> lstUpdatedPurchaseOrder = new List<Purchase_Order__c>(); 		
				List<Purchase_Order__c> lstPurchaseOrder0 = [Select Selected_Product__c,Entity__c, Product_Type__c, 
																	Entity__r.Virtual_Partner__c,
																	Product_Master__r.Name,
																	Product_Price__c, Product_Master__c, Name, Id 
														     From Purchase_Order__c 
														     Where  Entity__r.Virtual_Partner__c IN: setVirtualPartnerId
																 and Entity__r.RecordTypeId =: clientRecordTypeId
														    and Product_Type__c = 'Base Product' order By CreatedDate Desc];
				for(Purchase_Order__c objPurchaseOrder: lstPurchaseOrder0)
				{
					if(!mapEntityIdToPurchaseOrderNew.containsKey(objPurchaseOrder.Entity__c))
					{
						mapEntityIdToPurchaseOrderNew.put(objPurchaseOrder.Entity__c, objPurchaseOrder);
						lstUpdatedPurchaseOrder.add(objPurchaseOrder);
					}	
				}										    
													    
														    			
				List<Purchase_Order__c>  lstPurchaseOrder1 = [Select Selected_Product__c,Entity__c, Product_Type__c, 
																	Entity__r.Virtual_Partner__c,
																	Product_Master__r.Name,
																	Product_Price__c, Product_Master__c, Name, Id 
														     From Purchase_Order__c 
														     Where  Product_Type__c != 'Base Product'
														     and Entity__r.Virtual_Partner__c IN: setVirtualPartnerId  
														     and Entity__r.RecordTypeId =: clientRecordTypeId
														    ];
				
														    
					
															    
				lstUpdatedPurchaseOrder.addAll(lstPurchaseOrder1);	
				
				
			/*	
			
			List<Purchase_Order__c>  lstUpdatedPurchaseOrder = [Select Selected_Product__c,Entity__c, Product_Type__c,
																	Entity__r.Virtual_Partner__c,
																	Product_Price__c, Product_Master__c,Product_Master__r.Name, Name, Id 
																 From Purchase_Order__c 
																 Where Entity__r.Virtual_Partner__c IN: setVirtualPartnerId
																 and Entity__r.RecordTypeId = '01220000000DnK3'
																 and Product_Type__c = 'Base Product' order By CreatedDate Desc
																 ];
			*/													 
			if(!lstUpdatedPurchaseOrder.isEmpty())	
			{													 
				for(Purchase_Order__c objPurchaseOrder: lstUpdatedPurchaseOrder)	
				{
					if(!mapProductMasterIdTolstPurchaseOrder.containsKey(objPurchaseOrder.Product_Master__c))
						mapProductMasterIdTolstPurchaseOrder.put(objPurchaseOrder.Product_Master__c , new List<Purchase_Order__c>{objPurchaseOrder});
					else
						mapProductMasterIdTolstPurchaseOrder.get(objPurchaseOrder.Product_Master__c).add(objPurchaseOrder);
						
					mapPurchaseOrderIdToProductMaster.put(objPurchaseOrder.Id , objPurchaseOrder.Product_Master__c);
					
					if(!mapEntityIdTolstPurchaseOrder.containsKey(objPurchaseOrder.Entity__r.Virtual_Partner__c))
						mapEntityIdTolstPurchaseOrder.put(objPurchaseOrder.Entity__r.Virtual_Partner__c , new List<Purchase_Order__c>{objPurchaseOrder});
					else
						mapEntityIdTolstPurchaseOrder.get(objPurchaseOrder.Entity__r.Virtual_Partner__c).add(objPurchaseOrder);
						
				}												 
						
				lstPriceBook =  [Select Product_code__c, 
										Price_value__c, 
										Name, 
										Flat_Commission__c 
							     From Product_Price_Book__c
						         Where Product_code__c IN : mapProductMasterIdTolstPurchaseOrder.keyset()];
			}	
			
			system.debug('************mapEntityIdTolstPurchaseOrder'+mapEntityIdTolstPurchaseOrder);	
			system.debug('************lstUpdatedPurchaseOrder'+lstUpdatedPurchaseOrder.size());	
												     
			if(!lstPriceBook.isEmpty())	
			{									     
				for(Product_Price_Book__c objPriceBook: lstPriceBook)	
				{
					mapProductMasterIdToPriceBook.put(objPriceBook.Product_code__c, objPriceBook);
					system.debug('************mapProductMasterIdToPriceBook'+mapProductMasterIdToPriceBook);
				}									     
			}
			system.debug('************mapProductMasterIdToPriceBookFinal'+mapProductMasterIdToPriceBook);
			
			if(mapEntityIdTolstPurchaseOrder.keySet() != null)	
			{
				for(Id virtualPartnerId : mapEntityIdTolstPurchaseOrder.keySet())
				{
					Account objAccount = new Account(Id = virtualPartnerId);
					objAccount.Total_Flat_Commission__c = 0;
						
					List<Purchase_Order__c> lstPurchaseOrderUpdated = mapEntityIdTolstPurchaseOrder.get(virtualPartnerId); 	
					for(Purchase_Order__c objPurchaseOrder : lstPurchaseOrderUpdated)
					{
						if(objPurchaseOrder.Entity__r.Virtual_Partner__c == objAccount.Id )
						{
							system.debug('************objPurchaseOrder.Entity__r'+objPurchaseOrder.Entity__c +'Product Name  '+ objPurchaseOrder.Product_Master__r.Name);	
							Id objProductMasterId = mapPurchaseOrderIdToProductMaster.get(objPurchaseOrder.Id);
							Product_Price_Book__c objPriceBook = mapProductMasterIdToPriceBook.get(objProductMasterId);
							
							objPriceBook.Flat_Commission__c = objPriceBook.Flat_Commission__c != null ? objPriceBook.Flat_Commission__c: 0;
							objAccount.Total_Flat_Commission__c += objPriceBook.Flat_Commission__c;
							mapIdToVirtualPartnerAccount.put(objAccount.Id, objAccount);
							
							system.debug('************objAccount'+objAccount.Total_Flat_Commission__c );	
							
						}	
					}
				}
			}
			if(mapIdToVirtualPartnerAccount.size() > 0 && mapIdToVirtualPartnerAccount.keyset() != null)
			{
					update mapIdToVirtualPartnerAccount.values();	
					if(trigger.isAfter && trigger.isInsert && isRecursiveAccountFlatCommissionInsert)		
						isRecursiveAccountFlatCommissionInsert = false;	
					if(trigger.isAfter && trigger.isUpdate && isRecursiveAccountFlatCommissionUpdate)			
					isRecursiveAccountFlatCommissionUpdate = false;						 
				system.debug('************mapIdToVirtualPartnerAccount'+mapIdToVirtualPartnerAccount);	
				system.debug('************isRecursiveAccountFlatCommissionEnd'+isRecursiveAccountFlatCommissionInsert);	
				system.debug('************isRecursiveAccountFlatCommissionUpdateEnd'+isRecursiveAccountFlatCommissionUpdate);
			}	
		}										 													 
	}
	
	
	public void onAfterDeletePurchaseOrder(Map<Id, Purchase_Order__c> mapNewIdTopPurchaseOrder)
	{
		Map<Id, List<Purchase_Order__c>> mapProductMasterIdTolstPurchaseOrder = new Map<Id, List<Purchase_Order__c>>(); 
		Map<Id, Purchase_Order__c> mapEntityIdToPurchaseOrder = new Map<Id, Purchase_Order__c>();
		Map<Id, Purchase_Order__c> mapEntityIdToPurchaseOrderNew = new Map<Id, Purchase_Order__c>();
		Map<Id, String> mapPurchaseOrderIdToProductMaster = new Map<Id, String>();
		Map<Id, Product_Price_Book__c> mapProductMasterIdToPriceBook = new Map<Id, Product_Price_Book__c>();
		Map<Id, Account> mapIdToVirtualPartner = new Map<Id, Account>();
		Map<Id, Account> mapIdToVirtualPartnerAccount = new Map<Id, Account>();
		Map<Id, Account> mapIdToAccount = new Map<Id, Account>();
		List<Product_Price_Book__c> lstPriceBook = new List<Product_Price_Book__c> ();
		Map<Id, List<Purchase_Order__c>> mapEntityIdTolstPurchaseOrder = new Map<Id, List<Purchase_Order__c>>(); 
		Set<Id> setVirtualPartnerId = new Set<Id>();
		Set<Id> setVirtualPartnerId1 = new Set<Id>();	
			
		system.debug('************mapNewIdTopPurchaseOrder'+mapNewIdTopPurchaseOrder);	
		for(Purchase_Order__c objPurchaseOrder: mapNewIdTopPurchaseOrder.values())//mapNewIdTopPurchaseOrder.values())
		{
			setVirtualPartnerId1.add(objPurchaseOrder.Entity__c);
			//mapEntityIdToPurchaseOrder.put(objPurchaseOrder.Entity__c, objPurchaseOrder);
			
		}
		system.debug('************setVirtualPartnerId1'+setVirtualPartnerId1);
		
		List<Account> lstAccount = [Select Id, Name,Virtual_Partner__c, Total_Flat_Commission__c 
								 							 					  From Account 
								 							 					  Where  Id IN: setVirtualPartnerId1];
								 							 					  
		for(Account objAccount: lstAccount)
		{
			
			setVirtualPartnerId.add(objAccount.Virtual_Partner__c);
		}						 							 					  
								 							 					  
		system.debug('************setVirtualPartnerId'+setVirtualPartnerId);
		
		
			List<Purchase_Order__c> lstUpdatedPurchaseOrder = new List<Purchase_Order__c>(); 		
			/*
			List<Purchase_Order__c> lstPurchaseOrder0 = [Select Selected_Product__c,Entity__c, Product_Type__c, 
																Entity__r.Virtual_Partner__c,
																Product_Master__r.Name,
																Product_Price__c, Product_Master__c, Name, Id 
													     From Purchase_Order__c 
													     Where  Entity__r.Virtual_Partner__c IN: setVirtualPartnerId
															 and Entity__r.RecordTypeId =: clientRecordTypeId // '01220000000DnK3'
													    and Product_Type__c = 'Base Product' order By CreatedDate Desc];
			for(Purchase_Order__c objPurchaseOrder: lstPurchaseOrder0)
			{
				if(!mapEntityIdToPurchaseOrderNew.containsKey(objPurchaseOrder.Entity__c))
				{
					mapEntityIdToPurchaseOrderNew.put(objPurchaseOrder.Entity__c, objPurchaseOrder);
					lstUpdatedPurchaseOrder.add(objPurchaseOrder);
				}	
			}	
			*/	
			List<Purchase_Order__c> lstPurchaseOrder0 = [Select Selected_Product__c,Entity__c, Product_Type__c, 
																		Entity__r.Virtual_Partner__c,
																		Product_Master__r.Name,
																		Product_Price__c, Product_Master__c, Name, Id 
															     From Purchase_Order__c 
															     Where  Entity__r.Virtual_Partner__c IN: setVirtualPartnerId
																	 and Entity__r.RecordTypeId =: clientRecordTypeId
															    	 //and Product_Type__c = 'Base Product' 
															         order By CreatedDate Desc];
					Set<String> strProductType = new Set<String>();										    
					for(Purchase_Order__c objPurchaseOrder: lstPurchaseOrder0)
					{
						/*if(!mapEntityIdToPurchaseOrderNew.containsKey(objPurchaseOrder.Entity__c))
						{
							//mapPurchaseOrderIdToProductMaster.put(objPurchaseOrder.Id, objPurchaseOrder.Product_Master__c);
							lstUpdatedPurchaseOrder.add(objPurchaseOrder);
						}*/
						
						if(!strProductType.contains('Base Product'))	
						{
							lstUpdatedPurchaseOrder.add(objPurchaseOrder);
							strProductType.add('Base Product');
						}
						else
						{
							lstUpdatedPurchaseOrder.add(objPurchaseOrder);
						}
					}										    
									
			
											    
			system.debug('************lstUpdatedPurchaseOrder'+lstUpdatedPurchaseOrder);									    
			/*										    			
			List<Purchase_Order__c>  lstPurchaseOrder1 = [Select Selected_Product__c,Entity__c, Product_Type__c, 
																Entity__r.Virtual_Partner__c,
																Product_Master__r.Name,
																Product_Price__c, Product_Master__c, Name, Id 
													     From Purchase_Order__c 
													     Where  Product_Type__c != 'Base Product'
													     and Entity__r.Virtual_Partner__c IN: setVirtualPartnerId  
													     and Entity__r.RecordTypeId =: clientRecordTypeId// '01220000000DnK3'
													    ];
			
														    
			lstUpdatedPurchaseOrder.addAll(lstPurchaseOrder1);	
			*/
			
		/*	
		
		List<Purchase_Order__c>  lstUpdatedPurchaseOrder = [Select Selected_Product__c,Entity__c, Product_Type__c,
																Entity__r.Virtual_Partner__c,
																Product_Price__c, Product_Master__c,Product_Master__r.Name, Name, Id 
															 From Purchase_Order__c 
															 Where Entity__r.Virtual_Partner__c IN: setVirtualPartnerId
															 and Entity__r.RecordTypeId = '01220000000DnK3'
															 and Product_Type__c = 'Base Product' order By CreatedDate Desc
															 ];
		*/													 
		if(!lstUpdatedPurchaseOrder.isEmpty())	
		{													 
			for(Purchase_Order__c objPurchaseOrder: lstUpdatedPurchaseOrder)	
			{
				if(!mapProductMasterIdTolstPurchaseOrder.containsKey(objPurchaseOrder.Product_Master__c))
					mapProductMasterIdTolstPurchaseOrder.put(objPurchaseOrder.Product_Master__c , new List<Purchase_Order__c>{objPurchaseOrder});
				else
					mapProductMasterIdTolstPurchaseOrder.get(objPurchaseOrder.Product_Master__c).add(objPurchaseOrder);
					
				mapPurchaseOrderIdToProductMaster.put(objPurchaseOrder.Id , objPurchaseOrder.Product_Master__c);
				
				if(!mapEntityIdTolstPurchaseOrder.containsKey(objPurchaseOrder.Entity__r.Virtual_Partner__c))
					mapEntityIdTolstPurchaseOrder.put(objPurchaseOrder.Entity__r.Virtual_Partner__c , new List<Purchase_Order__c>{objPurchaseOrder});
				else
					mapEntityIdTolstPurchaseOrder.get(objPurchaseOrder.Entity__r.Virtual_Partner__c).add(objPurchaseOrder);
					
			}												 
					
			lstPriceBook =  [Select Product_code__c, 
									Price_value__c, 
									Name, 
									Flat_Commission__c 
						     From Product_Price_Book__c
					         Where Product_code__c IN : mapProductMasterIdTolstPurchaseOrder.keyset()];
		}	
		
		system.debug('************mapEntityIdTolstPurchaseOrder'+mapEntityIdTolstPurchaseOrder);	
		system.debug('************lstUpdatedPurchaseOrder'+lstUpdatedPurchaseOrder.size());	
											     
		if(!lstPriceBook.isEmpty())	
		{									     
			for(Product_Price_Book__c objPriceBook: lstPriceBook)	
			{
				mapProductMasterIdToPriceBook.put(objPriceBook.Product_code__c, objPriceBook);
				system.debug('************mapProductMasterIdToPriceBook'+mapProductMasterIdToPriceBook);
			}									     
		}
		system.debug('************mapProductMasterIdToPriceBookFinal'+mapProductMasterIdToPriceBook);
		
		if(mapEntityIdTolstPurchaseOrder.keySet() != null)	
		{
			for(Id virtualPartnerId : mapEntityIdTolstPurchaseOrder.keySet())
			{
				Account objAccount = new Account(Id = virtualPartnerId);
				objAccount.Total_Flat_Commission__c = 0;
					
				List<Purchase_Order__c> lstPurchaseOrderUpdated = mapEntityIdTolstPurchaseOrder.get(virtualPartnerId); 	
				for(Purchase_Order__c objPurchaseOrder : lstPurchaseOrderUpdated)
				{
					if(objPurchaseOrder.Entity__r.Virtual_Partner__c == objAccount.Id )
					{
						system.debug('************objPurchaseOrder.Entity__r'+objPurchaseOrder.Entity__c +'Product Name  '+ objPurchaseOrder.Product_Master__r.Name);	
						Id objProductMasterId = mapPurchaseOrderIdToProductMaster.get(objPurchaseOrder.Id);
						Product_Price_Book__c objPriceBook = mapProductMasterIdToPriceBook.get(objProductMasterId);
						
						objPriceBook.Flat_Commission__c = objPriceBook.Flat_Commission__c != null ? objPriceBook.Flat_Commission__c: 0;
						objAccount.Total_Flat_Commission__c += objPriceBook.Flat_Commission__c;
						mapIdToVirtualPartnerAccount.put(objAccount.Id, objAccount);
						
						system.debug('************objAccount'+objAccount.Total_Flat_Commission__c );	
						
					}	
				}
			}
		}
		if(mapIdToVirtualPartnerAccount.size() > 0 && mapIdToVirtualPartnerAccount.keyset() != null)
				update mapIdToVirtualPartnerAccount.values();											 
		system.debug('************mapIdToVirtualPartnerAccount'+mapIdToVirtualPartnerAccount);												 													 
	}
		
}