Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsTestTaken__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsTestTaken</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Wellness_Score_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wellness_Score_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Freedom Scale Score Card</label>
    <nameField>
        <label>Freedom Scale Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freedom Scale Score Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/EntityHandler.cls
/* 
*   EntityHnadler class update the field on Account(Entity) for verifying Wellness Test is Taken or not
*
*   Revision History:
*
*   Version        Author          Date            Description
*   1.0            Gaurav      15/01/2013          Initial Draft
*   
*/

public with sharing class EntityHandler {
	
	public void onAfterInsert(List<Wellness_Score_Card__c> plstNewWellnessScoreCard){
		
		if(plstNewWellnessScoreCard[0].Account__c == NULL ) return;
		if(plstNewWellnessScoreCard[0].Account__r.IsTestTaken__c == false){
			
			plstNewWellnessScoreCard[0].Account__r.IsTestTaken__c = true;
		}  
		
		
		try{
			
		}
		catch(Exception e){
			system.debug('Exception while Updating Account'+e.getMessage());
			
		}
	}

}