Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Factor__c</fullName>
        <label>Adjustment Factor %</label>
        <picklist>
            <picklistValues>
                <fullName>-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Manufacturer_Master__c.object
<CustomObject>
    <description>Created for product master</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product Master</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Short_Code__c</fullName>
        <description>Product master</description>
        <label>Short Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Product Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Master__c.object
<CustomObject>
    <fields>
        <fullName>IsRenewalAllowed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Renewal Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Product Master object</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exchange-Traded Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FFreedom Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Added Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Manufacturer__c</fullName>
        <label>Product Manufacturer</label>
        <referenceTo>Product_Manufacturer_Master__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Product_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Grace_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renewal Grace Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Period_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Renewal Period In Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscription_Period_In_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Subscription Period In Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PRD-{000000}</displayFormat>
        <label>Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Price_Book__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education_Cess__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Education Cess</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Flat_Commission__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Flat Commission</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_value__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Products where Price Category is One Time, Price should be set as a decimal number containing 2 decimal places. e.g. 12545.22. 
Products where Price Category is other One Time, Price should be set as percentage containing 2 decimal places. e.g.  0.75.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Code</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Product Price Books</relationshipLabel>
        <relationshipName>Product_Price_Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Tax__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Service Tax</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sp_Education_Cess__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Sp. Education Cess</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <defaultValue>0</defaultValue>
        <label>VAT</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Price Book</label>
    <nameField>
        <displayFormat>PRBK-{0000000}</displayFormat>
        <label>Product Price Book Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Price Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Purchase_Order__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Education_Cess__c</fullName>
        <label>Education Cess</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Product_Orders</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Cancel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Cancel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_status__c</fullName>
        <label>Order status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payable_Amount__c</fullName>
        <label>Payable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Master__c</fullName>
        <label>Product Master</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Purchase Orders</relationshipLabel>
        <relationshipName>Product_Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Price__c</fullName>
        <label>Product Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product  Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Renewal_Grace_Days__c</fullName>
        <label>Renewal Grace Days</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Renewal_Period_In_Days__c</fullName>
        <label>Renewal Period In Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selected_Product__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service_Tax__c</fullName>
        <label>Service Tax</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sp_Education_Cess__c</fullName>
        <label>Sp. Education Cess</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Subscription_Period_In_Days__c</fullName>
        <label>Subscription Period In Days</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Tax__c</fullName>
        <formula>Service_Tax__c + Sp_Education_Cess__c + Education_Cess__c + VAT__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>VAT__c</fullName>
        <label>VAT</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Renewal__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewals</relationshipLabel>
        <relationshipName>Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Renew</label>
        <type>Checkbox</type>
    </fields>
    <label>Renewal</label>
    <nameField>
        <displayFormat>Renewal-{0}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ProductOrderInformationController.cls
public class ProductOrderInformationController 
{
    public List<PurchaseOrderDetail> lstPurchaseOrderDetail {get;set;}
    public Id entityId {get;set;}
    public Purchase_Order__c objPurchaseOrder{get;set;}
    public Double totalPaybleAmount{get;set;}
    public Boolean isEditPurchasedOrder {get;set;}
    //public Boolean isRenewal{get;set;}
    public Boolean isRenewalAndPurchaseServices{get;set;}
    public ProductOrderInformationController(ApexPages.StandardController controller)
    {
        entityId = controller.getId();
        //isRenewal = FreedomUtils.hasRenewalPeriod(entityId);
        try
        {
            Purchase_Order__c objPO = [Select Product_Master__r.IsRenewalAllowed__c from Purchase_Order__c where Entity__c =: entityId and Product_Type__c = 'Base Product'
                                                and Is_Cancel__c = false];
            isRenewalAndPurchaseServices = objPO.Product_Master__r.IsRenewalAllowed__c;
            /*Boolean isCheck = [Select Is_Renew__c from Renewal__c where Entity__c =: entityId order by CreatedDate limit  1].Is_Renew__c;
            if(isRenewal && isCheck)
            {
                isRenewal = !isCheck;
            }*/
        }
        catch(Exception e)
        {
            isRenewalAndPurchaseServices = true;
        }
        createPurchaseOrderDetail();
    }
    
    private void createPurchaseOrderDetail()
    {
        totalPaybleAmount = 0;
        Set<String> setOrder = new Set<String>();
        objPurchaseOrder = new Purchase_Order__c();
        lstPurchaseOrderDetail = new List<PurchaseOrderDetail>();
        isEditPurchasedOrder = false;
        
        for(Purchase_Order__c objPurchaseOrder : [Select Id, Order__c, VAT__c, Education_Cess__c,Sp_Education_Cess__c, Service_Tax__c, Product_Type__c, Product_Price__c, 
                                                         Product_Master__c, Is_Cancel__c, Discount__c,Renewal_Grace_Days__c, Renewal_Period_In_Days__c,     
                                                         Subscription_Period_In_Days__c,Total_Tax__c, 
                                                         Selected_Product__c, Entity__c,  Payable_Amount__c, Product_Master__r.Product_Name__c , Order_Status__c
                                                    From Purchase_Order__c
                                                    Where Entity__c =: entityId and Is_Cancel__c = false order by CreatedDate])
        { 
            if(!setOrder.contains(objPurchaseOrder.Order__c))
            {
                lstPurchaseOrderDetail.add(new PurchaseOrderDetail(objPurchaseOrder.Order__c, objPurchaseOrder.Order_status__c, objPurchaseOrder));
                setOrder.add(objPurchaseOrder.Order__c);
            }
            else
            {
                lstPurchaseOrderDetail.add(new PurchaseOrderDetail('', '', objPurchaseOrder));
            }
            
            if(!objPurchaseOrder.Is_Cancel__c)
                totalPaybleAmount += objPurchaseOrder.Payable_Amount__c;
        }
        try
        {
            objPurchaseOrder = [Select Product_Master__c, Is_Cancel__c, Discount__c,Renewal_Grace_Days__c, Renewal_Period_In_Days__c,   
                                   Subscription_Period_In_Days__c
                              From Purchase_Order__c
                              Where Entity__c =: entityId And  Is_Cancel__c = false and Product_Type__c = 'Base Product' order by CreatedDate];
            isEditPurchasedOrder = true;
        }
        catch(Exception e)
        {
            System.debug('------------------'+e);
        }
        
    }
    
    public class PurchaseOrderDetail
    {
        public String purchaseOrder {get;set;}
        public String orderStatus {get;set;}
        public Purchase_Order__c objPurchaseOrder{get;set;}
        
        public PurchaseOrderDetail(String purchaseOrder, String orderStatus, Purchase_Order__c objPurchaseOrder)
        {
            this.purchaseOrder = purchaseOrder;
            this.orderStatus = orderStatus;
            this.objPurchaseOrder = objPurchaseOrder;
        }
    }
    
    @isTest(SeeAllData = true)
    public static void testProductOrderInformationController()
    {
        Product_Manufacturer_Master__c PM1 = new Product_Manufacturer_Master__c(Name='HDFC Life Insurance1', Short_Code__c='HDFCLI', Is_Active__c=true);
        insert PM1;
        
        // Insert Product record
        Product_Master__c objProduct = new Product_Master__c(Product_Manufacturer__c=PM1.Id, 
                                                            Is_Active__c=false, Product_Name__c='Risk Plan', ProductType__c='Base Product',
                                                            Subscription_Period_In_Days__c = 365, Renewal_Period_In_Days__c = 365,
                                                            Renewal_Grace_Days__c = 30);
        insert objProduct;                                                      
        Product_Price_Book__c objPriceBook = new Product_Price_Book__c(Product_code__c = objProduct.Id, Price_value__c = 1500, Discount__c= 500,
                                                                        Service_Tax__c = 2, Sp_Education_Cess__c = 4, VAT__c = 5, Education_Cess__c = 6,Flat_Commission__c =1000 );
        insert objPriceBook;    
        
        
         Account objGeneralAccount = new Account(Name='Parner Account Test',
    								RecordTypeId = RecTypes__c.getInstance('General_Business').Record_Type_Value__c);
    	insert 	objGeneralAccount;
    	
        Account objAccount = new Account(LastName='Test Freedom', Adjustment_Factor__c='2',Virtual_Partner__c = objGeneralAccount.Id,
                           PersonTitle='TestData',PersonBirthdate=system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463712345',
                           Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',PersonMailingStreet='aa',
                           PersonMailingCity='bbb',Retirement_Year__c=2034,Residential_Status_del__c='own',Retirement_Age__c='58',Estimated_Life_Expectancy__c='67',
                           Estimated_Life_EndYear__c=2041,Relationship_to_Entity__pc='husband', Related_To__c ='Ffreedom',
                           RecordTypeId = RecTypes__c.getInstance('AccountClient').Record_Type_Value__c,Will__c = true);    
        insert objAccount;  
        
        ApexPages.StandardController std = new ApexPages.StandardController(objAccount);        
        ProductOrderInformationController objPIC = new ProductOrderInformationController(std);  
        
        Purchase_Order__c objPO = new Purchase_Order__c(Order__c = 'FFP/001', VAT__c = 4, Education_Cess__c = 5,Sp_Education_Cess__c = 6, Service_Tax__c = 7, 
                                                         Product_Type__c = 'Base Product', Product_Price__c = 1500, 
                                                         Product_Master__c = objProduct.Id, Is_Cancel__c = false, Discount__c = 500, 
                                                         Renewal_Grace_Days__c = 30, Renewal_Period_In_Days__c = 365,   
                                                         Subscription_Period_In_Days__c = 365,
                                                         Selected_Product__c = 'Risk Plan', Entity__c = objAccount.Id, Payable_Amount__c = 1000, Order_Status__c = 'New');
        insert objPO;   
        
        Purchase_Order__c objPO1 = new Purchase_Order__c(Order__c = 'FFP/001', VAT__c = 4, Education_Cess__c = 5,Sp_Education_Cess__c = 6, Service_Tax__c = 7, 
                                                         Product_Type__c = 'Base Product 1', Product_Price__c = 1500, 
                                                         Product_Master__c = objProduct.Id, Is_Cancel__c = false, Discount__c = 500, 
                                                         Renewal_Grace_Days__c = 30, Renewal_Period_In_Days__c = 365,   
                                                         Subscription_Period_In_Days__c = 365,
                                                         Selected_Product__c = 'Risk Plan 1', Entity__c = objAccount.Id, Payable_Amount__c = 1000, Order_Status__c = 'New');
        insert objPO1;
        
        ProductOrderInformationController objPIC1 = new ProductOrderInformationController(std); 
    }
}