Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <defaultValue>00</defaultValue>
        <label>Age</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <label>Amount - 1st Installment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cheque_Received_Date__c</fullName>
        <label>Cheque Received Date - 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cheque_date__c</fullName>
        <label>Cheque date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expected_Amount__c</fullName>
        <formula>IF(ISBLANK( TDS__c ),
(IF(ISPICKVAL( Agreement_Structure__c ,&quot;2,500&quot; ),
2500*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;5,000&quot; ),
5000*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;7,500&quot; ),
7500*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;10,000&quot; ),
10000*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;12,500&quot; ),
12500*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;15,000&quot; ),
15000*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;25,000&quot; ),
25000*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;35,000&quot; ),
35000*((100- Discount__c  )/100)*1.103,
IF(ISPICKVAL( Agreement_Structure__c ,&quot;30,000&quot; ),
30000*((100- Discount__c  )/100)*1.103,NULL)))))))))),
(IF(ISPICKVAL( Agreement_Structure__c ,&quot;15,000&quot; ),
15000*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;2,500&quot; ),
2500*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;5,000&quot; ),
5000*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;7,500&quot; ),
7500*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;10,000&quot; ),
10000*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;12,500&quot; ),
12500*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;25,000&quot; ),
25000*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;35,000&quot; ),
35000*((100- Discount__c  )/100)*1.103*(1-TDS__c),
IF(ISPICKVAL( Agreement_Structure__c ,&quot;30,000&quot; ),
30000*((100- Discount__c  )/100)*1.103*(1-TDS__c),NULL))))))))))
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Has_Opted_For_Renewal__c</fullName>
        <label>Has Opted For Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <formula>Cheque_Received_Date__c + 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_SMS_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal SMS Sent</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Cheque_Details__c.object
<CustomObject>
    <description>To represent cheque related details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cheque Details</relationshipLabel>
        <relationshipName>Cheque_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <label>Amount Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cheque_Date__c</fullName>
        <label>Cheque Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cheque_No__c</fullName>
        <label>Cheque No</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Cheque_Status__c</fullName>
        <label>Cheque Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dishonoured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEFT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Installment__c</fullName>
        <label>Installment</label>
        <picklist>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Detail</label>
        <referenceTo>Order_Detail__c</referenceTo>
        <relationshipLabel>Cheque Details</relationshipLabel>
        <relationshipName>Cheque_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cheque Details</label>
    <nameField>
        <displayFormat>CHQ-{000000}</displayFormat>
        <label>Cheque Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cheque Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Cheque_No__c</fullName>
        <label>Cheque No</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completion_Date__c</fullName>
        <label>Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <formula>Approve_Action_Plan__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name__c</fullName>
        <label>Opportunity Name</label>
        <picklist>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Succession Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Income Tax Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsequent Investments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Renewal__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <label>Amount Received</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cheque_Received_Date__c</fullName>
        <label>Cheque Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewals</relationshipLabel>
        <relationshipName>Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expected_Amount__c</fullName>
        <label>Expected Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Has_Opted_for_Renewal__c</fullName>
        <label>Has Opted for Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsCompleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsCompleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Renewal_SMS_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Renewal SMS Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Renewal</label>
    <nameField>
        <displayFormat>Renewal-{0}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Workstation__c.object
<CustomObject>
    <fields>
        <fullName>Financial_Planner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Planner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Engagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Engagement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workstation</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Workstation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestBatchForRenewalProcess.cls
public class TestBatchForRenewalProcess 
{ 
	
	@isTest(SeeAllData = true)
    static void BatchForRenewalProcessTest()
    {
      
      ID ProfileID = [ Select id from Profile where name = 'Financial Planner'].id;
      system.debug('*******ProfileID*****'+ProfileID);
      List<User> lstUser = new List<User>();
      User user1,user2,user;
      
      user1 = new User( email='test-user@TLemail.com', profileid = ProfileID, UserName='test-user@feemail.com', alias='tuser1', CommunityNickName='tuser3',TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', FirstName = 'Test_Y_Fname', LastName = 'ManagerLname' );
      lstUser.add(user1);
        
      user2 = new User( email='test-user@TLemail.com', profileid = ProfileID, UserName='test-user@email.com', alias='tuser1', CommunityNickName='tuser2',TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', FirstName = 'Test_Z_Fname', LastName = 'MemberEngagementLname' );
      lstUser.add(user2);
      
	  user = new User( email='test-user@fakeemail.com', profileid = ProfileID,ManagerId=user1.Id , UserName='test-user@fakeemail.com', alias='tuser1', CommunityNickName='tuser1',TimeZoneSidKey='America/New_York', LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', FirstName = 'Test_Parent_Fname', LastName = 'Test_Parent_Lname' );
      lstUser.add(user);
      insert lstUser;
      
      Workstation__c objWorkstation = new Workstation__c();
      objWorkstation.Financial_Planner__c = user.Id;
      objWorkstation.Manager__c = user1.Id;
      objWorkstation.Member_Engagement__c = user2.Id;
      insert objWorkstation;
      
      
      Account acc1 = new Account();
      acc1.LastName ='Test';
      acc1.FirstName='Test';
      acc1.Age__c=22;
       // Commented on 01Mar 2012 : because Cheque_Received_Date__c will be removed from Account object 
      //acc1.Cheque_Received_Date__c = Date.newInstance(2010, 12, 1);
      acc1.Entity_Status__c = 'Active';
      system.debug('*****User Id*******'+user.Id);
      acc1.OwnerId = user.Id;
      acc1.PersonEmail  = 'test.test@eternussolutions.com';
      acc1.PersonMobilePhone = '1223131100';
      insert acc1;
      String strNewOrderNumber = 'FFP/' + String.valueOf(System.today().year()).substring(2, 4) + '-' + 
                                         String.valueOf(System.today().year() + 1).substring(2, 4) + '/001' ; 
                                           
	   Order_Detail__c objOrderDetail = new Order_Detail__c(Order_Number__c = strNewOrderNumber, Account__c = acc1.Id );
       insert objOrderDetail;
        
      //Account account = [select Id,LastName from Account where LastName='Test_Renewal_Lname1'];
      Cheque_Details__c objchq = new Cheque_Details__c(Account__c = acc1.Id, Installment__c = '1st',
      								Cheque_Date__c = Date.today(),Cheque_No__c = 'Ch0012',Amount_Received__c = 1200,
      								Order_Detail__c = objOrderDetail.Id,Cheque_Status__c = 'Deposited');
      insert objchq;
        
      Id idaccount =user.Id;
      Renewal__c ren1 = new Renewal__c();
      ren1.Cheque_Received_Date__c = Date.newInstance(2011, 12, 1);
      ren1.Has_Opted_for_Renewal__c = 'Yes';
      //ren1.IsCompleted__c = false;
      ren1.Entity__c = acc1.Id; 
      ren1.Renewal_Date__c = Date.newInstance(2011, 12, 20);
      insert ren1;
      
      //Commented on 01Mar 2012 : because Cheque_Received_Date__c will be removed from Account object 
      //Account acc = new Account(FirstName='Test_Fname1',LastName='Test_Renewal_Lname1',Cheque_Received_Date__c= Date.newInstance(2010, 12, 1),PersonMobilePhone='9876543210',PersonEmail='tech@ffreedom.in',Entity_Status__c='Active',OwnerId = idaccount);
      //Account acc = new Account(FirstName='Test_Fname1',LastName='Test_Renewal_Lname1',PersonMobilePhone='9876543210',PersonEmail='tech@ffreedom.in',Entity_Status__c='Active',OwnerId = idaccount);
      //insert acc;
        
      //Cheque_Details__c objchq1 = new Cheque_Details__c(Account__c = acc.Id, Installment__c = '1st',Cheque_Date__c = Date.today(),Cheque_No__c = 'Ch0013',Amount_Received__c = 1200,Cheque_Status__c = 'Deposited');
      //insert objchq1;
        
      //Renewal__c renewal = new Renewal__c();
      //renewal.Entity__c = acc.Id; 
      //renewal.Renewal_Date__c = Date.newInstance(2011, 12, 1);
      //upsert renewal;
        
      //Renewal__c renewal2 = new Renewal__c();
      //renewal2.Entity__c = acc.Id; 
      //renewal2.Renewal_Date__c = Date.newInstance(2011, 12, 1);
      // upsert renewal2;
        
      /*  Execution_Tracker__c objExecution = new Execution_Tracker__c();
        objExecution.Entity_Name__c =acc1.Id;
        objExecution.Opportunity_Name__c = 'SIP';
        objExecution.Completion_Date__c =Date.newInstance(2010, 12, 1); 
        insert  objExecution; 
        */
      Execution_Tracker__c objExecution1 = new Execution_Tracker__c();
      objExecution1.Entity_Name__c =acc1.Id;
      objExecution1.Opportunity_Name__c = 'SIP';
      objExecution1.Completion_Date__c =Date.newInstance(2010, 12, 1); 
      insert  objExecution1;
      
      String []lstCCAddress = new String[]{'tech@ffreedom.in'};
      Id templateId = [ Select e.Name, e.Id From EmailTemplate e where Name = 'Renewal Template With Atleast One Execution'].Id;
      Renewal__c objRenewal = [Select id ,Entity__c,Entity_Name__c,Mobile__c From Renewal__c where id =:ren1.Id];
      
      Account acct= [Select Id, PersonContactId from Account where Id =:acc1.Id]; 
      BatchForRenewalProcess objBatch = new BatchForRenewalProcess();
      objBatch.query = 'Select r.Id,r.Renewal_SMS_Sent__c, r.IsCompleted__c,r.Renewal_Date__c ,r.Entity_Name__c,r.Mobile__c,r.Has_Opted_for_Renewal__c, r.Expected_Amount__c, r.Entity__r.Entity_Status__c, r.Entity__r.OwnerId, r.Entity__c, r.Discount__c, r.Discontinuation_SMS_Sent__c, r.CreatedDate, r.Cheque_Received_Date__c,r.Entity__r.Email_Temp__c, r.Entity__r.PersonEmail,r.Entity__r.PersonContactId ' +
            'FROM Renewal__c r where Id=\'' + ren1.Id +'\''+' limit 2';
      Test.startTest();
      objBatch.todaysDate = Date.newInstance(2011,11,20);
      database.executebatch(objBatch);
      objBatch.todaysDate = Date.newInstance(2011,12,5);
      database.executebatch(objBatch);
      Task objTask =  objBatch.createMultipleTask(acc1.OwnerId,objRenewal);
      objBatch.sendEmailFunctionality(lstCCAddress, templateId, acct.PersonContactId);
      Test.stopTest();
    }
}