Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>From_Portal__c</fullName>
        <defaultValue>0</defaultValue>
        <label>From_Portal</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsSynched__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSynched</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Synched_Date_Time__c</fullName>
        <label>Synched Date Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/HandlerForAfterUpdateOnContact.cls
public with sharing class HandlerForAfterUpdateOnContact 
{
	public void beforeUpdateAccount(List<Account> lstNewAccount, List<Account> lstOldAccount)
		{
		for(Account objNewAccount : lstNewAccount)
		{
			for(Account objOldAccount : lstOldAccount)
		    {
			   if(objOldAccount.From_Portal__c == 1 && objNewAccount.Synched_Date_Time__c > objOldAccount.LastModifiedDate )
			   {
				  objNewAccount.From_Portal__c = 0;
				  objNewAccount.IsSynched__c = true;
			   }
			   else if(objOldAccount.From_Portal__c == 1 && objNewAccount.Synched_Date_Time__c < objOldAccount.LastModifiedDate )
			   {
				  objNewAccount.From_Portal__c = 0;
			   }
			   else if(objOldAccount.From_Portal__c == 0)
			   {
			   	 objNewAccount.IsSynched__c = false;
			   }
			   }
			
		   }
	}

}