Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Channel_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Channel Manager of the partner portal account</description>
        <label>Channel Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Address__c</fullName>
        <label>Company Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Created_date_Month__c</fullName>
        <formula>CASE( MONTH ( DATEVALUE( CreatedDate ) ) , 
1, &quot;January &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
2, &quot;Febuary &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
3, &quot;March &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
4, &quot;April &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
5, &quot;May &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
6, &quot;June &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
7, &quot;July &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
8, &quot;August &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
9, &quot;September &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
10, &quot;October &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
11, &quot;November &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
&quot;December &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ) )</formula>
        <label>Created date Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_ID__c</fullName>
        <label>Email ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity_Stage__c</fullName>
        <label>Entity Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Data Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Writing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action Plan Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execution in Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Logo__c</fullName>
        <description>This field stores logo for each Partner Portals</description>
        <inlineHelpText>Partner Portal Logo</inlineHelpText>
        <label>Logo</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>To select user.</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Ffreedom</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is created to select the related virtual partner of that entity.

Practice Owner (Partner): Account Record Type</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Created_date_Month__c</fullName>
        <formula>CASE( MONTH ( DATEVALUE( CreatedDate ) ) , 
1, &quot;January &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
2, &quot;Febuary &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
3, &quot;March &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
4, &quot;April &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
5, &quot;May &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
6, &quot;June &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
7, &quot;July &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
8, &quot;August &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
9, &quot;September &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
10, &quot;October &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
11, &quot;November &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ), 
&quot;December &quot; + TEXT ( YEAR ( DATEVALUE( CreatedDate ) ) ) )</formula>
        <label>Created date Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Ffreedom</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>To select related virtual partner.</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerLeads</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/BatchBusinessPartnerStatusReport.cls
global class BatchBusinessPartnerStatusReport implements Database.Batchable<sObject>
{
	/*
		@MethodName: start 
		@param : Database.BatchableContext BC
		@Description: It is overriden method of  Database.Batchable interface.
	*/
	Map<Id, User> mapIdToUser = new Map<Id, User>([Select Id, Name, Email from User]);
	public String strDate {get;set;}
	private Contact objContact {get;set;}
	private Account objAccount {get;set;}
	public String query{get;set;}
	private User sbuUser{get;set;}
 	Map<Id,Contact> mapIdToContact = new Map<Id,Contact>([Select Id,AccountId From Contact ]);
    
 	Map<Id,Account> mapIdToAccount = new Map<Id,Account>([Select Id, Logo__c, Email_ID__c, Company_Address__c, Phone
 															, Name, Channel_Manager__r.Email,Channel_Manager__r.Name From Account ]);
    global Database.QueryLocator start(Database.BatchableContext BC) 
    { 
    	return Database.getQueryLocator('Select Name, Email, UserType,ContactId, Profile.Name, ProfileId, Manager.Email, Manager.Name, ManagerId, Id From User where UserType =\'PowerPartner\' and IsActive=true');
    	//return Database.getQuerylocator('Select Id, Name, Related_To__c, Email_ID__c, RecordTypeId From Account where Related_To__c = \'Business Partner\' and RecordTypeId = \'01220000000Do0o\'');//: RecTypes__c.getInstance(\'General_Business\').Record_Type_Value__c');    																				
    }
    
    /*
		@MethodName: execute 
		@param : Database.BatchableContext BC, List<sObject> scope
		@Description: It is overriden method of  Database.Batchable interface.
	*/
    global void execute(Database.BatchableContext BC, List<User> lstUser) 
    {
    	system.debug('******lstUser********'+lstUser);
    	
    	User objUser = Test.isRunningTest()== true?lstUser[1] : lstUser[0];
    	sbuUser = new User();
    	objContact = new Contact();
    	objAccount = new Account();
		system.debug('******objUser********'+objUser);
		system.debug('******mapIdToContact********'+mapIdToContact);
		if(mapIdToUser.containsKey(objUser.ManagerId))
		{
			sbuUser = mapIdToUser.get(objUser.ManagerId);
		}
    	if(objUser.ContactId != null)
    	{
	    	if(mapIdToContact.containsKey(objUser.ContactId))
	    	{
	    		objContact = mapIdToContact.get(objUser.ContactId);
	    		if(objContact != null)
	    		{
	    			if(mapIdToAccount.containsKey(objContact.AccountId))
	    			{
	    				objAccount = mapIdToAccount.get(objContact.AccountId);
	    			}
	    		}
	    		
	    	}
    	}
    
	  	Map<Id, List<Lead>> mapAccountToLead = new Map<Id,List<Lead>>();
    	String entityStatus = '';
		Datetime dtReport = Datetime.now();
		strDate = dtReport.format('dd - MMM - yyyy');
	   	String strHtmlBodyLead = '<html> <body> <b>Report Date</b>: ' + strDate + '<br/> <b>Partner Name</b> : ' +  objAccount.Name 
    							+ '<br/> <b>FPPM</b> : ' +  objAccount.Channel_Manager__r.Name +'<br/><br/>';
								//+'<br/> <b>SBU</b> : ' +  sbuUser.Name +'<br/><br/>';
    	String strHtmlBody = '';
    	Integer counter = 1;
		Integer entityCounter = 1;
    	Map<Id,Campaign> mapIdToCampaign = new Map<Id,Campaign>([select Id,Name,Owner.Name from Campaign]);
		List<Lead> lstLead = [Select Related_To__c, 
    								Name, Id,
    								Virtual_Partner__c, 
    								Status, 
    								Owner.Name, 
    								LeadSource, 
    								Created_date_Month__c,
    								CreatedDate,
    								Virtual_Partner__r.Name,
    							    (Select CampaignId From CampaignMembers limit 1) campaign 
    							From Lead 
    							where Related_To__c = 'Business Partner' and OwnerId =: objUser.Id order by CreatedDate asc];
		List<Account> lstAcc = [Select Related_To__c, 
    									RecordTypeId, 
    									Name, Id, 
    									Entity_Status__c, 
    									Entity_Stage__c,
    									Virtual_Partner__c, 
    									Created_date_Month__c, 
    									CreatedDate,
    									Owner.Name
    								From Account 
    								where Related_To__c = 'Business Partner' 
    								and RecordTypeId =: RecTypes__c.getInstance('AccountClient').Record_Type_Value__c 
    								and OwnerId =: objUser.Id order by CreatedDate asc];
		
		system.debug('**lstLead*'+lstLead);
		system.debug('**strHtmlBodyLead*'+strHtmlBodyLead);
		if(lstLead != null && lstLead.size() > 0)
    	{
			strHtmlBodyLead += '<table border="1" cellspacing="0" cellpadding="5"><tr bgcolor="#E6E6E7"><th align="center">Sr. No.</th> <th>Lead Creation <br/> Month-Year</th><th> Lead Name </th> <th> Lead Status </th> <th> Campaign Name </th> <th> Campaign Owner </th> </tr>';
							// <th> Lead Source </th> <th> Lead Owner </th> </tr>' ;
			for(Lead objLead : lstLead)
			{
				if(objLead.CampaignMembers.size() > 0)
				{
					if(mapIdToCampaign.containsKey(objLead.CampaignMembers[0].CampaignId)) 
					{
						Campaign objCampaign = mapIdToCampaign.get(objLead.CampaignMembers[0].CampaignId);
						if(objCampaign != null)
						{
							strHtmlBodyLead += '<tr><td align="center">' +  counter 
									+ '</td><td>' +  objLead.Created_date_Month__c
									+ '</td><td>' +  objLead.Name
									+ '</td><td>' +  objLead.Status
									+ '</td><td>' +  objCampaign.Name
									+ '</td><td>' +  objCampaign.Owner.Name + '</td></tr>';
							counter++;
						}
					}
				}
				else
				{
				
					strHtmlBodyLead += '<tr><td align="center">' +  counter 
									+ '</td><td>' +  objLead.Created_date_Month__c
									+ '</td><td>' +  objLead.Name
									+ '</td><td>' +  objLead.Status
									+ '</td><td>' +  '-'
									+ '</td><td>' +  '-' + '</td></tr>';
								// <td>' +  objLead.LeadSource +'</td> <td>' + objLead.Owner.Name +'</td> </tr>';mapContactIdToEntity.get(contactId).Name
					counter++;
				}
					
				
			}
			strHtmlBodyLead += '<table> <br/></body></html>';
    	}
		if(lstAcc != null && lstAcc.size() > 0)							
    	{
    		strHtmlBody = '<br/><table border="1" cellspacing="0" cellpadding="5"><tr bgcolor="#E6E6E7"><th align="center">Sr. No.</th> <th>Client Creation <br/> Month-Year</th> <th> Client Name </th> <th> Client Stage </th></tr>' ;
    		for(Account objAcc : lstAcc)
			{
				strHtmlBody += '<tr> <td align="center">' +  entityCounter + '</td><td>' 
											+ objAcc.Created_date_Month__c + '</td> <td>' 
											+ objAcc.Name + '</td> <td>' 
											+ objAcc.Entity_Stage__c + '</td> </tr>';
				entityCounter++;
			}
			strHtmlBody += '<table> <br/>Thank you </body></html>';
    	}
    	
    	strHtmlBodyLead += strHtmlBody;
    	
		//create an object of SingleEmailMessage 	 
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
       
        //create an array of  email addresses
        String[] toAddresses = new String[] {objUser.Email};
        String[] toCcAddresses = new String[] {objAccount.Channel_Manager__r.Email,sbuUser.Email};
      //  toCcAddresses = new String[] {sbuUser.Email};
        //set array of email addresses 
        mail.setToAddresses(toAddresses); 
        mail.setCcAddresses(toCcAddresses);
        //set Subject name 
        mail.setSubject('Year To Date Report of Leads and Entities'); 
        mail.setUseSignature(false);
        
        //set email body 
        mail.setHtmlBody(strHtmlBodyLead);
        if(!test.isRunningTest())
        if((lstLead.size() > 0 ||  lstAcc.size() > 0 )&& toAddresses != null)
        	Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
		
    }
    /*
		@MethodName: finish 
		@param : Database.BatchableContext BC
		@Description: It is overriden method of  Database.Batchable interface.
	*/
    global void finish(Database.BatchableContext BC)
    {
    	
    }
}