Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Expected_Return_on_Investment__c</fullName>
        <label>Expected Return on Investment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Income_Growth_Rate__c</fullName>
        <label>Income Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Plan_Generation_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Added in FP changes</description>
        <label>Plan Generation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>To select user.</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Ffreedom</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold (Align to goal)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/AssetRecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AssetRecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Entity_Global_Assumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entity Global Assumptions</relationshipLabel>
        <relationshipName>ntity_Global_Assumptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Expected_Return_on_Investment__c</fullName>
        <label>Expected Return on Investment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Income_Growth_Rate__c</fullName>
        <label>Income Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Entity Global Assumption</label>
    <nameField>
        <label>Entity Global Assumption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Global Assumptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Percent</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goal Profiles</relationshipLabel>
        <relationshipName>Goal_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goal Profile</label>
    <nameField>
        <label>Goal Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <label>Allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalAssetAssociation</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>G Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInsuranceAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Insurance</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <referenceTo>Insurance__c</referenceTo>
        <relationshipLabel>Goal</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>allocated__c</fullName>
        <label>allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>GoalInsuranceAssociation</label>
    <nameField>
        <displayFormat>GI-{0000}</displayFormat>
        <label>GoalInsuranceAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInsuranceAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInvestmentAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <description>Mapping with Goal object</description>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>InvestmentAssets</relationshipLabel>
        <relationshipName>GoalMapping</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Investment_Asset__c</fullName>
        <description>Investment asset relation</description>
        <label>Investment Asset</label>
        <referenceTo>Investment_Asset__c</referenceTo>
        <relationshipLabel>GoalInvestmentAssetAssociations</relationshipLabel>
        <relationshipName>InvestmentAssetMapping</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>GoalInvestmentAssetAssociation</label>
    <nameField>
        <displayFormat>GIAA-{0000}</displayFormat>
        <label>GoalInvestmentAssetAssociationId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInvestmentAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalSIPAmount__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>GoalSIPsAmount</relationshipLabel>
        <relationshipName>GoalSIPsAmount</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalSIPAmount</label>
    <nameField>
        <displayFormat>GS-{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalSIPsAmount</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold (Align to goal)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investment Assets</relationshipLabel>
        <relationshipName>Investment_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Gold</fullName>
        <active>true</active>
        <description>Added regarding new FP changes</description>
        <label>Gold and Silver</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InvestmentAsset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>InvestmentAsset</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/GoalControllerTest.cls
/*
  Revision History:
  Version     Version Author     Date        Comments
    1.0         --                --        Initial Draft
    2.0      Manasi Ranade     21/06/2011  Issue id: F0057 :
                          1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                              exception for totalAmount parameter.
                            2. So added querrystring parameter 'totalAmount' below with its value as '1234' 
                               for further calculation in testData() function.  
   2.0      Manasi Ranade     24/08/2011  Issue id: FS0129 :
                          Change in function :GoalControllerTest
                          Commented startTest from start of the function because it was crossing Governer Limits.
                        And added it after goalTestCon.singleYearGoal.
  3.0      Prajakta Sanap     19/04/2013  Created TestData_Ffreedom which contains all the test data for this test class.                      
*/
@isTest
private class GoalControllerTest 
{
  static GoalController goalTestCon;
  static Account acc;
  static GoalOutputController goalOutCon;
  static GoalComponentController goalCompCon;
  static GoalSummaryController goalSummary;
  static NewGoalService objNewGoalService; 
  static GoalMappingBean objGoalBean; 
  static  Goal__c gol;
  
  @isTest(seeAlldata=true) 
  public static void testData()
  {
     
    TestData_Ffreedom testData = new TestData_Ffreedom();
        acc = testData.initializeAccount();
        acc.PAN_ID__pc = 'ABCDF1234M'; 
      upsert acc;
      system.assertNotEquals(null,acc);
         
    Entity_Global_Assumption__c ega = testData.initialize_GlobalAssumptions(acc);
    upsert ega;
      system.assertNotEquals(null,ega.id);
         
      List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
      Database.insert(lstGoalProfile);
        
      List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
      Database.insert(lstAsset);
      List<Goal__c> lstGoal = new List<Goal__c>();  
      Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      insert goalProfile2;  
      gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
      lstGoal.add(gol);
      Goal__c gol1 = testData.initialize_Goal(acc, 'Retirement',goalProfile2);
      lstGoal.add(gol1);
      Goal__c gol2 = testData.initialize_Goal(acc, 'Education',goalProfile2);
      lstGoal.add(gol2); 
       
      insert lstGoal;
      system.assertNotEquals(null,gol.id);
      
      Asset__c asset = testData.initialize_Asset(acc,'EPF',AssetRecTypes__c.getInstance ('Retirement Accounts').RecordTypeId__c,'To be grown till maturity and continue saving');  
      insert asset;
      Asset__c asset1 = testData.initialize_Asset(acc,'PPF',AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,'To be grown till maturity and continue saving');
      insert asset1;
       
      List<GoalAssetAssociation__c> lstGoalAssetAssociation = new List<GoalAssetAssociation__c>();
      
      GoalAssetAssociation__c gasset1 = testData.intialize_GoalAssetAssociation(asset,gol);
      lstGoalAssetAssociation.add(gasset1);
      GoalAssetAssociation__c gasset2 = testData.intialize_GoalAssetAssociation(asset1,gol);
      lstGoalAssetAssociation.add(gasset2);
      Database.insert(lstGoalAssetAssociation);
       
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      GoalInsuranceAssociation__c gasset3 = testData.initialize_GoalIA(insurance,gol1);
      insert gasset3; 
      system.assertNotEquals(null,gasset3.id);
        
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
        
       Investment_Asset__c inv = new Investment_Asset__c(Entity__c=acc.id,action__c='yes',RecordTypeId=InvestmentAsset__c.getInstance('Mutual Fund').RecordTypeId__c,
                                                        Maturity_Date__c = system.today());
       insert inv; 
       GoalInvestmentAssetAssociation__c gInvAss = new GoalInvestmentAssetAssociation__c(Investment_Asset__c=inv.id,Goal__c=gol2.id,allocated__c=45);
       insert gInvAss;  
        
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      objGoalBean = new GoalMappingBean(gol.Id,2013,2060,2020,2013);
      goalTestCon=new GoalController();
        // boolean singleYearGoal=goalTestCon.singleYearGoal;
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
          
      goalOutCon = new GoalOutputController();
      objNewGoalService = new NewGoalService();
      goalCompCon = new GoalComponentController();
      goalTestCon.getCustomRiskProfile();
     // goalSummary=new GoalSummaryController();
     
     
     //(integer Name, double equity,double gold,double debt) 
     GoalMappingBean.ChartDataItem objChart = new GoalMappingBean.ChartDataItem(5,4,3,1);
     objGoalBean.ClearSipBeanList(2035,gol.Id,2013);
     
     GoalMappingBean.GoalDetailBean detailBean1 = new GoalMappingBean.GoalDetailBean();
     objGoalBean.populateGoalDetailBeanList(2012,2020,5000,4000,true,detailBean1);
     
     GoalMappingBean.GoalFinancialDataBean objGoal = new GoalMappingBean.GoalFinancialDataBean(); 
     objGoal.financialYear = 2013;
     objGoal.futureValue = 5000;
     objGoal.futureValueActual = 4000;
     objGoal.goalPV = 2000;
     objGoal.goalPVActual = 2000;
     objGoal.pmt = 200;
     objGoal.pmtActual = 2000;
     objGoal.presentValue = 4000;
     objGoal.presentValueActual = 4000;
     
     //objGoalBean.populatePresentFutureValueAndSIPForLiquidate(2013,2020,objGoal,true);
     //objGoalBean.getIncrementFactor();
  }
  
  @isTest(seeAlldata=true)     
  public static void testData1()
  {
      TestData_Ffreedom testData = new TestData_Ffreedom();
        acc = testData.initializeAccount(); 
      upsert acc;
      system.assertNotEquals(null,acc);
         
      List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
      Database.insert(lstGoalProfile);
             
      List<Asset__c> lstAsset = new List<Asset__c>(); 
        
      Asset__c asset3 = testData.initialize_Asset(acc,null,AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,'Liquidate (Sell)');
      lstAsset.add(asset3);
      Asset__c asset4 = testData.initialize_Asset(acc,'PPF',AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,'Hold');
      lstAsset.add(asset4);
      Asset__c asset5 = testData.initialize_Asset(acc,null,AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,'Sell');
      lstAsset.add(asset5);
      Asset__c asset6 = testData.initialize_Asset(acc,null,AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,'Liquidate (Align to goal)');
      lstAsset.add(asset6);
      Database.insert(lstAsset);
      
      Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      insert goalProfile2;  
      gol = testData.initialize_Goal(acc, 'Retirement',goalProfile2);
      insert gol;
      system.assertNotEquals(null,gol.id);
        
      List<GoalAssetAssociation__c> lstGoalAssetAssociation = new List<GoalAssetAssociation__c>();
        
      GoalAssetAssociation__c gasset2 = testData.intialize_GoalAssetAssociation(asset3,gol);
      lstGoalAssetAssociation.add(gasset2);
      GoalAssetAssociation__c gasset3 = testData.intialize_GoalAssetAssociation(asset4,gol); 
      lstGoalAssetAssociation.add(gasset3);
      GoalAssetAssociation__c gasset4 = testData.intialize_GoalAssetAssociation(asset5,gol);
      lstGoalAssetAssociation.add(gasset4);
      GoalAssetAssociation__c gasset5 = testData.intialize_GoalAssetAssociation(asset6,gol);
      lstGoalAssetAssociation.add(gasset5);
      Database.insert(lstGoalAssetAssociation);
       
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
      goalTestCon=new GoalController(); 
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
  }
   
  @isTest(seeAlldata=true)     
  public static void GoalControllerTest()
  {
      //
      /** Eternus Solutions       **/
    /** Author  : Manasi Ranade **/
    /** Issue Id: FS0129        **/
    /** Date    : 24/08/2011   **/
    /** Purpose : Commented startTest from here because it was crossing Governer Limits.
            And added it after goalTestCon.singleYearGoal.
            
    /****************************************************/
    testData();
      
      boolean singleYearGoal = goalTestCon.singleYearGoal;
      Test.startTest();
      List<SelectOption> savingTypeList = goalTestCon.savingTypeList;
     
      goalTestCon.customized();
      goalTestCon.save();
      goalTestCon.cancel();
      goalTestCon.output();
      goalTestCon.getSipStartYear();
      
      test.stopTest();
  }
  
  @isTest(seeAlldata=true) 
  public static void GoalComponentTest(){
      Test.startTest();
      testData();
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
  @isTest(seeAlldata=true)     
  public static void GoalControllerTestService()
  {
      
      TestData_Ffreedom testData = new TestData_Ffreedom();
        acc = testData.initializeAccount();
        acc.PAN_ID__pc = 'ABDDF1234M'; 
        acc.Plan_Generation_Date__c = System.today();
      insert acc;
      system.assertNotEquals(null,acc);
      
      Test.startTest();
      
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      objNewGoalService = new NewGoalService();
      objNewGoalService.getTotalExpenses(acc.Id);
      Test.stopTest();
     
  }
  
  
    @isTest(seeAlldata=true) 
    public static void GoalComponentTest1()
    {
        TestData_Ffreedom testData = new TestData_Ffreedom();

        Account objGeneralAccount = testData.init_GeneralAccount();
        insert objGeneralAccount;
        Contact objBizContact = testData.init_BizContact(objGeneralAccount);
        insert objBizContact;
        User partnerUser = testData.initBusinessUser(objBizContact);
        insert partnerUser;

        acc = testData.initBusinessAccount(partnerUser);
        acc.Related_To__c = 'Business Partner';
        insert acc;
   
        // update acc;
    
        Entity_Global_Assumption__c ega = testData.initialize_GlobalAssumptions(acc);
        insert ega;
         
        List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
        Database.insert(lstGoalProfile);
        
        List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
        Database.insert(lstAsset);
        
        Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
        insert goalProfile2;  
        gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
        insert gol;
        system.assertNotEquals(null,gol.id);
      
        Asset__c asset = testData.initialize_Asset(acc, 'EPF', AssetRecTypes__c.getInstance ('Retirement Accounts').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
        insert asset;

        Asset__c asset1 = testData.initialize_Asset(acc, 'PPF', AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
        insert asset1;        

      List<GoalAssetAssociation__c> lstGoalAssetAssociation = new List<GoalAssetAssociation__c>();
      GoalAssetAssociation__c gasset1 =  testData.intialize_GoalAssetAssociation(asset,gol);
      lstGoalAssetAssociation.add(gasset1);
      GoalAssetAssociation__c gasset2 =  testData.intialize_GoalAssetAssociation(asset1,gol);
      lstGoalAssetAssociation.add(gasset2);
      Database.insert(lstGoalAssetAssociation);
       
      
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      GoalInsuranceAssociation__c gasset3 = testData.initialize_GoalIA(insurance, gol);
      insert gasset3;
      system.assertNotEquals(null,gasset3.id);
      
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      goalTestCon=new GoalController();
        // boolean singleYearGoal=goalTestCon.singleYearGoal;
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
       
       Test.startTest();   
      //goalOutCon=new GoalOutputController();
      goalCompCon=new GoalComponentController();
      goalTestCon.GoalProfilePicklist();
     // goalSummary=new GoalSummaryController();
      
      
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
    @isTest(seeAlldata=true) 
    public static void GoalComponentTest11()
    {
        TestData_Ffreedom testData = new TestData_Ffreedom();    
        Account objGeneralAccount = testData.init_GeneralAccount();
        insert objGeneralAccount;
        Contact objBizContact = testData.init_BizContact(objGeneralAccount);
        insert objBizContact; 
        User partnerUser = testData.initBusinessUser(objBizContact);
        insert partnerUser;           
        system.debug('--------partnerUser---ss-----'+partnerUser);
        
        acc = testData.initBusinessAccount(partnerUser);
        insert acc;
        acc.Related_To__c = 'Business Partner';            
        update acc;
    
    Entity_Global_Assumption__c ega = testData.initialize_GlobalAssumptions(acc);
      insert ega;
         
      List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
      Database.insert(lstGoalProfile);
         
        
      List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
      Database.insert(lstAsset);
        
        
      Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      insert goalProfile2;  
      gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
      insert gol;
      system.assertNotEquals(null,gol.id);
      
    Asset__c asset = testData.initialize_Asset(acc, 'EPF', AssetRecTypes__c.getInstance ('Retirement Accounts').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
      insert asset;

    Asset__c asset1 = testData.initialize_Asset(acc, 'PPF', AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
      insert asset1;        

        List<GoalAssetAssociation__c> lstGoalAssetAssociation = new List<GoalAssetAssociation__c>();
      GoalAssetAssociation__c gasset1 =  testData.intialize_GoalAssetAssociation(asset,gol);
      lstGoalAssetAssociation.add(gasset1);
      GoalAssetAssociation__c gasset2 =  testData.intialize_GoalAssetAssociation(asset1,gol);
      lstGoalAssetAssociation.add(gasset2);
      Database.insert(lstGoalAssetAssociation);
       
      
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      GoalInsuranceAssociation__c gasset3 = testData.initialize_GoalIA(insurance, gol);
      insert gasset3;
      system.assertNotEquals(null,gasset3.id);
       Test.startTest();  
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      goalTestCon=new GoalController();
        // boolean singleYearGoal=goalTestCon.singleYearGoal;
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
       
       
      //goalOutCon=new GoalOutputController();
      goalCompCon=new GoalComponentController();
      goalSummary=new GoalSummaryController();
      
      
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
  @isTest(seeAlldata=true) 
    public static void GoalComponentTest111111()
    {
        TestData_Ffreedom testData = new TestData_Ffreedom();

        Account objGeneralAccount = testData.init_GeneralAccount();
        insert objGeneralAccount;
        Contact objBizContact = testData.init_BizContact(objGeneralAccount);
        insert objBizContact;
        User partnerUser = testData.initBusinessUser(objBizContact);
        insert partnerUser;

        acc = testData.initBusinessAccount(partnerUser);
        acc.Related_To__c = 'Business Partner';
        insert acc;
   
        // update acc;
    
        Entity_Global_Assumption__c ega = testData.initialize_GlobalAssumptions(acc);
        insert ega;
         
        List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
        Database.insert(lstGoalProfile);
        
        List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
        Database.insert(lstAsset);
        
        Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
        insert goalProfile2;  
        gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
        insert gol;
        system.assertNotEquals(null,gol.id);
      
        Asset__c asset = testData.initialize_Asset(acc, 'EPF', AssetRecTypes__c.getInstance ('Retirement Accounts').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
        insert asset;

        Asset__c asset1 = testData.initialize_Asset(acc, 'PPF', AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
        insert asset1;        

      List<GoalAssetAssociation__c> lstGoalAssetAssociation = new List<GoalAssetAssociation__c>();
      GoalAssetAssociation__c gasset1 =  testData.intialize_GoalAssetAssociation(asset,gol);
      lstGoalAssetAssociation.add(gasset1);
      GoalAssetAssociation__c gasset2 =  testData.intialize_GoalAssetAssociation(asset1,gol);
      lstGoalAssetAssociation.add(gasset2);
      Database.insert(lstGoalAssetAssociation);
       
      
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      GoalInsuranceAssociation__c gasset3 = testData.initialize_GoalIA(insurance, gol);
      insert gasset3;
      system.assertNotEquals(null,gasset3.id);
      
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      goalTestCon=new GoalController();
        // boolean singleYearGoal=goalTestCon.singleYearGoal;
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
       
       Test.startTest();   
      //goalOutCon=new GoalOutputController();
      goalCompCon=new GoalComponentController();
      goalTestCon.GoalProfilePicklist();
     // goalSummary=new GoalSummaryController();
      
      
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
    @isTest(seeAlldata=true) 
    public static void GoalComponentTest11_1()
    {
        TestData_Ffreedom testData = new TestData_Ffreedom();    
        Account objGeneralAccount = testData.init_GeneralAccount();
        insert objGeneralAccount;
        Contact objBizContact = testData.init_BizContact(objGeneralAccount);
        insert objBizContact; 
        User partnerUser = testData.initBusinessUser(objBizContact);
        insert partnerUser;           
        system.debug('--------partnerUser---ss-----'+partnerUser);
        
        acc = testData.initBusinessAccount(partnerUser);
        insert acc;
        acc.Related_To__c = 'Business Partner';            
        update acc;
    
    Entity_Global_Assumption__c ega = testData.initialize_GlobalAssumptions(acc);
      insert ega;
         
      List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
      Database.insert(lstGoalProfile);
         
        
      List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
      Database.insert(lstAsset);
        
        
      Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      insert goalProfile2;  
      gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
      insert gol;
      system.assertNotEquals(null,gol.id);
      
    Asset__c asset = testData.initialize_Asset(acc, 'EPF', AssetRecTypes__c.getInstance ('Retirement Accounts').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
      insert asset;

    Asset__c asset1 = testData.initialize_Asset(acc, 'PPF', AssetRecTypes__c.getInstance ('Govt. Saving Schemes').RecordTypeId__c,
                           'To be grown till maturity and continue saving');
      insert asset1;        

        List<GoalAssetAssociation__c> lstGoalAssetAssociation = new List<GoalAssetAssociation__c>();
      GoalAssetAssociation__c gasset1 =  testData.intialize_GoalAssetAssociation(asset,gol);
      lstGoalAssetAssociation.add(gasset1);
      GoalAssetAssociation__c gasset2 =  testData.intialize_GoalAssetAssociation(asset1,gol);
      lstGoalAssetAssociation.add(gasset2);
      Database.insert(lstGoalAssetAssociation);
       
      
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      GoalInsuranceAssociation__c gasset3 = testData.initialize_GoalIA(insurance, gol);
      insert gasset3;
      system.assertNotEquals(null,gasset3.id);
       Test.startTest();  
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      goalTestCon=new GoalController();
        // boolean singleYearGoal=goalTestCon.singleYearGoal;
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
       
       
      goalOutCon=new GoalOutputController();
      goalCompCon=new GoalComponentController();
      
      
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
  @isTest(seeAlldata=true) 
  public static void GoalComponentTest2()
  {
         
    TestData_Ffreedom testData = new TestData_Ffreedom(); 
    Account objAccount = testData.initVirtualAccount();      
     objAccount.Related_To__c = 'Virtual Partner';            
    insert objAccount;
   
    //update objAccount;
      acc = testData.initVirtualAccount(objAccount);
       acc.Related_To__c = 'Virtual Partner';
    acc.PAN_ID__pc = 'HJKLK1324L';
    insert acc;
   
    //update acc;
      
      Entity_Global_Assumption__c ega=new Entity_Global_Assumption__c(Account__c=acc.id,Expected_Return_on_Investment__c=30,Income_Growth_Rate__c=3,Inflation_Rate__c=6,Number_Of_Months__c=5);
      insert ega;
         
      List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
      Database.insert(lstGoalProfile);
        
      List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
      Database.insert(lstAsset);
       
      Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      insert goalProfile2;  
      gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
      insert gol;
      system.assertNotEquals(null,gol.id);
       
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      goalTestCon=new GoalController();
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
       
       Test.startTest();
     // goalOutCon=new GoalOutputController();
      goalCompCon=new GoalComponentController();
     // goalSummary=new GoalSummaryController();
      
       
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
    @isTest(seeAlldata=true) 
  public static void GoalComponentTest4()
  {
     
    TestData_Ffreedom testData = new TestData_Ffreedom(); 
    Account objAccount = testData.initVirtualAccount();   
    objAccount.Related_To__c = 'Virtual Partner';               
    insert objAccount;
    
    
    acc = testData.initVirtualAccount(objAccount);
    acc.Related_To__c = 'Virtual Partner';
    acc.PAN_ID__pc = 'HJVLK1324B';
    insert acc;
   
      Entity_Global_Assumption__c ega=new Entity_Global_Assumption__c(Account__c=acc.id,Expected_Return_on_Investment__c=30,Income_Growth_Rate__c=3,Inflation_Rate__c=6,Number_Of_Months__c=5);
      insert ega;
         
      List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
      Database.insert(lstGoalProfile);
        
      List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
      Database.insert(lstAsset);
       
      Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      insert goalProfile2;  
      gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
      insert gol;
      system.assertNotEquals(null,gol.id);
       
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      goalTestCon=new GoalController();
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
       
       Test.startTest();   
      goalOutCon=new GoalOutputController();
      goalCompCon=new GoalComponentController();
      //goalSummary=new GoalSummaryController();
      
       
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
  @isTest(seeAlldata=true) 
  public static void GoalComponentTest3()
  {
     
    TestData_Ffreedom testData = new TestData_Ffreedom(); 
    Account objAccount = testData.initVirtualAccount();  
    objAccount.Related_To__c = 'Virtual Partner';                
    insert objAccount;
    
    //update objAccount;
      acc = testData.initVirtualAccount(objAccount);
       acc.Related_To__c = 'Virtual Partner';
      acc.PAN_ID__pc = 'HJKLK1324B';
    insert acc;
   
   // update acc;
      
      Entity_Global_Assumption__c ega=new Entity_Global_Assumption__c(Account__c=acc.id,Expected_Return_on_Investment__c=30,Income_Growth_Rate__c=3,Inflation_Rate__c=6,Number_Of_Months__c=5);
      insert ega;
         
      List<Goal_Profile__c> lstGoalProfile = testData.initialize_lstGoalProfile(acc);
      Database.insert(lstGoalProfile);
        
      List<Asset__c> lstAsset = testData.initialize_lstAsset(acc);
      Database.insert(lstAsset);
       
      Goal_Profile__c goalProfile2 = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      insert goalProfile2;  
      gol = testData.initialize_Goal(acc, 'Marriage',goalProfile2);
      insert gol;
      system.assertNotEquals(null,gol.id);
       
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
      
      GoalSIPAmount__c goalsip = testData.initialize_GoalSIPAmount(gol);
      upsert goalsip;
      system.assertNotEquals(null,goalsip.id);
      Apexpages.currentPage().getParameters().put('entityId',acc.id);
      ApexPages.currentPage().getParameters().put('goalId',gol.id);    
         /** Eternus Solutions       **/
       /** Author  : Manasi Ranade **/
       /** Issue Id: F0057        **/
       /** Date    : 21/06/2011    **/
       /** Purpose : 1. Test class was throwing 'System.NullPointerException: Argument 1 cannot be null ' 
                 exception for totalAmount parameter.
                2. So added querrystring parameter 'totalAmount' below with its value as '1234' for further calculation.
       /****************************************************/       
      ApexPages.currentPage().getParameters().put('totalAmount','1234');
      goalTestCon=new GoalController();
      goalMappingBean.GoalAssetMappingBean currentGoalAsset=goalTestCon.currentGoalAsset;
        //FS0196
      ApexPages.currentPage().getParameters().put('dblEquitySIP','12');
      ApexPages.currentPage().getParameters().put('dblGoldSIP','13');
      ApexPages.currentPage().getParameters().put('dblDebtSIP','14');
      ApexPages.currentPage().getParameters().put('dblTotalSIP','15');
       
       Test.startTest();   
     // goalOutCon=new GoalOutputController();
      goalCompCon=new GoalComponentController();
      goalSummary=new GoalSummaryController();
      
       
      goalCompCon.objGoalMappingBean=goalTestCon.goalMappingBean;
      boolean singleYearGoal=goalCompCon.singleYearGoal;
      double futureValueActual=goalCompCon.futureValueActual;
      goalCompCon.output();
      
      test.stopTest();
  }
  
  @isTest(seeAlldata=true) 
  public static void  goalOutputTest()
  {
      Test.startTest();
      testData();
      GoalMappingBean goalMappingBean =goalOutCon.goalMappingBean;
        
      double futureValueActual=goalOutCon.futureValueActual;
      boolean singleYearGoal = false;
      GoalMappingBean golMappingBean=new GoalMappingBean(gol.id,2011,2018,2018,2013);
      double minValue = 10;
      String chartData = '';
      GoalSIPAmount__c currentSIP=golMappingBean.currentSIP;
      List<SelectOption> goalProfileList=golMappingBean.goalProfileList;
      List<List<DataEntrySummaryBean>> getPresentFutureValueList=golMappingBean.getPresentFutureValueList;
      goalOutCon.output();
      
      test.stopTest();
  }
  
 /* @isTest(seeAlldata=true) 
  public static void GoalControllerTest1()
  {
     Test.startTest();
      testData();
      TestData_Ffreedom testData = new TestData_Ffreedom();    
      acc = testData.initializeAccount();
      acc.PAN_ID__pc = 'TYUII7898B';
       insert acc;
     
      
      Insurance__c  insurance = testData.initialize_Insurance(acc);
      insert insurance;
      system.assertNotEquals(null,insurance.id);
     // GoalInsuranceAssociation__c gins = new GoalInsuranceAssociation__c(Insurance__c=insurance.id,Goal__c=gol.id,Allocated__c=30);
     /// insert gins;
     // Test.startTest();
     // system.assertNotEquals(null,gins.id);
      //goalTestCon.save();
      test.stopTest();
  }
  */
}