Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Members</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referred_by_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referred by Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Referred by Entity)</relationshipLabel>
        <relationshipName>Entity</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>General</description>
        <label>General</label>
    </recordTypes>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Approve_Action_Plan__c.object
<CustomObject>
    <description>Created for new action plan</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approve Action Plans</relationshipLabel>
        <relationshipName>Approve_Action_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Approve Action Plans</relationshipLabel>
        <relationshipName>Approve_Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approve Action Plan</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approve Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/ARPP_Detail__c.object
<CustomObject>
    <description>New object for ARPP  calculation</description>
    <fields>
        <fullName>Action_Amount_Revenue__c</fullName>
        <formula>Action_Plan_Amount__c  +  Action_Plan_Trial_Comm_Amount__c  +  Action_Plan_Upfront_Comm_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expected Amount Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Action_Plan_Upfront_Comm_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Expected Upfront Comm Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approve_Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approve Action Plan</label>
        <referenceTo>Approve_Action_Plan__c</referenceTo>
        <relationshipName>ARPP_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ET_Remark__c</fullName>
        <label>Actual Remark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>ARPP_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker_Actual_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Actual Product</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>RPP Details (Execution Tracker Actual Product)</relationshipLabel>
        <relationshipName>ARPP_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker_Trial_Comm_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Trial Comm Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Tracker</label>
        <referenceTo>Execution_Tracker__c</referenceTo>
        <relationshipName>ARPP_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker_upfront_Comm_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Actual Upfront Comm Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expected Product</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>RPP Details (Product)</relationshipLabel>
        <relationshipName>ARPP_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <label>Expected Remark</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Difference__c</fullName>
        <formula>Action_Amount_Revenue__c - Execution_Tracker_Total_Revenue__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Revenue Difference</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RPP Detail</label>
    <nameField>
        <displayFormat>RPP-{00000}</displayFormat>
        <label>RPP Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RPP Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Agreed_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreed Product</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approve_Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approve Action Plan</label>
        <referenceTo>Approve_Action_Plan__c</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <formula>Approve_Action_Plan__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentExecutionTracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Tracker</label>
        <referenceTo>Execution_Tracker__c</referenceTo>
        <relationshipLabel>Related Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surrender Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payable_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Payable Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Master__c.object
<CustomObject>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exchange-Traded Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FFreedom Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Added Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Manufacturer__c</fullName>
        <label>Product Manufacturer</label>
        <referenceTo>Product_Manufacturer_Master__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Product_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PRD-{000000}</displayFormat>
        <label>Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ARPPDetailController.cls
/*
    Revision History:
    
    Version     Version Author     Date           Comments
    1.0         Gaurav  Kakariya   5/16/2013       To Show ARPP Detail record when action plan or execution tracker record saved. 
    
*/
public class ARPPDetailController 
{
	public String entityId{get;set;}
	public String strEntityName{get;set;}
	public Double orderAmount{get;set;}
	public List<ARPP_Detail__c>	lstARPPDetails{get;set;}
	public List<Order_Detail__c> lstOrderDetails{get;set;}
	public Double actionAmountRevenue{get;set;}
	public Double executionTrackerAmountRevenue{get;set;}
	public Double revenueDiffernece{get;set;}
	
	//public String strRevenueDifference{get;set;}
	//public List<WrapperARPP> lstWrapperARPP{get;set;}
	
	public Boolean isRender{get;set;}
	
	//Constructor
	public ARPPDetailController()
	{
		isRender = true;
		actionAmountRevenue = 0;
		executionTrackerAmountRevenue = 0;
		revenueDiffernece = 0;
		
		if(!ApexPages.currentPage().getParameters().containsKey('entityid') || ApexPages.currentPage().getParameters().get('entityid') == '')
		{
			isRender = false;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid or Insufficient Parameter(s)'));
            return;
		}   
		 
		initialise();
	}
	
	
	//This method initialise and collect the ARPP Detail Record
	private void initialise()
	{
		List<Account> lstEntity = new List<Account>();
		//lstWrapperARPP = new List<WrapperARPP>();
		Set<Id> setEntityId = new Set<Id>();
	 	entityId = ApexPages.currentPage().getParameters().get('entityid');
	 	
	 	lstEntity = [SELECT Id,Name, (Select Id,Name,Order_Number__c,Payable_Amount__c From Order_Details__r Order by CreatedDate Desc limit 1) FROM Account WHERE Id =: entityId OR Parent_Entity__c =: entityId];
	 	//lstOrderDetails = [Select Id,Name,Order_Number__c,Payable_Amount__c From Order_Detail__c Where Account__c =: entityId];
	 	lstOrderDetails =new List<Order_Detail__c>();
	 	//Collect EntityId from list of Entity
	 	for(Account objAccount : lstEntity)
	 	{
	 		if(objAccount.Id == entityId )
	 		{
	 			strEntityName = objAccount.Name;
	 			if (objAccount.Order_Details__r.size() != 0)
	 			    lstOrderDetails.add(objAccount.Order_Details__r[0]);
	 		}	
	 		setEntityId.add(objAccount.Id);
	 	}
	 	
	 	//Call to getARPPDetailRecord Method to collect ARPP Details Record
	 	getARPPDetailsRecord(setEntityId);
		
	}
	
	
	//Collect the ARPP Details Record
	private void getARPPDetailsRecord(Set<Id> setEntityId)
	{
		lstARPPDetails = new List<ARPP_Detail__c>();
		
	  	lstARPPDetails = [Select Product__r.Product_Manufacturer__c, 								
								Product__r.ProductType__c,ET_Remark__c,
								Product__r.Product_Name__c, Product__c, Name, Id, 
								Execution_Tracker_upfront_Comm_Amount__c,Execution_Tracker_Amount__c,
								Revenue_Difference__c, Execution_Tracker_Actual_Product__r.Product_Name__c,
								Execution_Tracker__c, Execution_Tracker_Trial_Comm_Amount__c,
								Execution_Tracker__r.Name, 
								Type__c, Action_Amount_Revenue__c,Execution_Tracker_Actual_Product__c,
								Entity__c, Entity__r.Name,Approve_Action_Plan__c, Action_Plan_Upfront_Comm_Amount__c, 
								Action_Plan_Trial_Comm_Amount__c, Action_Plan_Amount__c, 
								Approve_Action_Plan__r.Name,
								Execution_Tracker_Total_Revenue__c,Remark__c
						  From ARPP_Detail__c Where Entity__c IN: setEntityId order by Type__c];
						  
		for(ARPP_Detail__c objARPP : lstARPPDetails)
		{
			actionAmountRevenue += objARPP.Action_Amount_Revenue__c;
			executionTrackerAmountRevenue +=  objARPP.Execution_Tracker_Total_Revenue__c;
			revenueDiffernece +=  objARPP.Revenue_Difference__c;
			
		}				  
						  
	}
	//Method call from Recalcualte ARPP button
	public PageReference recalculateARPP()
	{
		actionAmountRevenue = 0;
		executionTrackerAmountRevenue = 0;
		revenueDiffernece = 0;
		initialise();
		return null;
	} 

	/*	
	//Wrapper Class
	public class WrapperARPP
	{
		public Double revenueDifference{get;set;}
		public ARPP_Detail__c objARPPDetail{get;set;} 
		
		public WrapperARPP( ARPP_Detail__c objARPPDetail)
		{
			this.objARPPDetail = objARPPDetail;
			revenueDifference = objARPPDetail.Action_Amount_Revenue__c - objARPPDetail.Execution_Tracker_Total_Revenue__c;
		}	
	}//end WrapperARPP Class
	
	*/
	
	/*Test method for ARPP Details*/
	@isTest
	public static void testARPPDetail()
	{
		Schema.DescribeSObjectResult DESCRIBE_RESULT = Account.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_MAP = DESCRIBE_RESULT.getRecordTypeInfosByName();
    	
    	Schema.DescribeSObjectResult DESCRIBE_RESULT_INSURANCE = Insurance__c.SobjectType.getDescribe();
    	Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_MAP_INSURANCE = DESCRIBE_RESULT_INSURANCE.getRecordTypeInfosByName();
    	
    	TestData_Ffreedom testData = new TestData_Ffreedom();
    	
    	//Insert RecordType record
    	List<RecTypes__c> lstRecTypes = new List<RecTypes__c>();
    	RecTypes__c objRecType = new RecTypes__c(Name='General_Business', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	
    	RecTypes__c objRecType1 = new RecTypes__c(Name='AccountFamily', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Family Member').getRecordTypeId());
    	RecTypes__c objRecType2 = new RecTypes__c(Name='AccountClient', 
    											 Record_Type_Value__c=RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
    	
    	lstRecTypes.add(objRecType);										 
    	lstRecTypes.add(objRecType1);
    	lstRecTypes.add(objRecType2);	
    	insert lstRecTypes;
    	
    	InsuranceRecTypes__c objInsuranceRecType = new InsuranceRecTypes__c(Name='Life Insurance', 
    											RecordTypeId__c=RECORD_TYPE_INFO_MAP_INSURANCE.get('Life Insurance').getRecordTypeId());
    							
    	insert 	objInsuranceRecType;
    										 											 										 
    	List<Account> lstAccount = new List<Account>();
    	
    	//Insert smagicbasic SMS Template record 
    	List<smagicbasic__SMS_Template__c> lstTemplate = new List<smagicbasic__SMS_Template__c>();
    	
    	smagicbasic__SMS_Template__c template= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Discontinuation Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	
    	smagicbasic__SMS_Template__c template1= new smagicbasic__SMS_Template__c(smagicbasic__Name__c= 'Renewal Template', 
    																			smagicbasic__ObjectName__c = 'Account');
    	lstTemplate.add(template);
    	lstTemplate.add(template1);
    	
    	insert lstTemplate;
    	
    	ID ProfileID = [ Select Id from Profile where name = 'Financial Planner'].Id;
      	User objUser = new User(email='test-user@fakeemail1.com', profileid = ProfileID, UserName='test-user@fakeemail1.com', 
      	 							alias='tuser11', CommunityNickName='tuser1',TimeZoneSidKey='America/New_York', 
      	 							LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1',LanguageLocaleKey='en_US', FirstName = 'Test_Parent_Fname1',
      	 						    LastName = 'Test_Parent_Lname1' );

        insert objUser;
        
    	//Insert Account record
    	Account objGeneralAccount = new Account(Name='Parner Account Test',
    								RecordTypeId= RECORD_TYPE_INFO_MAP.get('General').getRecordTypeId());
    	
        Account objAccount1 = new Account(LastName='Test Freedom', Adjustment_Factor__c='2', OwnerId = objUser.Id,
	                       PersonTitle='TestData',PersonBirthdate=system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463712345',
	                       Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',PersonMailingStreet='aa',
	                       PersonMailingCity='bbb',Retirement_Year__c=2034,Residential_Status_del__c='own',Retirement_Age__c='58',Estimated_Life_Expectancy__c='67',
	                       Estimated_Life_EndYear__c=2041,Relationship_to_Entity__pc='husband', Related_To__c ='Ffreedom',
	                       RecordTypeId = RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId(),Will__c = true);
	                       
	    lstAccount.add(objAccount1);
	    lstAccount.add(objGeneralAccount);               
		insert lstAccount;
      			
      	//Call without passing Url parameter(s)	
	    ARPPDetailController objARPP = new ARPPDetailController();
	                  											
		ApexPages.currentPage().getParameters().put('entityid',objAccount1.Id);
		
		//Insert ARPP Detail record
		ARPP_Detail__c objARPPDetail = new ARPP_Detail__c(Entity__c = objAccount1.Id );
		//insert objARPPDetail;
		
		ARPPDetailController objARPP1 = new ARPPDetailController();
		objARPP1.recalculateARPP();
		
	}
	
}//end of ARPPDetailController class