Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>To select user.</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Ffreedom</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/AssetRecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AssetRecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalAssetAssociation</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>G Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInsuranceAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Insurance</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <referenceTo>Insurance__c</referenceTo>
        <relationshipLabel>Goal</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalInsuranceAssociation</label>
    <nameField>
        <displayFormat>GI-{0000}</displayFormat>
        <label>GoalInsuranceAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInsuranceAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInvestmentAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <description>Mapping with Goal object</description>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>InvestmentAssets</relationshipLabel>
        <relationshipName>GoalMapping</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Investment_Asset__c</fullName>
        <description>Investment asset relation</description>
        <label>Investment Asset</label>
        <referenceTo>Investment_Asset__c</referenceTo>
        <relationshipLabel>GoalInvestmentAssetAssociations</relationshipLabel>
        <relationshipName>InvestmentAssetMapping</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalInvestmentAssetAssociation</label>
    <nameField>
        <displayFormat>GIAA-{0000}</displayFormat>
        <label>GoalInvestmentAssetAssociationId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInvestmentAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investment Assets</relationshipLabel>
        <relationshipName>Investment_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Stocks</fullName>
        <active>true</active>
        <label>Stocks</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InvestmentAsset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>InvestmentAsset</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/NewAssetAllocationControllerTest.cls
/*
	Revision History:
	Version     Version Author     Date        Comments

	2.0  		Prajakta Sanap     22/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.											
*/

@isTest
private class NewAssetAllocationControllerTest 
{
	static Account acc;
 	static NewAssetAllocationController assetAllCon;
 	static Account objBPAccount;
 	static User partnerUser;
 	static void testData()
 	{
 		
 		TestData_Ffreedom testData = new TestData_Ffreedom();

       	Account objGeneralAccount = testData.init_GeneralAccount();
	    insert objGeneralAccount;
	    Contact objBizContact = testData.init_BizContact(objGeneralAccount);
	    insert objBizContact;
       	partnerUser = testData.initBusinessUser(objBizContact);
       	insert partnerUser;

 		List<Account> lstAcc = new List<Account>();
		acc = testData.initializeAccount();
	    lstAcc.add(acc);
	    objBPAccount = testData.initBusinessAccount(partnerUser);
	    objBPAccount.PAN_ID__pc = 'ABCDF3456M';
	    acc.Related_To__c = 'Business Partner';
	    lstAcc.add(objBPAccount);
	    
	    insert lstAcc;
	    
	    lstAcc[1].Related_To__c = 'Business Partner';
	    update lstAcc[1];
	    
	    Goal__c objGoal=new Goal__c(Entity__c=acc.id,Description__c='Education');
	    upsert objGoal;
	    List<Asset__c> lstAsset = new List<Asset__c>();
	    
	    Asset__c asset1 = testData.initialize_Asset(acc, 'EPF',AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
	    lstAsset.add(asset1);
	    Asset__c asset3 = testData.initialize_Asset(acc, 'EPF', AssetRecTypes__c.getInstance('Cash and Cash Equivalents').RecordTypeId__c, '');
	    lstAsset.add(asset3);
	    Asset__c asset2 = testData.initialize_Asset(acc, 'EPF', AssetRecTypes__c.getInstance('Business Assets').RecordTypeId__c, '');
	   	lstAsset.add(asset2);
	    insert lstAsset;
	    system.assertNotEquals(null,asset1.id);
	    system.assertNotEquals(null,asset2.id);
	    
	    //RecordType objRecType = [Select Name, Id From RecordType  where Name = 'Fixed Income'];
	    List<Investment_Asset__c> lstInvestmentAsset = new List<Investment_Asset__c>();
	    Investment_Asset__c insv = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance('Fixed Income').RecordTypeId__c);
	   	lstInvestmentAsset.add(insv);
	   	Investment_Asset__c insv1 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance('Stocks').RecordTypeId__c);
	   	lstInvestmentAsset.add(insv1);
	   	Investment_Asset__c insv2 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance('Mutual Fund').RecordTypeId__c);
	   	lstInvestmentAsset.add(insv2);
	   	
	   	insert lstInvestmentAsset;
	    system.assertNotEquals(null,insv.id);
	    
	    Insurance__c ins = testData.initialize_Insurance(acc);
	    upsert ins;
	    system.assertNotEquals(null,ins.id);

		Insurance__c ins1 = testData.initialize_Insurance(acc);
	    upsert ins1;

	    List<GoalAssetAssociation__c> lstGoalAssetAssociation = new List<GoalAssetAssociation__c>();
	    GoalAssetAssociation__c gasset = testData.intialize_GoalAssetAssociation(asset1, objGoal);
        lstGoalAssetAssociation.add(gasset);
        GoalAssetAssociation__c gasset1 = testData.intialize_GoalAssetAssociation(asset2, objGoal);
        lstGoalAssetAssociation.add(gasset1); 
        GoalAssetAssociation__c gasset2 = testData.intialize_GoalAssetAssociation(asset3, objGoal);
        lstGoalAssetAssociation.add(gasset2);
        insert lstGoalAssetAssociation;
        
        List<GoalInvestmentAssetAssociation__c> lstGoalInvestmentAssetAssociation = new List<GoalInvestmentAssetAssociation__c>();
        GoalInvestmentAssetAssociation__c ginv = testData.init_GoalInvAsset(insv, objGoal);
        lstGoalInvestmentAssetAssociation.add(ginv);
        insert lstGoalInvestmentAssetAssociation;
        
      	GoalInsuranceAssociation__c gins = testData.initialize_GoalIA(ins, objGoal);
       	insert gins;
      
	    SummaryBean summaryBean = new SummaryBean('Header',20,5);
	    Double summary = summaryBean.monthlySummary;
	    List<Double>Yrlist = summaryBean.totalValueByYear;
	    List<SummaryBean.SummaryDetail> summaryDetailList = summaryBean.summaryDetailList;
	    
	    SummaryBean.SummaryDetail detail = new summaryBean.SummaryDetail('Name',15);
	    summaryBean.populateSummaryDetailList(detail);
	    double dtailSummary = detail.monthlySummary;
	    double percent = detail.summaryPercent;
	    List<double> total = detail.totalValueByYear ; 
 	}
 	
    static testMethod void saveTest() 
    {
    	test.startTest();
       	testData();
      	Apexpages.currentPage().getParameters().put('entityId',acc.id);
     	assetAllCon = new NewAssetAllocationController();
       	assetAllCon.save();
       	AssetAllocationBean assetAllocationBean = new assetAllocationBean();
		MAP<ID,Asset__c> assetMap  = assetAllocationBean.assetMap;
		
    	AssetAllocationBean.AssetDetailBean objAssetDetailBean = new AssetAllocationBean.AssetDetailBean ();
    	AssetAllocationBean.GoalAssetMapping mappingBean = new AssetAllocationBean.GoalAssetMapping();
    	objAssetDetailBean.populateGoalAssetMappingList(mappingBean);
        test.stopTest();
    }
    
    static testMethod void saveTest1() 
    {
    	test.startTest();
    	testData();
      	Apexpages.currentPage().getParameters().put('entityId',objBPAccount.Id);//'001R000000');
      	System.runAs(partnerUser)
      	{
      		assetAllCon = new NewAssetAllocationController();
       		assetAllCon.save();
      	}
       	test.stopTest();
    }
    
    static testMethod void saveTest2() 
    {
    	test.startTest();
    	testData();
      	Apexpages.currentPage().getParameters().put('entityId',acc.Id);
      	assetAllCon = new NewAssetAllocationController();
       	assetAllCon.save();
       	test.stopTest();
    }
    
    static testMethod void saveTest3() 
    {
    	test.startTest();
      	//Apexpages.currentPage().getParameters().put('entityId','001R000000');
      	assetAllCon = new NewAssetAllocationController();
       	assetAllCon.save();
       	test.stopTest();
    }
}