Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_Expectancy__c</fullName>
        <label>Estimated Life Expectancy</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Members</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/HLVDetails__c.object
<CustomObject>
    <description>Its an intermediate object.This object will contain values which are generated in HLV calculation.
So while plan generation we can fetch these values to display on it</description>
    <fields>
        <fullName>Expected_Inflation_Adjusted_Return__c</fullName>
        <label>Expected Inflation Adjusted Return</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Inflation__c</fullName>
        <label>Expected Inflation</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expected_Return_on_Investments__c</fullName>
        <label>Expected Return on Investments</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Living_Years_B_A__c</fullName>
        <label>Living Years (B-A)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Normal_Age_of_Retirement_B__c</fullName>
        <description>Normal Age of Retirement (B) of Selected Entity</description>
        <label>Normal Age of Retirement (B)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Normal_Life_Expectancy_B__c</fullName>
        <label>Normal Life Expectancy (B)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Present_Age_in_case_of_Death_A_Dependent__c</fullName>
        <label>Present Age in case of Death (A)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Present_Age_in_case_of_Death_A__c</fullName>
        <description>Present Age in case of Death (A) of selected Entity</description>
        <label>Present Age in case of Death (A)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <label>Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Selected_Entity_Name__c</fullName>
        <label>Selected Entity Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Working_Life_B_A__c</fullName>
        <label>Working Life (B-A)</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>entity__c</fullName>
        <label>entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>HLVDetails</relationshipLabel>
        <relationshipName>HLVDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HLVDetail</label>
    <nameField>
        <label>HlvDetails Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HLVDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investment Assets</relationshipLabel>
        <relationshipName>Investment_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Gold</fullName>
        <active>true</active>
        <description>Added regarding new FP changes</description>
        <label>Gold and Silver</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stocks</fullName>
        <active>true</active>
        <label>Stocks</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InvestmentAsset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>InvestmentAsset</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Remarks__c.object
<CustomObject>
    <description>Space for ‘Remarks’ where the FP can give additional advice.(Except for Goal)</description>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Remark related entity</description>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Remarks</relationshipLabel>
        <relationshipName>Remarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <description>Space for ‘Remarks’ where the FP can give additional advice(Except for Goal)</description>
        <inlineHelpText>space for ‘Remarks’ where the FP can give additional advice</inlineHelpText>
        <label>Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Remark</label>
    <nameField>
        <label>Remarks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remarks</pluralLabel>
    <recordTypes>
        <fullName>LifeInsurancePlanning</fullName>
        <active>true</active>
        <label>LifeInsurancePlanning</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/LifeInsurancePlanningPageControllerTest.cls
/*
Revision History:

		Version     Version Author     Date        Comments
		1.0         --           	   --	  	   Initial Draft
		2.0  		Prajakta Sanap     25/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.				   				 					   
*/

@isTest
private class LifeInsurancePlanningPageControllerTest 
{
    
	static LifeInsurancePlanningPageController lifeInsurancePlanning;
	static Account acc;
	static Account spouse;
	static List<Account> accountlist = new List<Account>();
	 
	public static void testData()
	{
		TestData_Ffreedom testData = new TestData_Ffreedom();
		acc = testData.initializeAccount();
       
       upsert acc;
       system.assertNotEquals(null,acc);
       
       Loan__c loan = testData.init_Loan(acc);
       upsert loan;
       system.assertNotEquals(null,loan.id);
      
       List<Insurance__c> insuranceList = new List<Insurance__c>();
       Insurance__c ins = testData.initialize_Insurance(acc);
       insuranceList.add(ins);
       Insurance__c ins1 = testData.initialize_Insurance(acc);
       insuranceList.add(ins1);
       insert insuranceList;
       
	   List<Investment_Asset__c> invAssetList = new List<Investment_Asset__c>();
       Investment_Asset__c inss1 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Fixed Income').RecordTypeId__c);
       invAssetList.add(inss1);
       
       Investment_Asset__c inss3 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Gold and Silver').RecordTypeId__c);
       invAssetList.add(inss3);
       
       Investment_Asset__c inss2 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Stocks').RecordTypeId__c);
       invAssetList.add(inss2);
        
       Investment_Asset__c inss4 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Mutual Fund').RecordTypeId__c); 
       invAssetList.add(inss4);
       insert invAssetList;
       
       Expense__c exp = testData.init_Expense(acc, 'Housing');
       upsert exp;
       system.assertNotEquals(null,exp.id);
	    Remarks__c objRemarks = new Remarks__c(Entity__c=acc.id,Remark__c='aaa');
	    insert objRemarks;
       
	}

	
	public static testMethod void lifeInsurancePlanTest()
	{
	    testData();
	    Test.startTest();
	  	TestData_Ffreedom testData = new TestData_Ffreedom();
		
	    spouse = new Account(FirstName='ACD',LastName='GHJ',Estimated_Life_Expectancy__c='67',Dependent__c=acc.Id,
	    					Relationship_to_Entity__pc='wife',PersonBirthdate=system.today(),Parent_Entity__c = acc.Id);
		accountlist.add(spouse);
		
	    Account daughter = new Account(FirstName='Girl',LastName='GHJ',Estimated_Life_Expectancy__c='67',Dependent__c=acc.Id,
	    					Relationship_to_Entity__pc='daughter',PersonBirthdate=system.today(),Parent_Entity__c = acc.Id);				
	    accountlist.add(daughter);
	    insert accountlist;
	    Apexpages.currentPage().getParameters().put('entityId',acc.id);
        lifeInsurancePlanning = new LifeInsurancePlanningPageController();
	    system.assertNotEquals(null,spouse);
   	
   		lifeInsurancePlanning.getEntityPicklist();
	    lifeInsurancePlanning.getAdjustmentFactor();
	   // lifeInsurancePlanning.Calculate();
	    lifeInsurancePlanning.output();
	    lifeInsurancePlanning.analysis();
	    lifeInsurancePlanning.entities = null;
	    
	    test.stopTest();
	}
	
	/*public static testMethod void lifeInsurancePlanTest2()
	{
	   // testData();
	   
	    TestData_Ffreedom testData = new TestData_Ffreedom();
		acc = testData.initializeAccount();
       
        insert acc;
	    spouse = new Account(FirstName='ACD',LastName='GHJ',Estimated_Life_Expectancy__c='67',Dependent__c=acc.Id,
	    					Relationship_to_Entity__pc='wife',PersonBirthdate=system.today(),Parent_Entity__c = acc.Id);
		accountlist.add(spouse);
		
	    Account daughter = new Account(FirstName='Girl',LastName='GHJ',Estimated_Life_Expectancy__c='67',Dependent__c=acc.Id,
	    					Relationship_to_Entity__pc='daughter',PersonBirthdate=system.today(),Parent_Entity__c = acc.Id);				
	    accountlist.add(daughter);
	    insert accountlist;
	    Test.startTest();
	    Apexpages.currentPage().getParameters().put('entityId',acc.id);
        lifeInsurancePlanning = new LifeInsurancePlanningPageController();
	    system.assertNotEquals(null,spouse);
   	
   		lifeInsurancePlanning.getEntityPicklist();
	    lifeInsurancePlanning.getAdjustmentFactor();
	    lifeInsurancePlanning.Calculate();
	    
	    test.stopTest();
	   
	}*/
	public static testMethod void lifeInsurancePlanTest1()
	{
		
	    TestData_Ffreedom testData = new TestData_Ffreedom();
		acc = testData.initializeAccount();
       	upsert acc;
       	system.assertNotEquals(null,acc);
       
       	Loan__c loan = testData.init_Loan(acc);
       	upsert loan;
       	system.assertNotEquals(null,loan.id);
      
       	List<Insurance__c> insuranceList = new List<Insurance__c>();
       	Insurance__c ins = testData.initialize_Insurance(acc);
       	insuranceList.add(ins);
       
       	Insurance__c ins1 = testData.initialize_Insurance(acc);
       	insuranceList.add(ins1);
      	insert insuranceList;
       
	   	List<Investment_Asset__c> invAssetList = new List<Investment_Asset__c>();
       
       	Investment_Asset__c inss1 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Fixed Income').RecordTypeId__c);
       	invAssetList.add(inss1);
       
       /* Prajakta - FP changes - 26-02-2013 */
       	Investment_Asset__c inss3 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Gold and Silver').RecordTypeId__c);
       	invAssetList.add(inss3);
       
       	Investment_Asset__c inss2 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Stocks').RecordTypeId__c);
       	invAssetList.add(inss2);
       
        Investment_Asset__c inss4 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Mutual Fund').RecordTypeId__c);
       invAssetList.add(inss4);
       insert invAssetList;
      
	    Remarks__c objRemarks = new Remarks__c(Entity__c=acc.id,Remark__c='aaa');
	    insert objRemarks;
       
        List<HLVDetails__c> lstHLVDetails = new List<HLVDetails__c>();
       	HLVDetails__c HLVDetails = new HLVDetails__c(Present_Age_in_case_of_Death_A__c=50,Normal_Age_of_Retirement_B__c=60,
        									Working_Life_B_A__c=10,Present_Age_in_case_of_Death_A_Dependent__c=65,
        									Normal_Life_Expectancy_B__c=85,Living_Years_B_A__c=15,
        									Expected_Return_on_Investments__c=8,Expected_Inflation__c=9,
        									Expected_Inflation_Adjusted_Return__c=10,
        									Selected_Entity_Name__c=acc.Id,entity__c=acc.id);
        lstHLVDetails.add(HLVDetails);
        insert lstHLVDetails;	
       	  
	  	Test.startTest();
	    Apexpages.currentPage().getParameters().put('entityId',acc.id);
        lifeInsurancePlanning = new LifeInsurancePlanningPageController();
   	
   		lifeInsurancePlanning.getEntityPicklist();
	    lifeInsurancePlanning.getAdjustmentFactor();
	    //lifeInsurancePlanning.Calculate();
	    //lifeInsurancePlanning.getHLVEntityDetails(acc.Id);
	    lifeInsurancePlanning.save();
	    lifeInsurancePlanning.output();
	    lifeInsurancePlanning.analysis();
	   
	    lifeInsurancePlanning.entities = null;
	    //lifeInsurancePlanning.calculateSummaryBeanValues();
	    test.stopTest();
		
	}
	
}