Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Agreement_Received__c</fullName>
        <label>Agreement Received</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Option_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Question_Option_List__c</referenceTo>
        <relationshipLabel>Option Details</relationshipLabel>
        <relationshipName>Option_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>XRayScoreCard__c</fullName>
        <label>X-Ray Score Card</label>
        <referenceTo>XRay_ScoreCard__c</referenceTo>
        <relationshipLabel>Option Details</relationshipLabel>
        <relationshipName>Option_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option Detail</label>
    <nameField>
        <displayFormat>Option Details -{0000}</displayFormat>
        <label>Option Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Option Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank__c.object
<CustomObject>
    <description>This will be the question bank and act as a master object to Questionnaire.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine whether the given Question Bank is to be used as a part of the Questionnaire.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{00}</displayFormat>
        <label>Question Bank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank_List__c.object
<CustomObject>
    <description>This will store all the questions  and will act as a master table to Questionnaire. Dummy questions will not have any answer (No Points).</description>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsDummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dummy?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Parent</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Bank Lists (Master Parent)</relationshipLabel>
        <relationshipName>MasterParent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Bank Lists (Parent Question)</relationshipLabel>
        <relationshipName>Question_Bank_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multichoice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Option_List__c.object
<CustomObject>
    <description>This will store the options for each question in the pool,  the score to be given and the feedback to be displayed.</description>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Option Lists</relationshipLabel>
        <relationshipName>Question_Option_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question Option List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Option Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Questionnaire__c.object
<CustomObject>
    <description>This will give the ability to configure the questions for a particular questionnaire.</description>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <label>Display Sequence</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/X_Ray_Score_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>X-Ray Score Card Details</relationshipLabel>
        <relationshipName>X_Ray_Score_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>X-Ray Score Card Details</relationshipLabel>
        <relationshipName>X_Ray_Score_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipLabel>X-Ray Score Card Details</relationshipLabel>
        <relationshipName>X_Ray_Score_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>X-Ray Score Card Detail</label>
    <nameField>
        <label>X-Ray Score Card Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>X-Ray Score Card Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/XRay_ScoreCard__c.object
<CustomObject>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <description>This will store the sequence of question.</description>
        <label>Display Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>X-Ray Score Cards</relationshipLabel>
        <relationshipName>X_Ray_Score_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score_Master__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XRayScoreCardMaster__c</fullName>
        <label>X-Ray Score Card Detail</label>
        <referenceTo>X_Ray_Score_Card_Detail__c</referenceTo>
        <relationshipLabel>X-Ray Score Cards</relationshipLabel>
        <relationshipName>X_Ray_Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>X-Ray Score Card</label>
    <nameField>
        <label>X-Ray Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>X-Ray Score Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestExistingXRay.cls
@isTest
private class TestExistingXRay 
{
	static testMethod void ExistingXRayTest()
	{
		
        List<Questionnaire__c> lstQuestionnaire = new List<Questionnaire__c>();
		List<Question_Bank_List__c> lstQuesBankList = new List<Question_Bank_List__c>();
		List<Question_Option_List__c> lstQuesOptionList = new List<Question_Option_List__c>();
		List<Option_Detail__c> lstOptionsScorecards = new List<Option_Detail__c>();
		List<XRay_ScoreCard__c> lstScoreCardTest = new List<XRay_ScoreCard__c>();
		List<X_Ray_Score_Card_Detail__c> lstScoreCardDetailTest = new List<X_Ray_Score_Card_Detail__c>();
		Set<ID>setOfQuestionIds = new Set<ID>();
		/* Lead  */
    	
       	Question_Bank__c objQuestionBank = new Question_Bank__c ();
    	objQuestionBank.IsActive__c = true;  
    	insert objQuestionBank;
    	
    	/* Question_Bank_List__c  */
    	Question_Bank_List__c quesMasters1 = new Question_Bank_List__c();
    	quesMasters1.Question__c = 'Have you prepared a budget for household expenses?'; 
    	quesMasters1.Criteria__c = 'Yes';
    	quesMasters1.IsDummy__c = false;
    	quesMasters1.Question_Type__c = 'Yes/No';
    	insert quesMasters1;
    	lstQuesBankList.add(quesMasters1);
    	setOfQuestionIds.add(quesMasters1.Id);
    	
    	Question_Bank_List__c quesMasters2 = new Question_Bank_List__c();
    	quesMasters2.Question__c = 'If YES, do you follow your budgeting?'; 
    	quesMasters2.IsDummy__c = false;
    	quesMasters2.Question_Type__c = 'Yes/No';
    	quesMasters2.Master_Parent__c = quesMasters1.Id; 
    	quesMasters2.Parent_Question__c = quesMasters1.Id;
    	insert quesMasters2;
    	lstQuesBankList.add(quesMasters2);
    	setOfQuestionIds.add(quesMasters2.Id);
    	
    	Question_Bank_List__c quesMasters3 = new Question_Bank_List__c();
    	quesMasters3.Question__c = 'If YES, do you follow your budgeting?'; 
    	quesMasters3.IsDummy__c = false;
    	quesMasters3.Question_Type__c = 'Yes/No';
    	//quesMasters3.Master_Parent__c = quesMasters1.Id; 
    	//quesMasters3.Parent_Question__c = quesMasters1.Id;
    	insert quesMasters3;
    	lstQuesBankList.add(quesMasters3);
    	setOfQuestionIds.add(quesMasters3.Id);
    	
    	Question_Bank_List__c quesMasters4 = new Question_Bank_List__c();
    	quesMasters4.Question__c = 'If YES, do you follow your budgeting?'; 
    	quesMasters4.IsDummy__c = true;
    	quesMasters4.Question_Type__c = 'Multichoice';
    	//quesMasters3.Master_Parent__c = quesMasters1.Id; 
    	//quesMasters3.Parent_Question__c = quesMasters1.Id;
    	insert quesMasters4;
    	lstQuesBankList.add(quesMasters4);
    	setOfQuestionIds.add(quesMasters4.Id);
    	
    	Questionnaire__c objQuestionnaire1 = new Questionnaire__c();
    	objQuestionnaire1.Question_Bank__c = objQuestionBank.Id;
    	objQuestionnaire1.Question_Bank_List__c = quesMasters1.Id;
    	objQuestionnaire1.Display_Sequence__c = '1';
    	lstQuestionnaire.add(objQuestionnaire1); 
    	 
    	Questionnaire__c objQuestionnaire2 = new Questionnaire__c();
    	objQuestionnaire2.Question_Bank__c = objQuestionBank.Id;
    	objQuestionnaire2.Question_Bank_List__c = quesMasters3.Id;
    	objQuestionnaire2.Display_Sequence__c = '2';
    	lstQuestionnaire.add(objQuestionnaire2);
    	
    	Questionnaire__c objQuestionnaire3 = new Questionnaire__c();
    	objQuestionnaire3.Question_Bank__c = objQuestionBank.Id;
    	objQuestionnaire3.Question_Bank_List__c = quesMasters1.Id;
    	objQuestionnaire3.Display_Sequence__c = '3';
    	lstQuestionnaire.add(objQuestionnaire3); 
    	 
    	Questionnaire__c objQuestionnaire4 = new Questionnaire__c();
    	objQuestionnaire4.Question_Bank__c = objQuestionBank.Id;
    	objQuestionnaire4.Question_Bank_List__c = quesMasters4.Id;
    	objQuestionnaire4.Display_Sequence__c = '4';
    	lstQuestionnaire.add(objQuestionnaire4);
    	
    	if(!lstQuestionnaire.isEmpty())
    		insert lstQuestionnaire;
    	/* Question_Option_List__c */
    	Question_Option_List__c objQuesOptionList1 =  new Question_Option_List__c();
    	objQuesOptionList1.Name = 'Yes';
    	objQuesOptionList1.Score__c = 5;
    	objQuesOptionList1.Question_Bank_List__c = quesMasters1.Id;
    	insert objQuesOptionList1;
    	lstQuesOptionList.add(objQuesOptionList1); 
    	
    	Question_Option_List__c objQuesOptionList2 =  new Question_Option_List__c();
    	objQuesOptionList2.Score__c = 0;
    	objQuesOptionList2.Name = 'No';
    	objQuesOptionList2.Question_Bank_List__c = quesMasters1.Id;
    	insert objQuesOptionList2; 
    	lstQuesOptionList.add(objQuesOptionList2);
    	
    	Question_Option_List__c objQuesOptionList3 =  new Question_Option_List__c();
    	objQuesOptionList3.Name = 'Yes';
    	objQuesOptionList3.Score__c = 5;
    	objQuesOptionList3.Question_Bank_List__c = quesMasters2.Id;
    	insert objQuesOptionList3;
    	lstQuesOptionList.add(objQuesOptionList3);
	
    	Question_Option_List__c objQuesOptionList4 =  new Question_Option_List__c();
    	objQuesOptionList4.Name = 'No';
    	objQuesOptionList4.Score__c = 0;
    	objQuesOptionList4.Question_Bank_List__c = quesMasters2.Id;
    	insert objQuesOptionList4;
    	lstQuesOptionList.add(objQuesOptionList4);
    	
    	Question_Option_List__c objQuesOptionList5 =  new Question_Option_List__c();
    	objQuesOptionList5.Name = 'Yes';
    	objQuesOptionList5.Score__c = 5;
    	objQuesOptionList5.Question_Bank_List__c = quesMasters3.Id;
    	insert objQuesOptionList5;
    	lstQuesOptionList.add(objQuesOptionList5);
	
    	Question_Option_List__c objQuesOptionList6 =  new Question_Option_List__c();
    	objQuesOptionList6.Name = 'No';
    	objQuesOptionList6.Score__c = 0;
    	objQuesOptionList6.Question_Bank_List__c = quesMasters3.Id;
    	insert objQuesOptionList6;
    	lstQuesOptionList.add(objQuesOptionList6);
    	
    	Question_Option_List__c objQuesOptionList7 =  new Question_Option_List__c();
    	objQuesOptionList7.Name = 'Yes';
    	objQuesOptionList7.Score__c = 5;
    	objQuesOptionList7.Question_Bank_List__c = quesMasters4.Id;
    	insert objQuesOptionList7;
    	lstQuesOptionList.add(objQuesOptionList7);
	
    	Question_Option_List__c objQuesOptionList8 =  new Question_Option_List__c();
    	objQuesOptionList8.Name = 'No';
    	objQuesOptionList8.Score__c = 0;
    	objQuesOptionList8.Question_Bank_List__c = quesMasters4.Id;
    	insert objQuesOptionList8;
    	lstQuesOptionList.add(objQuesOptionList8);
    	
    	
    	/* X_Ray_Score_Card_Detail__c */
    	/* XRay_ScoreCard__c 
    	XRay_ScoreCard__c objXrayScore1 = new XRay_ScoreCard__c ();
    	objXrayScore1.Display_Sequence__c = 1;
    	objXrayScore1.Question_Bank_List__c = quesMasters1.Id;
    	objXrayScore1.XRayScoreCardMaster__c = ObjXrayScoreCardDetail.Id;
    	objXrayScore1.Score_Master__c = 5;   
    	insert objXrayScore1;
    	lstScoreCardTest.add(objXrayScore1);
    	
    	XRay_ScoreCard__c objXrayScore2 = new XRay_ScoreCard__c ();
    	objXrayScore2.Display_Sequence__c = 2;
    	objXrayScore2.Question_Bank_List__c = quesMasters2.Id;
    	objXrayScore2.XRayScoreCardMaster__c = ObjXrayScoreCardDetail.Id;
    	objXrayScore2.Score_Master__c = 5;   
    	insert objXrayScore2;
    	lstScoreCardTest.add(objXrayScore2);
    	
    	Option_Detail__c objOptions1 = new Option_Detail__c();
    	objOptions1.Answer__c = objQuesOptionList1.Id ;
    	objOptions1.XRayScoreCard__c=  objXrayScore1.Id;
    	lstOptionsScorecards.add(objOptions1);
    	
    	
    	Option_Detail__c objOptions2 = new Option_Detail__c();
    	objOptions2.Answer__c = objQuesOptionList3.Id;
    	objOptions2.XRayScoreCard__c=  objXrayScore2.Id;
    	lstOptionsScorecards.add(objOptions2);
    	
    	if(!lstOptionsScorecards.isEmpty())
    		insert lstOptionsScorecards;*/
    	
    	
    	Test.startTest();
    	Lead objLead = new Lead();
    	objLead.LastName = 'TestLastName';
    	objLead.LeadSource = 'Web';
    	objLead.MobilePhone = '9090909090';
    	insert objLead;
    	
    	X_Ray_Score_Card_Detail__c ObjXrayScoreCardDetail = new X_Ray_Score_Card_Detail__c();
    	ObjXrayScoreCardDetail.Question_Bank__c= objQuestionBank.Id;
    	ObjXrayScoreCardDetail.Lead__c = objLead.Id;
    	insert ObjXrayScoreCardDetail;
    	lstScoreCardDetailTest.add(ObjXrayScoreCardDetail);
    	
    	ExistingLeadXRay objExistingXRay = new ExistingLeadXRay(); 
    	objExistingXRay.leadId = objLead.Id;
    	 
    	objExistingXRay.Init();
    	objExistingXRay.objLead = objLead;
    	objExistingXRay.getQuestionAnswers(setOfQuestionIds);
    	objExistingXRay.Save();
    	objExistingXRay.parentId =quesMasters1.Id; 
    	objExistingXRay.resetAllChild();
    	
    	Account objAccount = new Account();
    	objAccount.LastName = 'testAccount';
    	objAccount.Entity_Status__c='Active';
    	objAccount.Agreement_Received__c ='Yes';
    	objAccount.Description = 'testDesc';
    	insert objAccount;
    	
    	X_Ray_Score_Card_Detail__c ObjXrayScoreCardDetail1 = new X_Ray_Score_Card_Detail__c();
    	ObjXrayScoreCardDetail1.Question_Bank__c= objQuestionBank.Id;
    	ObjXrayScoreCardDetail1.Entity__c = objAccount.Id;
    	insert ObjXrayScoreCardDetail1;
    	
    	
    	XRay_ScoreCard__c objXrayScore1 = new XRay_ScoreCard__c ();
    	objXrayScore1.Display_Sequence__c = 1;
    	objXrayScore1.Question_Bank_List__c = quesMasters1.Id;
    	objXrayScore1.XRayScoreCardMaster__c = ObjXrayScoreCardDetail1.Id;
    	objXrayScore1.Score_Master__c = 5;   
    	insert objXrayScore1;
    	setOfQuestionIds.add(objXrayScore1.Id);
    	lstScoreCardTest.add(objXrayScore1);
    	
    	setOfQuestionIds = new Set<ID>();
    	XRay_ScoreCard__c objXrayScore2 = new XRay_ScoreCard__c ();
    	objXrayScore2.Display_Sequence__c = 2;
    	objXrayScore2.Question_Bank_List__c = quesMasters2.Id;
    	objXrayScore2.XRayScoreCardMaster__c = ObjXrayScoreCardDetail1.Id;
    	objXrayScore2.Score_Master__c = 5;   
    	insert objXrayScore2;
    	setOfQuestionIds.add(objXrayScore2.Id);
    	lstScoreCardTest.add(objXrayScore2);
    	
    	Option_Detail__c objOptions1 = new Option_Detail__c();
    	objOptions1.Answer__c = objQuesOptionList1.Id ;
    	objOptions1.XRayScoreCard__c=  objXrayScore1.Id;
    	lstOptionsScorecards.add(objOptions1);
    	
    	
    	Option_Detail__c objOptions2 = new Option_Detail__c();
    	objOptions2.Answer__c = objQuesOptionList3.Id;
    	objOptions2.XRayScoreCard__c=  objXrayScore2.Id;
    	lstOptionsScorecards.add(objOptions2);
    	
    	if(!lstOptionsScorecards.isEmpty())
    		insert lstOptionsScorecards;
    	
    	objExistingXRay = new ExistingLeadXRay();
    	objExistingXRay.entityId = objAccount.Id;
    	objExistingXRay.Init();
    	objExistingXRay.lstScoreCards = lstScoreCardTest;
    	objExistingXRay.setOfScoreCardIds = setOfQuestionIds;
    	//objExistingXRay.getQuestionAnswers(setOfQuestionIds);
    	//objExistingXRay.Save();
    	objExistingXRay.parentId =quesMasters1.Id;
    	objExistingXRay.resetAllChild(); 
    	Test.stopTest();
    	
    	
    	
    	/*Lead objLead1 = new Lead();
    	objLead1.LastName = 'TestLastName';
    	objLead1.LeadSource = 'Web';
    	objLead1.MobilePhone = '9090909090';
    	insert objLead1;
    	
    	objExistingXRay.objLead = objLead1;
    	objExistingXRay.Init();
    	objExistingXRay.parentId =quesMasters1.Id; 
    	objExistingXRay.resetAllChild();
    	objExistingXRay.getQuestionAnswers(setOfQuestionIds);
    	
    	objExistingXRay.leadId = objLead.Id;
    	objExistingXRay.Init(); */
    	
    }
}