Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Factor__c</fullName>
        <label>Adjustment Factor %</label>
        <picklist>
            <picklistValues>
                <fullName>-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Alternate_E_Mail_Address__c</fullName>
        <label>Alternate E-Mail Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alternate_Mobile__c</fullName>
        <label>Alternate Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Default_Estimated_Life_Expectancy__c</fullName>
        <label>Default Estimated Life Expectancy</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Retirement_Age__c</fullName>
        <label>Default Retirement Age</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_EndYear__c</fullName>
        <label>Estimated Life EndYear</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_Expectancy__c</fullName>
        <label>Estimated Life Expectancy</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Return_on_Investment__c</fullName>
        <label>Expected Return on Investment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gold_Growth_Rate__c</fullName>
        <defaultValue>10</defaultValue>
        <description>Added to decide growth rate of new record type GOLD in Investment Asset.</description>
        <label>Gold Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Income_Growth_Rate__c</fullName>
        <label>Income Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Number_Of_Months__c</fullName>
        <label>Number Of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_To__c</fullName>
        <description>To select user.</description>
        <label>Related To</label>
        <picklist>
            <picklistValues>
                <fullName>Ffreedom</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Residential_Status_del__c</fullName>
        <label>Residential Status</label>
        <picklist>
            <picklistValues>
                <fullName>Permanent Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident but not Ordinary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Resident</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retirement_Age__c</fullName>
        <label>Retirement Age</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retirement_Year__c</fullName>
        <label>Retirement Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Growth_Rate__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Stock Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Virtual_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is created to select the related virtual partner of that entity.

Practice Owner (Partner): Account Record Type</description>
        <label>Practice Owner (Partner)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Virtual Partner)</relationshipLabel>
        <relationshipName>VirtualPartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Entity_Global_Assumption__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Entity Global Assumptions</relationshipLabel>
        <relationshipName>ntity_Global_Assumptions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Data_Collection_Analysis_Control__c</fullName>
        <label>Data Collection Analysis Control</label>
        <picklist>
            <picklistValues>
                <fullName>Portfolio Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Networth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Flow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asset Allocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Succession Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Assumptions</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Default_Estimated_Life_Expectancy__c</fullName>
        <label>Default Estimated Life Expectancy</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Retirement_Age__c</fullName>
        <description>This field is created by the Eternus . If the field Retirement Age form the account is null then fetch this field.</description>
        <label>Default Retirement Age</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Return_on_Investment__c</fullName>
        <label>Expected Return on Investment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Financial_Planing_Output_Report__c</fullName>
        <label>Financial Planing Output Report</label>
        <picklist>
            <picklistValues>
                <fullName>Introduction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disclosure Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Goal Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Goal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estate Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summary Action Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annexure 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Risk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery Acknowledgement</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Goals_Allowed_List__c</fullName>
        <label>Goals Allowed List</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marriage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parental Responsibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money to Heirs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Gold_Growth_Rate__c</fullName>
        <defaultValue>8</defaultValue>
        <description>Added to decide growth rate of new record type GOLD in Investment Asset.</description>
        <label>Gold Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Income_Growth_Rate__c</fullName>
        <label>Income Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>No_of_Goals__c</fullName>
        <label>No of Goals</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_Months__c</fullName>
        <label>Number Of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Growth_Rate__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Stock Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Entity Global Assumption</label>
    <nameField>
        <label>Entity Global Assumption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Global Assumptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goal Profiles</relationshipLabel>
        <relationshipName>Goal_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Goal Profile</label>
    <nameField>
        <label>Goal Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/GlobalAssumptionControllerTest.cls
@isTest
private class GlobalAssumptionControllerTest {
	static GlobalAssumptionController GlobalAssumptionPlan;
	static Account acc;
	static List<User> standardUser;
	public static final Schema.DescribeSObjectResult DESCRIBE_RESULT = Account.SobjectType.getDescribe();
	public static final Map<String, Schema.RecordTypeInfo> RECORD_TYPE_INFO_MAP = DESCRIBE_RESULT.getRecordTypeInfosByName();
	
	public static void testData()
	{
		Account partnerAcc,partnerAcc1;
	    Contact con;
	    Entity_Global_Assumption__c ega;
		
	   standardUser = [select Id from user where usertype = 'Standard' and Profile.Name like '%System Admin%' limit 1];
       System.runAs(standardUser[0])
       {
       		acc = new Account(LastName='ABC',FirstName='PQR',RecordTypeId = RECORD_TYPE_INFO_MAP.get('Client').getRecordTypeId());
	      	upsert acc;
	      	
	       	partnerAcc = new Account(Name='Parner Account Test',RecordTypeId = RecTypes__c.getInstance('General_Business').Record_Type_Value__c);
	       	insert partnerAcc;
	       	
	       	con = new Contact(FirstName='Parner Contact Test', LastName='Contact',AccountId= partnerAcc.id);
	       	insert con;
	       	
	       	//need to comment below
    		//=========================================For Virtual Partner================================================================================================
	       	/*partnerAcc1=new Account(Name='Parner Account Test',RecordTypeId=RecTypes__c.getInstance('General_Business').Record_Type_Value__c);
         	insert partnerAcc1;
	       	
			Id clientRecId=RecTypes__c.getInstance('AccountClient').Record_Type_Value__c;
  			Account act = new Account(FirstName='ABC',LastName='XYZ',RecordTypeId=clientRecId ,Related_To__c = 'Virtual Partner');
        	insert act;
        	*/
        	//==============================================================================================================================================================
	       	ega=new Entity_Global_Assumption__c(Account__c=partnerAcc.id,Expected_Return_on_Investment__c=30,Income_Growth_Rate__c=3,Inflation_Rate__c=6,Number_Of_Months__c=5);
       		upsert ega;  
       }
   }
   
  static testMethod void virtualEntityTest() 
    {
    	Test.startTest();
    	standardUser = [select Id from user where usertype = 'Standard' and Profile.Name like '%System Admin%' limit 1];
    	Account partnerAcc1 = new Account(Name='Partner Account Test',RecordTypeId=RecTypes__c.getInstance('General_Business').Record_Type_Value__c, Related_To__c = 'Virtual Partner');
        insert partnerAcc1;
	       	
    	List<Account> lstAccount = new List<Account>();
    	Account objAccount = new Account(LastName = 'ABC', FirstName='PQR', Adjustment_Factor__c='2',
	                       				  PersonTitle = 'TestData', PersonBirthdate = system.today(), PersonHomePhone = '54623676', PersonMobilePhone = '5463712345',
	                       				  Alternate_Mobile__c = '356475', PersonEmail = 'sgdh@test.com', Alternate_E_Mail_Address__c =' test@test.com',
				                          Retirement_Year__c = 2034, Residential_Status_del__c = 'own', Retirement_Age__c = '58', Estimated_Life_Expectancy__c = '67',
				                          Estimated_Life_EndYear__c = 2041, Relationship_to_Entity__pc = 'husband', Related_To__c = 'Virtual Partner',
				                          RecordTypeId = RecTypes__c.getInstance('AccountClient').Record_Type_Value__c);
	    lstAccount.add(objAccount);
	    
	    Account objFamily = new Account(LastName = 'ABC', FirstName='PQR',Dependent__c=objAccount.Id,
	    								RecordTypeId = RecTypes__c.getInstance('AccountFamily').Record_Type_Value__c);
	    lstAccount.add(objFamily);
	    insert lstAccount;
	    
	    Entity_Global_Assumption__c objGlobal1 = new Entity_Global_Assumption__c 
	    										(Expected_Return_on_Investment__c = 8,
	    										Income_Growth_Rate__c = 14,
	                                  			Inflation_Rate__c = 10, 
	                                  			Account__c = objAccount.Id,
	                                  			Number_Of_Months__c = 50,
	                                  			Stock_Growth_Rate__c = 14,
	                                  			Gold_Growth_Rate__c = 10,	   /* Prajakta - FP changes - 01-04-2013 */
	                                  			Default_Estimated_Life_Expectancy__c = '80',
	                                  			Default_Retirement_Age__c = '60',
	                                  			No_of_Goals__c = 2,
												Data_Collection_Analysis_Control__c = 'Introduction1; Test1',
										 		Financial_Planing_Output_Report__c = 'Personal Information1;Test2',
												Goals_Allowed_List__c = 'Retirement1;Test3');
	    insert objGlobal1;
	    objAccount.Related_To__c = 'Virtual Partner';
	    objAccount.Virtual_Partner__c = partnerAcc1.Id;
	    update objAccount;
	    
	 
	    Entity_Global_Assumption__c objGlobal = new Entity_Global_Assumption__c 
	    										(Expected_Return_on_Investment__c = 8,
	    										Income_Growth_Rate__c=14,
	                                  			Inflation_Rate__c=10,
	                                  			Account__c=partnerAcc1.Id,
	                                  			Number_Of_Months__c=50,
	                                  			Stock_Growth_Rate__c=14,
	                                  			Gold_Growth_Rate__c=10,	   /* Prajakta - FP changes - 01-04-2013 */
	                                  			Default_Estimated_Life_Expectancy__c='80',
	                                  			Default_Retirement_Age__c='60',
	                                  			No_of_Goals__c = 2,
												Data_Collection_Analysis_Control__c = 'Introduction1; Test1',
										 		Financial_Planing_Output_Report__c= 'Personal Information1;Test2',
												Goals_Allowed_List__c ='Retirement1;Test3');
	                                  		    
	    insert objGlobal;                              			
	    
	    Apexpages.currentPage().getParameters().put('entityId',objAccount.id);
	    GlobalAssumptionController GlobalAssumptionPlan1 = new GlobalAssumptionController();
	    
	    Goal_Profile__c goalProfile2;
	    System.runAs(standardUser[0])
	    {
	    	goalProfile2=new Goal_Profile__c(account__c=objAccount.id,Goal_Profile_Type__c='Customize',Debt_Allocation__c=23,Equity_Allocation__c=32,Gold_allocation__c=33);
	        insert goalProfile2;
	    }
	    
	   GlobalAssumptionPlan1.display();
	   GlobalAssumptionPlan1.save();
	   GlobalAssumptionPlan1.cancel();
	   test.stopTest();
	}
   
    public static testMethod void GlobalAssumptionTest1()
    {
	    Test.startTest();
	    testData();
	    Apexpages.currentPage().getParameters().put('entityId',acc.id);
	    GlobalAssumptionPlan=new GlobalAssumptionController();
	    Goal_Profile__c goalProfile2;
	    System.runAs(standardUser[0])
	    {
	    	goalProfile2=new Goal_Profile__c(account__c=acc.id,Goal_Profile_Type__c='Customize',Debt_Allocation__c=23,Equity_Allocation__c=32,Gold_allocation__c=33);
	        insert goalProfile2;
	    }
	    system.assertNotEquals(null,goalProfile2.id);

	    GlobalAssumptionPlan.display();
	    GlobalAssumptionPlan.save();
		GlobalAssumptionPlan.cancel();   
	    test.stopTest();
	}
	
	static testMethod void myUnitTestBPAttachment() 
	{
		TestData_Ffreedom testData = new TestData_Ffreedom();
       	List<Account> lstAcc = new List<Account>(); 
	    Account objGeneralAccount = testData.init_GeneralAccount();
	    insert objGeneralAccount;
	    Contact objBizContact = testData.init_BizContact(objGeneralAccount);
	    insert objBizContact; 
	    User partnerUser = testData.initBusinessUser(objBizContact);
	    insert partnerUser;           
        system.debug('--------partnerUser---ss-----'+partnerUser);
      	
        Account partnerAcc = testData.initBusinessAccount(partnerUser);
        insert partnerAcc;
        partnerAcc.Related_To__c = 'Business Partner';	           
        update partnerAcc; 
        
       	test.startTest();
       	ApexPages.currentPage().getParameters().put('EntityId',partnerAcc.id);
       	GlobalAssumptionPlan = new GlobalAssumptionController();
       	
       	test.stopTest();
    }
    
}