Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Amount_2nd_Installment__c</fullName>
        <label>Amount - 2nd Installment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <label>Amount - 1st Installment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cheque_Received_Date__c</fullName>
        <label>Cheque Received Date - 1</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cheque_date__c</fullName>
        <label>Cheque date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Has_Opted_For_Renewal__c</fullName>
        <label>Has Opted For Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <formula>Cheque_Received_Date__c + 365</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Cheque_Details__c.object
<CustomObject>
    <description>To represent cheque related details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cheque Details</relationshipLabel>
        <relationshipName>Cheque_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <label>Amount Received</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cheque_Date__c</fullName>
        <label>Cheque Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cheque_No__c</fullName>
        <label>Cheque No</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Cheque_Status__c</fullName>
        <label>Cheque Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cleared</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dishonoured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Presented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deposited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NEFT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Installment__c</fullName>
        <label>Installment</label>
        <picklist>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Detail</label>
        <referenceTo>Order_Detail__c</referenceTo>
        <relationshipLabel>Cheque Details</relationshipLabel>
        <relationshipName>Cheque_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Cheque Details</label>
    <nameField>
        <displayFormat>CHQ-{000000}</displayFormat>
        <label>Cheque Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cheque Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD-{00000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Renewal__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Received__c</fullName>
        <label>Amount Received</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Cheque_Received_Date__c</fullName>
        <label>Cheque Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewals</relationshipLabel>
        <relationshipName>Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Opted_for_Renewal__c</fullName>
        <label>Has Opted for Renewal</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Renew__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Renew</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Renewal_Date__c</fullName>
        <label>Renewal Date</label>
        <type>Date</type>
    </fields>
    <label>Renewal</label>
    <nameField>
        <displayFormat>Renewal-{0}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestCreateSubsequentRenewalsTrigger.cls
@isTest
private class TestCreateSubsequentRenewalsTrigger {

    static testMethod void TestingCreateSubsequentRenewalsTrigger() {
      Date todayDate = Date.today(); 
     
     	/* Commented statements on 05Mar 2012 : because Cheque_Received_Date__c,Amount_Received__c,Amount_2nd_Installment__c will be removed from Account object */
       // Account acc = new Account(FirstName='Test_Fname1',LastName='Test_Renewal_Lname1',Cheque_Received_Date__c=todayDate,PersonMobilePhone='9876543210',PersonEmail='test@ffreedom.in',Entity_Status__c='Active');
        Account acc = new Account(FirstName='Test_Fname1',LastName='Test_Renewal_Lname1',PersonMobilePhone='9876543210',PersonEmail='test@ffreedom.in',Entity_Status__c='Active');//Cheque_Received_Date__c=todayDate,
        insert acc;
        
        Account account = [select Id,LastName from Account where LastName='Test_Renewal_Lname1'];
              
        Renewal__c objRenewal = new Renewal__c(Renewal_Date__c= Date.today(), Entity__c= account.Id,  Is_Renew__c= false);
		insert objRenewal;
		
		String strNewOrderNumber = 'FFP/' + String.valueOf(System.today().year()).substring(2, 4) + '-' + 
                                         String.valueOf(System.today().year() + 1).substring(2, 4) + '/001' ; 
                                           
		Order_Detail__c objOrderDetail = new Order_Detail__c(Order_Number__c = strNewOrderNumber, Account__c = account.Id );
        insert objOrderDetail;
        
        Cheque_Details__c objchq = new Cheque_Details__c(Account__c = account.Id, Installment__c = '1st',Cheque_Date__c = todayDate,
        									Cheque_No__c = 'Ch0011',Amount_Received__c = 1200,Cheque_Status__c = 'Deposited',
        									Order_Detail__c = objOrderDetail.Id);
        insert objchq;
                      
       /*===========No need to insert record in Renewal__c,it gets automatically generated through trigger===*/ 
        //Renewal__c renewal = [select Cheque_Received_Date__c,Id from Renewal__c where Entity__c=:account.Id];
        
        objRenewal.Cheque_Received_Date__c=todayDate.addYears(1);
        objRenewal.Has_Opted_for_Renewal__c='Yes';
      
        update objRenewal;
        //Renewal__c renewal = new Renewal__c (Entity__c=acc.Id); 
        //insert renewal;
    }
}