Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Business_Unit__c.object
<CustomObject>
    <label>Business Unit</label>
    <nameField>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Departments</relationshipLabel>
        <relationshipName>Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Event__c.object
<CustomObject>
    <label>Conveyance Submission</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conveyance Submission</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Event_Master__c.object
<CustomObject>
    <fields>
        <fullName>Escalation_Event_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Escalation Event Master</label>
        <referenceTo>Event_Master__c</referenceTo>
        <relationshipLabel>Event Masters</relationshipLabel>
        <relationshipName>Event_Masters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Master</label>
    <nameField>
        <label>Event Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Notification_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Biz_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Biz Unit</label>
        <referenceTo>Business_Unit__c</referenceTo>
        <relationshipLabel>Notification Queues</relationshipLabel>
        <relationshipName>Notification_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <label>Channel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Custom_ID__c</fullName>
        <label>Custom ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Custom_Object_Type__c</fullName>
        <label>Custom Object Type</label>
        <picklist>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Notification Queues</relationshipLabel>
        <relationshipName>Notification_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event_Master__c</referenceTo>
        <relationshipLabel>Notification Queues</relationshipLabel>
        <relationshipName>Notification_Queues</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Id__c</fullName>
        <label>Member Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Notification Queue</label>
    <nameField>
        <displayFormat>NQ-{0000}</displayFormat>
        <label>Notification Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notification Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Workflows_Tracker_Details__c.object
<CustomObject>
    <fields>
        <fullName>Channel_Type__c</fullName>
        <label>Channel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Days_After__c</fullName>
        <label>Days After</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Workflows Tracker Details</relationshipLabel>
        <relationshipName>Workflows_Tracker_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event Master</label>
        <referenceTo>Event_Master__c</referenceTo>
        <relationshipLabel>Workflows Tracker Details</relationshipLabel>
        <relationshipName>Workflows_Tracker_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Workflows_Tracker_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Workflows Tracker Details</label>
        <referenceTo>Workflows_Tracker_Details__c</referenceTo>
        <relationshipLabel>Workflows Tracker Details</relationshipLabel>
        <relationshipName>Workflows_Tracker_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Workflow_Details_Date__c</fullName>
        <description>Entity Creation Date and Data Collection Date is used to getting Due Date for Particular Task.</description>
        <label>Related Workflow Details Date</label>
        <picklist>
            <picklistValues>
                <fullName>Entity Creation Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Collection Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Presentation Date</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Id__c</fullName>
        <label>Task Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task_Sequence__c</fullName>
        <label>Task Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Workflows_Tracker_Master__c</fullName>
        <label>Workflows Tracker Master</label>
        <referenceTo>Workflows_Tracker_Master__c</referenceTo>
        <relationshipLabel>Workflows Tracker Details</relationshipLabel>
        <relationshipName>Workflows_Tracker_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Workflows Tracker Details</label>
    <nameField>
        <label>Workflows Tracker Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflows Tracker Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Workflows_Tracker_Master__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Workflows Tracker Masters</relationshipLabel>
        <relationshipName>Workflows_Tracker_Masters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Workflows Tracker Master</label>
    <nameField>
        <label>Workflows Tracker Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Workflows Tracker Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/BatchTaskEscalation.cls
global with sharing class BatchTaskEscalation implements Database.Batchable<sObject> 
{
	global Database.QueryLocator start(Database.BatchableContext BC) 
    { 
    	//Get All Task Whose Due Date = Yesterday and Status not Completed
    	return Database.getQueryLocator('Select WhoId, WhatId, Subject, Status, Stage__c, Priority, OwnerId, ActivityDate,LastModifiedDate, Id, Description, AccountId From Task  Where ActivityDate = YESTERDAY and Status !=\'Completed\' ');
    	
    }
     global void execute(Database.BatchableContext BC, List<Task> lstTask) 
    {
    	Map<Id,Task> mapTaskIdToTask = new Map<Id,Task> ();
    	Map<Id,Id> mapTaskIdToAccountId = new Map<Id,Id> ();
    	Map<Id, Workflows_Tracker_Details__c> mapTaskIdToWFlowTrackerDetails = new Map<Id, Workflows_Tracker_Details__c> ();
    	List<Notification_Queue__c> lstNotificationQueue = new List<Notification_Queue__c>();
    	List<Task> lstEscalatedTask = new List<Task>();
    	
    	//Iterate All task and Create Map TaskId to Account
    	for(Task objTask : lstTask)
    	{
    		mapTaskIdToTask.put(objTask.Id, objTask);
    		mapTaskIdToAccountId.put(objTask.Id, objTask.WhatId);
    	}
    	
    	//Get all the Entity Workflow Tracker Details Where Task Id and Account id will be present
    	if(mapTaskIdToAccountId != null && mapTaskIdToAccountId.keySet() != null)
    	{
	    	List<Workflows_Tracker_Details__c> lstWFlowTrackerDetails = [Select Task_Sequence__c, 
														    					Task_Id__c, Subject__c, Status__c, 
														    					Related_Workflow_Details_Date__c, Priority__c,
														    					Event_Master__r.Escalation_Event_Master__c,Workflows_Tracker_Master__c,
																				Parent_Workflows_Tracker_Details__c, Name, Id, Event_Master__c, 
																				Due_Date__c, Department__c, Department__r.Business_Unit__c,Days_After__c, Comments__c, 
																				Channel_Type__c ,Workflows_Tracker_Master__r.Parent_Account__c
																		 From Workflows_Tracker_Details__c 
																		 Where Task_Id__c IN: mapTaskIdToAccountId.keyset()
																		 and Workflows_Tracker_Master__r.Parent_Account__c IN: mapTaskIdToAccountId.values()];
			
			system.debug('***************lstWFlowTrackerDetails'+lstWFlowTrackerDetails);																	
			
			//if WFlow Tracker Details is not Empty																	
			if(lstWFlowTrackerDetails.size() > 0)
			{
		        for(Workflows_Tracker_Details__c objEntityWFlowTrackerDetails : lstWFlowTrackerDetails)		
		        {
		        	//Collect All TaskId and There WFlow Tracker Detail Object
		        	mapTaskIdToWFlowTrackerDetails.put(objEntityWFlowTrackerDetails.Task_Id__c, objEntityWFlowTrackerDetails);
		        }
			
			
				if(mapTaskIdToWFlowTrackerDetails.keySet() != null)
				{
					 //Collect All Escalated Task
			       	 lstEscalatedTask = [Select WhoId, WhatId, Subject, Status, Stage__c, Priority, OwnerId, 
			        										ActivityDate,LastModifiedDate, Id, Description, AccountId
			        							   From Task  Where ActivityDate =YESTERDAY and Status !=: Label.Completed and 
			        										Id IN: mapTaskIdToWFlowTrackerDetails.keySet()];
			        system.debug('***************lstEscalatedTask'+lstEscalatedTask);										
				}				
			}
			
			//Insert Notification Queue Record
	        if(lstEscalatedTask.size() > 0 )
	        {									
		        for(Task objEscatedTask :lstEscalatedTask )
		        {
		        	Notification_Queue__c objNotificationQueue = new Notification_Queue__c();
		        	Id eventMasterId = mapTaskIdToWFlowTrackerDetails.get(objEscatedTask.Id).Event_Master__r.Escalation_Event_Master__c;
		        	if(eventMasterId != null && mapTaskIdToAccountId.get(objEscatedTask.Id) != null)
		        	{
			        	objNotificationQueue.Department__c = mapTaskIdToWFlowTrackerDetails.get(objEscatedTask.Id).Department__c;
			        	objNotificationQueue.Event__c =  eventMasterId;
			        	objNotificationQueue.Member_Id__c = mapTaskIdToAccountId.get(objEscatedTask.Id);
			        	objNotificationQueue.Channel_Type__c = 'Email';
			        	objNotificationQueue.Priority__c = 'High';
			        	objNotificationQueue.Custom_Object_Type__c = 'Task';
			        	objNotificationQueue.Custom_ID__c = objEscatedTask.id;
			        	objNotificationQueue.Biz_Unit__c = mapTaskIdToWFlowTrackerDetails.get(objEscatedTask.Id).Department__r.Business_Unit__c;
			        	lstNotificationQueue.add(objNotificationQueue);
			        	system.debug('***************lstNotificationQueue'+lstNotificationQueue);		
		        	}	
		        }	
		        									                                                 													
				//Insert Notification Queue Record	
				if(lstNotificationQueue.size() > 0)
					insert lstNotificationQueue;
	        }		
    	}					
																			
    }
    
    global void finish(Database.BatchableContext BC)
    {
    	//Do Nothing
    }

}//end Class