Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Health_History_del__c</fullName>
        <label>Health History</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Family Members</relationshipLabel>
        <relationshipName>Entities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Will__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check yes if the Will has been created</description>
        <label>Will</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Client_Details__c.object
<CustomObject>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Billing_Zip_Postal_Code__c</fullName>
        <label>Billing Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Details</relationshipLabel>
        <relationshipName>Client_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Health_History__c</fullName>
        <label>Health History</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <label>Mailing City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Country__c</fullName>
        <label>Mailing Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <label>Mailing State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street__c</fullName>
        <label>Mailing Street</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Postal_Code__c</fullName>
        <label>Mailing Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marital_Status__c</fullName>
        <label>Marital Status</label>
        <picklist>
            <picklistValues>
                <fullName>Single</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Divorced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Widowed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_City__c</fullName>
        <label>Office City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Country__c</fullName>
        <label>Office Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_State__c</fullName>
        <label>Office State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Office_Street__c</fullName>
        <label>Office Street</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Office_Zip_Postal_Code__c</fullName>
        <label>Office Zip/Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pan_Id__c</fullName>
        <label>Pan Id</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Details (Parent Entity)</relationshipLabel>
        <relationshipName>Client_Details1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <label>Passport Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Entity__c</fullName>
        <label>Relationship to Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daughter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Father</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Husband</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mother</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Son</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wife</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Dependant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <picklist>
            <picklistValues>
                <fullName>Mr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ms.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mrs.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dr.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prof.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Will__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether will is present</description>
        <label>Will</label>
        <type>Checkbox</type>
    </fields>
    <label>Client Detail</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Client Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Financial_Account__c.object
<CustomObject>
    <description>To represent Bank and DP accounts.</description>
    <fields>
        <fullName>Account__c</fullName>
        <description>Relationship with parent a/c</description>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>EntityFinancialOrg</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Financial Account ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/FinancialRecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>FinancialRecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ClientInfoService.cls
/**
 * @Author: Sandip C
 * @since :08th Feb 2011
 * @Description:ClientInfoService is class for ClientInfoPage which used for 
 * customer portal to populate Client_Details__c custom object and the trigger on the custom object will
 * populate the data in account. 
 */
 public class ClientInfoService{
	    DatabaseDML databaseAccess=new DatabaseDML();
	    DatabaseSOQL databaseObj = new DatabaseSOQL();
	/**
	  * @Description: Constructor to initialise the bean class,service class and fetch existing data
	  * @param: None 
	  * @return type: 
	  */
	    public ClientInfoService(){
	    }
   /**
	 * @getEntity() function returns the details of Client_Details__c
	 * @params:id of particular Client_Details__c(Entity)
	 * @Return Type:Client_Details__c object instance for that particular entity
	 */  
	    public Client_Details__c getEntity(String clientId) {
		        Client_Details__c ct = new Client_Details__c();
		        List<Client_Details__c> ctList = databaseObj.getClient(clientId);
		        if(ctList ==null || ctList.size()==0) {
		        }
		        else{
		            ct = ctList[0];
		        }
		        Account acc = databaseObj.getEntity(clientId);
		        ct.First_Name__c = acc.FirstName;
		        ct.Last_Name__c = acc.LastName;
		        ct.Entity__c = acc.Id;
		        ct.Parent_Entity__c =  acc.Parent_Entity__c;
		        ct.Billing_City__c =  acc.BillingCity;
		        ct.Billing_Country__c =  acc.BillingCountry;
		        ct.Billing_State__c =  acc.BillingState;
		        ct.Billing_Street__c =  acc.BillingStreet;
		        ct.Billing_Zip_Postal_Code__c =  acc.BillingPostalCode;
		        ct.Date_Of_Birth__c =  acc.PersonBirthdate;
		        ct.Email__c =  acc.PersonEmail;
		        ct.Gender__c =  acc.Gender__pc;
		        ct.Health_History__c =  acc.Health_History_del__c;
		        ct.Home_Phone__c =  acc.PersonHomePhone;
		        ct.Mailing_City__c =  acc.PersonMailingCity;
		        ct.Mailing_Country__c =  acc.PersonMailingCountry;
		        ct.Mailing_State__c =  acc.PersonMailingState;
		        ct.Mailing_Street__c =  acc.PersonMailingStreet;
		        ct.Mailing_Zip_Postal_Code__c =  acc.PersonMailingPostalCode;
		        ct.Marital_Status__c =  acc.Marital_Status__pc;
		        ct.Middle_Name__c =  acc.Middle_Name__pc;
		        ct.Mobile__c =  acc.PersonMobilePhone;
		        ct.Office_City__c =  acc.PersonOtherCity;
		        ct.Office_Country__c =  acc.PersonOtherCountry;
		        ct.Office_State__c =  acc.PersonOtherState;
		        ct.Office_Street__c =  acc.PersonOtherStreet;
		        ct.Office_Zip_Postal_Code__c =  acc.PersonOtherPostalCode;
		        ct.Pan_Id__c =  acc.PAN_ID__pc;
		        ct.Passport_Number__c =  acc.Passport__pc;
		        ct.Relationship_to_Entity__c =  acc.Relationship_to_Entity__pc;
		        ct.Will__c =  acc.Will__c;
		        ct.Salutation__c =  acc.Salutation;
		        return ct;
		        
	    }
  /**
	* @save() Method is used to save the values enterd in the ClientInfoPage. 
	* @params:familyinfoBean class object instance and id of the account
	*/
	    public void save(ClientInfoBean ciBean){
	       	   for (integer index=0;index<ciBean.bankList.size();index++) {
	            	Financial_Account__c fAcc=ciBean.bankList.get(index);
	            	if (ciBean.isEmpty(fAcc,ciBean.bankRec.name)) {
	              		ciBean.bankList.remove(index);
	            	}
	        	}
	        
	        	for (integer index=0;index<ciBean.dematList.size();index++) {
		            Financial_Account__c fAcc=ciBean.dematList.get(index);
		            if (ciBean.isEmpty(fAcc,ciBean.dematRec.name)) {
		              ciBean.dematList.remove(index);
		            }
	        	}
	        
	        	try{
		            ciBean.validate(ciBean.acc);
		            databaseAccess.upsertObject(ciBean.acc);
		            if (ciBean.bankList.size()>0) {
		               databaseAccess.upsertObject(ciBean.bankList);
		            }
		            if (ciBean.dematList.size()>0) {
		                databaseAccess.upsertObject(ciBean.dematList);
		            }
	        	}
		        catch(ValidationException e) {
		            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage()));
		        }
		        catch(Exception ex){
		           ApexPages.addMessages(ex);
		        }
		         return;
	    }
	    public List<Client_Details__c> getClientFamily(String clientId) {
	         	return databaseObj.getClientFamily(clientId);
	    }
   /**
	 * addNewMembers() method used insert/update the new/existing family members of particular entity
	 * params:List of family members
	 * Return Type:void
	 */   
	 
	   public void addNewMembers(List<Client_Details__c> entityLst){
	    	   databaseAccess.upsertObject(entityLst);
	   }
	  
   /**
	 * saveNext() method used to save the details of client/family members and move to next family member details
	 * params:id of client and particular family member
	 * Return Type:pageReference
	 */  
	 
	   public Pagereference saveNext(String parentId,String childId){
		     List<Account> accList=new List<account>();
		      Pagereference pageRef;
		      String newPageId;
		      integer i;
		      if (parentId!=null && parentId!='') {
		         accList=databaseObj.getFamilyDetails(parentId);
		         if (accList.size()>0) {
		          	if (childId!=null && childId!='') {
		            	for (i=0;i<accList.size();i++) {
		             		String accId=acclist.get(i).Id;
		              		if (accId.equalsIgnoreCase(childId)) {
		                		if ((i+1)!=accList.size()) {
		                 			newPageId=accList.get(i+1).Id;
		                  			pageRef =new pageReference('/apex/clientInfoPage?fentityId='+newPageId+'&entityId='+
		                                                        parentId+'&RecType=family&tabname=Financial Planning');
		                        }
		                        else{
		                            pageRef = new pageReference ('/apex/IncomeSummaryPage?entityId='+parentId+
		                                                         '&tabname=Financial Planning');
		                        }
		                       break;
		                    }  
		                }
		            }
		            else{
		            	if (accList.get(1)!=null) {
		              		newPageId=accList.get(1).id;
		              		pageRef = new pageReference ('/apex/clientInfoPage?fentityId='+newPageId+'&entityId='+
		              		                              parentId+'&RecType=family&tabname=Financial Planning');
		            	}
		            	else{
		              		pageRef = new pageReference ('/apex/IncomeSummaryPage?entityId='+parentId+
		              		                             '&tabname=Financial Planning');
		            	}
		            }
		         }
		      }
		      return pageRef;
	   }
	   
   /**
	 * addNewRow() method used to add new rows for entering aditional bank/demat account Details
	 * params:id familyMemberInfoBean object instance and account recordtype(bank/demat)
	 * Return Type:void
	 */  
	   public void addNewRow(ClientInfoBean ciBean,String financialRecType){
		      if (financialRecType.equalsIgnoreCase(Label.DematAccount)) {
		          Financial_Account__c tmp = new Financial_Account__c();
		          tmp.recordtypeId = ciBean.dematRec.RecordTypeId__c;
		          tmp.Account__c= ciBean.entId;
		          ciBean.dematList.add(tmp);
		      }
		      if (financialRecType.equalsIgnoreCase(Label.BankAccount)) {
		          Financial_Account__c tmp1 = new Financial_Account__c();
		          tmp1.recordtypeId = ciBean.bankRec.RecordTypeId__c;
		          tmp1.Account__c= ciBean.entId;
		          ciBean.bankList.add(tmp1);
		      }
	   }  
	      
   /**
	 * getFinancialRec() method used to get FinancialRecTypes__c object instance  for bank/demat account
	 * params:recordtype Name
	 * Return Type:FinancialRecTypes__c
	 */  
	  public  FinancialRecTypes__c getFinancialRec (String recordName){
	     	  return  databaseObj.getFinancialRec(recordName);
	   }
	   
   /**
	 * getBankDetails() method used to get bank/demat account details of particular client
	 * params:recordtype Name
	 * Return Type:FinancialRecTypes__c
	 */  
	 public List<Financial_Account__c> getBankDetails(String entityId,String recId) {
	        return databaseObj.getBankDetails(entityId, recId);
	  }
 }