Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Adjustment_Factor__c</fullName>
        <label>Adjustment Factor %</label>
        <picklist>
            <picklistValues>
                <fullName>-100</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>40</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>60</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>70</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>80</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>90</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>100</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Alternate_E_Mail_Address__c</fullName>
        <label>Alternate E-Mail Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alternate_Mobile__c</fullName>
        <label>Alternate Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_EndYear__c</fullName>
        <label>Estimated Life EndYear</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Estimated_Life_Expectancy__c</fullName>
        <label>Estimated Life Expectancy</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Residential_Status_del__c</fullName>
        <label>Residential Status</label>
        <picklist>
            <picklistValues>
                <fullName>Permanent Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident but not Ordinary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Resident</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Retirement_Age__c</fullName>
        <label>Retirement Age</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Retirement_Year__c</fullName>
        <label>Retirement Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <description>General</description>
        <label>General</label>
    </recordTypes>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Approve_Action_Plan__c.object
<CustomObject>
    <description>Created for new action plan</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Approve Action Plans</relationshipLabel>
        <relationshipName>Approve_Action_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tenure_of_Insurance__c</fullName>
        <label>Tenure of Insurance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Approve Action Plan</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approve Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Provided to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Handed over to Ops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approve_Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approve Action Plan</label>
        <referenceTo>Approve_Action_Plan__c</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ET_Status__c</fullName>
        <label>ET Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <formula>Approve_Action_Plan__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Floating__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Floating</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Risk_Commencement_Date__c</fullName>
        <label>Risk Commencement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target_Revenue__c</fullName>
        <label>Target Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Term_No_Of_Years__c</fullName>
        <label>Term (No. Of Years)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surrender Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Renewal_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Cheque_Submission_date__c</fullName>
        <label>Cheque Submission date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Renewal_Trackers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Tracker</label>
        <referenceTo>Execution_Tracker__c</referenceTo>
        <relationshipName>Renewal_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Type__c</fullName>
        <label>Insurance Type</label>
        <picklist>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_renewal_date__c</fullName>
        <label>Next renewal date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentId</label>
        <referenceTo>Renewal_Tracker__c</referenceTo>
        <relationshipName>Renewal_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Revenue__c</fullName>
        <label>Target Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Tenure_of_Insurance__c</fullName>
        <label>Tenure of Insurance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Renewal Tracker</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Renewal Tracker Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/RenewalTrackerforLIControllerTest.cls
/**
*  Test class for Controller class RenewalTrackerforLIController
*
*   Revision History:
*
*   Version        Author             Date            Description
*   1.0            Aditi          11/04/2013      Initial Draft
*/


public class RenewalTrackerforLIControllerTest 
{
    //test Method
	@isTest(SeeAllData=true)
	public static  void testRenewalTrackerforGeneralInsurance()
	{
		 
		RecordType objRecType = [Select Id from RecordType where Name = 'Client' and SobjectType = 'Account'];
		Account objAccount = new Account(LastName='Test',FirstName='Test',Adjustment_Factor__c='2',
	                       PersonTitle='TestData', PersonBirthdate= system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463712345',
	                       Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',
	                       Retirement_Year__c=2034, Residential_Status_del__c='own', Retirement_Age__c='58', Estimated_Life_Expectancy__c='67',
	                       Estimated_Life_EndYear__c=2041, Relationship_to_Entity__pc='husband', RecordTypeId = objRecType.Id);
	    insert objAccount;
	    
	   
	    Approve_Action_Plan__c objAAP1 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    insert objAAP1;
	    
	    Approve_Action_Plan__c objAAP2 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    insert objAAP2;
        
        List<Execution_Tracker__c> lstET = new List<Execution_Tracker__c>();
        Execution_Tracker__c objET1 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP1.Id, Type__c = 'General Insurance');
        lstET.add(objET1);
        Execution_Tracker__c objET2 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP2.Id, Type__c = 'General Insurance');
        lstET.add(objET2);
        Execution_Tracker__c objET3 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP1.Id, Type__c = 'General Insurance');
        lstET.add(objET3);
        Execution_Tracker__c objET4 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP2.Id, Type__c = 'General Insurance');
        lstET.add(objET4);
        insert lstET;
        
        List<Renewal_Tracker__c> lstRenewalRracker = new List<Renewal_Tracker__c>();
        Renewal_Tracker__c objRenewalTracker1 = new Renewal_Tracker__c(Execution_Tracker__c=objET1.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='General Insurance');
        lstRenewalRracker.add(objRenewalTracker1);
      	Renewal_Tracker__c objRenewalTracker2 = new Renewal_Tracker__c(Execution_Tracker__c=objET2.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='General Insurance');
      	lstRenewalRracker.add(objRenewalTracker2);
        Renewal_Tracker__c objRenewalTracker3 = new Renewal_Tracker__c(Execution_Tracker__c=objET3.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='General Insurance');
        lstRenewalRracker.add(objRenewalTracker3);
  		Renewal_Tracker__c objRenewalTracker4 = new Renewal_Tracker__c(Execution_Tracker__c=objET4.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='General Insurance');
  		lstRenewalRracker.add(objRenewalTracker4);
        insert lstRenewalRracker;
        
        Renewal_Tracker__c objRenewalTracker5 = new Renewal_Tracker__c(Execution_Tracker__c=objET4.Id,Entity__c = objAccount.id,Insurance_Type__c='General Insurance',
        				ParentId__c = objRenewalTracker4.Id,Tenure_of_Insurance__c=12);
  		insert objRenewalTracker5;
        
	    objET1.Mode__c = 'Quaterly';
    	objET2.Mode__c = 'Monthly';	
    	objET3.Mode__c = 'Annual';
    	objET4.Mode__c = 'Semi-Annual';
    	update lstET;
    	
    	objRenewalTracker1.Next_renewal_date__c = system.today();
    	objRenewalTracker1.Target_Revenue__c = 200;
    	objRenewalTracker1.Cheque_Submission_date__c = system.today();
    	update objRenewalTracker1;
    	
    	objRenewalTracker2.Next_renewal_date__c = system.today();
    	objRenewalTracker2.Target_Revenue__c = 200;
    	objRenewalTracker2.Cheque_Submission_date__c = system.today();
    	update objRenewalTracker2;
    	
    	objRenewalTracker3.Next_renewal_date__c = system.today();
    	objRenewalTracker3.Target_Revenue__c = 200;
    	objRenewalTracker3.Cheque_Submission_date__c = system.today();
    	update objRenewalTracker3;
    	
    	objRenewalTracker4.Next_renewal_date__c = system.today();
    	objRenewalTracker4.Target_Revenue__c = 200;
    	objRenewalTracker4.Cheque_Submission_date__c = system.today();
    	update objRenewalTracker4;
    	
    	objRenewalTracker5.Next_renewal_date__c = system.today();
    	objRenewalTracker5.Target_Revenue__c = 200;
    	objRenewalTracker5.Cheque_Submission_date__c = system.today();
    	update objRenewalTracker5;
    	
    	Test.startTest();
        ApexPages.currentPage().getParameters().put('entityId', objAccount.id);
    	RenewalTrackerforLIController objRT = new RenewalTrackerforLIController(); 
    	objRT.saveRenewalTracker();
    	objRT.lifeInsuranceTracker();
    	objRT.generalInsuranceTracker();
    	objRT.ViewRecords();
    	objRT.closeRT();
    	objRT.cancel();
	 	Test.stopTest();
	}
	
	@isTest(SeeAllData=true)
	public static  void testRenewalTrackerForLifeInsurance()
	{
		 
		RecordType objRecType = [Select Id from RecordType where Name = 'Client' and SobjectType = 'Account'];
		Account objAccount = new Account(LastName='Test',FirstName='Test',Adjustment_Factor__c='2',
	                       PersonTitle='TestData', PersonBirthdate= system.today(),PersonHomePhone='54623676',PersonMobilePhone='5463123457',
	                       Alternate_Mobile__c='356475',PersonEmail='sgdh@test.com', Alternate_E_Mail_Address__c='fdgr@test.com',
	                       Retirement_Year__c=2034, Residential_Status_del__c='own', Retirement_Age__c='58', Estimated_Life_Expectancy__c='67',
	                       Estimated_Life_EndYear__c=2041, Relationship_to_Entity__pc='husband', RecordTypeId = objRecType.Id);
	    insert objAccount;
	    
	   
	    Approve_Action_Plan__c objAAP1 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    insert objAAP1;
	    
	    Approve_Action_Plan__c objAAP2 = new Approve_Action_Plan__c(Account__c = objAccount.Id);
	    insert objAAP2;
        
        List<Execution_Tracker__c> lstET = new List<Execution_Tracker__c>();
        Execution_Tracker__c objET1 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,Term_No_Of_Years__c=12,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP1.Id, Type__c = 'Life Insurance');
        lstET.add(objET1);
        Execution_Tracker__c objET2 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,Term_No_Of_Years__c=12,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP2.Id, Type__c = 'Life Insurance');
        lstET.add(objET2);
        Execution_Tracker__c objET3 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,Term_No_Of_Years__c=12,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP1.Id, Type__c = 'Life Insurance');
        lstET.add(objET3);
        Execution_Tracker__c objET4 = new Execution_Tracker__c(Entity_Name__c = objAccount.id,  ET_Status__c = 'Assigned to Operations', Is_Floating__c = false,Term_No_Of_Years__c=12,
        									Risk_Commencement_Date__c = system.today(),Application_Status__c = 'Opened', Approve_Action_Plan__c = objAAP2.Id, Type__c = 'Life Insurance');
        lstET.add(objET4);
        insert lstET;
    	objET1.Mode__c = 'Quaterly';
    	objET2.Mode__c = 'Monthly';
    	objET3.Mode__c = 'Annual';
    	objET4.Mode__c = 'Semi-Annual';
    	update lstET;
        
      	List<Renewal_Tracker__c> lstRenewalRracker = new List<Renewal_Tracker__c>();
        Renewal_Tracker__c objRenewalTracker1 = new Renewal_Tracker__c(Execution_Tracker__c=objET1.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='Life Insurance');
        lstRenewalRracker.add(objRenewalTracker1);
      	Renewal_Tracker__c objRenewalTracker2 = new Renewal_Tracker__c(Execution_Tracker__c=objET2.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='Life Insurance');
      	lstRenewalRracker.add(objRenewalTracker2);
        Renewal_Tracker__c objRenewalTracker3 = new Renewal_Tracker__c(Execution_Tracker__c=objET3.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='Life Insurance');
        lstRenewalRracker.add(objRenewalTracker3);
  		Renewal_Tracker__c objRenewalTracker4 = new Renewal_Tracker__c(Execution_Tracker__c=objET4.Id,Entity__c = objAccount.id,Tenure_of_Insurance__c=12,Insurance_Type__c='Life Insurance');
  		lstRenewalRracker.add(objRenewalTracker4);
        
        insert lstRenewalRracker;
       
    	objRenewalTracker1.Next_renewal_date__c = system.today();
    	objRenewalTracker1.Target_Revenue__c = 200;
    	objRenewalTracker1.Cheque_Submission_date__c = system.today();
    	
    	objRenewalTracker2.Next_renewal_date__c = system.today();
    	objRenewalTracker2.Target_Revenue__c = 200;
    	objRenewalTracker2.Cheque_Submission_date__c = system.today();
    	
    	objRenewalTracker3.Next_renewal_date__c = system.today();
    	objRenewalTracker3.Target_Revenue__c = 200;
    	objRenewalTracker3.Cheque_Submission_date__c = system.today();
    	
    	objRenewalTracker4.Next_renewal_date__c = system.today();
    	objRenewalTracker4.Target_Revenue__c = 200;
    	objRenewalTracker4.Cheque_Submission_date__c = system.today();
    	update objRenewalTracker1;
    	
    	Test.startTest();
        ApexPages.currentPage().getParameters().put('entityId', objAccount.id);
    	RenewalTrackerforLIController objRT = new RenewalTrackerforLIController();
    	objRT.saveRenewalTracker();	 
    	objRT.lifeInsuranceTracker();
    	objRT.generalInsuranceTracker();
    	objRT.ViewRecords();
	 	Test.stopTest();
	}
}