Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Number_Of_Months__c</fullName>
        <label>Number Of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan_Generation_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Added in FP changes</description>
        <label>Plan Generation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Referred_by_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referred by Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Referred by Entity)</relationshipLabel>
        <relationshipName>Entity</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>EPF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superannuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Saving Certificate (NSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kisan Vikas Patra (KVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indra Vikas Patra / Others (IVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Income Plan (MIP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Recurring Deposit (RD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Time Deposit (FD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Provident Fund (PPF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Citizens Savings Scheme (SCSS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate of Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Deposits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash in hand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others…</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Asset_Types__c</fullName>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>EPF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superannuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Saving Certificate (NSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kisan Vikas Patra (KVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indra Vikas Patra / Others (IVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Income Plan (MIP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Recurring Deposit (RD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Time Deposit (FD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Provident Fund (PPF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Citizens Savings Scheme (SCSS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash in hand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Limited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jewelry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EmergencyFundAction__c</fullName>
        <label>EmergencyFundAction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Entity_Global_Assumption__c.object
<CustomObject>
    <fields>
        <fullName>Number_Of_Months__c</fullName>
        <label>Number Of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Entity Global Assumption</label>
    <nameField>
        <label>Entity Global Assumption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Global Assumptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInvestmentAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>Allocation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Investment_Asset__c</fullName>
        <description>Investment asset relation</description>
        <label>Investment Asset</label>
        <referenceTo>Investment_Asset__c</referenceTo>
        <relationshipLabel>GoalInvestmentAssetAssociations</relationshipLabel>
        <relationshipName>InvestmentAssetMapping</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>GoalInvestmentAssetAssociation</label>
    <nameField>
        <displayFormat>GIAA-{0000}</displayFormat>
        <label>GoalInvestmentAssetAssociationId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInvestmentAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Premium_amount__c</fullName>
        <formula>CASE(  
     Premium_Frequency__c ,
      &apos;Annually&apos;,  Premium_Amount_Rs__c ,
     &apos;Semi Annual&apos;, (Premium_Amount_Rs__c  * 2), 
     &apos;Quarterly&apos;,( Premium_Amount_Rs__c  * 4), 
     &apos;Monthly&apos;,(Premium_Amount_Rs__c   * 12),
    0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual_Premium_amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commencement_Date__c</fullName>
        <inlineHelpText>Please Enter Date In Format : DD/MM/YY</inlineHelpText>
        <label>Commencement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EmergencyFundAction__c</fullName>
        <label>EmergencyFundAction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tenure_of_Insurance__c</fullName>
        <label>Tenure of Insurance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>totalAsset__c</fullName>
        <formula>CASE(
 Policy_Type__c ,
&apos;Whole Life&apos;,  Annual_Premium_amount__c *  (1.06 ^ Tenure_of_Insurance__c ),
&apos;ULIP - Debt&apos;, Annual_Premium_amount__c *  (1.06 ^ Tenure_of_Insurance__c ),
&apos;Money-Back&apos;,Annual_Premium_amount__c * (1.05 ^ Tenure_of_Insurance__c ),
&apos;Endowment&apos;,Annual_Premium_amount__c *  (1.06 ^ Tenure_of_Insurance__c ),
&apos;ULIP - Equity&apos;,Annual_Premium_amount__c * (1.10 ^ Tenure_of_Insurance__c ),
&apos;Pension plan&apos;,Annual_Premium_amount__c * (1.06 ^ Tenure_of_Insurance__c ),
0
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>totalAsset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>EmergencyFundAction__c</fullName>
        <label>EmergencyFundAction</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investment Assets</relationshipLabel>
        <relationshipName>Investment_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TotalAsset__c</fullName>
        <description>Formula to calculate stock , Mutual Fund and Fixed Income total for a given record.</description>
        <formula>IF(CONTAINS(RecordTypeId , &apos;01220000000HYx5&apos; ) ,  Quantity__c  *  Current_Price__c ,
            IF(CONTAINS(RecordTypeId , &apos;01220000000HYx4&apos; ),  Units__c *  Current_NAV__c,
                         IF(CONTAINS(RecordTypeId, &apos;01220000000HYx3&apos; ),   Face_Value__c *  Quantity__c ,
                                    IF(CONTAINS(RecordTypeId, &apos;012W00000004OxK&apos; ),   Quantity__c  *  Current_Price__c ,
                                     0)
                          )
             )
 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalAsset</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/EmergencyPlanningServices.cls
/**
*
* Author:  Manasi Ranade 
*
* Revision History:
*   Version     Version Author     Date       		Comments
*   1.0        	Samruddhi P  	   17/2/2011		EmergencyPlanningServices is service class for EmergencyPlanningPage in Analysis Section
	2.0			Manasi			   31/1/2012	    Issue ID : 00001486 : Added code to avoid duplication in the list while upserting it to the database
* 				Prajakta		   21-05-2013  		FP changes II - Changed query in DatabaseSOQL as expense total is needed without vacation expense
*/
public class EmergencyPlanningServices {
    DatabaseSOQL dbSOQL {get; set;}
    DatabaseDML dbDML {get; set;}
	private Entity_Global_Assumption__c globalAssumptions;
	public Integer currentYearnew{get;set;}	/* Prajakta - FP changes - 30-04-2013 */
	public Account objAccount{get;set;}		/* Prajakta - FP changes - 12-04-2013 */
    public String entityId {get;set;}		/* Prajakta - FP changes - 12-04-2013 */
	
    public EmergencyPlanningServices()
    {
        dbSOQL = new DatabaseSOQL();
        dbDML = new DatabaseDML();
        
         /* Prajakta - FP changes - 12-04-2013 */
        //Integer currentYearnew;
        entityId = System.currentPageReference().getParameters().get('entityId');
        objAccount = dbSOQL.getEntity(entityId);
        if(objAccount.Plan_Generation_Date__c != null) 
        	currentYearnew = objAccount.Plan_Generation_Date__c.year();
        else
        	currentYearnew = System.today().year();
        //error.DebugLog('----currentYearnew-----'+currentYearnew);
    }
    
    /**
    * getTotalExpenses() function returns the total family expenses for a particular entity
    * param:id of particular Account (Entity)
    * returns:Double
    */
    public Double getTotalExpenses(String entityId)
    {
        Double expenseValue = 0;
        try{
        	
	        
	        /*AggregateResult aggResult = dbSOQL.getTotalExpenses(entityId);    
            if(aggResult.get('expenses') != null)
                expenseValue = (Double)aggResult.get('expenses');
                Error.DebugLog('expenseValue====>>>>'+expenseValue);
            aggResult=dbSOQL.getTotalFamilyLiabilities(entityId);
            Error.DebugLog('(Emi====>>>>'+(Double)aggResult.get('emi'));    
            if(aggResult.get('emi')!=null)
            {
            	expenseValue = expenseValue + (Double)aggResult.get('emi');
            }
            //FS0244
            List<Insurance__c> objInsuranceList = dbSOQL.getInsurances(entityId,'Data Entry');
            //////////
            Date tempDate;
            Integer startYear,endYear;
            double dblAnnualTotalInsurance = 0;
            for(Insurance__c result : objInsuranceList) 
            {
                  tempDate  = (result.Commencement_Date__c);
            
	            if(result.Commencement_Date__c != null) {
	                startYear = tempDate.year(); 
	            } else {
	                startYear = Date.today().year();
	            }
				if(result.Tenure_of_Insurance__c != null) {				
					endYear = startYear + Integer.valueof(String.valueOf(result.Tenure_of_Insurance__c).trim());
					endYear = endYear - 1;
	            } else {
	                endYear = Date.today().year(); 
	            }
	            if(endYear>=Date.today().year()){
	            	//summaryRecordTypeBean  = summaryBean.getSummaryRecordTypeBean('Insurance');
	            	dblAnnualTotalInsurance = dblAnnualTotalInsurance + result.Annual_Premium_amount__c;
	            	//summaryRecordTypeBean.populateSummaryDetailList(startYear,endYear,result.Annual_Premium_amount__c,0); 
	            }
	        }
	         Error.DebugLog('(Insurance====>>>>'+dblAnnualTotalInsurance); 
	         expenseValue = expenseValue + (dblAnnualTotalInsurance/12);*/
	         
		    /*
	    	Modified By : Dipak Nikam.
	    	Modified At : 29 Feb 2012
	    	Case Number : 00001522
	    	Summary 	: Commented the above  code and also added code below code,Expense value should be Total Expense page less savings.  
	    	*/	
		    List<Expense__c> expenseList; 
	        List<Loan__c> loanList;
	        List<Insurance__c> insuranceList;     
    		NewCashFlowService objNewCashFlowService = new NewCashFlowService();
   			List<NewSummaryBean> summaryList = new List<NewSummaryBean>();                                                  
    		NewSummaryBean summaryBean;                
    		Integer currentYear = currentYearnew; //Date.today().year()/*Praj*/
    		Integer defaultStartYear = currentYear,defaultEndYear = defaultStartYear;
    
	        globalAssumptions = dbSOQL.getEntityGlobalAssumption(entityId);
	        summaryBean = new NewSummaryBean('Expenses',currentYear,currentYear);
	        summaryList.add(summaryBean);
	        //expenseList = dbSOQL.getMonthlyExpenseForCashFlow(entityId);
	        /* Prajakta - FP changes II - 21-05-2013 - Changed query in DatabaseSOQL as expense total is needed without vacation expense*/
	        expenseList = dbSOQL.getMonthlyExpenseForCashFlowWithoutVacation(entityId);
	        objNewCashFlowService.setExpensesSummaryDetails(expenseList,defaultStartYear,defaultEndYear,summaryBean);
	       
	        loanList = dbSOQL.getLoanList(entityId);
	        objNewCashFlowService.setLoanSummaryDetails(loanList,defaultStartYear,defaultEndYear,summaryBean);
	      	
	      	insuranceList = dbSOQL.getInsurances(entityId,'Data Entry');
	        objNewCashFlowService.setInsuranceSummaryDetails(insuranceList,defaultStartYear,defaultEndYear,summaryBean);
		    objNewCashFlowService.setYearList(1);
		    
		   	NewCashFlowBean objCashFlowBean = new NewCashFlowBean(summaryList,1);
		   	if(objCashFlowBean.summaryList != null && objCashFlowBean.summaryList.size() > 0)
		   	{
			   	for(NewSummaryBean objNewSummaryBean :objCashFlowBean.summaryList)
			   	{
			   		List<Double>lstDouble = objNewSummaryBean.totalValueByYear;
			   		if(lstDouble != null && lstDouble.size() > 0)
			   		{
			   			//error.debugLog('-------lstDouble----------'+lstDouble);
			   			for(Double dbleValue :lstDouble )
			   			{
			   				expenseValue = expenseValue + dbleValue;
			   				//error.debugLog('-------expenseValue----------'+expenseValue);
			   			}
			   		} 
			   	}
			}
			if(expenseValue != 0)
				expenseValue =expenseValue/12;
				//error.debugLog('-------expenseValue----after------'+expenseValue);
	   }
        catch(System.Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage())); 
        }
        return expenseValue;
     } 
     
   
       
    
    /**
    * getNoOfMonths() function returns the no fo emeregncy fund months for a particular entity
    * param:id of particular Account (Entity)
    * returns:Double 
    */ 
    public Double getNoOfMonths(String entityId){
        Double months;
        try{
            Entity_Global_Assumption__c assumption=dbSOQL.getGlobalAssumptions(entityId);
            if(assumption!=null && assumption.Number_Of_Months__c!=null)
                months=(Double)assumption.Number_Of_Months__c;
            else   
                months=0;
        }
        catch(System.Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage())); 
        }
        return months;
    }
    
    /**
    * getAssetAllocation() function returns the assets allocated to emergency fund for a particular entity
    * param:id of particular Account (Entity),List<EmergencyActionPlanBean>
    * returns:void
    */
    public void getAssetAllocation(String entityId,List<EmergencyActionPlanBean> beanList){
        try{
            List<AggregateResult> goalAsset=dbSOQL.getTotalAssetsForEmergencyFund(entityId);
            system.debug('==goalAsset=='+goalAsset);
            if(goalAsset !=null){
                for(AggregateResult ar: goalAsset ){
                    EmergencyActionPlanBean apbean= new EmergencyActionPlanBean();
                    if(ar.get('amount')!=null && ar.get('amount')!=0){
                        if(ar.get('accounttype')!=null)
                            apbean.Name=(String)ar.get('accounttype');
                        if(ar.get('assettype')!=null)
                            apbean.Name=(String)ar.get('assettype');
                        apbean.Owner=(String)ar.get('entity');
                        apbean.Amount=(Double)ar.get('amount');
                        apbean.Action=(String)ar.get('action');
                        apbean.ObjectName=Label.Asset;
                        beanList.add(apbean);
                    }
                }
            }
        }
        catch(System.Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage())); 
        }
    }  
   
    /**
    * getInsuranceAllocation() function returns the insurance allocated to emergency fund for a particular entity
    * param:id of particular Account (Entity),List<EmergencyActionPlanBean>
    * returns:void
    */
    public void getInsuranceAllocation(String entityId,List<EmergencyActionPlanBean> beanList){
        try{
            List<AggregateResult> goalInsurance=dbSOQL.getTotalInsuranceForEmergencyFund(entityId);
            system.debug('==goalInsurance=='+goalInsurance);
            if(goalInsurance!=null){
                for(AggregateResult ar: goalInsurance){
                    EmergencyActionPlanBean apbean= new EmergencyActionPlanBean();
                    if(ar.get('amount')!=null && ar.get('amount')!=0){
                        apbean.Name=(String)ar.get('recordtype');
                        apbean.Owner=(String)ar.get('entity');
                        apbean.Amount=(Double)ar.get('amount');
                        apbean.Action=(String)ar.get('action');
                        apbean.ObjectName=Label.Insurance;
                        beanList.add(apbean);
                    }    
                }
            }
        }
        catch(System.Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage())); 
        }
    }
    
    /**
    * getInvestmentAssetAllocation() function returns the investment assets allocated to emergency fund for a particular entity
    * param:id of particular Account (Entity),List<EmergencyActionPlanBean>
    * returns:void
    */
    public void getInvestmentAssetAllocation(String entityId,List<EmergencyActionPlanBean> beanList){
        try{
            List<AggregateResult> goalInvAsset=dbSOQL.getTotalInvestmentAssetsForEmergencyFund(entityId);
            /*
            * Added on : 7/10/2013 - Aditi Satpute
    		* Purpose : Fixed income doesn't store Allocated Amount in Allocation__c 
    			and Fixed Income is treated as individual Record so cannot Add its Total Assets as done in above Aggregate function.
    			Created new function wich returns individually allocated Fixed Income list.
            */
            List<GoalInvestmentAssetAssociation__c> goalInvAssetFixedIncomeList=dbSOQL.getListFixedIncomeInvestmentAssetsForEmergencyFund(entityId);
            
            system.debug('=========goalInvAsset =='+goalInvAsset );
            if(goalInvAsset!=null){
                for(AggregateResult ar:goalInvAsset){
                    EmergencyActionPlanBean apbean= new EmergencyActionPlanBean();
                    if(ar.get('amount')!=null && ar.get('amount')!=0){
                        apbean.Name=(String)ar.get('recordtype');
                        apbean.Owner=(String)ar.get('entity');
                        system.debug('=========apbean.Name =='+apbean.Name );
                       /* if(apbean.Name == 'Fixed Income')
                        {
                        	Double TotalAssets = (Double)ar.get('totalAsset');
                        	Double allocatedAmount = (Double)ar.get('amount');
                        	apbean.Amount= (TotalAssets * allocatedAmount)/100;
                        	system.debug('=======apbean.Amount in if=='+apbean.Amount );
                        }
                        else
                        {	
                        	apbean.Amount=(Double)ar.get('amount');
                        	system.debug('=======apbean.Amount in else=='+apbean.Amount );
                        }*/
                        apbean.Amount=(Double)ar.get('amount');
                        apbean.Action=(String)ar.get('action');
                        apbean.ObjectName=Label.Investment_Asset;
                        beanList.add(apbean);
                    }
                }
           	}  
	         for(GoalInvestmentAssetAssociation__c objFixedIncome : goalInvAssetFixedIncomeList)
	         {
	         	 EmergencyActionPlanBean apbean= new EmergencyActionPlanBean();
	         	 apbean.Name = objFixedIncome.Investment_Asset__r.RecordType.Name;
	             apbean.Owner = objFixedIncome.Investment_Asset__r.Entity__r.Name;
	             system.debug('=========apbean.Name =='+apbean.Name );
	               /* if(apbean.Name == 'Fixed Income')
	                {
	                	Double TotalAssets = (Double)ar.get('totalAsset');
	                	Double allocatedAmount = (Double)ar.get('amount');
	                	apbean.Amount= (TotalAssets * allocatedAmount)/100;
	                	system.debug('=======apbean.Amount in if=='+apbean.Amount );
	                }
	                else
	                {	
	                	apbean.Amount=(Double)ar.get('amount');
	                	system.debug('=======apbean.Amount in else=='+apbean.Amount );
	                }*/
	             Double TotalAssets = objFixedIncome.Investment_asset__r.TotalAsset__c;
	        	 Double allocatedAmount = objFixedIncome.allocated__c; 
	        	 apbean.Amount = (TotalAssets * allocatedAmount)/100;
	             apbean.Action = objFixedIncome.Investment_Asset__r.EmergencyFundAction__c;
	             apbean.ObjectName=Label.Investment_Asset;
	             beanList.add(apbean);
	         }
           
        }
        catch(System.Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage())); 
        }
    }
    
    /**
    * save() function saves the action to be taken
    * param:id of particular Account (Entity),List<EmergencyActionPlanBean>
    * returns:void
    */
    public void save(String entityId,List<EmergencyActionPlanBean> beanList){
        try{
            List<Insurance__c> insuranceList=new List<Insurance__c>();
            List<Asset__c> assetList=new List<Asset__c>();
            List<Investment_Asset__c> invassetList=new List<Investment_Asset__c>();
    
            List<Insurance__c> insurances=dbSOQL.getInsurancesForEmergencyFund(entityId);
            system.debug('==insurances=='+insurances);
            List<Asset__c> assets=dbSOQL.getAssetsForEmergencyFund(entityId);
            system.debug('==assets=='+assets);
            List<Investment_Asset__c> investmentassets=dbSOQL.getInvestmentAssetsForEmergencyFund(entityId);
            system.debug('==investmentassets=='+investmentassets );
            /** Eternus Solutions     **/
			/** Author  : Manasi Ranade **/
			/** Issue Id: 00001486    **/
			/** Date    : 31/1/2012   **/
			/** Purpose : Added code to avoid duplication in the list while upserting it to the database
			/****************************************************/
            Set<String> checkDuplicateInsuranceSet = new Set<string>();
            Set<String> checkDuplicateAssetSet = new Set<string>();
            Set<String> checkDuplicateInvAssetSet = new Set<string>();
    
            for(EmergencyActionPlanBean bean: beanList){
                if(bean.ObjectName==Label.Insurance && bean.Action!=null){
                	//00001486 //Added code to avoid duplication in the list while upserting it to the database
                    for(Insurance__c insurance: insurances){
                        if(insurance.Entity__r.Name==bean.Owner && insurance.RecordType.Name==bean.Name && !checkDuplicateInsuranceSet.contains(insurance.id)){
                            insurance.EmergencyFundAction__c=bean.Action;
                            system.debug('==insuranceLis=='+insurance);
                            //00001486 //Added code to avoid duplication in the list while upserting it to the database
                            insuranceList.add(insurance);
                            checkDuplicateInsuranceSet.add(insurance.Id);
                        }    
                    }
                }
                if(bean.ObjectName==Label.Asset && bean.Action!=null){
                    for(Asset__c asset: assets){
                    	//00001486 //Added code to avoid duplication in the list while upserting it to the database
                        if( asset.Entity__r.Name==bean.Owner && (asset.Asset_Types__c==bean.Name || asset.Account_Type__c==bean.Name) 
                        					&& !checkDuplicateAssetSet.contains(asset.id)){
                            asset.EmergencyFundAction__c=bean.Action;
                            system.debug('==assetList=='+asset);
                            //00001486 //Added code to avoid duplication in the list while upserting it to the database
                            assetList.add(asset);
                            checkDuplicateAssetSet.add(asset.id);
                        }    
                    }
                }
                if(bean.ObjectName==Label.Investment_Asset && bean.Action!=null){
                	//00001486 //Added code to avoid duplication in the list while upserting it to the database
                    for(Investment_Asset__c invasset: investmentassets){
                        if(invasset.Entity__r.Name==bean.Owner && invasset.RecordType.Name==bean.Name && !checkDuplicateInvAssetSet.contains(invasset.id)){
                            invasset.EmergencyFundAction__c=bean.Action;
                            system.debug('==invassetList=='+invasset);
                            //00001486 //Added code to avoid duplication in the list while upserting it to the database
                            invassetList.add(invasset);
                            checkDuplicateInvAssetSet.add(invasset.id);
                        }    
                    }
                }
            }
            dbDML.upsertObject(assetList);
            dbDML.upsertObject(invassetList);
            dbDML.upsertObject(insuranceList);
        }
        catch(System.Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, e.getMessage())); 
        }
    }
}