Freedom Sanbox Ant Deploy/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Discontinuation_SMS_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Discontinuation SMS Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Entity_Status__c</fullName>
        <label>Entity Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Passive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pathfinder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Very Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestSendDiscontinuatonSMS.cls
public class TestSendDiscontinuatonSMS 
{
	@isTest(SeeAllData = true)
    static void testDiscontinueSMS() 
    {
        List<Account> accounts;
	
    	/*Account acc = new Account(FirstName='Test_Fname1',LastName='Test_Renewal_Lname',Entity_Status__c='Active',Discontinuation_SMS_Sent__c=false,PersonMobilePhone='9876543210');

		insert acc;
		accounts= [select Id,Discontinuation_SMS_Sent__c from Account where LastName = 'Test_Renewal_Lname'];
		accounts[0].Discontinuation_SMS_Sent__c=true;
		update accounts[0];*/
    }
}