Freedom Sanbox Ant Deploy/src/objects/Advisory__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Contains roles of users which are Financial Advisors</description>
    <label>Advisory</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Member_Engagement__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Member Engagement</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Tech__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>Tech</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Workstation__c.object
<CustomObject>
    <fields>
        <fullName>Advisory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Financial adviser of FP</description>
        <label>Advisory</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Business_Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Developer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compliance__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Compliance</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financial_Planner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Planner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Engagement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Engagement</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operations__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Operations</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Workstations (Operations)</relationshipLabel>
        <relationshipName>Workstations7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tech__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tech</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Workstations5</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Workstation</label>
    <nameField>
        <displayFormat>WS-{0000}</displayFormat>
        <label>Workstation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workstations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ViewWorkstationController.cls
/********************************************************************************************************** 
           Eternus Solutions 
		   Author  : Dipak Nikam
		   Date    : 15/09/2011
		   Purpose : Controller for View all workstation functionality .
		   Summary :  	
		   
		   Eternus Solutions 
		   Author  : Mahesh Hirugade
		   Date    : 09/02/2012
		   Purpose : To add new field "Advisor" to workstation object.
		   Summary : According to workstation hierarchy and assignment sheet sent by Swati Thakkar, new field "Advisory" is added to Workstation object.
		   			 So added w.Advisory__c and w.Advisory__r.Name fields to query to show on page, and shown this field on ViewAllWorkstations page.
		   			 
		   Eternus Solutions 
		   Author  : Anupam Agrawal
		   Date    : 28/12/2012
		   Purpose : To add new field "Operations" to workstation object.
		   Summary : 			 
		*********************************************************************************************************/



public with sharing class ViewWorkstationController 
{
	public List<Workstation__c> lstWorkstations {get;set;}
	public String Wid{set;get;}
	public ViewWorkstationController()
	{
		lstWorkstations = new List<Workstation__c> ();
	}
	
	
	public void Init()
	{
		lstWorkstations = [Select Tech__c,
	   							 Tech__r.Name, 
	   							 Name, 
							     Member_Engagement__c,
							     Member_Engagement__r.Name, 
							     Manager__c, 
							     Location__c, Id, 
							     Compliance__c, 
							     Compliance__r.Name,
							     Business_Developer__c,
							     Business_Developer__r.Name,
							     Advisory__c,
							     Advisory__r.Name,
							     Manager__r.Name,
							     Financial_Planner__c ,
							     Financial_Planner__r.Name,
							     Operations__c,
							     Operations__r.Name 
							     From Workstation__c 
							     Order By Financial_Planner__r.Name];
	}
	
	public Pagereference Close()
	{
		Pagereference pgRef = new Pagereference('/apex/WorkstationModel');
		pgRef.setRedirect(true);
		return pgRef;
	}
	
	public Pagereference CreateWorkstation()
	{
		Pagereference pgRef = new Pagereference('/apex/CreateWorkstation');
		pgRef.setRedirect(true);
		return pgRef;
	}
	
	public Pagereference Edit()
	{
		Pagereference pgRef = null;
		System.debug('Workstation Id======='+Wid);
		Wid = ApexPages.currentPage().getParameters().get('Wid');
		System.debug('Workstation Id======='+Wid);
		
		if(Wid != null && Wid != '')
		{
			pgRef = new Pagereference('/apex/EditWorkstation?wid='+Wid);
		}
		return pgRef;
	}
	
}