Freedom Sanbox Ant Deploy/src/objects/Approve_Action_Plan__c.object
<CustomObject>
    <description>Created for new action plan</description>
    <label>Approve Action Plan</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approve Action Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Action_Amount__c</fullName>
        <label>Actual Action Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agreed_Amount_Base_Amount__c</fullName>
        <label>Agreed Amount Base Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Agreed_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Agreed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>Opened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Provided to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forms Handed over to Ops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approve_Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approve Action Plan</label>
        <referenceTo>Approve_Action_Plan__c</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Balance_Remaining__c</fullName>
        <formula>Agreed_Amount__c -  Executed_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ET_Status__c</fullName>
        <label>ET Status</label>
        <picklist>
            <picklistValues>
                <fullName>Assigned to MET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned to Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Executed_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Executed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Executed_Product_Name__c</fullName>
        <label>Executed Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentExecutionTracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Tracker</label>
        <referenceTo>Execution_Tracker__c</referenceTo>
        <relationshipLabel>Related Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Suggested_Amount__c</fullName>
        <label>Suggested Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sum_Assured__c</fullName>
        <label>Sum Assured</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Remaining_Balance__c</fullName>
        <label>Total Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surrender Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/RelatedExecutionTrackerController.cls
/* 
    Version     Version Author     Date          Comments
    1.0         Aditi         28/04/2013     Display Closed and Rejected ET records on Entity detail page
*/
public class RelatedExecutionTrackerController 
{
	public List<Execution_Tracker__c> lstExecutionTracker {get;set;}
	private String strApproveActionPlanId;
	private String strType;
	public Boolean displayInsuranceFields {get;set;}
	public Boolean displayOtherProductsFields {get;set;}
	
	public RelatedExecutionTrackerController()
	{
		displayInsuranceFields = false;
		displayOtherProductsFields = false;	
		strApproveActionPlanId = Apexpages.currentPage().getParameters().get('apid');
		strType = Apexpages.currentPage().getParameters().get('type');
		Execution_Tracker__c objET = new Execution_Tracker__c();
		system.debug('***strType****'+strType);
		
		/*if(strType == 'Lumpsum' || strType == 'SIP')
			objET = [Select Id from Execution_Tracker__c where ParentExecutionTracker__c = null and Approve_Action_Plan__c =:strApproveActionPlanId
			      	  					and Type__c =: strType limit 1];
		else 
			objET = [Select Id from Execution_Tracker__c where ParentExecutionTracker__c = null and Approve_Action_Plan__c =:strApproveActionPlanId];
			 system.debug('***objET****'+objET);*/
			
		lstExecutionTracker = [Select Id,Name,CreatedDate, Executed_Product_Name__c, Agreed_Amount_Base_Amount__c,Balance_Remaining__c,Total_Remaining_Balance__c,
								Agreed_Amount__c,Type__c,Actual_Action_Amount__c,ET_Status__c, Owner__c,
								Suggested_Amount__c, Executed_Amount__c, Application_Status__c,Sum_Assured__c 
								from Execution_Tracker__c where Approve_Action_Plan__c =:strApproveActionPlanId and Type__c =: strType
								//and (ParentExecutionTracker__c =: objET.Id 
								//OR Id =: objET.Id) 
								order by CreatedDate];
	   
	    system.debug('-lstExecutionTracker--'+lstExecutionTracker);
	    if(strType == Label.Surrender_Insurance)
	    	displayInsuranceFields = true;
	    if(strType == 'Loan' || strType == 'Fixed Deposit' || strType == 'Bond')
	    	displayOtherProductsFields = true;	
		/*if(strType == 'Lumpsum' || strType == 'SIP')
			objET = [Select Id from Execution_Tracker__c where ParentExecutionTracker__c = null and Approve_Action_Plan__c =:strApproveActionPlanId
			      	  					and Type__c =: strType limit 1];
		else 
			objET = [Select Id from Execution_Tracker__c where ParentExecutionTracker__c = null and Approve_Action_Plan__c =:strApproveActionPlanId];
			      	  					
			      	  					 
		lstExecutionTracker = [Select Name, Executed_Product_Name__c, Agreed_Amount_Base_Amount__c,Balance_Remaining__c,Agreed_Amount__c,Type__c,Actual_Action_Amount__c,
								Suggested_Amount__c, Executed_Amount__c, Application_Status__c,Sum_Assured__c,
								ET_Status__c, Owner__c from Execution_Tracker__c where 	ParentExecutionTracker__c =: objET.Id 
								OR Id =: objET.Id order by createdDate];*/
	}
}