Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold (Align to goal)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <label>Allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalAssetAssociation</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>G Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInsuranceAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Insurance</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <referenceTo>Insurance__c</referenceTo>
        <relationshipLabel>Goal</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>allocated__c</fullName>
        <label>allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>GoalInsuranceAssociation</label>
    <nameField>
        <displayFormat>GI-{0000}</displayFormat>
        <label>GoalInsuranceAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInsuranceAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInvestmentAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <description>Mapping with Goal object</description>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>InvestmentAssets</relationshipLabel>
        <relationshipName>GoalMapping</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Investment_Asset__c</fullName>
        <description>Investment asset relation</description>
        <label>Investment Asset</label>
        <referenceTo>Investment_Asset__c</referenceTo>
        <relationshipLabel>GoalInvestmentAssetAssociations</relationshipLabel>
        <relationshipName>InvestmentAssetMapping</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>GoalInvestmentAssetAssociation</label>
    <nameField>
        <displayFormat>GIAA-{0000}</displayFormat>
        <label>GoalInvestmentAssetAssociationId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInvestmentAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>To be grown till maturity and continue saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>To be grown till maturity but stop saving more</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (Align to goal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liquidate (sell)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold (Align to goal)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InvestmentAsset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <label>InvestmentAsset</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/AssetAllocationBean.cls
/*
	Revision History:
	2.0         Niket              14/06/2011   Added the one property in AssetDetailBean Class
												String AssetType; 
												Summary : This property holds the Asset type for the portfolio 
												calculation.
	2.0         Mahesh             14/06/2011   1.  Added the one property in AssetDetailBean Class
													String Description; 
													Summary : This property holds the Description of all Asset Types to show on Asset Allocation Page
												2. Added new parameter named as Description to populateAssetDetailList()
												
*/

/*
	This bean is to provide single interface to handle  association  between asset and Goal on Asset Allocation.
	Possible combinations are
	Goal Asset Association
	Goal Insurance Association
	Goal Invesmtnet Asset Association	 
*/
public class AssetAllocationBean 
{ 
    public MAP<ID,Asset__c> assetMap 
    { 
        get {
            if(assetMap == null) {
                assetMap = new Map<ID, Asset__c>();                                              
            }
            return assetMap;
        }
        set;
    }                                       
    // We are using record Type here                                
    public Map<String, List<Investment_Asset__c>> investmentAssetMap {get;set;}
    public Map<ID, Insurance__c> insuranceMap { get;set;}    
    // ID will be Goal ID
    public Map<ID, List<GoalAssetAssociation__c>> goalAssetAssociationMap {get;set;}
    public Map<ID, List<GoalInvestmentAssetAssociation__c>> goalInvAssetAssociationMap {get;set;}
    public Map<ID, List<GoalInsuranceAssociation__c>> goalInsuranceAssociationMap {get;set;}
    
    
    public List<AssetRecordTypeBean> assetRecordTypeBeanList 
    { 
        get 
        {
            if(assetRecordTypeBeanList == null)
            {
                assetRecordTypeBeanList = new List<AssetRecordTypeBean>();
            }
            return assetRecordTypeBeanList;
        }   
        set;
   
	}
    public List<String> headerList 
    {
        get {
                if(headerList== null) {
                    headerList = new List<String>();
                   /* headerList.add('Assets');
                    headerList.add('Current Value');
                    headerList.add('Availaible');
                    headerList.add('Allocated');
                    headerList.add('Balance Remaining'); */                                                                                   
                }   
                return headerList;
        }
        set;
    }
    
    /*private void updateAssetRelatedData(AssetRecordTypeBean assetRecord , AssetTypeBean assetTypeBean , AssetDetailBean detailedBean) {
        InvestmentAsset__c assetObj;
        assetObj = assetMap.get(detailedBean.assetId);
        
        assetObj = assetMap.get(detailedBean.assetId);
        assetObj.Action__c = detailedBean.action;
                                                                                
        for(GoalAssetMapping goalAssetMapping :detailedBean.goalAssetMappingList) {

            goalAsetAssociationList =  goalAssetAssociationMap.get(goalAssetMapping.goalId);            
            recordInDbFlag = false;
            
            for(GoalAssetAssociation__c goalAssetAssociation : goalAsetAssociationList) {
                if(detailedBean.assetId.equals(goalAssetAssociation.Asset__c)){
                    goalAssetAssociation.Allocated__c = goalAssetMapping.assetallocated;
                    recordInDbFlag = true;
                }       
            }
            if((!recordInDbFlag) && (goalAssetMapping.assetAllocated >0)) {             
                GoalAssetAssociation__c goalAssetAssociation = new GoalAssetAssociation__c();
                goalAssetAssociation.Goal__c = goalAssetMapping.goalId;
                goalAssetAssociation.Asset__c = detailedBean.assetId;
                goalAssetAssociation.Allocated__c = goalAssetMapping.assetAllocated;                                                                                                            
            }               
        }               
    }           
    public void updateAllList()  {              
        for(AssetRecordTypeBean assetRecord : assetRecordTypeBeanList) {
            for(AssetTypeBean assetTypeBean : assetRecord.assetTypeList) {
                for(AssetDetailBean detailedBean : assetTypeBean.assetDetailList) {                 
                    if('Asset'.equals(assetRecord.parentType)) {
                        updateAssetRelatedData(assetRecord,assetTypeBean,detailedBean);
                    }                   
                }   
            }
        }                               
    } */
    // This method is to add a new RecordType Bean in list
    public AssetRecordTypeBean populateRecordTypeBeanList(String parentType,String recordType) 
    {
        AssetRecordTypeBean bean = new AssetRecordTypeBean();
        bean.parentType = parentType;
        bean.recordTypeName = recordType;
        bean.index = assetRecordTypeBeanList.size();
        assetRecordTypeBeanList.add(bean);
        return bean;
    }
    
    /*
    	This class is being used to show Asset ALlocation page based on record type. It is being used to separate Assets on record Type basis.
    */
    public class AssetRecordTypeBean 
    {
        public Integer index {get;set;}
        public String parentType;
        public String recordTypeName {get; set;}
        public List<AssetTypeBean>  assetTypeList 
        { 
        	get
        	{
	            if(assetTypeList == null)
	            {
	                assetTypeList = new List<AssetTypeBean>();
	            }
	            return assetTypeList;
	        }
	        set;
        }
        
        public AssetTypeBean populateAssetTypeBeanList(String assetTypeName) 
        {
        	AssetTypeBean assetTypeBean = new AssetTypeBean();
            assetTypeBean.assetTypeName = assetTypeName;
            assetTypeBean.index = assetTypeList.size();
            assetTypeList.add(assetTypeBean);
            return  assetTypeBean;  
        }
    }
    
    /*
    	This class is to have one more layer of classification of assets.
    */
    public class AssetTypeBean 
    {
        public Integer index {get;set;}
        public String assetTypeName {get;set;}
        public List<AssetDetailBean>  assetDetailList 
        {
        	get 
        	{
                if(assetDetailList==null) 
                {
                    assetDetailList = new List<AssetDetailBean>();
                }
                return assetDetailList;
            }
            set;
        }
        
        public AssetDetailBean populateAssetDetailList(String entityName, String Description, Double assetCurrentValue,String action,ID assetId)
        {
        	AssetDetailBean bean = new AssetDetailBean();
            bean.entityName = entityName;
            bean.assetCurrentValue = assetCurrentValue;
            bean.action = action;
            bean.assetId = assetId; 
            bean.index  = assetDetailList.size();
            bean.Description = Description;
            assetDetailList.add(bean);
            return bean;
        }
    }
    /*
    	This class is holding current asset amount and entity details 
    */
    
    /*
    	Modified By : Niket Chandane.
    	Modified At : 14 June 2011
    	Summary     :  Added one property "AssetType" Which hold the Assetstype ie. 
    				   Equity or Debt and this property is used in the Portfolio summary.
    */
    public class AssetDetailBean 
    {
        public Integer index {get;set;}
        public Double assetCurrentValue { get;set;}
        public String entityName { get;set;}
        public String entityId 	{ get;set;}
        public String AssetType{get;set;} // Property Created By : Niket Chandane for the Portfolio calculation Isuue.
        public String Description{get;set;} // Property created by Mahesh to show Asset Description on New Asset Allocation Page
        public String allocatedPercent 
        {
			get 
			{
                if(allocatedPercent== null) 
                    allocatedPercent = '0';
                return allocatedPercent;
            }
            set;
       }
     /*   public List<SelectOption> actionList {get {                             
                                                    List<SelectOption> options = new List<SelectOption>();      
                                                    Schema.DescribeFieldResult fieldResult = Asset__c.Action__c.getDescribe();
                                                    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                                                    options.add(new SelectOption('---None----','---None----'));                                                    
                                                    for(Schema.PicklistEntry f : ple) {
                                                        options.add(new SelectOption(f.getLabel(), f.getValue()));
                                                    }       
                                                    return options;                                             
                                            }
                                            set;
                                        }*/
        // To show Action list for each asset
        public List<SelectOption> actionList{get;set;}
        // It is for calculation purpose
        public Decimal availablePercent 
        {
            get 
            {
                if(allocatedPercent != null)
                    return  (100- Decimal.valueof(allocatedPercent));
                else 
                    return 100;
            }
            set;
        }
        
        // It is for calculation purpose
        public Double balance 
        {
                get 
                {
                    if(allocatedPercent != null) 
                        return ( assetCurrentValue * ((100- Decimal.valueof(allocatedPercent)) / 100 ));
                    else 
                        return  assetCurrentValue;
                }
                set;
        }
        public String action { get; set;}
        public ID assetId {get;set;}
        
        public List<GoalAssetMapping>  goalAssetMappingList 
        {
        	get {
                    if(goalAssetMappingList == null) 
                        goalAssetMappingList = new List<GoalAssetMapping>();
                    return goalAssetMappingList;
                } 
            set;
        }
        
        public GoalAssetMapping populateGoalAssetMappingList(ID goalId,String assetAllocated) 
        {
            GoalAssetMapping bean = new GoalAssetMapping();
            bean.index = goalAssetMappingList.size();
            bean.goalId = goalId;
            bean.assetAllocated = assetAllocated;
            goalAssetMappingList.add(bean);
            system.debug('*****goalAssetMappingList*****'+goalAssetMappingList);
            return bean;
        }
        
		public void populateGoalAssetMappingList(GoalAssetMapping mappingBean) 
		{            
            mappingBean.index = goalAssetMappingList.size();
            goalAssetMappingList.add(mappingBean);
    }   
    }   
    
    public class GoalAssetMapping 
    {
        public Integer index {get;set;}
        public ID goalId {get;set;} 
        public String goalAssetAssociationId;                    
        public Decimal goldAllocatedPercent { get;set;}
        public Decimal debtAllocatedPercent {get;set;}
        public Decimal equityAllocatedPercent {get;set;}
        public String assetAllocated 
        {
            get 
            {
                if(assetAllocated == null)
                    assetAllocated = '';                                                
                return assetAllocated;
            }
            set;
        }
    }
    
}