Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Types__c</fullName>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>EPF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gratuity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Superannuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Saving Certificate (NSC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kisan Vikas Patra (KVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indra Vikas Patra / Others (IVP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Income Plan (MIP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Recurring Deposit (RD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Office Time Deposit (FD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Provident Fund (PPF)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Citizens Savings Scheme (SCSS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings A/c</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash in hand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Proprietorship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LLP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Limited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jewelry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement Accounts</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Categories__c</fullName>
        <label>Categories</label>
        <picklist>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/AssetRecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AssetRecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalAssetAssociation</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>G Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalIAULIPAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Current_Value__c</fullName>
        <formula>Portfolio_Report__r.Current_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Investment Assets &amp; ULIP</relationshipLabel>
        <relationshipName>GoalIAULIPAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Portfolio_Report__c</fullName>
        <label>Investment Assets &amp; ULIP</label>
        <referenceTo>Portfolio_Report__c</referenceTo>
        <relationshipLabel>Investment Assets &amp; ULIP</relationshipLabel>
        <relationshipName>GoalIAULIPAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>GoalIAULIPAssociation</label>
    <nameField>
        <displayFormat>GU-{0000}</displayFormat>
        <label>GoalIAULIPAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalIAULIPAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInsuranceAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Insurance</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <referenceTo>Insurance__c</referenceTo>
        <relationshipLabel>Goal</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalInsuranceAssociation</label>
    <nameField>
        <displayFormat>GI-{0000}</displayFormat>
        <label>GoalInsuranceAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInsuranceAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Categories__c</fullName>
        <label>Categories</label>
        <picklist>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sum_Assured_Rs__c</fullName>
        <label>Sum Assured (Rs.)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Portfolio_Report__c.object
<CustomObject>
    <fields>
        <fullName>Categories__c</fullName>
        <formula>CASE( Asset_Class__c ,
&quot;Debt: Floating Rate&quot;, &quot;Debt&quot;,
&quot;Debt: Liquid Plus&quot;, &quot;Debt&quot;,
&quot;Debt: Medium Term&quot;, &quot;Debt&quot;, 
&quot;Debt: Short Term&quot;, &quot;Debt&quot;, 
&quot;Debt: Ultra Short Term&quot;, &quot;Debt&quot;, 
&quot;Equity: Tax Planning&quot;, &quot;Equity&quot;,
&quot;Hybrid: Monthly Income&quot;, &quot;Debt&quot;,
&quot;ULIP&quot;, &quot;Equity&quot;,
&quot;Hybrid: Equity Oriented&quot;, &quot;Equity&quot;,
&quot;Equity : Shares&quot;, &quot;Equity&quot;,
&quot;Equity: Diversified&quot;, &quot;Equity&quot;,
&quot;None&quot;)</formula>
        <label>Categories</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Value__c</fullName>
        <label>Current Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Portfolio Report</relationshipLabel>
        <relationshipName>Portfolio_Report</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Portfolio_Type__c</fullName>
        <label>Portfolio Type</label>
        <picklist>
            <picklistValues>
                <fullName>EQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scheme_Scrip_Name__c</fullName>
        <label>Scheme/Scrip Name</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>NOR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SWI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Portfolio Report</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Portfolio Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Report</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestGoalAllocationController.cls
@isTest
private class TestGoalAllocationController 
{

	static Account act ; 
    static testMethod void testGoalAllocation() 
    {
    	
    	List<Asset__c> AllAssets = new List<Asset__c>();
        List<Portfolio_Report__c> AllPortfolios = new List<Portfolio_Report__c>();
        List<Insurance__c> AllInsurances = new List<Insurance__c>();
        List<Goal__c> AllGoals = new List<Goal__c>();
          
        Double d=10;
          
        List<GoalAllocationController.Assets> AssetsList=new  List<GoalAllocationController.Assets>();
        List<GoalAllocationController.Insurances> InsurancesList=new  List<GoalAllocationController.Insurances>();
        List<GoalAllocationController.InvestmentAssets> SIPList=new  List<GoalAllocationController.InvestmentAssets>();
        List<GoalAllocationController.InvestmentAssets> InvestmentAssetsList=new  List<GoalAllocationController.InvestmentAssets>();
          
        List<GoalAssetAssociation__c> GoalAssetAssociationsList=new  List<GoalAssetAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsList=new  List<GoalIAULIPAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsSIPList=new  List<GoalIAULIPAssociation__c>();
        List<GoalInsuranceAssociation__c> GoalInsuranceAssociationsList=new  List<GoalInsuranceAssociation__c>();
           
        List<GoalAssetAssociation__c> GoalAssetAssociationsList1=new  List<GoalAssetAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsList1=new  List<GoalIAULIPAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsSIPList1=new  List<GoalIAULIPAssociation__c>();
        List<GoalInsuranceAssociation__c> GoalInsuranceAssociationsList1=new  List<GoalInsuranceAssociation__c>();
        
       
        TestData_Ffreedom testData = new TestData_Ffreedom();
		act = testData.initializeAccount();   
        insert act;
        
        Account child = testData.init_FamilyMember(act);
        insert child;   
        
        Goal_Profile__c goalProfile = testData.initialize_GoalProfile(act, 'Aggressive', 'Customized');
      	insert goalProfile;
      	
      	Goal__c goal1 = testData.initialize_Goal(act, 'Education', goalProfile);
      	AllGoals.add(goal1);
      	Goal__c goal2 = testData.initialize_Goal(act, 'Marriage', goalProfile);
    	AllGoals.add(goal2);
        Goal__c goal3 = testData.initialize_Goal(act, 'House', goalProfile);
    	AllGoals.add(goal3);            
        insert AllGoals;      
   	    
		Asset__c asset1 = testData.initialize_Asset(act, 'Land', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');   	     	  
    	AllAssets.add(asset1); 
    	Asset__c asset2 = testData.initialize_Asset(act, 'Vehicles', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset2);
    	Asset__c asset3 = testData.initialize_Asset(act, 'Other', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset3);  
    	Asset__c asset4 = testData.initialize_Asset(act, 'Vacation Home', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset4);
    	Asset__c asset5 = testData.initialize_Asset(act, 'Jewelry', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset5);
    	//Asset__c childAsset = testData.initialize_Asset(child, 'Jewelry', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	Asset__c childAsset = new Asset__c(Entity__c= child.Id, Asset_Types__c='Jewelry', Current_Value__c=1000,Categories__c='Gold');
    	AllAssets.add(childAsset);        	    	  
    	insert AllAssets;
    	
    	for(Goal__c g: AllGoals)
    	{
    	 	for(Asset__c a: AllAssets)
    	 	{
    	 		GoalAssetAssociation__c g1 = testData.intialize_GoalAssetAssociation(a, g);
    	 		GoalAssetAssociationsList1.add(g1);
    	 	}
    	}
    	insert GoalAssetAssociationsList1;
    	
    	Portfolio_Report__c port1 = testData.initialize_PortfolioReport(act, 'Birla Sun Life', 'EQ');
    	AllPortfolios.add(port1);
    	Portfolio_Report__c port2 = testData.initialize_PortfolioReport(act, 'Kotak Mahindra', 'MF');
    	AllPortfolios.add(port2);
    	Portfolio_Report__c port3 =  testData.initialize_PortfolioReport(act, 'HDFC', 'NOR');
  		AllPortfolios.add(port3);
  		//Portfolio_Report__c childPortfolio =  testData.initialize_PortfolioReport(child, 'HDFC', 'NOR');
  		Portfolio_Report__c childPortfolio = new Portfolio_Report__c( Entity__c=child.Id, Scheme_Scrip_Name__c='HDFC',Transaction_Type__c='NOR', Current_Value__c=2000,Portfolio_Type__c='EQ');
  		AllPortfolios.add(childPortfolio);	
  		insert AllPortfolios;
  		
  		for(Goal__c g: AllGoals)
  		{
    	 	for(Portfolio_Report__c a: AllPortfolios)
    	 	{
    	 		GoalIAULIPAssociation__c g1 = testData.init_GoalIAULIPAssociation(g, a);
    	 		GoalIAULIPAssociationsList1.add(g1);
    	 	}
    	}
    	insert GoalIAULIPAssociationsList1;	 
  			 
  		Insurance__c ins1 = testData.initialize_Insurance(act);		  			 
  		AllInsurances.add(ins1);
  		Insurance__c ins2 = testData.initialize_Insurance(act);
  		AllInsurances.add(ins2);
  		Insurance__c ins3 = testData.initialize_Insurance(act);
  		AllInsurances.add(ins3);
  		//Insurance__c childInsurance = testData.initialize_Insurance(act);
  		Insurance__c childInsurance = new Insurance__c( Entity__c=child.Id,Sum_Assured_Rs__c=3000,Surrender_Value__c=300,Policy_Type__c='Whole Life',Policy_Number_or_Name__c='abc Insurance Plan',Insurance_Company__c='',Categories__c='Equity');	 
  		AllInsurances.add(childInsurance);	 	 
  		insert AllInsurances;
  		  
  		for(Goal__c g: AllGoals)
  		{
    	 	for(Insurance__c a: AllInsurances){
    	 		GoalInsuranceAssociation__c g1 = testData.initialize_GoalIA(a, g);
    	 		GoalInsuranceAssociationsList1.add(g1);
    	 	}
    	}
    	insert GoalInsuranceAssociationsList1;	 
  		
  		PageReference Currentreference = new PageReference('/apex/Goal_Allocation?Id='+act.Id);
  		
        Test.setCurrentPage(Currentreference);
        GoalAllocationController gac=new GoalAllocationController(); 
                   
        String GoalValue=gac.getGoalValues();                       
            
        AssetsList= gac.getAllocateAssets();
        GoalAssetAssociationsList= AssetsList.get(0).goalList;         
        GoalAssetAssociationsList.get(0).Allocation__c=null;
        gac.id=AssetsList.get(0).assetType.Id;                    
        gac.updateUnallocatedAmount() ;   
          
                 
          GoalAssetAssociationsList.get(0).Allocation__c=100;
          gac.id=AssetsList.get(0).assetType.Id;                    
          gac.updateUnallocatedAmount() ; 
           
          
        //  gac.updateAllocationAsCategories(GoalAssetAssociationsList.get(0),'Assets');
                                       
          InvestmentAssetsList= gac.getAllocateInvestmentAssets();
          GoalIAULIPAssociationsList= InvestmentAssetsList.get(0).goalList;
          GoalIAULIPAssociationsList.get(0).Allocation__c=null;
          gac.id=InvestmentAssetsList.get(0).portfolio.Id;                    
          gac.updateUnallocatedAmountForInvAssets();
          GoalIAULIPAssociationsList.get(0).Allocation__c=200;
          gac.id=InvestmentAssetsList.get(0).portfolio.Id;                    
          gac.updateUnallocatedAmountForInvAssets();
        //  gac.updateAllocationAsCategories(GoalIAULIPAssociationsList.get(0),'InvestmentAssets');             
                                                       
          SIPList= gac.getAllocateSIP();
          GoalIAULIPAssociationsSIPList= SIPList.get(0).goalList;
          GoalIAULIPAssociationsSIPList.get(0).Allocation__c=null;
          gac.id=SIPList.get(0).portfolio.Id;                
          gac.updateUnallocatedAmountForSIP();
          GoalIAULIPAssociationsSIPList.get(0).Allocation__c=200;
          gac.id=SIPList.get(0).portfolio.Id;                
          gac.updateUnallocatedAmountForSIP();
        //  gac.updateAllocationAsCategories(GoalIAULIPAssociationsList.get(0),'InvestmentAssets');       
                                                    
          InsurancesList= gac.getAllocateInsurance();
          GoalInsuranceAssociationsList= InsurancesList.get(0).goalList;
          GoalInsuranceAssociationsList.get(0).Allocation__c=null;
          gac.id=InsurancesList.get(0).insurance.Id;             
          gac.updateUnallocatedAmountForInsurance();
          GoalInsuranceAssociationsList.get(0).Allocation__c=200;
          gac.id=InsurancesList.get(0).insurance.Id;             
          gac.updateUnallocatedAmountForInsurance();
       //   gac.updateAllocationAsCategories(GoalInsuranceAssociationsList.get(0),'Insurances');
       
       
         
         Integer numberOfGoals=gac.getCount();
         PageReference pgRef=gac.updateGoals();
        /// String str=pgRef.getUrl();
       //  System.assertEquals(str,act.id);
         
       //  System.assertEquals(3,numberOfGoals);
               
    }
    
    static testMethod void testGoalAllocationForChild() 
    {
    	/*
    	List<Asset__c> AllAssets = new List<Asset__c>();
        List<Portfolio_Report__c> AllPortfolios = new List<Portfolio_Report__c>();
        List<Insurance__c> AllInsurances = new List<Insurance__c>();
        List<Goal__c> AllGoals = new List<Goal__c>();
          
        Double d=10;
          
        List<GoalAllocationController.Assets> AssetsList=new  List<GoalAllocationController.Assets>();
        List<GoalAllocationController.Insurances> InsurancesList=new  List<GoalAllocationController.Insurances>();
        List<GoalAllocationController.InvestmentAssets> SIPList=new  List<GoalAllocationController.InvestmentAssets>();
        List<GoalAllocationController.InvestmentAssets> InvestmentAssetsList=new  List<GoalAllocationController.InvestmentAssets>();
          
        List<GoalAssetAssociation__c> GoalAssetAssociationsList=new  List<GoalAssetAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsList=new  List<GoalIAULIPAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsSIPList=new  List<GoalIAULIPAssociation__c>();
        List<GoalInsuranceAssociation__c> GoalInsuranceAssociationsList=new  List<GoalInsuranceAssociation__c>();
           
        List<GoalAssetAssociation__c> GoalAssetAssociationsList1=new  List<GoalAssetAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsList1=new  List<GoalIAULIPAssociation__c>();
        List<GoalIAULIPAssociation__c> GoalIAULIPAssociationsSIPList1=new  List<GoalIAULIPAssociation__c>();
        List<GoalInsuranceAssociation__c> GoalInsuranceAssociationsList1=new  List<GoalInsuranceAssociation__c>();
        
        TestData_Ffreedom testData = new TestData_Ffreedom();
	
        Account child = testData.init_FamilyMember(act);
        insert child;   
        
        Goal_Profile__c goalProfile = testData.initialize_GoalProfile(act, 'Aggressive', 'Customized');
      	insert goalProfile;
      	
      	Goal__c goal1 = testData.initialize_Goal(act, 'Education', goalProfile);
      	AllGoals.add(goal1);
      	Goal__c goal2 = testData.initialize_Goal(act, 'Marriage', goalProfile);
    	AllGoals.add(goal2);
        Goal__c goal3 = testData.initialize_Goal(act, 'House', goalProfile);
    	AllGoals.add(goal3);            
        insert AllGoals;      
   	    
		Asset__c asset1 = testData.initialize_Asset(act, 'Land', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');   	     	  
    	AllAssets.add(asset1); 
    	Asset__c asset2 = testData.initialize_Asset(act, 'Vehicles', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset2);
    	Asset__c asset3 = testData.initialize_Asset(act, 'Other', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset3);  
    	Asset__c asset4 = testData.initialize_Asset(act, 'Vacation Home', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset4);
    	Asset__c asset5 = testData.initialize_Asset(act, 'Jewelry', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	AllAssets.add(asset5);
    	//Asset__c childAsset = testData.initialize_Asset(child, 'Jewelry', AssetRecTypes__c.getInstance('Retirement Accounts').RecordTypeId__c, '');
    	Asset__c childAsset = new Asset__c(Entity__c= child.Id, Asset_Types__c='Jewelry', Current_Value__c=1000,Categories__c='Gold');
    	AllAssets.add(childAsset);        	    	  
    	insert AllAssets;
    	
    	for(Goal__c g: AllGoals)
    	{
    	 	for(Asset__c a: AllAssets)
    	 	{
    	 		GoalAssetAssociation__c g1 = testData.intialize_GoalAssetAssociation(a, g);
    	 		GoalAssetAssociationsList1.add(g1);
    	 	}
    	}
    	insert GoalAssetAssociationsList1;
    	
    	Portfolio_Report__c port1 = testData.initialize_PortfolioReport(act, 'Birla Sun Life', 'EQ');
    	AllPortfolios.add(port1);
    	Portfolio_Report__c port2 = testData.initialize_PortfolioReport(act, 'Kotak Mahindra', 'MF');
    	AllPortfolios.add(port2);
    	Portfolio_Report__c port3 =  testData.initialize_PortfolioReport(act, 'HDFC', 'NOR');
  		AllPortfolios.add(port3);
  		//Portfolio_Report__c childPortfolio =  testData.initialize_PortfolioReport(child, 'HDFC', 'NOR');
  		Portfolio_Report__c childPortfolio = new Portfolio_Report__c( Entity__c=child.Id, Scheme_Scrip_Name__c='HDFC',Transaction_Type__c='NOR', Current_Value__c=2000,Portfolio_Type__c='EQ');
  		AllPortfolios.add(childPortfolio);	
  		insert AllPortfolios;
  		
  		for(Goal__c g: AllGoals)
  		{
    	 	for(Portfolio_Report__c a: AllPortfolios)
    	 	{
    	 		GoalIAULIPAssociation__c g1 = testData.init_GoalIAULIPAssociation(g, a);
    	 		GoalIAULIPAssociationsList1.add(g1);
    	 	}
    	}
    	insert GoalIAULIPAssociationsList1;	 
  			 
  		Insurance__c ins1 = testData.initialize_Insurance(act);		  			 
  		AllInsurances.add(ins1);
  		Insurance__c ins2 = testData.initialize_Insurance(act);
  		AllInsurances.add(ins2);
  		Insurance__c ins3 = testData.initialize_Insurance(act);
  		AllInsurances.add(ins3);
  		//Insurance__c childInsurance = testData.initialize_Insurance(act);
  		Insurance__c childInsurance = new Insurance__c( Entity__c=child.Id,Sum_Assured_Rs__c=3000,Surrender_Value__c=300,Policy_Type__c='Whole Life',Policy_Number_or_Name__c='abc Insurance Plan',Insurance_Company__c='',Categories__c='Equity');	 
  		AllInsurances.add(childInsurance);	 	 
  		insert AllInsurances;
  		  
  		for(Goal__c g: AllGoals)
  		{
    	 	for(Insurance__c a: AllInsurances){
    	 		GoalInsuranceAssociation__c g1 = testData.initialize_GoalIA(a, g);
    	 		GoalInsuranceAssociationsList1.add(g1);
    	 	}
    	}
    	insert GoalInsuranceAssociationsList1;	 
  		
  		PageReference Currentreference = new PageReference('/apex/Goal_Allocation?Id='+act.Id);
  		
        Test.setCurrentPage(Currentreference);
        GoalAllocationController gac=new GoalAllocationController(); 
                   
        String GoalValue=gac.getGoalValues();                       
            
        AssetsList= gac.getAllocateAssets();
        GoalAssetAssociationsList= AssetsList.get(0).goalList;         
        GoalAssetAssociationsList.get(0).Allocation__c=null;
        gac.id=AssetsList.get(0).assetType.Id;                    
        gac.updateUnallocatedAmount() ;   
          
                 
          GoalAssetAssociationsList.get(0).Allocation__c=100;
          gac.id=AssetsList.get(0).assetType.Id;                    
          gac.updateUnallocatedAmount() ; 
           
          
        //  gac.updateAllocationAsCategories(GoalAssetAssociationsList.get(0),'Assets');
                                       
          InvestmentAssetsList= gac.getAllocateInvestmentAssets();
          GoalIAULIPAssociationsList= InvestmentAssetsList.get(0).goalList;
          GoalIAULIPAssociationsList.get(0).Allocation__c=null;
          gac.id=InvestmentAssetsList.get(0).portfolio.Id;                    
          gac.updateUnallocatedAmountForInvAssets();
          GoalIAULIPAssociationsList.get(0).Allocation__c=200;
          gac.id=InvestmentAssetsList.get(0).portfolio.Id;                    
          gac.updateUnallocatedAmountForInvAssets();
        //  gac.updateAllocationAsCategories(GoalIAULIPAssociationsList.get(0),'InvestmentAssets');             
                                                       
          SIPList= gac.getAllocateSIP();
          GoalIAULIPAssociationsSIPList= SIPList.get(0).goalList;
          GoalIAULIPAssociationsSIPList.get(0).Allocation__c=null;
          gac.id=SIPList.get(0).portfolio.Id;                
          gac.updateUnallocatedAmountForSIP();
          GoalIAULIPAssociationsSIPList.get(0).Allocation__c=200;
          gac.id=SIPList.get(0).portfolio.Id;                
          gac.updateUnallocatedAmountForSIP();
        //  gac.updateAllocationAsCategories(GoalIAULIPAssociationsList.get(0),'InvestmentAssets');       
                                                    
          InsurancesList= gac.getAllocateInsurance();
          GoalInsuranceAssociationsList= InsurancesList.get(0).goalList;
          GoalInsuranceAssociationsList.get(0).Allocation__c=null;
          gac.id=InsurancesList.get(0).insurance.Id;             
          gac.updateUnallocatedAmountForInsurance();
          GoalInsuranceAssociationsList.get(0).Allocation__c=200;
          gac.id=InsurancesList.get(0).insurance.Id;             
          gac.updateUnallocatedAmountForInsurance();
       //   gac.updateAllocationAsCategories(GoalInsuranceAssociationsList.get(0),'Insurances');
       
       
         
         Integer numberOfGoals=gac.getCount();
         PageReference pgRef=gac.updateGoals();
        /// String str=pgRef.getUrl();
       //  System.assertEquals(str,act.id);
         
    	*/
    	
    }
}