Freedom Sanbox Ant Deploy/src/objects/Asset__c.object
<CustomObject>
    <fields>
        <fullName>EmergencyFundAction__c</fullName>
        <label>EmergencyFundAction</label>
        <type>TextArea</type>
    </fields>
    <label>Asset</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/AssetRecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>AssetRecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal__c.object
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Goal_Profile__c.object
<CustomObject>
    <label>Goal Profile</label>
    <nameField>
        <label>Goal Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Allocated__c</fullName>
        <label>Allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <label>Asset</label>
        <referenceTo>Asset__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Assets</relationshipLabel>
        <relationshipName>GoalAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>GoalAssetAssociation</label>
    <nameField>
        <displayFormat>GA-{0000}</displayFormat>
        <label>G Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInsuranceAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>Insurance</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Insurance__c</fullName>
        <label>Insurance</label>
        <referenceTo>Insurance__c</referenceTo>
        <relationshipLabel>Goal</relationshipLabel>
        <relationshipName>GoalInvestAssetAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>allocated__c</fullName>
        <label>allocated</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>GoalInsuranceAssociation</label>
    <nameField>
        <displayFormat>GI-{0000}</displayFormat>
        <label>GoalInsuranceAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInsuranceAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/GoalInvestmentAssetAssociation__c.object
<CustomObject>
    <fields>
        <fullName>Goal__c</fullName>
        <description>Mapping with Goal object</description>
        <label>Goal</label>
        <referenceTo>Goal__c</referenceTo>
        <relationshipLabel>InvestmentAssets</relationshipLabel>
        <relationshipName>GoalMapping</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Investment_Asset__c</fullName>
        <description>Investment asset relation</description>
        <label>Investment Asset</label>
        <referenceTo>Investment_Asset__c</referenceTo>
        <relationshipLabel>GoalInvestmentAssetAssociations</relationshipLabel>
        <relationshipName>InvestmentAssetMapping</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>allocated__c</fullName>
        <defaultValue>0</defaultValue>
        <label>allocated</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>GoalInvestmentAssetAssociation</label>
    <nameField>
        <displayFormat>GIAA-{0000}</displayFormat>
        <label>GoalInvestmentAssetAssociationId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GoalInvestmentAssetAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>EmergencyFundAction__c</fullName>
        <label>EmergencyFundAction</label>
        <type>TextArea</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>EmergencyFundAction__c</fullName>
        <label>EmergencyFundAction</label>
        <type>TextArea</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Stocks</fullName>
        <active>true</active>
        <label>Stocks</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InvestmentAsset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>InvestmentAsset</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/EmergencyPlanningControllerTest.cls
/*
Revision History:

		Version     Version Author     Date        Comments
		1.0         --           	   --	  	   Initial Draft
		2.0  		Prajakta Sanap     23/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.				   				 					   
*/

@isTest
private class EmergencyPlanningControllerTest 
{
    static Account acc;
    static EmergencyPlanningController emergencyplanning;
    static Investment_Asset__c inv;
    
    static void testData()
    {
    	TestData_Ffreedom testData = new TestData_Ffreedom();
		acc = testData.initializeAccount();
        insert acc;
   
      	system.assertNotEquals(null,acc);
		
		Asset__c asset1 = testData.initialize_Asset(acc, 'EPF', AssetRecTypes__c.getInstance('Real Estate Assets').RecordTypeId__c, '');      
      	asset1.EmergencyFundAction__c = 'no';
      	insert asset1;
      	system.assertNotEquals(null,asset1.id);
      	
      	Goal_Profile__c goalProfile = testData.initialize_GoalProfile(acc, 'Aggressive', 'Customized');
      	insert goalProfile;
      	Goal__c goal2 = testData.initialize_Goal(acc, 'Emergency Fund', goalProfile);
    	insert goal2;
    	system.assertNotEquals(null,goal2.id);
      	
    	Insurance__c  insurance = testData.initialize_Insurance(acc);
      	insert insurance;
      	system.assertNotEquals(null,insurance.id);
      	
      	Goal__c goal3 = testData.initialize_Goal(acc, 'Emergency Fund', goalProfile);
      	insert goal3;
      	system.assertNotEquals(null,goal3.id);
     	
     	inv = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance ('Stocks').RecordTypeId__c);
      	insert inv;
      	system.assertNotEquals(null,inv.id);
      	
      	
      	Goal__c goal4 = testData.initialize_Goal(acc, 'Emergency Fund', goalProfile);
      	insert goal4;
      	system.assertNotEquals(null,goal4.id);
		
		GoalAssetAssociation__c gasset = testData.intialize_GoalAssetAssociation(asset1, goal2);		      
      	insert gasset;
      	system.assertNotEquals(null,gasset.id);
      	
      	GoalInsuranceAssociation__c gasset1 = testData.initialize_GoalIA(insurance, goal3);
      	System.debug('Allocation1s-->' +gasset1.Allocated__c);
      	insert gasset1;
      	system.assertNotEquals(null,gasset1.id);
      	
      	GoalInvestmentAssetAssociation__c gasset2 = testData.init_GoalInvAsset(inv, goal4);
      	insert gasset2;
      	system.assertNotEquals(null,gasset2.id);
      	Apexpages.currentPage().getParameters().put('entityId',acc.id);
      	emergencyplanning=new EmergencyPlanningController();
      	
      	EmergencyActionPlanBean apbean = new EmergencyActionPlanBean();
      	apbean.Action = 'Hold(Align to goal)';
      	apbean.ObjectName = 'Insurance__c';
    }
    
    static testMethod void emergencyPlanningTest1() 
    {
        Test.startTest();
        testData();
        emergencyplanning.save();
        test.stopTest();
    }
        
}