Freedom Sanbox Ant Deploy/src/objects/Checklist__c.object
<CustomObject>
    <fields>
        <fullName>Checklist_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Checklist Template</label>
        <referenceTo>Checklist_Template__c</referenceTo>
        <relationshipLabel>Checklists</relationshipLabel>
        <relationshipName>Checklists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <picklist>
            <controllingField>Stage__c</controllingField>
            <picklistValues>
                <fullName>Prospecting-Initation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educating Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement-Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement-Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment-Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-Collection-Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collection Over stretching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Reivew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Creation-Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DraftPlan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated Account Statement Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client-Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc/ Periodic requirement from the internel team for analysis purpose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual client meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assignment-send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Agreement-signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason of Leaving</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Prospecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Will-Join-Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Reviewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Checklist</label>
    <nameField>
        <displayFormat>CL-{00000000}</displayFormat>
        <label>Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Checklist_Step__c.object
<CustomObject>
    <fields>
        <fullName>Checklist__c</fullName>
        <label>Checklist</label>
        <referenceTo>Checklist__c</referenceTo>
        <relationshipLabel>Checklist Steps</relationshipLabel>
        <relationshipName>Checklist_Steps11</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <picklist>
            <picklistValues>
                <fullName>Prospecting-Initation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educating Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement-Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement-Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment-Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fllow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-Collection-Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collection Over stretching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Reivew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Creation-Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DraftPlan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated Account Statement Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client-Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc/ Periodic requirement from the internel team for analysis purpose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual client meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assignment-send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Agreement-signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason of Leaving</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Will-join-Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan-Reviewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Checklist Step</label>
    <nameField>
        <label>Checklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Checklist_Template__c.object
<CustomObject>
    <fields>
        <fullName>Checklist_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Checklist Template</label>
        <referenceTo>Checklist_Template__c</referenceTo>
        <relationshipLabel>Checklist Template Steps</relationshipLabel>
        <relationshipName>Checklist_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Context__c</fullName>
        <label>Context</label>
        <picklist>
            <controllingField>Stage__c</controllingField>
            <picklistValues>
                <fullName>Prospecting-Initation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educating Client</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement-Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreement-Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment-Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>fllow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-Collection-Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collection Over stretching</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Changes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Reivew</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Creation-Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DraftPlan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Interaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consolidated Account Statement Send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client-Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adhoc/ Periodic requirement from the internel team for analysis purpose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Updated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Half Yearly Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual client meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assignment-send</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal Agreement-signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason of Leaving</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <label>Sequence</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Prospecting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Will-join-Later</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data-Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan_creation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan_Execution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan_Monitoring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan_Reviewing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Customer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Checklist Template</label>
    <nameField>
        <label>Checklist Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Checklist Templates</pluralLabel>
    <recordTypes>
        <fullName>Steps</fullName>
        <active>true</active>
        <description>Check List Steps in the Template</description>
        <label>Steps</label>
    </recordTypes>
    <recordTypes>
        <fullName>Template</fullName>
        <active>true</active>
        <description>Check List Template fields</description>
        <label>Template</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/Freedom.cls
@isTest
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */

private class Freedom {
 /* Test method for freedom project it covers two trigger */
    public static testMethod void myUnitTest() {
        
        /* Deployment : Prajakta Sanap */
        /* Creating a new Checklist and Inserting*/   
     	Checklist_Template__c checkListTemp = new  Checklist_Template__c(Context__c='a', Stage__c='b', Sequence__c=2);
      	insert checkListTemp;
      	
        //  creating a new checklist Template and Inserting 
        Checklist_Template__c cht = [select id, Context__c, Stage__c, Sequence__c
         from Checklist_Template__c limit 1];
        
        /* Creating a new Checklist and Inserting*/ 
        Checklist__c ch = new Checklist__c(Stage__c='prospecting',Checklist_Template__c = cht.Id );
        insert ch;
     
        
        /* creating a new checklist steps and inserting   */
        Checklist_Step__c chs = new Checklist_Step__c(Step_Status__c='Processing', Sequence__c=1,Checklist__c=ch.id);
            insert chs;    
        
        chs.Start_Date__c = System.today();
        update chs;  
                      
        /* creating a new checkliststeps and inserting to it  */
        checkList_Step__c clt = new checkList_Step__c( Name = ch.Name,
            Context__c = chs.Context__c,
            Checklist__c = ch.id,
            Stage__c = chs.Stage__c,
            Sequence__c = chs.Sequence__c,
           
            Step_Status__c = 'Not Started');
            insert clt;
            
        /* Creating a new event and inerting the value on it  */
        Event event = new Event(       
            WhatId = cht.id,
           /* Context__c = cht.Context__c,
            Stage__c = cht.Stage__c,*/
            Subject = 'hello',
            StartDateTime= System.now() + 1,
            EndDateTime=System.now() + 6,
            description = 'hi');
                          
            insert event;  
        
        Task tsk = new Task(       
            WhatId = cht.id,
           /* Context__c = cht.Context__c,
            Stage__c = cht.Stage__c,*/
            Subject = 'hello',
            ActivityDate = System.TODAY() + 1
            //StartDateTime= System.now() + 1,
           // EndDateTime=System.now() + 6,
           // description = 'hi'
            );
                          
            insert tsk;  
      
    }
}