Freedom Sanbox Ant Deploy/src/objects/Commission__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Max Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Year_Value__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Max Year Value</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Min Months</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Year_Value__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Min Year Value</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trail_Commission__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Trail Commission Value should be in Percentage</inlineHelpText>
        <label>Trail Commission</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Upfront_Commission__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Upfront Commission Value should be in Percentage</inlineHelpText>
        <label>Upfront Commission</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Commission</label>
    <nameField>
        <displayFormat>COM-{000000}</displayFormat>
        <label>Commission Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <label>Asset Class</label>
        <picklist>
            <picklistValues>
                <fullName>Small Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBI Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Gains Tax Saving Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Convertible Debentures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Index</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Diversified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Large Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Mid Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Small Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Sectoral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Long Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Medium Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Ultra Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Arbitrage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Asset Allocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Debt Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Equity Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Monthly Income</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Fixed_Income</fullName>
        <active>true</active>
        <label>Fixed Income</label>
    </recordTypes>
    <recordTypes>
        <fullName>Gold</fullName>
        <active>true</active>
        <description>Added regarding new FP changes</description>
        <label>Gold and Silver</label>
    </recordTypes>
    <recordTypes>
        <fullName>Mutual_Fund</fullName>
        <active>true</active>
        <label>Mutual Fund</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stocks</fullName>
        <active>true</active>
        <label>Stocks</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Manufacturer_Master__c.object
<CustomObject>
    <description>Created for product master</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Product Master</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Manufacturer</label>
    <nameField>
        <label>Manufacturer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Manufacturers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Product_Master__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Class__c</fullName>
        <label>Asset Class</label>
        <picklist>
            <picklistValues>
                <fullName>Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Real Estate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Investment_Type__c</fullName>
        <label>Investment Type</label>
        <picklist>
            <controllingField>Asset_Class__c</controllingField>
            <picklistValues>
                <fullName>SIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lumpsum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity MF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt MF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Traditional Insurance Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold ETF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold MF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Scheme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Gold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Land</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REIT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loan Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For Product Master object</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy Type</label>
        <picklist>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Accident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Householder&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whole Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP - Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money-Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP - Equity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Mutual Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exchange-Traded Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FFreedom Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Product</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Added Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bond</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Manufacturer__c</fullName>
        <label>Product Manufacturer</label>
        <referenceTo>Product_Manufacturer_Master__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Product_Master</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <label>Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PRD-{000000}</displayFormat>
        <label>Product Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <recordTypes>
        <fullName>Mutual_Fund</fullName>
        <active>true</active>
        <label>Mutual Fund</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/InvestmentAssetController.cls
/*
    This class is controller for InvestmentAssetPage
*/
public class InvestmentAssetController 
{
    public List<Account> accountList {get; set;}
    public String entityId {get; set;}                
    public String objectName='Investment_Asset__c';
    public String selRecordTypeId {get; set;}    
    public Boolean displayPopUp {get; set;}    
    private String selectedIndexStr,selectedAMCName;
    public FamilyMemberInfoBean fmBean{get;set;}
    public FamilyMemberInfoService fmInfoService{get;set;}
    //Added on : 31/1/2013 : Aditi Satpute : Hide Save button for Business Partner Financial Plan //Sanat
	public Boolean isDisplaySaveButton{get;set;}
	private Map<String,String> mapTypeToProductNames;
	public Boolean isDisplayError{get;set;}
	
    public InvestmentAssetServices investmentAssetServicesInstance 
    {
        get 
        {           
            return investmentAssetServicesInstance ;
        } 
        set;
    }
    
    public InvestmentAssetBean investmentAssetBeanInstance 
    {
        get 
        {                                                                                        
            if(selectedIndexStr != null) 
            {
                InvestmentAssetBean.InvestmentWrapper wrapper = investmentAssetBeanInstance
                                                                    .investmentAssetWrapperList.get(Integer.valueOf(selectedIndexStr));                        
                wrapper.selectedAMCName = selectedAMCName;                
                /*if(selectedIndexStr != null) {
                    wrapper.schemeNameList =investmentAssetServicesInstance.getSchemeNameList(selectedAMCName);
                    wrapper.selectedSchemeName = wrapper.schemeNameList.get(0).getValue();
                }*/
                selectedIndexStr = null;
            }               
            return investmentAssetBeanInstance ;
        } 
        set;
    }                 
    public String recordType{get; set;}
    public final Investment_Asset__c investmentAsset {get; set;}
    public String selRecordTypeName{get; set;}
    public Integer listIndex{get; set;}
    public Investment_Asset__c  investmentInstance{get; set;}
    private List<SelectOption> amcNameList,schemeNameList;
    
    private ActionPlanUtility objActionPlanUtility;
    public String strProductSchemeName{get;set;}
    public Boolean includeHLV {get;set;} /* Prajakta - FP changes - 13-6-13 */
    
    public List<OuterClass> summaryTableList
    { 
    	get 
    	{
            if(summaryTableList == null) 
            {
                summaryTableList = investmentAssetServicesInstance.getSummaryTableList(entityId, accountList);      
            }
            return summaryTableList;
        }
        set;
    }
    
  	/*public List<SelectOption> getSchemeList(){
     		return this.schemeList;
    }*/
  	//Boolean isAddNew = true;
    
    public InvestmentAssetController(ApexPages.StandardController stdController)
    {
    	//Code Added on : 31/1/2013 : Aditi Satpute : Hide Save button for Business Partner Financial Plan : by default true //Sanat
   		isDisplaySaveButton = true;
   		isDisplayError =false;
        investmentAsset = (Investment_Asset__c)stdController.getRecord();
        investmentAssetServicesInstance = new InvestmentAssetServices();
        investmentAssetBeanInstance = new InvestmentAssetBean();        
        entityId = ApexPages.currentPage().getParameters().get('EntityId');
        accountList = investmentAssetServicesInstance.getFamilyDetails(entityId);        
        //amcNameList = investmentAssetServicesInstance.getAMCNameList();
        //schemeNameList = investmentAssetServicesInstance.getSchemeNameList(amcNameList.get(0).getValue());
        //system.debug('schemeNameList==###=='+schemeNameList); 
        fmBean = new FamilyMemberInfoBean();
        fmInfoService = new FamilyMemberInfoService();
        fmInfoService.isCostomerProfile(fmBean);
        recordType = 'null';   
        
        //Added Code on : 31/1/2013 : Aditi Satpute : Hide Save button for Business Partner Financial Plan //Sanat
        User objUser = [Select Profile.Name, ProfileId, UserType, Name, Id From User where Id =: UserInfo.getUserId() limit 1];
        if(objUser.UserType.equalsIgnoreCase('PowerPartner'))
        {
        	isDisplaySaveButton = false;
        }
         /* Gaurav (12-6-2013) :  for Display autocomeple in scheme name*/
        List<Product_Master__c> lstProductMaster = [Select Product_Name__c, Product_Manufacturer__c,Product_Manufacturer__r.Name, ProductType__c,Is_Active__c,
								   Policy_Type__c, Investment_Type__c, Asset_Class__c,
								   	(Select Min_Year_Value__c, Max_Year_Value__c, Min_Months__c, Max_Months__c, 
								   	Upfront_Commission__c, Trail_Commission__c from Commissions__r where Active__c = true)  
								From Product_Master__c Where Is_Active__c = true and Is_Recommended__c = true];
        objActionPlanUtility =  new ActionPlanUtility();
       	strProductSchemeName  = objActionPlanUtility.retrieveInsurance(objActionPlanUtility.getProductType('Mutual Fund',lstProductMaster));
       	mapTypeToProductNames = new Map<String,String>{'Mutual Fund' => strProductSchemeName };
       	/* End changes*/
    } 
    
        
    public void showPopUp() 
    {
        displayPopUp=true;
        if(selRecordTypeId == InvestmentAsset__c.getInstance('Stocks').RecordTypeId__c)
        {
        	system.debug('==========Stocks===========');
            recordType = 'Stocks';
        }
        if(selRecordTypeId == InvestmentAsset__c.getInstance('Mutual Fund').RecordTypeId__c)
        {
            recordType = 'Mutual_Fund';
        }
        if(selRecordTypeId == InvestmentAsset__c.getInstance('Fixed Income').RecordTypeId__c)
        {
            recordType = 'Fixed_Income';
        }
        //Prajakta - FP changes - 25-02-2013
        if(selRecordTypeId == InvestmentAsset__c.getInstance('Gold and Silver').RecordTypeId__c)  /*Prajakta - 24-05-2013 */
        {
        	system.debug('==========Gold===========');
            recordType = Label.Gold_and_Silver;		/*Prajakta - 24-05-2013 */
        }
                     
        if((investmentAssetBeanInstance.investmentAssetWrapperList.isEmpty())) 
        {
            investmentAssetServicesInstance.getInvestmentList(investmentAssetBeanInstance,selRecordTypeId,entityId);
            if(investmentAssetBeanInstance.investmentAssetWrapperList.isEmpty())
            {
                for(Integer i=0;i < 10; i++)
                {        
                    investmentAssetServicesInstance.addRow(investmentAssetBeanInstance,selRecordTypeId, true);
                }
            }
        }                   
    }
    
    //To Add default rows
    public void addNewRow() 
    {
    	/* Prajakta - FP changes - 13-6-13 */
        investmentAssetServicesInstance.addRow(investmentAssetBeanInstance,selRecordTypeId, true);//amcNameList,schemeNameList
        investmentAssetServicesInstance.addRow(investmentAssetBeanInstance,selRecordTypeId, true);
        investmentAssetServicesInstance.addRow(investmentAssetBeanInstance,selRecordTypeId, true); 
    }

    public void closePopUp()
    {
        displayPopUp = false;
        summaryTableList = null;
        investmentAssetBeanInstance.investmentAssetWrapperList = null;
        accountList = investmentAssetServicesInstance.getFamilyDetails(entityId);  
        system.debug('==========accountList========1==='+accountList);      
    }
    
    //To save/update investment asset in db.
    public void save() 
    {
        try 
        {   
        	for(InvestmentAssetBean.InvestmentWrapper objWrapper:  investmentAssetBeanInstance.investmentAssetWrapperList)
        	{
        	/* Gaurav (15-5-2013) : To validate entered product name of Mutual fund is available in Mutual fund  product name list   */ 
              if(objWrapper.investmentAsset.Scheme_Name_Text__c != null && objWrapper.investmentAsset.Scheme_Name_Text__c.trim() != '' &&
              			(recordType=='Mutual_Fund') && !(mapTypeToProductNames.get('Mutual Fund').contains('"'+objWrapper.investmentAsset.Scheme_Name_Text__c+'"')))
              {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, '"'+objWrapper.investmentAsset.Scheme_Name_Text__c+'"'+ ' is not valid Scheme name. '+ Label.EditET_Scheme_Name  ));
                return;
              }  
             /* Enf Changes  */
        		
        	}
        	 
        	investmentAssetServicesInstance.save(investmentAssetBeanInstance,recordType,selRecordTypeId,entityId);                   
            summaryTableList = null;
            investmentAssetBeanInstance.investmentAssetWrapperList = null;
            displayPopUp = false;
            accountList = investmentAssetServicesInstance.getFamilyDetails(entityId);
            system.debug('==========accountList=====save======'+accountList);
        }
        catch(ValidationException e) 
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,e.getMessage()));
        }             
    }
    
    public List<SelectOption> getOwnerItems() 
    {
        investmentAssetBeanInstance.options = investmentAssetServicesInstance.getOwnerItems(entityId,accountList);    
        return investmentAssetBeanInstance.options;
    }  
    
    //This function is called when user clicks remove button
	public void remove()
	{
	    investmentAssetServicesInstance.removeRecords(investmentAssetBeanInstance);                   
 	}  
       
    //Place holder method to update Picklist on edit page.
    public PageReference dummy()
    {
        selectedIndexStr = ApexPages.currentPage().getParameters().get('Index');            
        selectedAMCName = ApexPages.currentPage().getParameters().get('selectedAMCName');               
        return null;
    }
}