Freedom Sanbox Ant Deploy/src/objects/Conveyance_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_Details__c</fullName>
        <label>Bill Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conveyance_Manager__c</fullName>
        <label>Conveyance Manager</label>
        <referenceTo>Conveyance_Manager__c</referenceTo>
        <relationshipLabel>Conveyance_Details</relationshipLabel>
        <relationshipName>Conveyance_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Bill_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Bill Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Conveyance_Detail</label>
    <nameField>
        <label>Conveyance_Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conveyance_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Conveyance_Manager__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Reimbursed__c</fullName>
        <label>Amount Reimbursed</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date_of_Travel__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date of Travel</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Conveyance_Managers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <label>Conveyance</label>
    <nameField>
        <label>Conveyance</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conveyances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Event__c.object
<CustomObject>
    <label>Conveyance Submission</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conveyance Submission</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Remarks__c.object
<CustomObject>
    <description>Space for ‘Remarks’ where the FP can give additional advice.(Except for Goal)</description>
    <label>Remark</label>
    <nameField>
        <label>Remarks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remarks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ConveyanceControllerTest.cls
@isTest
private class ConveyanceControllerTest {
	
	static testmethod void testConveyanceManager(){
		test.startTest();
		/*
		// Use the vf page in my org named 'locatorDetails'
        PageReference pageRef = Page.locatorDetails;
        Test.setCurrentPage(pageRef);

        // Set the id of the current vf page to a Property__c record that I know has child Suite__c and Spec_Sheet__c records
        ApexPages.currentPage().getParameters().put('id', p.Id);
        TestMyPropertyExtension controller = new TestMyPropertyExtension();
		*/
		
		string strCOnManId = ConveyanceControllerTest.CreateTestDate();
		PageReference pageRef = Page.ConveyanceManager;
        Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id', strCOnManId);
		
		ConveyanceController objConveyanceController = new ConveyanceController();
		objConveyanceController.save();
		objConveyanceController.AddMore();
		objConveyanceController.Remove();
		test.stopTest();
	}
	
	static testmethod void testConveyanceManagerSubmit(){
		test.startTest();
		string strConManagerData = ConveyanceControllerTest.CreateTestDate();
		PageReference pageRef = Page.ConveyanceManager;
        Test.setCurrentPage(pageRef);
		ApexPages.currentPage().getParameters().put('id', strConManagerData);
		
		ConveyanceController objConveyanceController = new ConveyanceController();
		objConveyanceController.Submit();
		objConveyanceController.Cancel();
		
		test.stopTest();
	}
	
	static testmethod void testConveyanceManagerConstructor(){
	 test.startTest();
	 	ConveyanceController objConveyanceController = new ConveyanceController();
	 test.stopTest();
	}
	
	private static string CreateTestDate()
	{
		string strManagerId;
		
		Event__c objEvent = New Event__c();
		insert objEvent;
		
		Conveyance_Manager__c objConManager = new Conveyance_Manager__c();
		objConManager.Amount_Reimbursed__c = 10;
		objConManager.Date_of_Travel__c = System.today();
		objConManager.Event__c = objEvent.id;
		objConManager.Remarks__c = 'Test Remark';
		insert objConManager;
		
		Conveyance_Detail__c objDetailPoint = new Conveyance_Detail__c(); 
		objDetailPoint.Amount__c = 1000;
		objDetailPoint.Bill_Details__c = 'Bill Details';
		objDetailPoint.Conveyance_Manager__c = objConManager.id;
		objDetailPoint.Is_Bill_Available__c = true;
		objDetailPoint.Remarks__c = 'My Test Remarks';
		insert objDetailPoint;
		
		Conveyance_Detail__c objDetailPoint2 = new Conveyance_Detail__c(); 
		objDetailPoint2.Amount__c = 1000;
		objDetailPoint2.Bill_Details__c = 'Bill Details';
		objDetailPoint2.Conveyance_Manager__c = objConManager.id;
		objDetailPoint2.Is_Bill_Available__c = true;
		objDetailPoint2.Remarks__c = 'My Test Remarks';
		insert objDetailPoint2;
		
		return objConManager.id;
	}
}