Freedom Sanbox Ant Deploy/src/objects/Conveyance_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bill_Details__c</fullName>
        <label>Bill Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bill_Number__c</fullName>
        <label>Bill Number</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Conveyance_Manager__c</fullName>
        <label>Conveyance Manager</label>
        <referenceTo>Conveyance_Manager__c</referenceTo>
        <relationshipLabel>Conveyance_Details</relationshipLabel>
        <relationshipName>Conveyance_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Is_Bill_Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Bill Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Conveyance_Detail</label>
    <nameField>
        <label>Conveyance_Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conveyance_Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Conveyance_Manager__c.object
<CustomObject>
    <fields>
        <fullName>Amount_Claimed__c</fullName>
        <label>Amount Claimed</label>
        <summarizedField>Conveyance_Detail__c.Amount__c</summarizedField>
        <summaryForeignKey>Conveyance_Detail__c.Conveyance_Manager__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Amount_Reimbursed__c</fullName>
        <label>Amount Reimbursed</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Claim_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Claim Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Travel__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date of Travel</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipName>Conveyance_Managers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the convenance is submitted then this flag set to true.</description>
        <label>Is Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mode_of_Travel__c</fullName>
        <label>Mode of Travel</label>
        <picklist>
            <picklistValues>
                <fullName>Cab</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Train</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Vehicle</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <displayFormat>{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Reimbursement_date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Reimbursement date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Remarks__c</fullName>
        <label>Remarks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Travel_Type__c</fullName>
        <label>Travel Type</label>
        <picklist>
            <picklistValues>
                <fullName>Local</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>National</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Conveyance</label>
    <nameField>
        <label>Conveyance</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conveyances</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <label>Duration</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>End__c</fullName>
        <label>End</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Category__c</fullName>
        <label>Event Category</label>
        <picklist>
            <picklistValues>
                <fullName>Call</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Event_Place__c</fullName>
        <label>Meeting Place</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Status__c</fullName>
        <label>Event Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planned</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Conveyance Submission</label>
    <nameField>
        <label>Event  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conveyance Submission</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Remarks__c.object
<CustomObject>
    <description>Space for ‘Remarks’ where the FP can give additional advice.(Except for Goal)</description>
    <label>Remark</label>
    <nameField>
        <label>Remarks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remarks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ConveyanceController.cls
public with sharing class ConveyanceController 
{
	//public Conveyance_Manager__c objConveyanceManager;
	public Conveyance_Manager__c objConveyanceManager{get;set;}
	public Conveyance_Manager__c tmpConveyanceManager{get;set;}
	//public Conveyance_Detail__c objConveyanceDetail{set; get;}
	public Integer icount{set; get;}
	//Database.Saveresult saveResult = null;
	public List<ConveyanceDetails> lstConveyanceInfo {get;set;}
	public String BillingDescription{set; get;}
	public Boolean flag{set; get;}
	public Boolean ipflagShow{set; get;}
	public String strConManId {get;set;}
	public String eventId {get;set;}
	
	//Existing List of "Conveyance_Detail__c"
	List<Conveyance_Detail__c> lstConDetail{get;set;}
	/* Need to remove some items*/
	List<Conveyance_Detail__c> lstConDetailDelete{get;set;}
	public	Event__c objEvent{set;get;}
	
	public ConveyanceController()
	{
		//get the event id
		eventId = ApexPages.currentPage().getParameters().get('eventId');
		
		if(eventId !=null && eventId != '')
		{
			objEvent = [Select e.OwnerId, e.Name, e.Id, e.Event_Status__c, e.Event_Place__c, e.Event_Category__c, e.End__c, e.Email__c, e.Duration__c, e.Description__c From Event__c e where e.Id =: eventId];
		}
		else
		{
			String StrtmpId = ApexPages.currentPage().getParameters().get('id');
			if(StrtmpId != null)
			{
				Conveyance_Manager__c objtmpConveyence = [Select 
															c.Remarks__c, 
															c.Name,c.Is_Submitted__c, 
															c.Id, 
															c.Event__c,
															c.Event__r.Name
														From Conveyance_Manager__c c 
														where c.Id =:StrtmpId];
	      		if(objtmpConveyence != null)
	      		{
	      			eventId = objtmpConveyence.Event__c;
	      			objEvent = [Select e.OwnerId, 
	      							   e.Name, 
	      							   e.Id, 
	      							   e.Event_Status__c, 
	      							   e.Event_Place__c, 
	      							   e.Event_Category__c, 
	      							   e.End__c,
	      							   e.Email__c, 
	      							   e.Duration__c,
	      							   e.Description__c 
	      							   From Event__c e 
	      							   where e.Id =: eventId];
	      		}
			}
		}
		
		// Need to inititalise the Removed Detail list
		lstConDetailDelete = new List<Conveyance_Detail__c>();
		if(ApexPages.currentPage().getParameters().get('id') != null && ApexPages.currentPage().getParameters().get('id') != '')
		{
			strConManId = ApexPages.currentPage().getParameters().get('id');
			objConveyanceManager = [Select c.Travel_Type__c, 
										   c.Remarks__c, 
										   c.Reimbursement_date__c, 
										   c.OwnerId, 
										   c.Name__c, 
										   c.Name,c.Is_Submitted__c, 
										   c.Mode_of_Travel__c, 
										   c.Id, 
										   c.Event__c,
										   c.Event__r.Name, 
										   c.Date_of_Travel__c, 
										   c.Claim_Date__c, 
										   c.Amount_Reimbursed__c, 
										   c.Amount_Claimed__c,
										   c.Event__r.Id
									From Conveyance_Manager__c c 
									where c.Id =: strConManId];
									
			lstConDetail = [Select c.Bill_Number__c,
								   c.Remarks__c, 
								   c.Name, 
								   c.Is_Bill_Available__c, 
								   c.Id, 
								   c.Conveyance_Manager__c, 
								   c.Bill_Details__c, 
								   c.Amount__c 
								   From Conveyance_Detail__c c 
								   where c.Conveyance_Manager__c =: strConManId ORDER By c.CreatedDate];
			
			// Auto populating List
			lstConveyanceInfo = autoPopulateDetails(lstConDetail);
			/*if(ApexPages.currentPage().getParameters().get('mode') != null && ApexPages.currentPage().getParameters().get('mode') == 'edit')*/
			if(objConveyanceManager.Is_Submitted__c)
			{		 		
				flag = false;
			}
			else
			{
				flag = true;
			}
		}
		else
			flag = true;
		
		if(objConveyanceManager == Null)
		{
			objConveyanceManager = new Conveyance_Manager__c();
			objConveyanceManager.Date_of_Travel__c = System.today();
			objConveyanceManager.Claim_Date__c =  System.today();
			objConveyanceManager.Travel_Type__c = 'Local';
			objConveyanceManager.Mode_of_Travel__c = 'Cab';
		}
		if(lstConveyanceInfo == null)
		{
			lstConveyanceInfo = new List<ConveyanceDetails>();
			lstConveyanceInfo.add(new ConveyanceDetails(new Conveyance_Detail__c(),1));
		}
	}
	
	
	private List<ConveyanceDetails> autoPopulateDetails(List<Conveyance_Detail__c> lstConveyanceDetail)
	{
		List<ConveyanceDetails> lstConveyanceDetailsInfo = new List<ConveyanceDetails>();
		if(lstConveyanceDetail != null && lstConveyanceDetail.size() > 0)
		{
			Integer iIndex = 0;
			for(Conveyance_Detail__c objConDetail :lstConveyanceDetail)
			{
				iIndex ++;
				lstConveyanceDetailsInfo.add(new ConveyanceDetails(objConDetail,iIndex));
			}
		}
		return lstConveyanceDetailsInfo;
	}
	
	//Save Fuctionality//
	public PageReference save()
	{
		Pagereference pgReference = null;
			
		
			if(lstConDetailDelete != null && lstConDetailDelete.size() > 0)
			{
				// need to delete Details who get removed from the UI.
				List<Database.DeleteResult> sp	=Database.delete(lstConDetailDelete);
			}
			System.debug('========= In save=====');
			
			//objConveyanceManager.Name = objConveyanceManager.Event__r.Id;
		try
		{
			objConveyanceManager.Event__c = eventId;
			System.debug('========= objConveyanceManager.Event__c====='+eventId);
			objConveyanceManager.Mode_of_Travel__c = objConveyanceManager.Mode_of_Travel__c;
			objConveyanceManager.Claim_Date__c = objConveyanceManager.Claim_Date__c;
			objConveyanceManager.Travel_Type__c = objConveyanceManager.Travel_Type__c;
			objConveyanceManager.Remarks__c = objConveyanceManager.Remarks__c;
			objConveyanceManager.Date_of_Travel__c = objConveyanceManager.Date_of_Travel__c;
		
			Database.Upsertresult saveResult = Database.Upsert(objConveyanceManager);
			if(saveResult.isSuccess())
			{
				List<Conveyance_Detail__c> lstRecordsToInsert = new List<Conveyance_Detail__c>();
				
				if(lstConveyanceInfo !=null && lstConveyanceInfo.size()>0)
				{
					Conveyance_Detail__c objConveyanceDetail;
					
					for(ConveyanceDetails tmpConveyanceDetails : lstConveyanceInfo)
					{
						if(String.valueOf(tmpConveyanceDetails.objConveyance_Details.Id) != Null)
							objConveyanceDetail = new Conveyance_Detail__c(Id = tmpConveyanceDetails.objConveyance_Details.Id);
						else
						{
							objConveyanceDetail = new Conveyance_Detail__c();
							objConveyanceDetail.Conveyance_Manager__c = saveResult.getId();
						}
					objConveyanceDetail.Amount__c = tmpConveyanceDetails.objConveyance_Details.Amount__c;
					objConveyanceDetail.Bill_Details__c = tmpConveyanceDetails.objConveyance_Details.Bill_Details__c;
					objConveyanceDetail.Is_Bill_Available__c = tmpConveyanceDetails.objConveyance_Details.Is_Bill_Available__c;
					objConveyanceDetail.Bill_Number__c = tmpConveyanceDetails.objConveyance_Details.Bill_Number__c;
					lstRecordsToInsert.add(objConveyanceDetail);	
				}		
				
				List <Database.Upsertresult> lstUpResult = Database.upsert(lstRecordsToInsert);
				
				// lstUpResult can be used when we need to check that record is
				// Upserted or not.
			}
				pgReference = new Pagereference('/apex/ConveyanceManager?id='+saveResult.getId()+'&eventId='+eventId);
			
				//If you want to redirect via server mode please use SetRedirect(True)
				pgReference.setRedirect(true);
		}
			return pgReference;
		}
		catch(Exception ex)
		{
			pgReference = new Pagereference('/apex/ConveyanceManager?eventId='+eventId);
			
		}
		return pgReference;
	}
	
	

	//Add More ConveyanceDetails
	public void AddMore()
	{
		System.debug('In Add more fuction');
		lstConveyanceInfo.add(new ConveyanceDetails(new Conveyance_Detail__c(Conveyance_Manager__c = objConveyanceManager.Id),lstConveyanceInfo.size()+1));//lstConveyanceInfo.size()+1
		//Error.DebugLog('In Add more fuction');
	}
    
	public PageReference Cancel()
	{
		PageReference pgReference = null;
		if(eventId !=null)
		{
			pgReference = new Pagereference('/'+eventId);
			return pgReference;
		}
		else
		{
			return pgReference;
		}
	}
	
	
	//Submission of conveyance
	public PageReference Submit()
	{
		Database.Upsertresult saveResult = null;
		Pagereference pgReference = null;
		
		System.debug('========= In submit=====');
		try
		{	
			if(lstConDetailDelete != null && lstConDetailDelete.size() > 0)
			{
			// need to delete Details who get removed from the UI.
				Database.delete(lstConDetailDelete);
			}
			objConveyanceManager.Event__c = eventId;
			System.debug('=========Event name in submit====='+eventId);
			objConveyanceManager.Mode_of_Travel__c = objConveyanceManager.Mode_of_Travel__c;
			objConveyanceManager.Claim_Date__c = objConveyanceManager.Claim_Date__c;
			objConveyanceManager.Travel_Type__c = objConveyanceManager.Travel_Type__c;
			objConveyanceManager.Remarks__c = objConveyanceManager.Remarks__c;
			objConveyanceManager.Date_of_Travel__c = objConveyanceManager.Date_of_Travel__c;
			objConveyanceManager.Is_Submitted__c = true;
			saveResult = Database.upsert(objConveyanceManager);
			if(saveResult.isSuccess())
			{
				List<Conveyance_Detail__c> lstRecordsToInsert =new List<Conveyance_Detail__c>();
				if(lstConveyanceInfo !=null && lstConveyanceInfo.size()>0)
				{
					Conveyance_Detail__c objConveyanceDetail;
					for(ConveyanceDetails tmpConveyanceDetails:lstConveyanceInfo)
					{
						if(String.valueOf(tmpConveyanceDetails.objConveyance_Details.Id) != Null)
							objConveyanceDetail = new Conveyance_Detail__c(Id = tmpConveyanceDetails.objConveyance_Details.Id);
						else
						{
							objConveyanceDetail = new Conveyance_Detail__c();
							objConveyanceDetail.Conveyance_Manager__c = saveResult.getId();
						}
						objConveyanceDetail.Amount__c = tmpConveyanceDetails.objConveyance_Details.Amount__c;
						objConveyanceDetail.Bill_Details__c = tmpConveyanceDetails.objConveyance_Details.Bill_Details__c;
						objConveyanceDetail.Is_Bill_Available__c = tmpConveyanceDetails.objConveyance_Details.Is_Bill_Available__c;
						System.debug('=========objConveyanceDetail====='+tmpConveyanceDetails);
						System.debug('=========tmpConveyanceDetails.objConveyance_Details.Amount__c====='+tmpConveyanceDetails.objConveyance_Details.Amount__c);
						objConveyanceDetail.Bill_Number__c = tmpConveyanceDetails.objConveyance_Details.Bill_Number__c;
						lstRecordsToInsert.add(objConveyanceDetail);	
					}		
					List<Database.Upsertresult> lstSaveResult = Database.upsert(lstRecordsToInsert);
				}
				pgReference = new Pagereference('/apex/ConveyanceManager?id='+saveResult.getId()+'&mode=edit'+'&eventId='+eventId);
				pgReference.setRedirect(true);
			}
		}
		catch(Exception ex)
		{
			
		}
		
		return pgReference;
	}
	
	
	//To remove detail object from database as well as from UI
	public void Remove()
	{
		if(lstConveyanceInfo != null && lstConveyanceInfo.size()>1)
		{
			ConveyanceDetails objRemovedDetail = lstConveyanceInfo.get(lstConveyanceInfo.size()-1);
			lstConDetailDelete.add(objRemovedDetail.objConveyance_Details);
			lstConveyanceInfo.remove(lstConveyanceInfo.size()-1);
		}
		else 
		{
			Error.DebugLog('Please add atleast one Conveyance details record');
		}
	}
	
	
	//Inner Class
	public class ConveyanceDetails
	{
		public Integer iIndex {get;set;}
        public Conveyance_Detail__c objConveyance_Details {get;set;}
		
		public ConveyanceDetails(){}
		public ConveyanceDetails(Conveyance_Detail__c objConveyance_Details , Integer iCount)
        {
        	if(objConveyance_Details != null)
       		{
        		this.objConveyance_Details = objConveyance_Details;
       			this.iIndex = iCount;
        	}
        	else
        	{
        	 	//Error.DebugLog('Null Value');
        	}
        }
       
	}
}