Freedom Sanbox Ant Deploy/src/objects/EntityRelatedAttachment__c.object
<CustomObject>
    <description>This object will be the mapper between Entity and Attachment.</description>
    <fields>
        <fullName>Related_Entity__c</fullName>
        <label>Related Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RelatedAttachments</relationshipLabel>
        <relationshipName>RelatedAttachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EntityRelatedAttachment</label>
    <nameField>
        <displayFormat>Attachment-{00000000}</displayFormat>
        <label>Entity Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EntityRelatedAttachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ViewHTMLPlanLinksController.cls
/*
Revision History:

		Version     Version Author     Date        Comments
		1.0         --           	   --	  	   Initial Draft
		2.0  		Prajakta Sanap     24/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.				   				 					   
*/

public with sharing class ViewHTMLPlanLinksController 
{
	public List<Attachment> lstAttachment {get;set;}
	public Account objAccount {get;set;}
	EntityRelatedAttachment__c objRelatedAttachment{get;set;} 
	String entityID {set;get;}  
	public ViewHTMLPlanLinksController()
	{
		String entityID = ApexPages.currentPage().getParameters().get('EntityId');
		objAccount = [Select Id, Name from Account where Id=:entityID];
		if(entityID != null && entityID !='')
			objRelatedAttachment = [select Id,Related_Entity__c from EntityRelatedAttachment__c where Related_Entity__c = : entityID limit 1];
		lstAttachment = [Select Id, Name, CreatedDate from Attachment where ParentId =: objRelatedAttachment.Id And Name like '%.htm' order by CreatedDate desc];
	}
	
	@isTest
	static void TestViewHTMLPlanLinksController()
	{
		Test.StartTest();
		Account acc = new Account(FirstName='ACD',LastName='GHJ');
		insert acc;
		ApexPages.currentPage().getParameters().put('EntityId', acc.id);
		ViewHTMLPlanLinksController objController = new ViewHTMLPlanLinksController();
		Test.StopTest();
	}
}