Freedom Sanbox Ant Deploy/src/objects/Entity_Global_Assumption__c.object
<CustomObject>
    <fields>
        <fullName>Default_Estimated_Life_Expectancy__c</fullName>
        <label>Default Estimated Life Expectancy</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Retirement_Age__c</fullName>
        <description>This field is created by the Eternus . If the field Retirement Age form the account is null then fetch this field.</description>
        <label>Default Retirement Age</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expected_Return_on_Investment__c</fullName>
        <label>Expected Return on Investment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Gold_Growth_Rate__c</fullName>
        <defaultValue>8</defaultValue>
        <description>Added to decide growth rate of new record type GOLD in Investment Asset.</description>
        <label>Gold Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Income_Growth_Rate__c</fullName>
        <label>Income Growth Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Inflation_Rate__c</fullName>
        <label>Inflation Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>IsChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsChanged</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_Of_Months__c</fullName>
        <label>Number Of Months</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock_Growth_Rate__c</fullName>
        <defaultValue>14</defaultValue>
        <label>Stock Growth Rate</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Entity Global Assumption</label>
    <nameField>
        <label>Entity Global Assumption Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entity Global Assumptions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/OnEntityGlobalAssumptionUpdate.cls
public without sharing class OnEntityGlobalAssumptionUpdate {
	
	public static void UpdateEntityGlobalAssumptionFlag(List<Entity_Global_Assumption__c> lstEntityGlobalAssumption, Map<Id,Entity_Global_Assumption__c> MapEntityGlobalAssumption)
	{
		for(Entity_Global_Assumption__c globalAspt : lstEntityGlobalAssumption)
		{
			Entity_Global_Assumption__c globalAsptOld = MapEntityGlobalAssumption.get(globalAspt.Id);
			
			if(globalAspt.IsChanged__c) continue;
			
			If((globalAspt.Expected_Return_on_Investment__c != globalAsptOld.Expected_Return_on_Investment__c)
				|| globalAspt.Income_Growth_Rate__c != globalAsptOld.Income_Growth_Rate__c
				|| globalAspt.Inflation_Rate__c != globalAsptOld.Inflation_Rate__c
				|| globalAspt.Number_Of_Months__c != globalAsptOld.Number_Of_Months__c
				|| globalAspt.Number_Of_Months__c != globalAsptOld.Number_Of_Months__c
				|| globalAspt.Default_Retirement_Age__c != globalAsptOld.Default_Retirement_Age__c
				|| globalAspt.Default_Estimated_Life_Expectancy__c != globalAsptOld.Default_Estimated_Life_Expectancy__c
				|| globalAspt.Stock_Growth_Rate__c != globalAsptOld.Stock_Growth_Rate__c
				|| globalAspt.Gold_Growth_Rate__c != globalAsptOld.Gold_Growth_Rate__c)
				{
					globalAspt.IsChanged__c = true;
				}
		}
	}
}