Freedom Sanbox Ant Deploy/src/objects/Execution_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <formula>Approve_Action_Plan__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ParentExecutionTracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Tracker</label>
        <referenceTo>Execution_Tracker__c</referenceTo>
        <relationshipLabel>Related Execution Tracker</relationshipLabel>
        <relationshipName>Execution_Tracker</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Execution Tracker</label>
    <nameField>
        <displayFormat>ET#{0000}</displayFormat>
        <label>Execution Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Execution Tracker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Renewal_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>Cheque_Submission_date__c</fullName>
        <label>Cheque Submission date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Renewal_Trackers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Execution_Tracker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Execution Tracker</label>
        <referenceTo>Execution_Tracker__c</referenceTo>
        <relationshipName>Renewal_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Type__c</fullName>
        <label>Insurance Type</label>
        <picklist>
            <picklistValues>
                <fullName>Life Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Insurance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_renewal_date__c</fullName>
        <label>Next renewal date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ParentId</label>
        <referenceTo>Renewal_Tracker__c</referenceTo>
        <relationshipName>Renewal_Trackers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Renewal_Tracker_Name__c</fullName>
        <label>Renewal Tracker Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tenure_of_Insurance__c</fullName>
        <label>Tenure of Insurance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Renewal Tracker</label>
    <nameField>
        <displayFormat>RT-{0000000}</displayFormat>
        <label>Renewal Tracker Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewal Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/RenewalTrackerHandler.cls
public without sharing class RenewalTrackerHandler extends RenewalTrackerTrigger 
{
	public RenewalTrackerHandler(Renewal_Tracker__c[] Renewal_TrackerOldList, Renewal_Tracker__c[] Renewal_TrackerList)
	{
		super(Renewal_TrackerOldList,Renewal_TrackerList);
	}
	
	public override void execute()
	{
		//Renewal_TrackerOldList : trigger.Old value will be stored 
		//Renewal_TrackerNewList : trigger.New value will be stored
		Set<Id> EntityIdSet = new Set<Id>();
		for(Renewal_Tracker__c objNewRenewalTracker : Renewal_TrackerNewList)
		{
			EntityIdSet.add(objNewRenewalTracker.Entity__c);
		}
		List<Renewal_Tracker__c> lstUpdateChildRenewalTracker = new List<Renewal_Tracker__c>();
		Map<Id,Execution_Tracker__c> mapIdToExecutionTracker = new Map<Id,Execution_Tracker__c>([select Id,Mode__c from Execution_Tracker__c where Entity_Name__c IN: EntityIdSet]);
		
		system.debug('***mapIdToExecutionTracker.size()******'+mapIdToExecutionTracker.size());
		//system.debug('***Renewal_TrackerNewListMap******'+Renewal_TrackerNewListMap);
		 
						
		for(Renewal_Tracker__c objNewRenewalTracker : Renewal_TrackerNewList)
		{
			Renewal_Tracker__c objOldRenewalTracker = new Renewal_Tracker__c();
			if(Renewal_TrackerOldListMap.containsKey(objNewRenewalTracker.Id))
			{
				objOldRenewalTracker = Renewal_TrackerOldListMap.get(objNewRenewalTracker.Id);
				system.debug('******objOldRenewalTracker******'+objOldRenewalTracker);
				if(objOldRenewalTracker.Cheque_Submission_date__c == null && objNewRenewalTracker.Cheque_Submission_date__c != null)
				{
					if(objNewRenewalTracker.Tenure_of_Insurance__c > 1)
					{
						Renewal_Tracker__c objChildRenewal = new Renewal_Tracker__c();
						Execution_Tracker__c objET = new Execution_Tracker__c();
						objChildRenewal.Entity__c = objNewRenewalTracker.Entity__c;
						objChildRenewal.Execution_Tracker__c = objNewRenewalTracker.Execution_Tracker__c;
						if(objNewRenewalTracker.ParentId__c == null)
							objChildRenewal.ParentId__c = objNewRenewalTracker.Id;
						else
							objChildRenewal.ParentId__c = objNewRenewalTracker.ParentId__c;
						objChildRenewal.Renewal_Tracker_Name__c = objNewRenewalTracker.Renewal_Tracker_Name__c;
						if(objNewRenewalTracker.Tenure_of_Insurance__c != null)
								objChildRenewal.Tenure_of_Insurance__c = objNewRenewalTracker.Tenure_of_Insurance__c - 1;
						if(objNewRenewalTracker.Insurance_Type__c != null && objNewRenewalTracker.Insurance_Type__c.equalsIgnoreCase('Life Insurance'))
						{
							objChildRenewal.Insurance_Type__c = 'Life Insurance';
						}
						else if(objNewRenewalTracker.Insurance_Type__c != null && objNewRenewalTracker.Insurance_Type__c.equalsIgnoreCase('General Insurance'))
						{
							objChildRenewal.Insurance_Type__c = 'General Insurance';
						}
						
						system.debug('(objNewRenewalTracker.Execution_Tracker__r.Mode__c****'+objNewRenewalTracker.Execution_Tracker__r.Mode__c);
						if(mapIdToExecutionTracker.containsKey(objNewRenewalTracker.Execution_Tracker__c))
						{
							objET = mapIdToExecutionTracker.get(objNewRenewalTracker.Execution_Tracker__c);
						    system.debug('******objET.Mode__c******'+objET.Mode__c);
							if(objET.Mode__c != null)
			       			{
				       			if(objET.Mode__c.equalsIgnoreCase('Monthly'))
				       			{
				       				if(objNewRenewalTracker.Next_renewal_date__c != null)
				       				objChildRenewal.Next_renewal_date__c = objNewRenewalTracker.Next_renewal_date__c.addDays(30);
				       			}
				       			else if(objET.Mode__c.equalsIgnoreCase('Quaterly'))
				       			{
				       				if(objNewRenewalTracker.Next_renewal_date__c != null)
				       				objChildRenewal.Next_renewal_date__c = objNewRenewalTracker.Next_renewal_date__c.addDays(90);
				       			}
				       			else if(objET.Mode__c.equalsIgnoreCase('Semi-Annual'))
				       			{
				       				if(objNewRenewalTracker.Next_renewal_date__c != null)
				       				objChildRenewal.Next_renewal_date__c = objNewRenewalTracker.Next_renewal_date__c.addDays(180);
				       			}
				       			else
				       			{
				       				if(objNewRenewalTracker.Next_renewal_date__c != null)
				       				objChildRenewal.Next_renewal_date__c = objNewRenewalTracker.Next_renewal_date__c.addDays(365);
				       			}	
				       		}
						}
						lstUpdateChildRenewalTracker.add(objChildRenewal);
					}
				}
			}
		}
		if(!lstUpdateChildRenewalTracker.isEmpty())
			insert lstUpdateChildRenewalTracker;
	}
}