Freedom Sanbox Ant Deploy/src/objects/Goal__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marriage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parental Responsibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emergency Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retirement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money to Heirs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <description>Space for ‘Remarks’ where the FP can give additional advice(Only for Goal)</description>
        <inlineHelpText>Space for ‘Remarks’ where the FP can give additional advice</inlineHelpText>
        <label>Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RichText_Remark__c</fullName>
        <label>RichText Remark</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Goal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Remarks__c.object
<CustomObject>
    <description>Space for ‘Remarks’ where the FP can give additional advice.(Except for Goal)</description>
    <fields>
        <fullName>Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Remark related entity</description>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Remarks</relationshipLabel>
        <relationshipName>Remarks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remark__c</fullName>
        <description>Space for ‘Remarks’ where the FP can give additional advice(Except for Goal)</description>
        <inlineHelpText>space for ‘Remarks’ where the FP can give additional advice</inlineHelpText>
        <label>Remark</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RichText_Remark__c</fullName>
        <label>RichText Remark</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Remark</label>
    <nameField>
        <label>Remarks Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remarks</pluralLabel>
    <recordTypes>
        <fullName>SummaryActionPlan</fullName>
        <active>true</active>
        <label>SummaryActionPlan</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/SumActionPlanController.cls
/*
	Revision History:
	
    Version     Version Author     Date           Comments
    1.0         Prajakta Sanap     27/09/2012     New Action Plan Creation
    2.0			Gaurav			   15/04/2013	  To hide succesion palnning and Insurance disply on Action plan
*/

public with sharing class SumActionPlanController extends FPsidebarDispalyLink
{
    private SumActionPlanServices serviceObj;
    public SummaryActionPlanBean beanObj {get;set;}
    
    //Added on:06/02/2013 : Aditi Satpute : AP changes
    public String isShowActionPlan{get;set;}
    
    public List<SummaryDetail> lstSummaryDetail {get;set;}
    public SummaryDetail objSummaryDetail {get;set;}
    
    //Added on:23-May-2013 : Kiran : FP changes part2 - issue 10
    public Remarks__c remarks{get;set;}
    
    public SumActionPlanController()
    {
    	super(System.currentPageReference().getParameters().get('entityId')); //Changes by Gaurav (15-4-2013): To hide succesion palnning and Insurance disply on Action plan
    	lstSummaryDetail = new List<SummaryDetail>();
        serviceObj = new SumActionPlanServices();
        beanObj = new  SummaryActionPlanBean();
        remarks = new Remarks__c();
        beanObj.entityId = Apexpages.currentPage().getParameters().get('entityId');
        isShowActionPlan = Apexpages.currentPage().getParameters().get('isShowActionPlan');
       
        serviceObj.getFamilyDetails(beanObj);
        serviceObj.getGoals(beanObj);
        
        /*
		  Updated By : Kiran Patil
		  Updated At : 5-Jun-2013
		  Summary    : FP changes-part2 - issue 6 
		*/
		if(!(beanObj.goalList).isEmpty()) {
	        list<Goal__c> tempaddNewListView = new list<Goal__c>();
        	list<Goal__c> tempaddNewListViewRetirement = new list<Goal__c>();
        	for (Goal__c goal : beanObj.goalList) {
        		if (goal.Goal_Type__c.equalsIgnoreCase('Retirement'))
        		    tempaddNewListViewRetirement.add(goal);
        		else     
        		    tempaddNewListView.add(goal);
        	}
        	beanObj.goalList = new list<Goal__c>();
        	beanObj.goalList.addall(tempaddNewListView);
        	beanObj.goalList.addall(tempaddNewListViewRetirement);
        }
        
        serviceObj.getAsset(beanObj);
        beanObj.giList = serviceObj.getGenerelInsurance(beanObj.accList);
        if(beanObj.giList != null && beanObj.giList.size()>0)
        {
           beanObj.isGeneralInsExist = true;
        }
        beanObj.liList = serviceObj.getLifeInsurance(beanObj.accList);
        if(beanObj.liList != null && beanObj.liList.size()>0)
        {
           beanObj.isLifeInsExist = true;
        }
        serviceObj.prepareData(beanObj);
       
        System.debug('--------------------------------beanObj.goalList------------'+beanObj.goalList);
        System.debug('--------------------------------beanObj.sipList------------'+beanObj.sipList);
        System.debug('--------------------------------beanObj.asetList------------'+beanObj.asetList);
        
        for(Integer i = 0 ; i < beanObj.goalList.size() ; i++)
        {
       		String strDescription = beanObj.goalList[i].Description__c;
       		Double sipDebt = beanObj.sipList[0].golListVals[i];
       		Double sipEquity = beanObj.sipList[1].golListVals[i];
       		Double sipGold = beanObj.sipList[2].golListVals[i];
       		
       		Double lumpsumDebt = beanObj.asetList[0].golListVals[i];
       		Double lumpsumEquity = beanObj.asetList[1].golListVals[i];
       		Double lumpsumGold = beanObj.asetList[2].golListVals[i];
       		
       		lstSummaryDetail.add(new SummaryDetail(strDescription, new List<Double>{sipDebt,sipEquity, sipGold}, new List<Double>{lumpsumDebt,lumpsumEquity, lumpsumGold}));
       	}
       	
       	
   		List<Double> lstTotalSip = new List<Double>();
   		List<Double> lstTotalLumpsum = new List<Double>();
   		for(Integer i = 0; i < 3 ; i++)
   		{
   			lstTotalSip.add(0);
   			lstTotalLumpsum.add(0);
   		}
   		
   		for(Integer i = 0; i < 3 ; i++)
   		{
   			for(Integer j = 0; j < lstSummaryDetail.size(); j++)
   			{
   				lstTotalSip.set(i, lstTotalSip.get(i) + Math.roundToLong(lstSummaryDetail[j].lstSipValue[i]));
   				lstTotalLumpsum.set(i, lstTotalLumpsum.get(i) + Math.roundToLong(lstSummaryDetail[j].lstLumpsumValue[i]));	
   			}
   		}
   		
   		objSummaryDetail = new SummaryDetail('Total', lstTotalSip, lstTotalLumpsum);
   		
   		Map<String, Schema.RecordTypeInfo> remarksRecordTypeInfo = Schema.SObjectType.Remarks__c.getRecordTypeInfosByName();
        String remarksRecordTypeId = remarksRecordTypeInfo.get('SummaryActionPlan').getRecordTypeId();
        
        list<Remarks__c> remarksList = [
                                 Select Remark__c,
                                 		RichText_Remark__c
                                      , RecordTypeId
                                      , Name
                                      , Id
                                      , Entity__c
                                   From Remarks__c
                                  where Entity__c =: System.currentPageReference().getParameters().get('entityId')
                                    and RecordTypeId =: remarksRecordTypeId
        ];
        if (remarksList.isEmpty())
   			remarks = new Remarks__c(RecordTypeId = remarksRecordTypeId);
   		else
   			remarks = remarksList[0];
    }

	/*
	  Updated By : Kiran Patil
	  Updated At : 23-May-2013
	  Summary    : FP changes-part2 - issue 10 
	*/
    public void saveUnallocatedAssetsRemark()
    {
        try {
        	if (remarks.Entity__c == null)
        		remarks.Entity__c = Apexpages.currentPage().getParameters().get('entityId');
        	upsert remarks;
        }
        catch(System.Exception ex)
        {
            error.DebugLog('--- Error --->' + ex.getMessage());
        }
    }
    
 /**
 * @Description : actionPlan()is function used for navigating to ActionPlan page
 * ReturnType : pageReference 
 */
    public pageReference actionPlan()
    {
        pageReference pageRef = new pageReference('/apex/ActionPlan?entityId='+beanObj.entityId+'&tabname=Financial Planning');
        pageRef.setRedirect(true);
        return pageRef ;
    }
    
/**
 * @Description : actionPlanPDF()is function used for navigating to ActionPlanPDF page
 * ReturnType : pageReference 
 */
    public pageReference actionPlanPDF()
    {
        pageReference pageRef = new pageReference('/apex/ActionPlanPDF?entityId='+beanObj.entityId+'&tabname=Financial Planning');
        return pageRef ;
    }
    
    public class SummaryDetail
    {
    	public String description {get;set;}
    	public List<Double> lstSipValue {get;set;}
    	public List<Double> lstLumpsumValue {get;set;}
    	
    	public SummaryDetail(String description, List<Double> lstSipValue, List<Double> lstLumpsumValue)
    	{
    		this.description = description;
    		this.lstSipValue = lstSipValue;
    		this.lstLumpsumValue = lstLumpsumValue;
    	}
    	
    }
}