Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy_Name__c</fullName>
        <label>Policy Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy Type</label>
        <picklist>
            <picklistValues>
                <fullName>Term Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whole Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP - Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money-Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Householder&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarnteed Renewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP - Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Accident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Premium_Amount_Rs__c</fullName>
        <label>Premium Amount (Rs.)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Premium_Frequency__c</fullName>
        <label>Premium Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time Premium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sum_Assured_Rs__c</fullName>
        <label>Sum Assured (Rs.)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/GeneralInsurancePlanningBean.cls
/**
 * @Author: Samruddhi P
 * @since : 18th Feb 2011
 * @Description: GeneralInsurancePlanningBean is bean class for GeneralInsurancePlanningPage in Analysis Section
 */
public class GeneralInsurancePlanningBean{
    public List<Insurance__c> currentMedInsurance{
        get{
            if(currentMedInsurance == null)
                currentMedInsurance = new List<Insurance__c>();
            return currentMedInsurance;
        }
        set;
    }
    public List<Insurance__c> currentAssetInsurance{
        get{
            if(currentAssetInsurance == null)
                currentAssetInsurance = new List<Insurance__c>();
            return currentAssetInsurance;
        }
        set;
    }
    public List<Insurance__c> suggestedMedInsurance{
        get{
            if(suggestedMedInsurance == null)
                suggestedMedInsurance = new List<Insurance__c>();
            return suggestedMedInsurance;
        }
        set;
    }
    public List<Insurance__c> suggestedAssetInsurance{
        get{
            if(suggestedAssetInsurance == null)
                suggestedAssetInsurance = new List<Insurance__c>();
            return suggestedAssetInsurance;
        }
        set;
    }
    public Boolean currentAssetEmptyFlag {get; set;}
    public Boolean currentMedicalEmptyFlag {get; set;}
    public Boolean suggestedAssetEmptyFlag {get; set;}
    public Boolean suggestedMedicalEmptyFlag {get; set;}
    public List<Insurance__c> suggMedList{
        get{
            if(suggMedList==null){
                suggMedList = new List<Insurance__c>();
                for(Insurance__c insurance : suggestedMedInsurance ){
                    if(!GeneralInsurancePlanningBean.isRowEmpty(insurance))
                        suggMedList.add(insurance);
                }
            }
            return suggMedList;
        }
        set;
    }
    public List<Insurance__c> suggAssetList {
        get{
            if(suggAssetList == null){
                suggAssetList = new List<Insurance__c>();
                for(Insurance__c insurance : suggestedAssetInsurance ){
                    if(!GeneralInsurancePlanningBean.isRowEmpty(insurance))
                        suggAssetList.add(insurance);
                }
            }
            return suggAssetList;
        }
        set;
    }
    
    public List<Account> accountList {get; set;}
  
    /**
    * @isRowEmpty() function checks whether row is empty
    * @params:Insurance__c 
    * @Return Type:Boolean
    */
    public static Boolean isRowEmpty(Insurance__c insurance){
        if(insurance.Policy_Type__c==null || insurance.Policy_Type__c=='None')
            if(insurance.Policy_Name__c==null || insurance.Policy_Name__c.trim().equals(''))
                if(insurance.Premium_Amount_Rs__c==null || insurance.Premium_Amount_Rs__c == 0.0)
                    if(insurance.Premium_Frequency__c==null)
                        if(insurance.Sum_Assured_Rs__c==null  || insurance.Premium_Amount_Rs__c == 0.0)
                            return true;
        return false;
    }
    
    
    /**
    * @validate() function validates each row 
    * @params:Insurance__c 
    * @Return Type:None
    */
    public static void validate(Insurance__c insurance) {                                       
        if(insurance.Entity__c== null){
            throw new ValidationException(Label.EntityValidation);                                         
        }
        if(insurance.Policy_Type__c=='None'){
            throw new ValidationException(Label.InsurancePolicyTypeValidation);                                         
        }
        if(insurance.Premium_Amount_Rs__c==null){
            throw new ValidationException(Label.InsurancePremiumAmountValidation);                                         
        }
    }
}