Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Premium_Due_date__c</fullName>
        <label>Premium Due date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Premium_Frequency__c</fullName>
        <label>Premium Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One Time Premium</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ScheduleInsuranceDueDatesUpdate.cls
global class ScheduleInsuranceDueDatesUpdate implements Schedulable {
	global void execute(SchedulableContext SC) {
        //String email = 'tech@ffreedom.in';
        CalculateInsuranceNextDueDates calIns = new CalculateInsuranceNextDueDates();
        calIns.query ='Select i.Premium_Frequency__c,  i.Premium_Due_date__c From Insurance__c i';
        calIns.email= 'tech@ffreedom.in';
        database.executebatch(calIns); 
    } //close execute method
}