Freedom Sanbox Ant Deploy/src/objects/Insurance__c.object
<CustomObject>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Insurances</relationshipLabel>
        <relationshipName>Insurances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Policy_Type__c</fullName>
        <label>Policy Type</label>
        <picklist>
            <picklistValues>
                <fullName>Term Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Whole Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Endowment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP - Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Money-Back</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Householder&apos;s</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guarnteed Renewable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP - Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical Illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Accident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ULIP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Top Up</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Surrender_Cash_Value__c</fullName>
        <label>Surrender/ Cash Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Insurance</label>
    <nameField>
        <displayFormat>INS-{00000}</displayFormat>
        <label>Insurance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InsuranceRecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>Insurance record Types</description>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>InsuranceRecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBI Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Gains Tax Saving Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Convertible Debentures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Index</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Diversified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Large Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Mid Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Small Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Sectoral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Long Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Medium Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Ultra Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Arbitrage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Asset Allocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Debt Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Equity Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Monthly Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ETF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_NAV__c</fullName>
        <label>Current NAV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Price__c</fullName>
        <label>Current Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Investment Assets</relationshipLabel>
        <relationshipName>Investment_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Face_Value__c</fullName>
        <label>Face Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Gold</fullName>
        <active>true</active>
        <description>Added regarding new FP changes</description>
        <label>Gold and Silver</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stocks</fullName>
        <active>true</active>
        <label>Stocks</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/InvestmentAsset__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>InvestmentAsset</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/NetworthControllerTest.cls
/*
	
	Revision History:
	
    Version     Version Author     Date        Comments
    1.0         --           	   --	  		Initial Draft
    2.0			Manasi			   29/06/2011	Added querrystring parameter 'entityId' in testData() function before creating object of
    											NetworthController class
	3.0  		Prajakta Sanap     22/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.			    											
*/					  							

@isTest
private class NetworthControllerTest 
{
    static Account acc;
    static NetworthController netCon;
    static Investment_Asset__c inv,inv1,inv2;
    
    static void testData()
    {
    	TestData_Ffreedom testData = new TestData_Ffreedom();
		acc = testData.initializeAccount();
		
        //acc=new Account(LastName='ABC',RecordTypeId= RecTypes__c.getInstance('AccountClient').Record_Type_Value__c);// Gaurav '01220000000DnK3AAK');
    	upsert acc;
   
    	system.assertNotEquals(null,acc);
    
     	inv = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance('Stocks').RecordTypeId__c);
     	//inv = new   Investment_Asset__c(Entity__c=acc.id,Quantity__c =10,Current_Price__c=10000, RecordTypeId= InvestmentAsset__c.getInstance('Stocks').RecordTypeId__c);// Gaurav '01220000000HYx5AAG' );
     	insert inv;
     	system.assertNotEquals(null,inv.id);
     	
     	/*inv1 = new   Investment_Asset__c(Entity__c=acc.id,Quantity__c =10,Current_Price__c=10000, RecordTypeId= InvestmentAsset__c.getInstance('Gold').RecordTypeId__c);// Gaurav '01220000000HYx5AAG' );
     	insert inv1;
     	system.assertNotEquals(null,inv1.id);
     	*/
     	inv2 = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance('Fixed Income').RecordTypeId__c);
     	//inv2 = new Investment_Asset__c(Entity__c=acc.id,Quantity__c =10,Face_Value__c=10000, RecordTypeId= InvestmentAsset__c.getInstance('Fixed Income').RecordTypeId__c); // Gaurav '01220000000HYx3AAG' );
      	insert inv2;
     	system.assertNotEquals(null,inv2.id);
     	
     	Insurance__c  insurance = testData.initialize_Insurance(acc);
     	//Insurance__c  insurance=new Insurance__c(Entity__c=acc.id,Policy_Type__c ='Life Time',Surrender_Cash_Value__c=10000, RecordTypeId= InsuranceRecTypes__c.getInstance('Life Insurance').RecordTypeId__c); // Gaurav '01220000000Do0vAAC' );
      	insert insurance;
     	system.assertNotEquals(null,insurance.id);
	     /** Eternus Solutions       **/
		 /** Author  : Manasi Ranade **/
		 /** Issue Id: F0065      	**/
		 /** Date    : 29/06/2011 	**/
		 /** Purpose : Added querrystring parameter 'entityId' before creating object of
	    			   NetworthController class.Commented previous code.
		/****************************************************/ 
      	Apexpages.currentPage().getParameters().put('entityId',acc.id);
    	
    	netCon=new NetworthController();
     	//Previous Code
     	//Apexpages.currentPage().getParameters().put('entityId',acc.id);
       	String chart=netCon.getNetworthChart;
       	netCon.Output();
       	List<SummaryBean.SummaryDetail> summaryList=netCon.getNetworthSummaryList;
       	Double networth =netCon.getTotalNetworth;
        netCon.getChartData();
    }
    
    static testMethod void networthTest1() 
    {
       	Test.startTest();
        testData();
        TestData_Ffreedom testData = new TestData_Ffreedom();
        
        inv = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance('Mutual Fund').RecordTypeId__c);
       	//inv=new   Investment_Asset__c(Entity__c=acc.id,Asset_Type__c='Equity',Units__c =10,Current_NAV__c=10000,
          //                                          RecordTypeId= InvestmentAsset__c.getInstance('Mutual Fund').RecordTypeId__c);//Gaurav  '01220000000HYx4AAG' );
      	insert inv;
     	system.assertNotEquals(null,inv.id);
        test.stopTest();
    }
    
    static testMethod void networthTest2() 
    {
       	Test.startTest();
        testData();
        TestData_Ffreedom testData = new TestData_Ffreedom();
        
        inv = testData.init_InvestmentAsset(acc, InvestmentAsset__c.getInstance('Mutual Fund').RecordTypeId__c);
       // inv=new Investment_Asset__c(Entity__c=acc.id,Asset_Type__c='Debt',Units__c =10,Current_NAV__c=10000,
           //                                         RecordTypeId= InvestmentAsset__c.getInstance('Mutual Fund').RecordTypeId__c); //Gaurav '01220000000HYx4AAG' );
      	insert inv;
     	system.assertNotEquals(null,inv.id);
       
        test.stopTest();
    }
}