Freedom Sanbox Ant Deploy/src/objects/Investment_Asset__c.object
<CustomObject>
    <fields>
        <fullName>AMC_Name_Text__c</fullName>
        <label>AMC Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Acquisition_Date__c</fullName>
        <label>Acquisition Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Asset_Name__c</fullName>
        <label>Asset Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_Type__c</fullName>
        <label>Asset Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RBI Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital Gains Tax Saving Bonds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Convertible Debentures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Large Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Index</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Diversified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Large Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Mid Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Small Cap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - Sectoral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity - International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Long Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Medium Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Debt - Ultra Short Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Arbitrage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Asset Allocation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Debt Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Equity Oriented</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hybrid - Monthly Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ETF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Coupon_Rate__c</fullName>
        <label>Coupon Rate (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Current_NAV__c</fullName>
        <label>Current NAV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Face_Value__c</fullName>
        <label>Face Value</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maturity_Date__c</fullName>
        <label>Maturity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Monthly_SIP_Amount__c</fullName>
        <label>Monthly SIP Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purchase_NAV__c</fullName>
        <label>Purchase NAV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scheme_Name_Text__c</fullName>
        <label>Scheme Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Script_Name__c</fullName>
        <label>Script Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Investment Asset</label>
    <nameField>
        <displayFormat>IA-{00000}</displayFormat>
        <label>Investment Asset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Investment Assets</pluralLabel>
    <recordTypes>
        <fullName>Gold</fullName>
        <active>true</active>
        <description>Added regarding new FP changes</description>
        <label>Gold and Silver</label>
    </recordTypes>
    <recordTypes>
        <fullName>Mutual_Fund</fullName>
        <active>true</active>
        <label>Mutual Fund</label>
    </recordTypes>
    <recordTypes>
        <fullName>Stocks</fullName>
        <active>true</active>
        <label>Stocks</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/InvestmentAssetBean.cls
/*
    This class is to keep Investment Asset  and Fund  Object fields 
*/
public class InvestmentAssetBean 
{
    public List<InvestmentWrapper> investmentAssetWrapperList {get
            {
                if(investmentAssetWrapperList == null) {
                    investmentAssetWrapperList = new List<InvestmentWrapper>();
                }               
                return investmentAssetWrapperList;
            }
            set;
    }
    public List<SelectOption> options {get; set;}
    
    public InvestmentAssetBean() 
    {            
       options = new List<SelectOption>();  
    }    
    
    public void addInvestmentInstanceInList(Investment_Asset__c invAsset) 
    {
        InvestmentWrapper  wrapper = new InvestmentWrapper();
        wrapper.index =''+ investmentAssetWrapperList.size();
        wrapper.investmentAsset = invAsset;
      	//  wrapper.amcNameList = amcNameList;
        // wrapper.schemeNameList = schemeNameList;
        wrapper.selectedAMCName = invAsset.AMC_Name_Text__c;
        wrapper.selectedSchemeName = invAsset.Scheme_Name_Text__c;
         
        investmentAssetWrapperList.add(wrapper);
    }
    
    /*
        To Validate before storing object in Db  
    */    
    public static void validate(Investment_Asset__c investment,String recordName) 
    {
        String id;
        if(recordName.equals('Stocks')) {
        	system.debug('==========Stocks===========');
            if((investment.Script_Name__c == null) || (investment.Script_Name__c.trim().equals('')))                
                throw new ValidationException(Label.InvAssetScriptNameValidation);
        
        //Prajakta - FP changes - 25-02-2013        
        }else if(recordName.equals('Gold')) { /*Prajakta - 24-05-2013 */
        	system.debug('==========Gold===========');
            if((investment.Asset_Name__c == null) || (investment.Asset_Name__c.trim().equals('')))                
                throw new ValidationException(Label.InvAssetNameValidation);
                                           
        }else if (recordName.equals('Mutual_Fund')){
            if((investment.Scheme_Name_Text__c == null) || investment.Scheme_Name_Text__c.trim().equals(''))             
                throw new ValidationException(Label.InvAssetSchemeNameValidation);
            if((investment.AMC_Name_Text__c == null) || investment.AMC_Name_Text__c.trim().equals(''))
                throw new ValidationException(Label.InvAssetAMCNameValidation);                                          
        }
        //00001485
        if(investment.Asset_Type__c == null || investment.Asset_Type__c.trim().equals(''))
        	throw new ValidationException(Label.InvAssetAssetTypeValidation);
    }
    
    public static Boolean isRowEmpty(Investment_Asset__c investment) 
    {              
        if((investment.Script_Name__c == null) || (investment.Script_Name__c.trim().equals(''))) 
            if((investment.Description__c == null) || (investment.Description__c.trim().equals(''))) 
                if(investment.Asset_Type__c == null) 
                    if(((investment.Face_Value__c == null) || (investment.Face_Value__c ==0 ))) 
                        if((investment.Quantity__c == null) || (investment.Quantity__c == 0))
                            if((investment.Units__c == null)|| (investment.Units__c == 0))                              
                                if((investment.Acquisition_Date__c == null))
                                    if((investment.Purchase_NAV__c == null) || (investment.Purchase_NAV__c == 0))
                                        if((investment.Monthly_SIP_Amount__c == null) || (investment.Monthly_SIP_Amount__c == 0))
                                            if((investment.Purchase_Price__c == null) || (investment.Purchase_Price__c == 0))
                                                if((investment.Coupon_Rate__c == null) || (investment.Coupon_Rate__c == 0))
                                                    if((investment.Maturity_Date__c == null))
                                                        if((investment.AMC_Name_Text__c == null))
                                                            if((investment.Scheme_Name_Text__c == null))
                                                            	if((investment.Asset_Name__c == null))      //Prajakta - FP changes - 25-02-2013
                                                                 	if((investment.Current_NAV__c == null) || (investment.Current_NAV__c == 0))                                                 
                                                                		return true;        
        return false;            
    } 
        
    /*
        This method is being used on Networth page to show networth details for Investment asset by record Type.         
    */    
    public static SummaryBean.SummaryDetail getNetworthSummaryDetail(AggregateResult asset, String assetType)
    {
        SummaryBean.SummaryDetail networthSummary;  
        String assetClassStr;
        Double assetValue;
                
        assetClassStr = (String)asset.get('assetClass');                                                            
        assetValue = (Double) asset.get('assetValue');
        
        if(assetType != null) 
        {
            assetClassStr = assetType;  
        }
                                                                                                                                        
        networthSummary = new SummaryBean.SummaryDetail(assetClassStr,assetValue);
            
        return networthSummary; 
    }
    /**
        	Added on : 3/10/2013 - Aditi Satpute
        	Purpose : Merged Multiple queries into one and Added Hybrid Funds in Networth Service - As per call with Shweta
    **/ 
    public static SummaryBean.SummaryDetail getNetworthSummaryDetail(Double asset, String assetType)
    {
       SummaryBean.SummaryDetail networthSummary;  
     	String assetClassStr;
        /*Double assetValue;
                
        assetClassStr = (String)asset.get('assetClass');                                                            
        assetValue = (Double) asset.get('assetValue');
        */
        if(assetType != null) 
        {
            assetClassStr = assetType;  
        }
                                                                                                                                        
        networthSummary = new SummaryBean.SummaryDetail(assetClassStr,asset);
            
        return networthSummary; 
    }
                                  
    /*
        Wrapper class is needed to have index in place to populate Fund and Scheme name properly on Edit page.       
    */    
    public class InvestmentWrapper 
    {
        public String index { get; set;}
        public Investment_Asset__c investmentAsset { get; set;}
        public String selectedAMCName { get; 
            set {
                selectedAMCName =  value;
            }
        }
        public String selectedSchemeName { get; 
                set {
                    selectedSchemeName =  value;
                }
        }
        
        public List<SelectOption> amcNameList {
                get {                       
                    return amcNameList;
                }
                set;    
        }
        public List<SelectOption> schemeNameList {
                get {
                    if(schemeNameList == null) {
                        schemeNameList = new List<SelectOption>();                      
                    }                   
                    return schemeNameList;
                }
                set;
        }                  
    }
}