Freedom Sanbox Ant Deploy/src/objects/Lead_Platform_User__c.object
<CustomObject>
    <description>Its is the custom Lead object created for standard platform user.</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <color>#FF9900</color>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Follow-up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>TEXT (Salutation__c) &amp; &quot; &quot; &amp; First_Name__c &amp; &quot; &quot;  &amp; Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <label>Lead</label>
    <nameField>
        <label>Last Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/LeadNewController.cls
public with sharing class LeadNewController {
					
	//Lead_Platform_User__c				
	public String leadValue{get;set;}				
					
	public list<Lead_Platform_User__c>listLead				
	{				
		get{			
		if(listLead == null)			
			{		
				listLead = [Select l.Name, l.Name__c, l.Mobile__c, l.Lead_Status__c, l.Company_Name__c From Lead_Platform_User__c l ];	
			}		
			return listLead;		
		}set;			
	}				
					
	public PageReference go() 				
    {					
    	listLead = new List<Lead_Platform_User__c>();				
    	if(leadValue=='RecentlyModified')				
			{		
					
				system.debug('======inside========campValue'+leadValue);	
				listLead = [Select l.Name, l.Name__c, l.Mobile__c, l.Lead_Status__c, l.Company_Name__c From Lead_Platform_User__c l order by l.LastModifiedDate Desc];	
				system.debug('==============listCamp'+listLead);	
					
			}		
			else if(leadValue=='AllCampaigns')		
			{		
				listLead = [Select l.Name, l.Name__c, l.Mobile__c, l.Lead_Status__c, l.Company_Name__c From Lead_Platform_User__c l];	
			}		
			/*		
			else if (listLead == null || listLead.size() == 0)		
			{		
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'No data found to be shown.'));	
			}*/		
    	return null;				
    }					
    /*					
	public List<Lead_Platform_User__c> listNewLead				
	{				
		get			
		{			
		  		if(listNewLead == null)	
		  		{	
		  			listNewLead = new List<Lead_Platform_User__c>();
		  		}	
		  		return listNewLead;	
		}			
		set;			
	}				
	*/				
					
	  public PageReference newpage()				
   	{				
   		PageReference reference = new PageReference('/a1H/e?retURL=%2Fa1H%2Fo');			
   		reference.setRedirect(true);			
   		return reference;			
  	}				

}