Freedom Sanbox Ant Deploy/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Ffreedom_Score__c</fullName>
        <inlineHelpText>Please add the Ffreedom Score here</inlineHelpText>
        <label>Ffreedom Score</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Option_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <label>Answer Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer</label>
        <referenceTo>Question_Option_List__c</referenceTo>
        <relationshipLabel>Option Details</relationshipLabel>
        <relationshipName>Option_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuestionMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QuestionMaster</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Option Details</relationshipLabel>
        <relationshipName>Option_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>XRayScoreCard__c</fullName>
        <label>X-Ray Score Card</label>
        <referenceTo>XRay_ScoreCard__c</referenceTo>
        <relationshipLabel>Option Details</relationshipLabel>
        <relationshipName>Option_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Option Detail</label>
    <nameField>
        <displayFormat>Option Details -{0000}</displayFormat>
        <label>Option Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Option Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank__c.object
<CustomObject>
    <description>This will be the question bank and act as a master object to Questionnaire.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine whether the given Question Bank is to be used as a part of the Questionnaire.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{00}</displayFormat>
        <label>Question Bank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank_List__c.object
<CustomObject>
    <description>This will store all the questions  and will act as a master table to Questionnaire. Dummy questions will not have any answer (No Points).</description>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsDummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dummy?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Bank Lists (Parent Question)</relationshipLabel>
        <relationshipName>Question_Bank_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multichoice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Option_List__c.object
<CustomObject>
    <description>This will store the options for each question in the pool,  the score to be given and the feedback to be displayed.</description>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Option Lists</relationshipLabel>
        <relationshipName>Question_Option_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question Option List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Option Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/QuestionBank__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Question Bank List</description>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <description>Question Bank Name</description>
        <label>Question Bank</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>QuestionBank</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Questionnaire__c.object
<CustomObject>
    <description>This will give the ability to configure the questions for a particular questionnaire.</description>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <label>Display Sequence</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/X_Ray_Score_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>X-Ray Score Card Details</relationshipLabel>
        <relationshipName>X_Ray_Score_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipLabel>X-Ray Score Card Details</relationshipLabel>
        <relationshipName>X_Ray_Score_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>X-Ray Score Card Detail</label>
    <nameField>
        <label>X-Ray Score Card Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>X-Ray Score Card Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/XRay_ScoreCard__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Question_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Answer Question Master</label>
        <referenceTo>Question_Option_List__c</referenceTo>
        <relationshipLabel>X-Ray Score Cards</relationshipLabel>
        <relationshipName>X_Ray_Score_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <description>This will store the sequence of question.</description>
        <label>Display Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>X-Ray Score Cards</relationshipLabel>
        <relationshipName>X_Ray_Score_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score_Master__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>XRayScoreCardMaster__c</fullName>
        <label>X-Ray Score Card Detail</label>
        <referenceTo>X_Ray_Score_Card_Detail__c</referenceTo>
        <relationshipLabel>X-Ray Score Cards</relationshipLabel>
        <relationshipName>X_Ray_Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>X-Ray Score Card</label>
    <nameField>
        <label>X-Ray Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>X-Ray Score Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/XrayWizardController.cls
/*
Revision History:

   Version     Version Author     Date          Comments
   1.0         Dipak Nikam      NA      Initial Draft
   
   2.0        Mahesh Hirugade    30/03/2012  To remove browser compatibility issue with IE9, added a line
   3.0 		  Setty				10/31/2012  Web-FinancialX-Ray page@ Diff Lead source lead insert
*/  
public with sharing class XrayWizardController 
{
	public List<Question_Bank_List__c> lstQuestions {get;set;}
  	public List<Questionnaire__c> lstQuestionnaire {get;set;}
  	public List<Question_Bank__c> lstQuestionBank{get;set;}
  	public Question_Bank__c objActiveQuestionBank {set;get;}
   	public List<SelectQuestionAnswer> lstOfQuestionAnswer {get;set;}
  	public Integer queNo{get;set;} 
  	public Map<ID,List<Question_Option_List__c>> mapQuesIdAnswers{set;get;}  
  	public Lead objLead{set;get;}
  	Map<ID,Question_Option_List__c> mapOfOptionList{set;get;}
  	List<XRay_ScoreCard__c> lstXrayScoreCard = new List<XRay_ScoreCard__c> ();
  	public Boolean displayPopUp {get; set;}  
  	public Double dblFreedomScore{set;get;}  
  	public Integer quesSequence { get;set; }
  
  	/**** Constructor ****/
  	public XrayWizardController()
  	{
	    Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=8');//Added to remove IE9 compatibility issue
	    quesSequence = 0; 
	    mapOfOptionList = new Map<ID,Question_Option_List__c> ();
	    objLead = new Lead();
	    mapQuesIdAnswers = new Map<ID,List<Question_Option_List__c>>();
	    lstQuestions = new List<Question_Bank_List__c>();
	    lstQuestionnaire = new List<Questionnaire__c>();
	    lstQuestionBank = new List<Question_Bank__c>();
	    lstOfQuestionAnswer = new List<SelectQuestionAnswer>();
	    //Custom Setting used for collecting id of X-Ray questions
	    Map<String, QuestionBank__c> QuestionBank = QuestionBank__c.getAll();
	    String finXRayId = QuestionBank.get('FinancialXRay').Question_Bank__c;
	    objActiveQuestionBank  = [select id,Name,IsActive__c from Question_Bank__c  where IsActive__c =true and Id =: finXRayId limit 1]; 
  	}
  
  	/**** Action Method ****/
  	public Pagereference Init()
  	{
    	set<ID>setOfIds = new set<ID>();
    
    	lstQuestionnaire =[SELECT q.Question_Bank__c,
                q.Question_Bank_List__r.Question__c,
                q.Question_Bank_List__r.Name, 
                q.Display_Sequence__c ,
                q.Question_Bank_List__c,
                q.Name, q.Id ,
                q.Question_Bank_List__r.Parent_Question__c,
                q.Question_Bank_List__r.Question_Type__c,
                q.Question_Bank_List__r.Criteria__c, 
                q.Question_Bank_List__r.IsDummy__c 
                FROM Questionnaire__c q where q.Question_Bank__c =:objActiveQuestionBank.Id
                order by q.Display_Sequence__c ASC];
    
    	if(lstQuestionnaire  != null && lstQuestionnaire .size() >0)
    	{
      		for(Questionnaire__c objQuestionnaire :lstQuestionnaire)
      		{
        		setOfIds.add(objQuestionnaire.Question_Bank_List__c);  
      		}
          
      		//populating the question and its answer.
      		for(Question_Option_List__c objAnswer: [Select q.Score__c, q.Question_Bank_List__c, q.Name, q.Id From Question_Option_List__c q where Question_Bank_List__c IN:setOfIds])
      		{
        		mapOfOptionList.put(objAnswer.Id,objAnswer);
        		if(!mapQuesIdAnswers.isEmpty() && mapQuesIdAnswers.containsKey(objAnswer.Question_Bank_List__c))
        		{
          			List<Question_Option_List__c> lstAnswers = mapQuesIdAnswers.get(objAnswer.Question_Bank_List__c);
          			lstAnswers.add(objAnswer);
          			mapQuesIdAnswers.put(objAnswer.Question_Bank_List__c,lstAnswers);
        		}
        		else
        		{
          			List<Question_Option_List__c> lstAnswers = new List<Question_Option_List__c>();
		          	lstAnswers.add(objAnswer);
          			mapQuesIdAnswers.put(objAnswer.Question_Bank_List__c, lstAnswers);
        		}
      		}
      
      		for(Integer iCount =0;iCount < lstQuestionnaire.size() ;iCount++)
      		{
        		SelectQuestionAnswer objSelectQuesAnswer = new SelectQuestionAnswer();
        		objSelectQuesAnswer.objQuestionnaire = lstQuestionnaire[iCount]; 
        
        		if(!mapQuesIdAnswers.isEmpty()&& mapQuesIdAnswers.containsKey(lstQuestionnaire[iCount].Question_Bank_List__c))
        		{
          			List<Question_Option_List__c> lstAnswer = mapQuesIdAnswers.get(lstQuestionnaire[iCount].Question_Bank_List__c);
          			if(lstAnswer != null && lstAnswer.size()>0)
          			{
            			for(Question_Option_List__c objAns :lstAnswer)
            			{
              				objSelectQuesAnswer.strAnswer.add(new Selectoption(objAns.Id, objAns.Name));
            			}
          			}
        		}
	        
        		if(lstQuestionnaire[iCount].Question_Bank_List__r.Question_Type__c == 'Yes/No')
        		{
            		objSelectQuesAnswer.isMultiChoice = false;
        		}
	        
        		else if(lstQuestionnaire[iCount].Question_Bank_List__r.Question_Type__c == 'Multichoice')
        		{
          			objSelectQuesAnswer.isMultiChoice = true;
        		}
        
        		objSelectQuesAnswer.qno = iCount;
        		if(iCount==0)
        		{
          			objSelectQuesAnswer.isCurrentQuestn = true;
          			objSelectQuesAnswer.isVisited = true;
        		}
        		lstOfQuestionAnswer.add(objSelectQuesAnswer);
      		}
    	}
    	return null;
  	}
  
  	/**** Action on Next button *****/ 
  	public Pagereference goToNextQuestn()
  	{ 
    	if(queNo != null)
    	{
      		if(queNo < lstOfQuestionAnswer.size()-1)
      		{
        		if(lstOfQuestionAnswer[queNo].objQuestionnaire.Question_Bank_List__r.Question_Type__c  == 'Yes/No')
        		{
          			if(lstOfQuestionAnswer[queNo].selectedAnswer !=Null)
          			{ 
            			lstOfQuestionAnswer[queNo].isCurrentQuestn = false;
            			String tempParentId = null; 
            			if(!mapOfOptionList.isEmpty() && mapOfOptionList.containsKey(lstOfQuestionAnswer[queNo].selectedAnswer))
            			{
              				Question_Option_List__c objOptionList = mapOfOptionList.get(lstOfQuestionAnswer[queNo].selectedAnswer);
              				if(objOptionList.Name != lstOfQuestionAnswer[queNo].objQuestionnaire.Question_Bank_List__r.Criteria__c)
              				{
                				Integer index = 0;
                				for( index = queNo;index < lstOfQuestionAnswer.size()-1 ;index++)
                				{
                  					tempParentId = lstOfQuestionAnswer[index].objQuestionnaire.Question_Bank_List__c;
                  					if(tempParentId == (lstOfQuestionAnswer[index  + 1].objQuestionnaire.Question_Bank_List__r.Parent_Question__c ))
                  					{
                    					tempParentId = lstOfQuestionAnswer[index + 1].objQuestionnaire.Question_Bank_List__r.Parent_Question__c;
                  					}
                  					else
                  					{
                    					break;
                  					}
                				}
                				queNo = index;
              				}
              				quesSequence = quesSequence + 4;
            			}
            			lstOfQuestionAnswer[queNo].isCurrentQuestn = false;
            			lstOfQuestionAnswer[queNo+1].isCurrentQuestn = true;
            			lstOfQuestionAnswer[queNo+1].isVisited = true;
          			}
          			else
          			{
            			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Please select your Option');
            			ApexPages.addMessage(myMsg);
          			}
        		}
        		else if(lstOfQuestionAnswer[queNo].selMultipleAnswrs.size() > 0)
        		{
          			quesSequence = quesSequence + 4;
          			if(lstOfQuestionAnswer[queNo].objQuestionnaire.Question_Bank_List__r.Question_Type__c == 'Multichoice')
          			{
			            lstOfQuestionAnswer[queNo].isCurrentQuestn = false;
			            lstOfQuestionAnswer[queNo+1].isCurrentQuestn = true;
			            lstOfQuestionAnswer[queNo+1].isVisited = true;
          			}
        		}
        		else
        		{
          			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Please select your Option');
          			ApexPages.addMessage(myMsg);
        		}
      		}
    	}
    	return null;
  	}
  
  
  	/**** Action on Previous button *****/
  	public Pagereference goToPrevQuestn()
  	{
    	if(queNo != null)
    	{
      		if(queNo > 0)
      		{
		        lstOfQuestionAnswer[queNo].isCurrentQuestn = false;
		        lstOfQuestionAnswer[queNo].isVisited = false;
		        String tempParentId =null; 
		        Integer index = 0;
		        for( index = queNo -1;index > 0;index--)
		        {
          			if(lstOfQuestionAnswer[index].isVisited)
          			{
            			break;
          			}
          			tempParentId =lstOfQuestionAnswer[index].objQuestionnaire.Question_Bank_List__r.Parent_Question__c;
		          
          			if(tempParentId == (lstOfQuestionAnswer[index -1].objQuestionnaire.Question_Bank_List__c))
          			{
            			tempParentId = lstOfQuestionAnswer[index - 1].objQuestionnaire.Question_Bank_List__c;
          			}
          			else
          			{
            			break;
          			}
        		}
        		quesSequence = quesSequence - 4;
        		queNo = index;
      		}
      		lstOfQuestionAnswer[queNo].isCurrentQuestn = true;
      		lstOfQuestionAnswer[queNo].isVisited = true;
    	}
    	return null;
  	}
  
  
  	/***** Action on Submit *****/
  	public Pagereference saveDetailsOfCandidate()
  	{
    	Set<ID> setInsertedScorecardIds = new Set<ID>();
    	Database.Saveresult saveResult;
    	X_Ray_Score_Card_Detail__c objXrayScoreCardDetail ;
    	Pagereference pgRef;
    
    	if(objLead.FirstName == null)
    	{
      		objLead.FirstName.addError('You must enter a value');
    	}
    	else if(objLead.Email == null)
    	{
      		objLead.Email.addError('You must enter a value');
    	}
    
    	else
    	{
      		//User objMkgTeam = [Select Id, Name from User where Name = 'Ffreedom Team' limit 1];
      		//User objMkgTeam = [Select Id, Name from User where Name = 'Ffreedom Team' limit 1];
      		objLead.Ffreedom_Score__c = dblFreedomScore;
      		//objLead.LeadSource = Label.Lead_Source_Web;
      		//objLead.OwnerId = objMkgTeam.Id;
      		saveResult = Database.insert(objLead);
      		system.debug('Lead succefully inserted*****objLead.Name*******'+objLead.Name+'%%%%%%%%%%%objLead.Source%%%%%%%%%%%'+objLead.LeadSource);
    		if(saveResult.isSuccess())
    		{
        		try
        		{
            		objXrayScoreCardDetail =  new  X_Ray_Score_Card_Detail__c ();
            		objXrayScoreCardDetail.Lead__c = saveResult.getId();
            		objXrayScoreCardDetail.Question_Bank__c = objActiveQuestionBank.Id;
            		saveResult = Database.insert(objXrayScoreCardDetail);
        		}
        		catch(Exception ex)
        		{
          			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
         			String[] toAddresses = new String[] {'tech@ffreedom.in'};
        			mail.setToAddresses(toAddresses);
        			mail.setSenderDisplayName('Salesforce Support');
        			mail.setSubject('Error in Lead Creation by X-Ray from site');
          			mail.setPlainTextBody(' Error : '+ex.getMessage()+' Lead Id ----> : ' + saveResult.getId());
          			Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        		}
          		if(saveResult.isSuccess())
          		{
            		if(lstOfQuestionAnswer.size() > 0)
            		{
              			List<Option_Detail__c> lstOfOptionDetailsToInsert = new List<Option_Detail__c>();   
              			Map<ID,XRay_ScoreCard__c> mapQuesIdXrayScoreCard = new map<ID,XRay_ScoreCard__c> ();
              			XRay_ScoreCard__c objXrayScoreCard;
              			for(SelectQuestionAnswer objWrapper : lstOfQuestionAnswer)
              			{
                			objXrayScoreCard = new XRay_ScoreCard__c();
                			if(!objWrapper.objQuestionnaire.Question_Bank_List__r.IsDummy__c)
                			{
                  				ID userAnswer = String.valueOf(objWrapper.selectedAnswer);
                  				objXrayScoreCard.XRayScoreCardMaster__c = saveResult.getId();
                  				objXrayScoreCard.Display_Sequence__c = Double.valueOf(objWrapper.objQuestionnaire.Display_Sequence__c);
                  				objXrayScoreCard.Question_Bank_List__c = objWrapper.objQuestionnaire.Question_Bank_List__c;
		                  
                  				if(objWrapper.isVisited)
                  				{
                    				if(!mapOfOptionList.isEmpty() && mapOfOptionList.containsKey(userAnswer))
                    				{
                      					Question_Option_List__c objOptionList = mapOfOptionList.get(userAnswer);
		                      
                      					if(objOptionList.Score__c != null)
                      					{
                        					objXrayScoreCard.Score_Master__c = objOptionList.Score__c;
                      					}
                    				}
                  				}
                			}  
                			else 
                			{                
                  				objXrayScoreCard.XRayScoreCardMaster__c = saveResult.getId();
                  				objXrayScoreCard.Display_Sequence__c = Double.valueOf(objWrapper.objQuestionnaire.Display_Sequence__c);
                  				objXrayScoreCard.Question_Bank_List__c = objWrapper.objQuestionnaire.Question_Bank_List__c;
                			}
                			lstXrayScoreCard.add(objXrayScoreCard);  
              			}
	              
              			if(lstXrayScoreCard.size() > 0 )
              			{
                			List<Database.Saveresult>  lstScoreCardSaveResult = Database.insert(lstXrayScoreCard);
                			if(lstScoreCardSaveResult != null && lstScoreCardSaveResult.size() > 0)
                			{
                  				for(Database.Saveresult objSaveResult : lstScoreCardSaveResult)
                  				{
                    				setInsertedScorecardIds.add(objSaveResult.getId());
                  				}
                			}
              			}
		            
              			for(XRay_ScoreCard__c  objXrayScorecardInserted:[Select x.Score_Master__c, x.Question_Bank_List__c, x.Name, x.Id, x.Display_Sequence__c, x.Answer_Question_Master__c From XRay_ScoreCard__c x where Id IN: setInsertedScorecardIds])
              			{
                			mapQuesIdXrayScoreCard.put(objXrayScorecardInserted.Question_Bank_List__c,objXrayScorecardInserted);
              			}
	              
              			Option_Detail__c objOptionDetails;
              			Question_Option_List__c objOptionList;
              			for(SelectQuestionAnswer objWrapper : lstOfQuestionAnswer)
              			{
                			if(objWrapper.isVisited)
                			{
                  				if(objWrapper.objQuestionnaire.Question_Bank_List__r.Question_Type__c =='Yes/No')
                  				{
                    				ID userAnswer = String.valueOf(objWrapper.selectedAnswer);
		                    
                    				if(!mapOfOptionList.isEmpty() && mapOfOptionList.containsKey(userAnswer))
                    				{
                      					objOptionDetails = new Option_Detail__c ();
                      					objOptionList = mapOfOptionList.get(userAnswer);
                      					objOptionDetails.Answer__c = objOptionList.Id;
                        				objOptionDetails.Answer_Text__c = objOptionList.Name;
                        				objOptionDetails.QuestionMaster__c = objOptionList.Question_Bank_List__c;
                        				if(!mapQuesIdXrayScoreCard.isEmpty() && mapQuesIdXrayScoreCard.containsKey(objWrapper.objQuestionnaire.Question_Bank_List__c))
                        				{
                          					objOptionDetails.XRayScoreCard__c = mapQuesIdXrayScoreCard.get(objWrapper.objQuestionnaire.Question_Bank_List__c).Id;
                        				}
                        				lstOfOptionDetailsToInsert.add(objOptionDetails);
                    				}
                  				}
                  				else if(objWrapper.objQuestionnaire.Question_Bank_List__r.Question_Type__c == 'Multichoice')
                  				{
                    				List<String> lstMultichoiceAnswer = objWrapper.selMultipleAnswrs;
                    				for(String idAnswer:lstMultichoiceAnswer)
                    				{ 
                        				ID userAnswer = String.valueOf(idAnswer);
                          				if(!mapOfOptionList.isEmpty() && mapOfOptionList.containsKey(userAnswer))
                        				{
                            				objOptionDetails = new Option_Detail__c ();
                          					objOptionList = mapOfOptionList.get(userAnswer);
                          					objOptionDetails.Answer__c = objOptionList.Id;
                            				objOptionDetails.Answer_Text__c = objOptionList.Name;
                            				objOptionDetails.QuestionMaster__c = objOptionList.Question_Bank_List__c;
                            				if(!mapQuesIdXrayScoreCard.isEmpty() && mapQuesIdXrayScoreCard.containsKey(objWrapper.objQuestionnaire.Question_Bank_List__c))
                            				{
                              					objOptionDetails.XRayScoreCard__c = mapQuesIdXrayScoreCard.get(objWrapper.objQuestionnaire.Question_Bank_List__c).Id;
                            				}
                            				lstOfOptionDetailsToInsert.add(objOptionDetails);
                         				}
                    				}
                  				}
                			}
              			}
            			List<Database.Saveresult> lstSaveOptionDetais = Database.insert(lstOfOptionDetailsToInsert);
          			}
        		}
	  	  	}
      		pgRef = new Pagereference('/ThankYou');//Redirect to thank you page.
      		pgRef.setRedirect(true);
    	}
  		return pgRef;
  	}
    
   	public void showPopUp() 
   	{
     	if(lstOfQuestionAnswer.size() > 0)
     	{
       		dblFreedomScore = 0;
       		//Question_Option_List__c objOptionList;
       		for(SelectQuestionAnswer objSelect:lstOfQuestionAnswer)
       		{
         		if(objSelect.isVisited)
         		{
           			if(!objSelect.objQuestionnaire.Question_Bank_List__r.IsDummy__c)
           			{
               			ID userAnswer = String.valueOf(objSelect.selectedAnswer);
              			if(!mapOfOptionList.isEmpty() && mapOfOptionList.containsKey(userAnswer))
              			{
                			Question_Option_List__c objOptionList = mapOfOptionList.get(userAnswer);
                			dblFreedomScore = dblFreedomScore + objOptionList.Score__c;
              			}
           			}
         		}
       		}
	       
       		if(lstOfQuestionAnswer[lstOfQuestionAnswer.size()- 1].objQuestionnaire.Question_Bank_List__r.Question_Type__c  == 'Yes/No')
       		{
         		if(lstOfQuestionAnswer[lstOfQuestionAnswer.size()- 1].selectedAnswer != null)
         		{
           			displayPopUp=true;
             		quesSequence = quesSequence + 4;
         		}
         		else
         		{
           			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Please select your Option');
          			ApexPages.addMessage(myMsg);
         		}
       		}
       		else if(lstOfQuestionAnswer[lstOfQuestionAnswer.size()- 1].selMultipleAnswrs.size()>0)
       		{
	            displayPopUp=true;
            	quesSequence = quesSequence + 4;
       		}
       		else
       		{
         		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Please select your Option');
        		ApexPages.addMessage(myMsg);
       		}
     	}
   	}
   
   	public void closePopup()
   	{
     	displayPopUp = false;
   	}  
 	/*    Eternus Solutions  
	      Author  : Setty 
	      Issue Id: 00001700       
	      Date    : 18/7/2012    
	      Purpose : Online promotion page Without Score Card Lead Insert
 		  *************************************************** */
   	public Pagereference saveDetailsOfCandidatewithoutScore()
  	{
      
      	//User objMkgTeam = [Select Id, Name from User where Name = 'Ffreedom Team' limit 1];
      	//objLead.LeadSource =Label.Lead_Source_Web;
      	//objLead.OwnerId = objMkgTeam.Id;
      	if(objLead.FirstName == null|| objLead.Email == null||objLead.LastName==null||objLead.MobilePhone==null)
      	{
	      	ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'You must enter a values which have *');
      		ApexPages.addMessage(myMsg);
      	}
      	else
      	{
      		Database.insert(objLead);
      		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.Error, 'Thank you for your interest in Ffreedom Financial Planners.');
      		ApexPages.addMessage(myMsg);
      	}
     	// displayPopUp=true;*/
      	Pagereference pgRef = new Pagereference('/ThankYou');//Redirect to Same page.
      	pgRef.setRedirect(true);
      	return pgRef;
   	}
   
   /*-------End---*/
  //Wrapper Class     
  	public class SelectQuestionAnswer
  	{
    	public List<Selectoption> strAnswer { get;set; }
    	public Boolean isMultiChoice{ get;set; }
    	public Boolean isCurrentQuestn { get;set; }
    	public Boolean isVisited { get;set; }
    	public Integer qno{  get;set; }
    	public ID selectedAnswer {get;set;}
    	public List<String> selMultipleAnswrs { get;set; }
    	public Questionnaire__c objQuestionnaire{ get;set;}
	    
    
    	/**** Constructor ****/
    	public SelectQuestionAnswer()
    	{
      		strAnswer = new List<SelectOption>();
      		selMultipleAnswrs  = new List<String>();
      		objQuestionnaire = new Questionnaire__c();
      		isVisited = false;
    	}  
  	}
}