Freedom Sanbox Ant Deploy/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Balance_No_of_Years__c</fullName>
        <description>years remaining to pay EMI</description>
        <label>Balance No. of Years</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EMI__c</fullName>
        <label>EMI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Institution__c</fullName>
        <label>Financial Institution</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fixed_Floating__c</fullName>
        <label>Fixed /Floating</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prepayment_terms__c</fullName>
        <label>Prepayment terms</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_Amount_Outstanding__c</fullName>
        <label>Principal Amount Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term_No_of_years__c</fullName>
        <label>Term (No. of years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/LiabilityBean.cls
/*
Revision History:

   Version     Version Author     Date          Comments
   1.0         Persistent         NA  		  	Initial Draft
   
   2.0         Niket Chandane	  05/06/2011    added the method getNetworthSummaryDetail() to fix the Issue F0035 for the NewworthPage
   												This method accept the AggregateResult and gets the Liability Type and it's value and set in the the
       						 					SummaryBean.SummaryDetail to show the List of liabilities on the NetworthPage
*/

public class LiabilityBean {
    
    public List<Loan__c> loanList { 
        get {
            if(loanList== null){
                loanList = new List<Loan__c>();
            }
            return loanList;
        } set;
    } 
     
    public static SummaryBean.SummaryDetail getSummary(AggregateResult result){
        Double totalLoan;       
        ID entityId;
        
        totalLoan = (Double)result.get('liabilities');
        SummaryBean.SummaryDetail summary = new SummaryBean.SummaryDetail('Liabilities',totalLoan);
        return summary;     
    }
    public static DataEntrySummaryBean getDataEntrySummary(DataEntrySummaryBean dataEntrySummaryBean,Map<ID,integer> indexMap,AggregateResult result){
                
        ID entityId;
        dataEntrySummaryBean.linkField = result.get('Loan_Type__c');    
        entityId = (ID) result.get('Entity__c');                        
        dataEntrySummaryBean.fieldList.set(indexMap.get(entityId),(Double)result.get('liabilities'));                                               
        return dataEntrySummaryBean;            
    }
    /**
        validate() function is used to check all required field are filled or not
    */
    public static void validate(Loan__c loanInstance) {                         
          
        if(loanInstance.Entity__c == null) {              
            throw new ValidationException(Label.EntityValidation);                           
        }      
        if((loanInstance.EMI__c == null) || loanInstance.EMI__c <=0) {              
            throw new ValidationException(Label.LoanEMIValidation);                           
        }
        if(loanInstance.Loan_Type__c == null) {             
            throw new ValidationException(Label.LoanTypeValidation);                         
        }
        /**
        * Modified by = Dipak Nikam
		* Case Subject = Need mandatory field for rate of interest in Liabilities Page
        * Case number  =  00001499 
        * Case owner =  Shewta Karia
        * Comment = Added below if loop for validation of Interest Rate %.
        **/
        if(((loanInstance.Interest_Rate__c== null) || (loanInstance.Interest_Rate__c <=0))) {
            throw new ValidationException(Label.InterrestRateValidation);
         }   
        if(((loanInstance.Balance_No_of_Years__c == null) || (loanInstance.Balance_No_of_Years__c <=0))) {
            throw new ValidationException(Label.BalanceNumberOfYearValidation);
        }   
    }
     /**
        isRowEmpty() function is used to check record is empty or not 
    */
    public static Boolean isRowEmpty(Loan__c loanInstance) {
                
        if((loanInstance.EMI__c == null) || (loanInstance.EMI__c == 0)) {
            if((loanInstance.Loan_Type__c == null)) {
                if(loanInstance.Financial_Institution__c == null) {
                    if(((loanInstance.Principal_Amount_Outstanding__c == null) || (loanInstance.Principal_Amount_Outstanding__c ==0))) {
                        if((loanInstance.Fixed_Floating__c == null) || (loanInstance.Fixed_Floating__c.trim().equals(''))){
                            if((loanInstance.Interest_Rate__c == null)) {
                                if((loanInstance.Balance_No_of_Years__c == null) || (loanInstance.Balance_No_of_Years__c == 0))
                                    if((loanInstance.Term_No_of_years__c== null) || (loanInstance.Term_No_of_years__c == 0))
                                        if((loanInstance.Prepayment_terms__c==null) || (loanInstance.Prepayment_terms__c.trim().equals('')))
                                            return true;        
                            }               
                        }               
                    }   
                }
            }
        }
        return false;            
    }
    /*
       Function Created By : Niket Chandane.
       Created On		   : 05 June 2011
       Summary 			   : This method accept the AggregateResult and gets the Liability Type and it's value and set in the the
       						 SummaryBean.SummaryDetail to show the List of liabilities on the NetworthPage [Issue F0035]
    */
    
     public static SummaryBean.SummaryDetail getNetworthSummaryDetail(AggregateResult liability){
        SummaryBean.SummaryDetail networthSummary;
        String liablityType;
        Double liablityValue;
        
        liablityType = (String)liability.get('Loan_Type__c');
        liablityValue = (Double) liability.get('liabilities');
        
        networthSummary = new SummaryBean.SummaryDetail(liablityType,liablityValue);  
        return networthSummary;
    }
}