Freedom Sanbox Ant Deploy/src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Balance_No_of_Years__c</fullName>
        <description>years remaining to pay EMI</description>
        <label>Balance No. of Years</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EMI__c</fullName>
        <label>EMI</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loans</relationshipLabel>
        <relationshipName>Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Institution__c</fullName>
        <label>Financial Institution</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Fixed_Floating__c</fullName>
        <label>Fixed /Floating</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Floating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prepayment_terms__c</fullName>
        <label>Prepayment terms</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Principal_Amount_Outstanding__c</fullName>
        <label>Principal Amount Outstanding</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Term_No_of_years__c</fullName>
        <label>Term (No. of years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LN-{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/RecTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will store the all record type names that we will hard code in the apex code. Always take the record type name from here instead pf hardcode in apex</description>
    <fields>
        <fullName>Record_Type_Value__c</fullName>
        <label>Record Type Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>RecTypes</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/LoanControllerTest.cls
/*
Revision History:

		Version     Version Author     Date        Comments
		1.0         --           	   --	  	   Initial Draft
		2.0  		Prajakta Sanap     23/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.				   				 					   
*/

@isTest
private class LoanControllerTest 
{
    static Account account;
    static LoanController LoanTest;
    public static List<SelectOption> options;
    
    public static void setupData()
    {
    	TestData_Ffreedom testData = new TestData_Ffreedom();
		account = testData.initializeAccount();
        //account=new Account(FirstName='ABC',LastName='DEF',RecordTypeId= RecTypes__c.getInstance('AccountClient').Record_Type_Value__c);//Gaurav '01220000000DnK3AAK');
        upsert account;
        
        Loan__c loan1 = testData.init_Loan(account);
        /*Loan__c loan1=new Loan__c(Entity__c=account.id,EMI__c = 300,Loan_Type__c = 'Auto Loan' ,
                                Balance_No_of_Years__c =2);*/
        upsert loan1;
        System.assertNotEquals(null,loan1.id);
        
        Loan__c loan5 = testData.init_Loan(account);
        //Loan__c loan5=new Loan__c(Entity__c=account.id,EMI__c = 0,Loan_Type__c = '' ,
          ///                      Balance_No_of_Years__c =0,Financial_Institution__c ='',Principal_Amount_Outstanding__c=0,
             //                   Interest_Rate__c=4,Term_No_of_years__c=0,Prepayment_terms__c='',Fixed_Floating__c='');
        upsert loan5;
        System.assertNotEquals(null,loan5.id);
        ApexPages.currentPage().getParameters().put('EntityId',account.id);
        LoanTest=new LoanController();
      
        List<AggregateResult> liabilitiesList = new DatabaseSOQL().getLiabilitiesList(account.id);
        LiabilityBean.getSummary(liabilitiesList.get(0));
    }
    
    public static void setupDataNoLoan()
    {
    	TestData_Ffreedom testData = new TestData_Ffreedom();
		account = testData.initializeAccount();
        //account=new Account(FirstName='ABC',LastName='DEF',RecordTypeId= RecTypes__c.getInstance('AccountClient').Record_Type_Value__c);//Gaurav '01220000000DnK3AAK');
        upsert account;
        
        ApexPages.currentPage().getParameters().put('EntityId',account.id);
        LoanTest=new LoanController();
    }
    
    public static void setupDataNoLoanwithType()
    {
    	TestData_Ffreedom testData = new TestData_Ffreedom();
		account = testData.initializeAccount();
        //account=new Account(FirstName='ABC',LastName='DEF',RecordTypeId=RecTypes__c.getInstance('AccountClient').Record_Type_Value__c);//Gaurav '01220000000DnK3AAK');
        upsert account;
        ApexPages.currentPage().getParameters().put('EntityId',account.id);
        LoanTest=new LoanController();
    }
    
    public static testMethod void TestLoan()
    {
        Test.startTest();
        setupData();
        TestData_Ffreedom testData = new TestData_Ffreedom();
        Loan__c loan3 = testData.init_Loan(account);
            //Loan__c loan3=new Loan__c(Entity__c=account.id,EMI__c = 0,Loan_Type__c = 'Credit Card Loan' ,
             //                   Balance_No_of_Years__c =2);
        upsert loan3;
        System.assertNotEquals(null,loan3.id);
        LoanTest.loanSummaryForDataEntry[0].linkField ='Auto Loan';
        System.currentPageReference().getParameters().put('selectedLoanType','Auto Loan');
        LoanTest.showPopUp();
          LiabilityBean lbean=LoanTest.loanBean;
        LoanTest.closePopUp();
        LoanTest.getOwnerItems();
        LoanTest.addNewRow();
        LoanTest.Remove();
        LoanTest.Save();
        LoanTest.getOwnerItems();
        test.stopTest();
    }
    
    public static testMethod void TestCreditCardLoan()
    {
        Test.startTest();
        setupData();
        TestData_Ffreedom testData = new TestData_Ffreedom();
        Loan__c loan2 = testData.init_Loan(account);
         //Loan__c loan2=new Loan__c(Entity__c=account.id,EMI__c = 300, Balance_No_of_Years__c =2);
        upsert loan2;
        System.assertNotEquals(null,loan2.id);
        LoanTest.loanSummaryForDataEntry[0].linkField ='Credit Card Loan';
        System.currentPageReference().getParameters().put('selectedLoanType','Credit Card Loan');
        LoanTest.showPopUp();
          LiabilityBean lbean=LoanTest.loanBean;
        LoanTest.closePopUp();
        LoanTest.getOwnerItems();
       // LoanTest.checkOwnerChange();
        LoanTest.addNewRow();
        LoanTest.Remove();
        LoanTest.Save();
        LoanTest.getOwnerItems();
        test.stopTest();
    }
    
    public static testMethod void TestHomeLoan()
    {
        Test.startTest();
        setupData();
        TestData_Ffreedom testData = new TestData_Ffreedom();
        Loan__c loan4 = testData.init_Loan(account);
        // Loan__c loan4=new Loan__c(Entity__c=account.id,EMI__c = 200,Loan_Type__c = 'Credit Card Loan' ,
                       //         Balance_No_of_Years__c =null);
        upsert loan4;
        System.assertNotEquals(null,loan4.id);
        LoanTest.loanSummaryForDataEntry[0].linkField ='Home Loan';
         System.currentPageReference().getParameters().put('selectedLoanType','Home Loan');
        LoanTest.showPopUp();
        LoanTest.closePopUp();
        LoanTest.getOwnerItems();
      //  LoanTest.checkOwnerChange();
        LoanTest.addNewRow();
        LoanTest.Remove();
        LoanTest.Save();
        LoanTest.getOwnerItems();
        test.stopTest();
    }
    
    public static testMethod void TestNoLoanType()
    {
        Test.startTest();
        setupDataNoLoan();
        LoanTest.loanSummaryForDataEntry[0].linkField ='';
        LoanTest.showPopUp();
        LoanTest.closePopUp();
     
        test.stopTest();
    }
    
    public static testMethod void setupDataNoLoanType()
    {
        Test.startTest();
        setupDataNoLoanwithType();
        LoanTest.loanSummaryForDataEntry[0].linkField ='Auto Loan';
        //LoanTest.selectedLoanType='Auto Loan';
        LoanTest.loanBean = null;
        LoanTest.showPopUp();
        LoanTest.closePopUp();
        LoanTest.getOwnerItems();
      // LoanTest.checkOwnerChange();
        LoanTest.addNewRow();
        LoanTest.Remove();
        LoanTest.Save();
     
        test.stopTest();
    }
}