Freedom Sanbox Ant Deploy/src/objects/Planner_Points__c.object
<CustomObject>
    <fields>
        <fullName>Month__c</fullName>
        <label>Month</label>
        <type>Date</type>
    </fields>
    <label>Planner Points</label>
    <nameField>
        <label>Planner  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planner Points</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Related_Entity_Points__c.object
<CustomObject>
    <fields>
        <fullName>Entity_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Entity Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Entity Points</relationshipLabel>
        <relationshipName>Related_Entity_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planner_Points__c</fullName>
        <label>Planner Points</label>
        <referenceTo>Planner_Points__c</referenceTo>
        <relationshipLabel>Related Entity Points</relationshipLabel>
        <relationshipName>Related_Entity_Points</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Entity Points</label>
    <nameField>
        <label>Related Entity Points Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Related Entity Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestBatchPointCalculator.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestBatchPointCalculator {
        // TO DO: implement unit test
     static testMethod void testBatchPointsCalculator() { 
    	
        Test.startTest();
    	List<User> lstUser = [Select u.IsActive,u.Name, u.Id From User u Where u.IsActive = True and u.Profile.Name = 'System Administrator'];
		
		Account objAccount = new Account(LastName = 'Test Account');
		insert objAccount;
    	Database.Batchablecontext BC;
    	Planner_Points__c objPlannerPoint = new Planner_Points__c(Month__c = System.today());
    	insert objPlannerPoint;
    	Related_Entity_Points__c objRelatedEntityPoint = new Related_Entity_Points__c(Entity_Name__c = objAccount.Id, Planner_Points__c = objPlannerPoint.Id);
    	insert objRelatedEntityPoint;
    	BatchPointsCalculator objBatchPointsCalculator = new BatchPointsCalculator();
    	objBatchPointsCalculator.setParentId.add(objPlannerPoint.Id);
    	objBatchPointsCalculator.query='SELECT ID, Name  FROM User';
    	Database.executeBatch(objBatchPointsCalculator,1);
    	objBatchPointsCalculator.execute(BC, lstUser);
    	objBatchPointsCalculator.finish(BC);
    	Test.stopTest();
	}
	
}