Freedom Sanbox Ant Deploy/src/objects/Product_Recommendation_Master__c.object
<CustomObject>
    <fields>
        <fullName>CustomUniqueKey__c</fullName>
        <label>CustomUniqueKey</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <referenceTo>Product_Master__c</referenceTo>
        <relationshipLabel>Product Recommendations</relationshipLabel>
        <relationshipName>Product_Recommendation_Masters</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recommendation_End_date__c</fullName>
        <defaultValue>TODAY() + 30</defaultValue>
        <label>Recommendation End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recommendation_Start_date__c</fullName>
        <label>Recommendation Start date</label>
        <type>Date</type>
    </fields>
    <label>Product Recommendation</label>
    <nameField>
        <displayFormat>PREC-{0000000}</displayFormat>
        <label>Product Recommendation Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Recommendations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/DupeCheckRecommendation.cls
/*
*   Helper code that is invoked for an ProductRecommendationHandler classes. 
*   Dupes are checked for a given Product Recommendation Start Date and  
*   Recommendation Start Date and Statos should be same as there should exist only one 
*   record at a time.
*   
*   Revision History:
*
*	Version		Author				Date			Description
*	1.0			Prajakta Sanap		16/01/2013		Initial Draft
*
*/


public with sharing class DupeCheckRecommendation 
{
    /* Function to check duplicates for the records to be inserted */
	public void validate(List<Product_Recommendation_Master__c> lstProductRec)
	{
		/* To define Uniqueness
         * CustomUniqueKey__c = mark as Unique (50)     
         */
		for(Product_Recommendation_Master__c objProd  : lstProductRec)
		{
	        objProd.CustomUniqueKey__c = objProd.Product_Code__c +
	        							 String.valueOf(objProd.Recommendation_Start_date__c) + 
	        							 String.valueOf(objProd.Recommendation_End_date__c);
	    }
	}
}