Freedom Sanbox Ant Deploy/src/objects/Profiler_Card_Detail__c.object
<CustomObject>
    <description>To store details of each question and answer in profile question for each account</description>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <label>Display Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Profiler_Score_Card__c</fullName>
        <label>Profiler Score Card</label>
        <referenceTo>Profiler_Score_Card__c</referenceTo>
        <relationshipLabel>Profiler Card Details</relationshipLabel>
        <relationshipName>Profiler_Card_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Profiler Card Details</relationshipLabel>
        <relationshipName>Profiler_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Option_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Option List</label>
        <referenceTo>Question_Option_List__c</referenceTo>
        <relationshipLabel>Profiler Card Details</relationshipLabel>
        <relationshipName>Profiler_Card_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Profiler Card Detail</label>
    <nameField>
        <label>Profiler Card Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiler Card Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Profiler_Score_Card__c.object
<CustomObject>
    <description>Created to generate score card for profiler question-answers</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Profiler Score Cards</relationshipLabel>
        <relationshipName>Profiler_Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipLabel>Profiler Score Cards</relationshipLabel>
        <relationshipName>Profiler_Score_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <description>Sum up the score of all the scores from each profiler card details</description>
        <label>Score</label>
        <summarizedField>Profiler_Card_Detail__c.Score__c</summarizedField>
        <summaryForeignKey>Profiler_Card_Detail__c.Profiler_Score_Card__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Profiler Score Card</label>
    <nameField>
        <label>Profiler Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiler Score Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank__c.object
<CustomObject>
    <description>This will be the question bank and act as a master object to Questionnaire.</description>
    <fields>
        <fullName>IsProfilerQue__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsProfilerQue</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{00}</displayFormat>
        <label>Question Bank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank_List__c.object
<CustomObject>
    <description>This will store all the questions  and will act as a master table to Questionnaire. Dummy questions will not have any answer (No Points).</description>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multichoice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Option_List__c.object
<CustomObject>
    <description>This will store the options for each question in the pool,  the score to be given and the feedback to be displayed.</description>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Option Lists</relationshipLabel>
        <relationshipName>Question_Option_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question Option List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Option Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Questionnaire__c.object
<CustomObject>
    <description>This will give the ability to configure the questions for a particular questionnaire.</description>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <label>Display Sequence</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ProfQuestionPageControllerTest.cls
/* 
*  Test class created for ProfQuestionPageController
*
*   Revision History:
*
*   Version			Author             Date          Description
*   1.0         Prajakta Sanap		18/07/2013 	 	Initial Draft 
*/


@isTest
private class ProfQuestionPageControllerTest 
{
    static testMethod void profilerTest() 
    {
        Test.startTest();
    	TestData_Ffreedom testData = new TestData_Ffreedom();
    	List<Account> lstAccount = new List<Account>();
    	
    	Account objAccount = testData.initializeAccount();
	    lstAccount.add(objAccount);
	    insert lstAccount;
	    
	    Question_Bank__c  questionBank =  getQuestionBank();
	    insert questionBank;	
	    
	    List<Question_Bank_List__c>  lstQuestionBankList = getQuestionBankList();
	    insert lstQuestionBankList;
	     
	    List<Questionnaire__c> lstQuestionnaire = getQuestionnaire(questionBank.Id , lstQuestionBankList[0].Id);
	    insert lstQuestionnaire;	
	     
	    List<Question_Option_List__c> lstQuestionOption =  getQuestionOptionList(lstQuestionBankList[0].Id);
	    insert lstQuestionOption;
	    
	    List<Profiler_Score_Card__c> lstProfileScoreCard = getProfileScoreCardList(questionBank.Id , objAccount.Id);
	    insert lstProfileScoreCard;
	    
	    List<Profiler_Card_Detail__c> lstProfileCardDetail = getProfileCardDetailList(lstProfileScoreCard[0].Id, lstQuestionBankList[0].Id, lstQuestionOption[0].Id);
	    insert lstProfileCardDetail;
	    
	    Apexpages.currentPage().getParameters().put('entityId',objAccount.id);
	    ProfQuestionPageController objProfilerQue = new ProfQuestionPageController();
	    
	    objProfilerQue.Init();
	    objProfilerQue.lstOfQuestionAnswer[0].selectedAnswer = lstQuestionOption[0].Id;
	    objProfilerQue.lstOfQuestionAnswer[1].selectedAnswer = lstQuestionOption[1].Id;
	    
	    objProfilerQue.save();
	    objProfilerQue.isProfilerOutput = false;
	    objProfilerQue.isProfilerQuestion = true;
	    objProfilerQue.totalScore = 55;
	    
		test.stopTest();
    }
    
    static testMethod void profilerScoreCardTest() 
    {
        Test.startTest();
    	TestData_Ffreedom testData = new TestData_Ffreedom();
    	List<Account> lstAccount = new List<Account>();
    	
    	Account objAccount = testData.initializeAccount();
	    lstAccount.add(objAccount);
	    insert lstAccount;
	    
	    Question_Bank__c  questionBank =  getQuestionBank();
	    insert questionBank;	
	    
	    List<Question_Bank_List__c>  lstQuestionBankList = getQuestionBankList();
	    insert lstQuestionBankList;
	     
	    List<Questionnaire__c> lstQuestionnaire = getQuestionnaire(questionBank.Id , lstQuestionBankList[0].Id);
	    insert lstQuestionnaire;	
	     
	    List<Question_Option_List__c> lstQuestionOption =  getQuestionOptionList(lstQuestionBankList[0].Id);
	    insert lstQuestionOption;
	    
	    List<Profiler_Score_Card__c> lstProfileScoreCard = new List<Profiler_Score_Card__c>();
	    insert lstProfileScoreCard;
	    /*List<Profiler_Score_Card__c> lstProfileScoreCard = getProfileScoreCardList(questionBank.Id , objAccount.Id);
	    insert lstProfileScoreCard;
	    
	    List<Profiler_Card_Detail__c> lstProfileCardDetail = getProfileCardDetailList(lstProfileScoreCard[0].Id, lstQuestionBankList[0].Id, lstQuestionOption[0].Id);
	    insert lstProfileCardDetail;*/
	    
	    Apexpages.currentPage().getParameters().put('entityId',objAccount.id);
	    ProfQuestionPageController objProfilerQue = new ProfQuestionPageController();
	    objProfilerQue.Init();
	    objProfilerQue.Reset();
	    //objProfilerQue.save();
	    objProfilerQue.isProfilerOutput = false;
	    objProfilerQue.isProfilerQuestion = true;
	    objProfilerQue.totalScore = 55;
	    
		test.stopTest();
    }
    
    //Create Question Bank for Wellness
    private static Question_Bank__c getQuestionBank()
    {
    	return new Question_Bank__c(IsProfilerQue__c = true);
    }
    
    //Create Require Data for Questionnaire
    private static List<Question_Bank_List__c> getQuestionBankList()
    {
    	List<Question_Bank_List__c> lstQuestionBankList = new List<Question_Bank_List__c>();
    	
    	Question_Bank_List__c qBankList = new Question_Bank_List__c(
	    									  Question__c = 'My Current Stage of Life Best Described As Follows:',
	    									  Question_Type__c = 'Yes/No');
    	lstQuestionBankList.add(qBankList);								  
    									  
        Question_Bank_List__c qBankList1 = new Question_Bank_List__c(
	    									  Question__c = 'Number of people (other than yourself) dependent on your income?',
	    									  Question_Type__c = 'Yes/No');
    	lstQuestionBankList.add(qBankList1);
    	
    	Question_Bank_List__c qBankList2 = new Question_Bank_List__c(
	    									  Question__c = 'What is your view regarding the stability of your income?',
	    									  Question_Type__c = 'Yes/No');
	    lstQuestionBankList.add(qBankList2);	
	    
	    Question_Bank_List__c qBankList3 = new Question_Bank_List__c(
	    									  Question__c = 'How well do you understand investing and the equity market?',
	    									  Question_Type__c = 'Yes/No');
	    lstQuestionBankList.add(qBankList3);									  								  
    	Question_Bank_List__c qBankList4 = new Question_Bank_List__c(
	    									  Question__c = 'You have three investment options to choose from:',
	    									  Question_Type__c = 'Yes/No');
	    lstQuestionBankList.add(qBankList4);									  
	    Question_Bank_List__c qBankList5 = new Question_Bank_List__c(
	    									  Question__c = 'You invest Rs 1,00,000 in a fund that goes down by 8% the next day. You ?',
	    									  Question_Type__c = 'Yes/No');
	    lstQuestionBankList.add(qBankList5); 									  
    	return lstQuestionBankList;
    }
    
    //Create Require Data for Questionnaire
    private static List<Questionnaire__c> getQuestionnaire(Id pQuestionBankId, Id pQuestionBankListId){
    	
    	List<Questionnaire__c> lstQuestionnaire = new List<Questionnaire__c>();
    	
    	Questionnaire__c Questionnaire1 = new Questionnaire__c(
	    									  Question_Bank__c = pQuestionBankId,
	    									  Question_Bank_List__c = pQuestionBankListId,
	    									  Display_Sequence__c = '1');
    									  
    	 lstQuestionnaire.add(Questionnaire1);								  
    									  
        Questionnaire__c Questionnaire2 = new Questionnaire__c(
	    									  Question_Bank__c = pQuestionBankId,
	    									  Question_Bank_List__c= pQuestionBankListId,
	    									  Display_Sequence__c = '2');
    									  
    	lstQuestionnaire.add(Questionnaire2);
    	
    	return lstQuestionnaire;
    }
    
    //Create Require Data for Question Option List
    private static List<Question_Option_List__c> getQuestionOptionList(Id pQuestionBankListId){
    	
    	List<Question_Option_List__c> lstQuestionOption = new List<Question_Option_List__c>();
    	Question_Option_List__c QuestionOption1 = new Question_Option_List__c(
			    									  Name = 'No',
			    									  Score__c = 5,
			    									  Question_Bank_List__c = pQuestionBankListId);
    									  
    	lstQuestionOption.add(QuestionOption1);								  
        Question_Option_List__c QuestionOption2 = new Question_Option_List__c(
			    									  Name = 'Yes',
			    									  Score__c= 5,
			    									  Question_Bank_List__c = pQuestionBankListId);
    									  
    	lstQuestionOption.add(QuestionOption2);
    	return lstQuestionOption;
    }
    
    //Create Require Data for Profiler_Score_Card__c List for Entity
    private static List<Profiler_Score_Card__c> getProfileScoreCardList(Id pQuestionBankId, Id pRecordId){
    	
    	List<Profiler_Score_Card__c> lstProfileScoreCard = new List<Profiler_Score_Card__c>();
    	Profiler_Score_Card__c ProfileScoreCard1 = new Profiler_Score_Card__c(
				    									Name = 'Test1',
				    									Account__c = pRecordId,
				    								    Question_Bank__c = pQuestionBankId);
    	lstProfileScoreCard.add(ProfileScoreCard1);								  
    	return lstProfileScoreCard;
    }
    
    //Create Require Data for Profiler_Score_Card__c List for Entity
    private static List<Profiler_Card_Detail__c> getProfileCardDetailList(Id pProfileScoreCardId, Id pQuestionBankListId, Id pQuestionOptionListId){
    	
    	List<Profiler_Card_Detail__c> lstProfileCardDetail = new List<Profiler_Card_Detail__c>();
    	Profiler_Card_Detail__c ProfileCardDetail1 = new Profiler_Card_Detail__c(
				    									Name = 'Test1',
				    									Question_Bank_List__c = pQuestionBankListId,
				    									Question_Option_List__c = pQuestionOptionListId,
				    								    Profiler_Score_Card__c = pProfileScoreCardId);
    	lstProfileCardDetail.add(ProfileCardDetail1);

		Profiler_Card_Detail__c ProfileCardDetail2 = new Profiler_Card_Detail__c(
				    									Name = 'Test2',
				    									Question_Bank_List__c = pQuestionBankListId,
				    									Question_Option_List__c = pQuestionOptionListId,
				    								    Profiler_Score_Card__c = pProfileScoreCardId);
    	lstProfileCardDetail.add(ProfileCardDetail2);
		
		Profiler_Card_Detail__c ProfileCardDetail3 = new Profiler_Card_Detail__c(
				    									Name = 'Test2',
				    									Question_Bank_List__c = pQuestionBankListId,
				    									Question_Option_List__c = pQuestionOptionListId,
				    								    Profiler_Score_Card__c = pProfileScoreCardId);
    	lstProfileCardDetail.add(ProfileCardDetail3);
    	
    	Profiler_Card_Detail__c ProfileCardDetail4 = new Profiler_Card_Detail__c(
				    									Name = 'Test2',
				    									Question_Bank_List__c = pQuestionBankListId,
				    									Question_Option_List__c = pQuestionOptionListId,
				    								    Profiler_Score_Card__c = pProfileScoreCardId);
    	lstProfileCardDetail.add(ProfileCardDetail4);
    	
    	Profiler_Card_Detail__c ProfileCardDetail5 = new Profiler_Card_Detail__c(
				    									Name = 'Test2',
				    									Question_Bank_List__c = pQuestionBankListId,
				    									Question_Option_List__c = pQuestionOptionListId,
				    								    Profiler_Score_Card__c = pProfileScoreCardId);
    	lstProfileCardDetail.add(ProfileCardDetail5);
    	
    	Profiler_Card_Detail__c ProfileCardDetail6 = new Profiler_Card_Detail__c(
				    									Name = 'Test2',
				    									Question_Bank_List__c = pQuestionBankListId,
				    									Question_Option_List__c = pQuestionOptionListId,
				    								    Profiler_Score_Card__c = pProfileScoreCardId);
    	lstProfileCardDetail.add(ProfileCardDetail6);
		
    	return lstProfileCardDetail;
    }
    
}