Freedom Sanbox Ant Deploy/src/objects/Question_Bank__c.object
<CustomObject>
    <description>This will be the question bank and act as a master object to Questionnaire.</description>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{00}</displayFormat>
        <label>Question Bank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank_List__c.object
<CustomObject>
    <description>This will store all the questions  and will act as a master table to Questionnaire. Dummy questions will not have any answer (No Points).</description>
    <label>Question Bank List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/QuestionNoToQuestionName__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>QuestionNo__c</fullName>
        <label>QuestionNo</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>QuestionNoToQuestionName</label>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Wellness_Card_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <label>Display Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wellness_Score_Card__c</fullName>
        <label>Wellness Score Card</label>
        <referenceTo>Wellness_Score_Card__c</referenceTo>
        <relationshipName>Wellness_card_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wellness Card Detail</label>
    <nameField>
        <label>Wellness card Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wellness Card Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Wellness_Option_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Answer_Text__c</fullName>
        <label>Answer Text</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>QuestionMaster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QuestionMaster</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Wellness Option Details</relationshipLabel>
        <relationshipName>Wellness_Option_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wellness_card_Detail__c</fullName>
        <label>Wellness card Detail</label>
        <referenceTo>Wellness_Card_Detail__c</referenceTo>
        <relationshipLabel>Wellness Option Details</relationshipLabel>
        <relationshipName>Wellness_Option_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wellness Option Detail</label>
    <nameField>
        <label>Wellness Option Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wellness Option Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Wellness_Score_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Wellness_Score_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipName>Wellness_Score_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <summarizedField>Wellness_Card_Detail__c.Score__c</summarizedField>
        <summaryForeignKey>Wellness_Card_Detail__c.Wellness_Score_Card__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Wellness_Test_Date__c</fullName>
        <label>Freedom ScaleTest Date</label>
        <type>Date</type>
    </fields>
    <label>Freedom Scale Score Card</label>
    <nameField>
        <label>Freedom Scale Score Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freedom Scale Score Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/ExportToExcelFreedomScaleController.cls
/*
  Revision History:
  
    Version     Version Author     Date         Comments
    1.0         Gaurav            17/7/2012       This class is used to Export all details related to Freedom Scale Card
   
*/

public with sharing class ExportToExcelFreedomScaleController 
{
	public List<Wellness_Option_Detail__c>	lstWellneesOptionDetail{get;set;}
	public List<WrapperExportToExcel> lstWrapperExportToExcel{get;set;}
	public string entityId{get;set;}
	public Boolean isRender{get;set;}
	Map<Id,map<string,string>> mapScoreCardToScoreCardOption;
	
	//Constructor
	public ExportToExcelFreedomScaleController()
	{
		lstWrapperExportToExcel = new List<WrapperExportToExcel>();
		Map<Id, String> mapAccountIdTOOwner = new Map<Id, String>();
		Map<Id,List<String>> mapWellnessScoreCardIdTOAnswer = new Map<Id,List<String>> ();
		entityId = ApexPages.currentPage().getParameters().get('entityid'); 
		List<Wellness_Score_Card__c> lstWellnessScoreCard = new List<Wellness_Score_Card__c>();
		List<Wellness_Option_Detail__c>	lstWellneesOptionDetail = new List<Wellness_Option_Detail__c>();
		isRender = false;
		mapScoreCardToScoreCardOption = new map<Id,map<string,string>>();//new Map<Id,List<String>>();
		
		if(ApexPages.currentPage().getParameters().get('entityid') == '')
		{
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid or Insufficient Parameter(s)'));
			isRender = true;
            return;
		}
		
		if(!ApexPages.currentPage().getParameters().containsKey('entityid'))
		{	
			//Collect all Freedom Scale Record 
			lstWellnessScoreCard = [Select Wellness_Test_Date__c, 
										   Account__r.Name, Account__r.OwnerId, 
										   Account__r.Owner.Name, 
										   Question_Bank__c, 
										   Name, Id, Account__c 
									From Wellness_Score_Card__c 
									Where Account__c != Null]; 	
			
			if(!lstWellnessScoreCard.isEmpty())
			{
				//Collect all Freedom Scale Answer Record
			 	lstWellneesOptionDetail = [Select Wellness_card_Detail__r.Wellness_Score_Card__c, 
												  Wellness_card_Detail__r.Score__c, 
												  Wellness_card_Detail__c,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Wellness_Test_Date__c,
												  QuestionMaster__r.Name, 
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__c,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__r.Id,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__r.Name,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__r.OwnerId,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__r.Owner.Name,
												  Name, Id,
												  Answer_Text__c 
											From Wellness_Option_Detail__c 
											Where Wellness_card_Detail__r.Wellness_Score_Card__c IN: lstWellnessScoreCard
											order by CreatedDate Desc ];
											
            	for(Wellness_Option_Detail__c objWellnessOptionDetail : lstWellneesOptionDetail)
			    {
			    	system.debug('objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c--->'+objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c);
			    	if (mapScoreCardToScoreCardOption.containsKey(objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c)) 
			    	{
			    		mapScoreCardToScoreCardOption.get(objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c).put(objWellnessOptionDetail.QuestionMaster__r.Name,objWellnessOptionDetail.Answer_Text__c);
			    	} else 
			    	{
			    		map<string,string> optionMap = new map<String,String>();
			    		optionMap.put(objWellnessOptionDetail.QuestionMaster__r.Name,objWellnessOptionDetail.Answer_Text__c);
			    		mapScoreCardToScoreCardOption.put(objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c,optionMap);
			    	}
			    	
			    }											
			}							
		}	
		else if(entityId != null && entityId.substring(0, 3).compareTo('001') == 0 )
		{
			//Collect all Freedom Scale Record 
			lstWellnessScoreCard = [Select Wellness_Test_Date__c, 
										   Account__r.Name, Account__r.OwnerId, 
										   Account__r.Owner.Name, 
										   Question_Bank__c, 
										   Name, Id, Account__c 
									From Wellness_Score_Card__c 
									Where Account__c =:  entityId ]; 	
			
			if(!lstWellnessScoreCard.isEmpty())
			{
				//Collect all Freedom Scale Answer Record
			 	lstWellneesOptionDetail = [Select Wellness_card_Detail__r.Wellness_Score_Card__c, 
												  Wellness_card_Detail__r.Score__c, 
												  Wellness_card_Detail__c,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Wellness_Test_Date__c,
												  QuestionMaster__r.Name, 
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__c,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__r.Name,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__r.OwnerId,
												  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__r.Owner.Name,
												  Name, Id,
												  Answer_Text__c 
											From Wellness_Option_Detail__c 
											Where  Wellness_card_Detail__r.Wellness_Score_Card__r.Account__c =: entityId 
											order by Wellness_card_Detail__r.Display_Sequence__c];
											
            	for(Wellness_Option_Detail__c objWellnessOptionDetail : lstWellneesOptionDetail)
			    {
			    	system.debug('objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c--->'+objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c);
			    	if (mapScoreCardToScoreCardOption.containsKey(objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c)) 
			    	{
			    		mapScoreCardToScoreCardOption.get(objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c).put(objWellnessOptionDetail.QuestionMaster__r.Name,objWellnessOptionDetail.Answer_Text__c);
			    	} else 
			    	{
			    		map<string,string> optionMap = new map<String,String>();
			    		optionMap.put(objWellnessOptionDetail.QuestionMaster__r.Name,objWellnessOptionDetail.Answer_Text__c);
			    		mapScoreCardToScoreCardOption.put(objWellnessOptionDetail.Wellness_card_Detail__r.Wellness_Score_Card__c,optionMap);
			    	}
			    	
			    }											
			} 							
		}
		List<String> lstAnswerText = new List<String>();
		List<QuestionNoToQuestionName__c> QnoToQNameList = new list<QuestionNoToQuestionName__c>();
		map<Decimal,String> QnoToQNameMap = new Map<Decimal,String>();
		system.debug('-----------QuestionNoToQuestionName--------'+QuestionNoToQuestionName__c.getAll().Values());
		QnoToQNameList.addAll(QuestionNoToQuestionName__c.getAll().Values());
		for(QuestionNoToQuestionName__c QuestionNoToQuestionName : QnoToQNameList){
			QnoToQNameMap.put(QuestionNoToQuestionName.QuestionNo__c,QuestionNoToQuestionName.Name);
		}
		
		for(Wellness_Score_Card__c objWellnessScoreCard: lstWellnessScoreCard)
		{
			system.debug('objWellnessScoreCard.Id--->'+objWellnessScoreCard.Id);
			
			if(mapScoreCardToScoreCardOption.get(objWellnessScoreCard.Id) != null)
			{
				WrapperExportToExcel  objWrapperExcel = new WrapperExportToExcel();
				objWrapperExcel.entityName = objWellnessScoreCard.Account__r.Name;
				objWrapperExcel.entityOwner = objWellnessScoreCard.Account__r.Owner.Name;
				map<string,string> mapOption = mapScoreCardToScoreCardOption.get(objWellnessScoreCard.Id);
				system.debug('mapOption---->'+mapOption);
				for (Integer i=1; i<= QnoToQNameList.size(); i++) {
					Decimal No = i+0.0;
					system.debug('No-->'+No);
					string questionName = QnoToQNameMap.get(No);
					system.debug('questionName--->'+questionName+'mapOption.get(questionName)-->'+mapOption.get(questionName));
					objWrapperExcel.lstAnswerText.add(mapOption.get(questionName));
				}
				objWrapperExcel.wellnessTestDate = objWellnessScoreCard.Wellness_Test_Date__c;
				//Collect all Wrapper Record with Wellness Score Card and Account
				lstWrapperExportToExcel.add(objWrapperExcel);
			}
		}
		
	}
						
	//Wrapper Class
	public class WrapperExportToExcel
	{
		public List<String> lstAnswerText{get;set;}
		public String entityName{get;set;}
		public string entityOwner{get;set;}
		public Date wellnessTestDate{get;set;}
		
		public WrapperExportToExcel()
		{
			lstAnswerText = new List<String>();
		}
	}//end WrapperExportToExcel

}//end