Freedom Sanbox Ant Deploy/src/objects/Question_Bank__c.object
<CustomObject>
    <description>This will be the question bank and act as a master object to Questionnaire.</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will determine whether the given Question Bank is to be used as a part of the Questionnaire.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Question Bank</label>
    <nameField>
        <displayFormat>QB-{00}</displayFormat>
        <label>Question Bank Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Bank_List__c.object
<CustomObject>
    <description>This will store all the questions  and will act as a master table to Questionnaire. Dummy questions will not have any answer (No Points).</description>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsDummy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Dummy?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Master_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Parent</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Bank Lists (Master Parent)</relationshipLabel>
        <relationshipName>MasterParent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Bank Lists (Parent Question)</relationshipLabel>
        <relationshipName>Question_Bank_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multichoice</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Question Bank List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Bank Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Question_Option_List__c.object
<CustomObject>
    <description>This will store the options for each question in the pool,  the score to be given and the feedback to be displayed.</description>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Question Option Lists</relationshipLabel>
        <relationshipName>Question_Option_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question Option List</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Option Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/objects/Questionnaire__c.object
<CustomObject>
    <description>This will give the ability to configure the questions for a particular questionnaire.</description>
    <fields>
        <fullName>Display_Sequence__c</fullName>
        <label>Display Sequence</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Bank_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank List</label>
        <referenceTo>Question_Bank_List__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Bank__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Bank</label>
        <referenceTo>Question_Bank__c</referenceTo>
        <relationshipLabel>Questionnaires</relationshipLabel>
        <relationshipName>Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questionnaire</label>
    <nameField>
        <label>Questionnaire Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestCreateQuestionBank.cls
@isTest
private class TestCreateQuestionBank 
{

    static testMethod void CreateQuestionBankTest()
    {
        Test.startTest();
        List<Questionnaire__c> lstQuestionnaire = new List<Questionnaire__c>();
		List<Question_Bank_List__c> lstQuesBankList = new List<Question_Bank_List__c>();
		List<Question_Option_List__c> lstQuesOptionList = new List<Question_Option_List__c>();
		
       	Question_Bank__c objQuestionBank = new Question_Bank__c ();
    	objQuestionBank.IsActive__c = true;  
    	insert objQuestionBank;
    	
    	/* Question_Bank_List__c  */
    	Question_Bank_List__c quesMasters1 = new Question_Bank_List__c();
    	quesMasters1.Question__c = 'Have you prepared a budget for household expenses?'; 
    	quesMasters1.Criteria__c = 'Yes';
    	quesMasters1.IsDummy__c = false;
    	quesMasters1.Question_Type__c = 'Yes/No';
    	insert quesMasters1;
    	lstQuesBankList.add(quesMasters1);
    	
    	Question_Bank_List__c quesMasters2 = new Question_Bank_List__c();
    	quesMasters2.Question__c = 'If YES, do you follow your budgeting?'; 
    	quesMasters2.IsDummy__c = false;
    	quesMasters2.Question_Type__c = 'Multichoice';
    	quesMasters2.Master_Parent__c = quesMasters1.Id; 
    	quesMasters2.Parent_Question__c = quesMasters1.Id;
    	insert quesMasters2;
    	lstQuesBankList.add(quesMasters2);
    	
    	Question_Bank_List__c quesMasters3 = new Question_Bank_List__c();
    	quesMasters3.Question__c = 'If YES, do you follow your budgeting?'; 
    	quesMasters3.IsDummy__c = false;
    	quesMasters3.Question_Type__c = 'Yes/No';
    	//quesMasters3.Master_Parent__c = quesMasters1.Id; 
    	//quesMasters3.Parent_Question__c = quesMasters1.Id;
    	insert quesMasters3;
    	lstQuesBankList.add(quesMasters3);
    	
    	Questionnaire__c objQuestionnaire1 = new Questionnaire__c();
    	objQuestionnaire1.Question_Bank__c = objQuestionBank.Id;
    	objQuestionnaire1.Question_Bank_List__c = quesMasters1.Id;
    	objQuestionnaire1.Display_Sequence__c = '1';
    	lstQuestionnaire.add(objQuestionnaire1); 
    	 
    	Questionnaire__c objQuestionnaire2 = new Questionnaire__c();
    	objQuestionnaire2.Question_Bank__c = objQuestionBank.Id;
    	objQuestionnaire2.Question_Bank_List__c = quesMasters2.Id;
    	objQuestionnaire2.Display_Sequence__c = '2';
    	lstQuestionnaire.add(objQuestionnaire2);
    	
    	if(!lstQuestionnaire.isEmpty())
    		insert lstQuestionnaire;
    	/* Question_Option_List__c */
    	Question_Option_List__c objQuesOptionList1 =  new Question_Option_List__c();
    	objQuesOptionList1.Name = 'Yes';
    	objQuesOptionList1.Score__c = 5;
    	objQuesOptionList1.Question_Bank_List__c = quesMasters1.Id;
    	insert objQuesOptionList1;
    	lstQuesOptionList.add(objQuesOptionList1); 
    	
    	Question_Option_List__c objQuesOptionList2 =  new Question_Option_List__c();
    	objQuesOptionList2.Score__c = 0;
    	objQuesOptionList2.Name = 'No';
    	objQuesOptionList2.Question_Bank_List__c = quesMasters1.Id;
    	insert objQuesOptionList2; 
    	lstQuesOptionList.add(objQuesOptionList2);
    	
    	Question_Option_List__c objQuesOptionList3 =  new Question_Option_List__c();
    	objQuesOptionList3.Name = 'Yes';
    	objQuesOptionList3.Score__c = 5;
    	objQuesOptionList3.Question_Bank_List__c = quesMasters2.Id;
    	insert objQuesOptionList3;
    	lstQuesOptionList.add(objQuesOptionList3);
	
    	Question_Option_List__c objQuesOptionList4 =  new Question_Option_List__c();
    	objQuesOptionList4.Name = 'No';
    	objQuesOptionList4.Score__c = 0;
    	objQuesOptionList4.Question_Bank_List__c = quesMasters2.Id;
    	insert objQuesOptionList4;
    	lstQuesOptionList.add(objQuesOptionList4);
    	
    	Question_Option_List__c objQuesOptionList5 =  new Question_Option_List__c();
    	objQuesOptionList5.Name = 'Yes';
    	objQuesOptionList5.Score__c = 5;
    	objQuesOptionList5.Question_Bank_List__c = quesMasters3.Id;
    	insert objQuesOptionList5;
    	lstQuesOptionList.add(objQuesOptionList5);
	
    	Question_Option_List__c objQuesOptionList6 =  new Question_Option_List__c();
    	objQuesOptionList6.Name = 'No';
    	objQuesOptionList6.Score__c = 0;
    	objQuesOptionList6.Question_Bank_List__c = quesMasters3.Id;
    	insert objQuesOptionList6;
    	lstQuesOptionList.add(objQuesOptionList6);
    	
    	CreateQuestionBank objCreateQuestionBank = new CreateQuestionBank(); 
    	objCreateQuestionBank.strUrlFlag ='';
    	objCreateQuestionBank.objActiveQuestionBank = objQuestionBank;
    	objCreateQuestionBank.Init();
    	objCreateQuestionBank.createNewQuestionBank();
    	objCreateQuestionBank.modifyQuestionBank();
    	objCreateQuestionBank.createQuestionBankAndQuestionnaire();
    	objCreateQuestionBank.cancel();
    	objCreateQuestionBank.strUrlFlag ='new';
    	objCreateQuestionBank.Init();
    	objCreateQuestionBank.createQuestionBankAndQuestionnaire();
    	objCreateQuestionBank.strUrlFlag ='edit';
    	objCreateQuestionBank.Init();
    	objCreateQuestionBank.createQuestionBankAndQuestionnaire();
    	Test.stopTest();
    }
}