Freedom Sanbox Ant Deploy/src/objects/Renewal__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Renewals</relationshipLabel>
        <relationshipName>Renewals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Renewal</label>
    <nameField>
        <displayFormat>Renewal-{0}</displayFormat>
        <label>Renewal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Renewals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Freedom Sanbox Ant Deploy/src/classes/TestUpdateEmailAddressOnRenewal.cls
/*
Revision History:

		Version     Version Author     Date        Comments
		1.0         --           	   --	  	   Initial Draft
		2.0  		Prajakta Sanap     25/04/2013	Created TestData_Ffreedom which contains all the test data for this test class.				   				 					   
*/

@isTest
private class TestUpdateEmailAddressOnRenewal 
{

    static testMethod void testUpdateEmail() 
    {
    	TestData_Ffreedom testData = new TestData_Ffreedom();
		Account acc = testData.initializeAccount();
        insert acc;
        Renewal__c renewal = testData.init_Renewal(acc);
        insert renewal;
        //Renewal__c ren = [select email__c,Id from Renewal__c where Entity__c =:acc.Id];
        //System.assertEquals(ren.email__c,acc.PersonEmail);
    }
}